### ISSUE TITLE
When will Jetty 12 be released

### ISSUE THREAD

**Issue by fzyzcjy** [eclipse/jetty.project#10137]
Hi thanks for the project! In https://projects.eclipse.org/projects/rt.jetty/releases/12.0, the doc says:

> Release Date: 
Thursday, July 20, 2023

However, I checked https://github.com/eclipse/jetty.project/releases and only see:

> 12.0.0.beta3
last week

Also, https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-server

> 12.0.x | 12.0.0.beta3 | Jul 06, 2023

Therefore, I wonder when will 12.0 be released? Thanks!

**Comment by lachlan-roberts** [comment]
There is no set release date but we are hoping to get it released as soon as possible.
We are currently testing this staged release of `12.0.0`, and looking good so far.

If successful we will release in next few days, otherwise we will postpone if there are any major issues.

Once the official release is made we will announce it and it will be available on maven central.

**Comment by fzyzcjy** [comment]
Thank you!
