### ISSUE TITLE
PCI-SSS : Sensitive data remains in memory dumps

### ISSUE THREAD

**Issue by ggsosa** [eclipse/jetty.project#10285]
**Jetty version** 9.4.51.v20230217

**Java version** 11

**Question** 

Good morning everyone,

I am using Jetty to expose an HTTPS endpoint. When making get/post queries on an endpoint with sensitive data, once the flow ends, if I perform a memory dump, the sensitive information still appears in the memory even after I've finished processing it.

From the memory structure, it seems the information was internally stored in Jetty from the HTTPS requests and responses but was never overwritten before being released. Is there any mechanism by which I can explicitly override this information before releasing it to the garbage collector?

**Comment by joakime** [comment]
Jetty 9.x is at End of Community Support

* #7958

**Comment by sbordet** [comment]
Jetty does not hold, per se, data structures with TLS crypto material, because we delegate TLS to the JDK implementation.

We cannot access the JDK implementation to zero out their data structures.

Is there anything specific that you found that is Jetty related?
We need evidence that it is a Jetty class that we can zero out, not a JDK class.

**Comment by ggsosa** [comment]
> sbordet

It's not that cryptographic information appears in the memory dump (I haven't validated that part).
The sensitive information that appears in the memory dumps is contained within the actual body and the HTTP headers, even though the request has been completed and responded to correctly. I'm taking the dump several minutes after making the HTTP requests.

Basically, the content of my HTTP requests is not overwritten before the memory is released in Java.
I've tried making request dumps (with harmless information in the bodies) to overwrite the memory structures, but I always end up with remnants of my original bodies.

![image](https://github.com/eclipse/jetty.project/assets/58897935/b7932cdb-3665-444f-b302-121422e8405e)

In red is my original request, and in blue is a dummy request I made to overwrite the data... apparently, before releasing the memory, the body data isn't overwritten.

**Comment by sbordet** [comment]
This is normal behavior, as it would cost too much to zero out every HTTP data structure.

Furthermore, it would be impossible to zero-out `String`s for example, so that would mean that we would have to ditch `String` and use `char[]` everywhere, making it impossible to interact with practically every library (to name one, logging libraries).

**Comment by ggsosa** [comment]
> This is normal behavior, as it would cost too much to zero out every HTTP data structure.
> 
> Furthermore, it would be impossible to zero-out `String`s for example, so that would mean that we would have to ditch `String` and use `char[]` everywhere, making it impossible to interact with practically every library (to name one, logging libraries).

I understand perfectly, I completely agree with you... I know that in terms of performance it is too hard.
I just wanted to know if there was any way to configure Jetty in which that would be possible (I imagined it wouldn't be possible, but I wanted to check with you guys anyway)....

It's not something I want on a personal level, it's a requirement I'm getting from PCI SSS to comply with the standard. Basically, I'm being forced in my own application to handle char[] to avoid using immutable data types... I use several frameworks and always find that when using third-party libraries, sooner or later they end up using immutable data that affects my own application. The only technical option I'm finding to meet this requirement is to handle end-to-end encryption on my sensitive data for later control within my application with char[] where I have total control of memory usage. At the business and interoperability level, it complicates things a lot for me with the different actors and systems involved.

so... Could we conclude then that there is no mechanism by which that memory can be purged as far as Jetty is concerned?

thanks so much @sbordet ...

**Comment by sbordet** [comment]
> Could we conclude then that there is no mechanism by which that memory can be purged as far as Jetty is concerned?

It is kind of correct that there is no such mechanism, but let's think out loud here.

What you can do is to encode all sensitive data as the body of an HTTP request.
That data will be read into a Jetty network buffer, which will be recycled (more on that later).
The HTTP request will be parsed by Jetty, and Jetty will call your application, where you will be able to read and parse the request content, carefully using `char[]` rather than strings, etc.
Once you are done processing, you zero-out your `char[]`s.

What's left is to override the behavior of Jetty's `ArrayByteBufferPool` to zero-out the buffers when they are released.
In this way, the body of the requests won't be present in the recycled buffers, and you should have successfully zeroed-out all sensitive data.

Would that work?

**Comment by joakime** [comment]
Incidentally, other organizations do not consider RAM to be subject to PCI-DSS rules.

Examples

* https://d30000001huxdea4.my.salesforce-sites.com/faq/articles/Frequently_Asked_Question/Should-cardholder-data-be-encrypted-while-in-memory
* https://security.stackexchange.com/questions/49693/does-server-ram-count-as-storage-for-pci-compliance

**Comment by ggsosa** [comment]
Thank you so much @joakime for the links. In the PCI DSS standard, it used to be as you mentioned. It was enough to link that responsibility to the permissions on the operating system: applications have been certified under the PA-DSS standard with that justification. Not just any user can perform a memory dump because it's precisely one of the things the operating system controls.

The issue is that the new PCI SSS standard is much more restrictive...
The PCI SSS (Secure Software Standard) simply does not allow software to delegate the responsibility of "protecting" memory to the operating system.
I've consulted directly with the QSA (Qualified Security Assessor), I've spoken directly with the regional PCI manager, and there's no valid containment measure; it's a strict requirement of the standard.

At the application level, it's a very tough restriction because it essentially takes away my ability to use any library or framework....

@sbordet 
That approach works and is correct... in fact, I've already adopted it in a standalone application where I have an embedded Grizzly server. The difference is that this application is a microservice that I consume myself and can adapt to the requirement...

The problem is that in the product I have with Jetty, I can't adopt that approach because I have interoperability between several systems... In fact, in this product, the integration I have with Jetty is through camel-jetty... I use many other camel components that have exactly the same problem... All the power and interoperability that Camel provides me, I've completely lost with this new requirement... I'm absolutely and utterly screwed

It's really crazy, that requirement about the PCI SSS standard... I hope the PCI people strongly reconsider that standard definition because, while theoretically it might make sense, in practice it's somewhat unapplicable in some cases.


By the way, guys, thank you so much for your help. I truly appreciate your time and value your opinion on the matter.

**Comment by sbordet** [comment]
Keep us posted on whether you found a solution. Good luck!

**Comment by gregw** [comment]
@ggsosa So in summary,  Jetty is able to be configured with a buffer pool that will null out all buffers as they are returned to the pool (we should perhaps provide a simple pool wrapper to do this?), but your issue is that you are consuming jetty via Camel and that makes it more difficult to access jetty and configure it.   So perhaps reach out the to Camel folks to see how you can/can't access jetty to configure it.  Once you can tell us what access to jetty you have, we can suggest how to configure a byte buffer pool.

**Comment by ggsosa** [comment]
> @ggsosa So in summary.......you are consuming jetty via Camel and that makes it more difficult to access jetty and configure it......."

Indeed, @gregw , it's not easy to access that direct configuration from Jetty since I'm going through Camel. I've been looking at the Camel project and its respective Jetty configuration (at the code level on GitHub). If I continue along this line of work, I will consult with them directly. 
While it's possible to configure the size of the buffers for requests and responses, it doesn't seem to make any change regarding the problem I mentioned at the beginning (I had already tried this before opening this ticket with you and set small sizes in the buffers). 
I didn't find an easy way to specifically configure a custom buffer like (perhaps because my knowledge in Camel & Jetty is somewhat limited).


@sbordet 
> What's left is to override the behavior of Jetty's

I had the idea in my head to make the change you mentioned (the one about manually overriding the buffer and changing the implementation...). This led me to the following very basic question...
Is it possible that in Java the use of sockets inherently leaves dirty memory simply by handling a stream?

I proceeded to create a client to send data to a server over SSL with the respective certificates, then I created a socket on the server side and its respective InputStream.
With the InputStream, I tried reading from it in different ways, which abstractly we could summarize in 2 cases:
1- byte by byte
2- buffer (passing it as a parameter to the Java API)

I was careful not to create mutable structures in my code. In all cases, no matter how much I cleared the buffer, made explicit calls to gc(), and waited a reasonable amount of time before taking the dumps, the information I sent from the client always ended up in the server process memory... I also took care to close the stream and the socket and got the same results.

Based on the tests I conducted, I'm coming to the conclusion that it's not possible in Java to use the socket API without leaving behind dirty memory.
Do you know of any other way in Java to avoid using the Java socket API to open a port and receive data? To my understanding, every library or framework eventually ends up using the Java socket API.
This leaves the only viable option to meet the requirement to encode the data under some type of encryption before sending it from the client (as we originally discussed with you, @sbordet, and as it worked in the microservice I mentioned earlier).
Given that if I use the socket API the information remains in memory, overwriting the buffer that Jetty uses will not solve my problem with the dumps... hence, that approach lacks sense. What's your opinion on this @sbordet ?

The issue is that sometimes it's not possible to encode that data due to interoperability between systems. In general, external systems handle data encryption several levels above, usually at the level of SSL connections and not at the application level with encryption on the payload itself... At the risk of repeating myself, this PCI SSS requirement is insane.

The only thing I can think of doing is testing on different implementations and versions of the Java JDK to see if the socket issue is repeated in all implementations... but I'm reaching a point of no return on this topic.

I know this point is not directly related to Jetty but rather it's related to Java and the socket API. I appreciate any comments, ideas, or opinions you can provide.

**Comment by sbordet** [comment]
> Based on the tests I conducted, I'm coming to the conclusion that it's not possible in Java to use the socket API without leaving behind dirty memory.

There are a lot of details to take care.
For example, if you use heap `ByteBuffer`s, their content is copied into direct `ByteBuffer`s that are cached by the JVM.
If you use direct `ByteBuffer`s, the copy does not happen and therefore it may be enough not to retain any trace of what went through the network.

I would not use `Socket` but `SocketChannel` instead, and in non-blocking mode, as I think `Socket` or blocking mode may copy data that is kept around.

I you decide not to dive deeper into the JVM internals when using `SocketChannel`s, encrypting the data should work: you will still be able to dump the encrypted data from memory (and for a very short period of time also the key used to decrypt during the decryption operation but let's not count this case), but since it's encrypted it should not matter (I think; I have not read the details of the PCI SSS requirements).
Obviously you'll have to distribute the keys, set up all the systems with your custom encrypt/decrypt step, which is difficult for interoperability.

Another option would be to look into the [foreign function & memory JEP](https://openjdk.org/jeps/442).
With that API you should be able to call C and do sockets there where you would have, I presume, more control on the data structures you use (but you would have to verify that the implementation does not use the same tricks the JVM is using.

**Comment by sbordet** [comment]
Closing as answered.
