### ISSUE TITLE
Jetty 12: ResourceService throws NPE when resource has no filesystem path

### ISSUE THREAD

**Issue by uschindler** [eclipse/jetty.project#10330]
**Jetty version(s)**
Jetty 12.0.0

**Jetty Environment**
core, ee8

**Description**
I have my own Resource subclass that fetches content from database. Therefore, it has no Path. This is valid according to documentation and also used by some Resources like MemoryResource.

Unfortunately when the browser wants to do a range request, it fails with NPE:

```
2023-08-16 23:21:37,295 WARN o.e.j.e.n.HttpChannel - /reference/118030/attachments/msm_114_2_vmadcp_75khz.nc
java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.getFileSystem()" because "path" is null
        at java.nio.file.Files.provider(Files.java:105) ~[?:?]
        at java.nio.file.Files.newByteChannel(Files.java:380) ~[?:?]
        at java.nio.file.Files.newByteChannel(Files.java:432) ~[?:?]
        at org.eclipse.jetty.ee8.nested.ResourceService.lambda$writeContent$1(ResourceService.java:703) ~[jetty-ee8-nested-12.0.0.jar:12.0.0]
        at org.eclipse.jetty.ee8.nested.resource.SeekableByteChannelRangeWriter.skipTo(SeekableByteChannelRangeWriter.java:80) ~[jetty-ee8-nested-12.0.0.jar:12.0.0]
        at org.eclipse.jetty.ee8.nested.resource.SeekableByteChannelRangeWriter.writeTo(SeekableByteChannelRangeWriter.java:63) ~[jetty-ee8-nested-12.0.0.jar:12.0.0]
        at org.eclipse.jetty.ee8.nested.ResourceService.writeContent(ResourceService.java:704) ~[jetty-ee8-nested-12.0.0.jar:12.0.0]
        at org.eclipse.jetty.ee8.nested.ResourceService.sendData(ResourceService.java:628) ~[jetty-ee8-nested-12.0.0.jar:12.0.0]
        at org.eclipse.jetty.ee8.nested.ResourceService.doGet(ResourceService.java:279) ~[jetty-ee8-nested-12.0.0.jar:12.0.0]
        at org.eclipse.jetty.ee8.servlet.DefaultServlet.doGet(DefaultServlet.java:432) ~[jetty-ee8-servlet-12.0.0.jar:12.0.0]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:503) ~[jetty-servlet-api-4.0.6.jar:?]
```

I have only checked the ee8 ResourceService, not the core one. They may all have the same problem. I have not seen that problem with Jetty 10. The code there uses Resource's byte channel and just checks if it is seekable. Otherwise it falls back to `InputStreamRangeWriter`: https://github.com/eclipse/jetty.project/blob/5bca6994645b62d22dca67cc24f41a9f3a365344/jetty-server/src/main/java/org/eclipse/jetty/server/resource/HttpContentRangeWriter.java#L56-L76

Actually the range writer should check for NULL or -- better -- it should get the channel from the Resource, unfortunately the resource only has ReadableByteChannel, so instanceof check is required. But maybe it can still at least skip?!

**Comment by uschindler** [comment]
When multiple ranges are requested it fails in similar ways @ `HttpContentRangeWriter`.

**Comment by uschindler** [comment]
Possibly the code that fails above should better use `HttpContentRangeWriter` and code should be fixed there.

**Comment by gregw** [comment]
Yeah, Multipart got a bit of an overhaul so that it could be fully asynchronous.... and looks like we only have content sources that need paths at the moment.   Should be fairly easy to add something that uses the InputStream at least.

@lorban Can you get this one.  Whilst you are at it, can you ponder the fact that it appears we have no way of asynchronously consuming an abstract Resource.  I know we never did before, but.....

**Comment by uschindler** [comment]
One observation that I made on top of this bug, not sure if it is a bug:

As workaround I added `ResourceService#setAcceptRanges(false)` to the configuration. The server then no longer sends `"Accept-Ranges: bytes"` header, but it still accepts ranges and tries to fulfil them, which causes the bug again. It also does not explicitely send `"Accept-Ranges: none"`. To actually work around this bug, you have to explicitely remove the Range header from request before delegating to the `ResourceService`.

**Comment by uschindler** [comment]
Another observation: When the NPE occurs, the client gets a 200 response with empty body. So it looks like the NPE is swallowed and just logged (see above), but the client does not get an error 500.

**Comment by uschindler** [comment]
I found another unrelated case where a servlet called a method that caused a class initialization error in another class. This produced no error (servlet was just not used and handling delegated to next handler). I will open a separate issue about some `RuntimeExceptions` are swallowed (in this case it was swallowed in the `ContextHandler` and just logged with `DEBUG`).

**Comment by uschindler** [comment]
> I found another unrelated case where a servlet called a method that caused a class initialization error in another class. This produced no error (servlet was just not used and handling delegated to next handler). I will open a separate issue about some `RuntimeExceptions` are swallowed (in this case it was swallowed in the `ContextHandler` and just logged with `DEBUG`).

Ignore that one, it does not happen in simple servlet. The problem here is: If `DefaultServlet#resolve(String pathInContext)` throws an unchecked exception it is treated as "not found".

This is an unrelated error, but occurred to me while debugging.

**Comment by lorban** [comment]
@uschindler Thanks for the precise report; I managed to reproduce all the issues you reported (I believe I didn't forget any) and came up with the appropriate fixes for EE8, 9 and 10.

Would it be possible for you to locally build the `fix/jetty-12-10330-ee9-ResourceService-fixes` branch and report back your findings?

**Comment by uschindler** [comment]
Have you also checked the "core" ResourceHandler? I did not try it out, as this was a port of a ee8 servlet based infra. The changes for ee9 looks fine, for ee10 I can't test.

My code is a bit different than yours in the test, I have subclassed DefaultServlet and implemented a custom `protected Resource resolve(String pathInContext)` that returns my own resource. But from what I understand, your code is basically doing the same with a custom `HttpContentFactory`.

**Comment by lorban** [comment]
@uschindler the core `ResourceHandler` and the EE10 `DefaultServlet` actually share the same `ResourceService` codebase, so whatever fixes I made for EE10 should also apply to core. I nevertheless just added similar tests to the core test suite to be certain of that.

Looking at the stack you reported, the problem is that there is no fallback code in place for `Resource`s that are not `java.nio.file.Path`-based, so I used the `MemoryResource` in my tests as that one also isn't backed by `Path`. I'm reasonably confident that this covers the bug you hit but I asked you to test that branch if possible just in case my understanding of your exact setup wasn't spot on.

**Comment by uschindler** [comment]
Hi,
I built your branch after downloading it quickly as ZIP and deployed to local maven. After that I build my app (it is embedded server, so its easy to deploy) and all works.

I did some tests with Chrome and Firefox by stopping the download and retrying. Looks like ranges are correctly handled.
Also `curl --range` worked for single and multi-ranges.

So to me looks fine, I will closely check the PR and add a review comment. While my initial review, I was wondering about the fact that the ee10 codebase that it does not touch the same files like the ee9 one (and of course, ee8 is autogenerated by transforming ee9 source files with a Maven plugin).

**Comment by lorban** [comment]
Thank you for the feedback!

**Comment by uschindler** [comment]
I left a review. I think the explicit "Accept-Ranges: none" is not needed, but that's a separate discussion. To me it was only important to make sure that if you disable ranges in the Handler / DefaultServlet it should ignore any ranges sent by client.

**Comment by uschindler** [comment]
Hi actually, why is the code not using the same approach like before in Jetty 10? Coming from an abstract `Resource` class, which is abstracted away from filesystems, the code should not use `getPath()` at all. The Jetty 10 code used `getChannel()` and if the return value is a `SeekableByteChannel` it used it for ranges (and the default implementation uses the same call to `nio.Files` like the ResourceService). If that does not work it falls back to `InputStream`. This makes best use of the abstraction.

IMHO, `getPath()` could possibly be removed from `Resource` at some point in future!? Maybe make sure that the returned channel is always seekable by an API change, but this would require to implement it downstream (and I found no easy way to get a `SeekableByteChannel` on to of a `byte[]` array).

**Comment by lorban** [comment]
@uschindler The `Resource` class and its usages were revisited for Jetty 12 as they accumulated too much legacy over the years.

One fundamental thing is that in Jetty 12, `Resource` is a read-only abstraction over something akin to a file, and since the `SeekableByteChannel` allows writing we decided we couldn't use it in the `Resource` API.

`Resource` is used in very many different mechanisms all over Jetty, so we had to make compromises, and exposing `getPath()` is one of them, as there are a few places where we know `Resource`s are file-based and must be written to.

But as @gregw suggested at https://github.com/eclipse/jetty.project/pull/10335#pullrequestreview-1583665644 , `Resource` could be improved further, for instance, exposing a `Content.Source` instead of using `InputStream` and `ReadableByteChannel` as that is a more natural construct for Jetty which would help to avoid those kinds of `if (resource.getPath() != null)` checks while still getting optimum performance where possible. We're aware of the shortcomings, and #10063 was opened to address this problem. You can expect improvements to happen over time.

**Comment by lorban** [comment]
> I left a review. I think the explicit "Accept-Ranges: none" is not needed, but that's a separate discussion. To me it was only important to make sure that if you disable ranges in the Handler / DefaultServlet it should ignore any ranges sent by client.

It is also my understanding that `Accept-Ranges: none` isn't strictly needed but I believe the way I added it is spec-compliant and it helps a bit in writing tighter tests.

**Comment by uschindler** [comment]
Thanks for fixing!

**Comment by uschindler** [comment]
Hi,
I think this issue is missing in the Jetty 12.0.1 release notes. I updated today and all issues described here were fixed.

Would it be possible to add it to release notes here?: https://github.com/eclipse/jetty.project/releases

Thanks, Uwe

**Comment by uschindler** [comment]
P.S.: Range requests work fine, this request was failing previously (the example below loads from a blob in database using a custom resource doing a JDBI request to Postgres):

```sh
$ curl -I -H "Range: bytes=20-1023" https://download.pangaea.de/reference/118656/attachments/M186_1_nav.jpg
HTTP/2 206
server: nginx/1.25.2
date: Mon, 04 Sep 2023 16:42:14 GMT
content-type: image/jpeg
content-length: 1004
x-powered-by: Jetty(12.0.1)
vary: Origin, Cookie, Authorization
set-cookie: pansessid=deb5668bb71ce420a08ab6ae1a0c7e56; Path=/; Domain=.pangaea.de; Secure; HttpOnly
cache-control: public
x-cid: deb5668bb71ce420a08ab6ae1a0c7e56
last-modified: Mon, 22 May 2023 07:33:25 GMT
accept-ranges: bytes
content-range: bytes 20-1023/783559
alt-svc: clear
strict-transport-security: max-age=31536000
x-ua-compatible: IE=Edge
x-content-type-options: nosniff
```

(keep in mind: proxied through NGINX)

**Comment by lorban** [comment]
@joakime could you please check why this resolution didn't make it into the release notes? Thanks!

**Comment by joakime** [comment]
@lorban the release tooling for this issue detected the following commits associated with it, but surprisingly none of them had a detected `base_ref` (the name of the branch they belong to)

* 7f0a3565859d17f64d330bb11df22b0b908cebb0 - no base_ref
* 1ad557f454f50a1d63333e840e263f6697b6096c - not present
* 6ba125637da35dd58008b3003bcc0ce7c2de9552 - not present
* b13c498da9d2e6365881601be49ee1bc1f379bf7 - not present
* a88b2c20d201e8d2f8470441deefd7adda5bd91c - not present
* dd6a971f27247228171015b6897093360edccb50 - no base_ref
* c6470646c40c485302893ecc6666b042647517cf - not present
* f3cd33331bad87d262971fe165202ddf06cc7455 - not present
* e7946e6756c2bfe64071fff376cce0073dd1a913 - not present
* 772a76f15a162e555bf4c0dbdd9c2e8b931a7abb - not present
* 7d639ec29ebb8ad715f100e03472b7bdc061bca5 - not present
* 5b934353581f598bd91d80a9bfb3dd188fd0a2c3 - no base_ref
* 8582b3a624b46e2c17a76a08f2cb9f0b0f50f8bb - not present
* ded90926f6fe989b6b9180c37fcdfb1a6dfdded2 - no base_ref
* 8954079b69c80eff8b2f35be8a1e625c85847886 - not present
* 8a2ff3db0d9a3ceb37ee16b4d15df5c1ed8b79cb - not present
* 57823bef6eaf96f9f2638e36715b3e9e945e6d36 - no base_ref
* 6b1c490dbc287fc9484c6fbcedd0e5a92a6e375f - no base_ref

When you see "not present" it usually means it detected the change, but it only exists in the PR (likely because the PR was squash merged or rebase merged back into the main line branch).

I don't (yet) understand why it detected no `base_ref` for the few commits that are in the tree.

**Comment by lorban** [comment]
@joakime Thanks for the explanation.

We should review the 12.0.1 release notes to add notes about the PRs that have been omitted, and come up with some solution to avoid this problem in the future.

**Comment by joakime** [comment]
@lorban I added another step to the webtide/webtide-release-tools, where if the issue has no discovered base-ref, then it performs another query to find the github issue base-ref from the issue cross-reference events (when they point to a pull-request)

The release https://github.com/eclipse/jetty.project/releases/tag/jetty-12.0.1 has been updated with the new output
