### ISSUE TITLE
Introduce QoSHandler

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#10361]
**Jetty version(s)**
12

**Enhancement Description**
`DoSFilter` and `QoSFilter` should be ported as `Handler`, possibly in a single class (as they overlap in functionalities?).

**Comment by gregw** [comment]
A couple of questions/issues to consider...

For QoS, we have to decide if we are going to:
 a) limit only simultaneous calls to `Handler.handle`.  This will not help QoS of async applications... but async applications can use the thread pool size for such limitations.  Maybe QoS dispatch limits relate only to blocking applications?
 b) limit all dispatches: calls to `Handler.handle`, write callbacks, demand callbacks, error listeners etc. Lot's of wrapping might be needed.
 c) limit the number of uncompleted requests regardless of dispatches, but this could end up with deadlock and/or idle server with queued requests.
 d) limit only blocking dispatches to `Handler.handle`?
 3) allow an async application to request a QoS permit independently of a dispatch to `Handler.handle`?

Not also that currently the initial dispatch to `Handler.handle` is special in that it is not serialized.  This is done so a handler can be written in blocking style and not prevent write and demand callbacks due to serialization.    The issue then is that if we delay the call to `Handler.handle` (for DOS or QoS reasons) until some other event, then we have to make sure we do not invoke the handler with a serialized thread, else if it is written in blocking style it will deadlock.    So if we are freeing up requests by a previous request existing `Handler.handle`, then we can use that thread to handle the delayed request, as it was already dispatched without being serialized.   But if it is a completion of the callback or the return of a demand/write callback, then we may need to dispatch to the threadpool to avoid serialization.

**Comment by sbordet** [comment]
I think a) is the simpler and intuitive solution: you only allow N concurrent requests in the Handler tree.

I think that would work for blocking cases as well as for non-blocking cases where I may want to limit the number of requests to a 3rd party system that I call via `HttpClient` non-blocking.

Good point about the wake-up thread.
I think we should just always execute. 
Thread A came in, hit the QoSHandler, but is not allowed to continue. We return true and park the tuple (req, res, cbk). At this point, CPU locality is gone already.
When a spot frees up, we just execute the tuple in a different thread, so we don't worry about the wake-up thread problem.
Assuming that the number of spots in QoS is larger than the thread pool maxThreads, we should always have a thread available to run, just a little delay.

We can add optimizations later to detect whether it is a serialized thread.

**Comment by gregw** [comment]
> I think a) is the simpler and intuitive solution: you only allow N concurrent requests in the Handler tree.
> 
> Good point about the wake-up thread. I think we should just always execute.

Perhaps... although if we go with a), then that is the simplest one to reuse the returning thread from handle to call the waiting requests handle.

**Comment by sbordet** [comment]
Fixed by #10480.
