### ISSUE TITLE
AttributeNormalizer does not favor ${WAR} over other attributes, like ${jetty.base}

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1038]
The current AttributeNormalizer does not normalize to `${WAR}` if the `${jetty.base}` overlaps.

Eg:

``` none
${jetty.base} = /opt/jetty/mybase
${WAR} = /opt/jetty/mybase/webapps/FOO

// Incorrect behavior of bug
.normalize("/opt/jetty/mybase/webapps/FOO/css/main.css") => ${jetty.base}/webapps/FOO/css.main.css

// Proper behavior

.normalize("/opt/jetty/mybase/webapps/FOO/css/main.css") => ${WAR}/css.main.css
```

**Comment by ludoch** [comment]
Just to be clear, the user should not provide the sys property WAR, right? It should be calculated internally by the quickstart process?
We did not define it in 9.3.8 and it was working.

**Comment by joakime** [comment]
Correct.  `${WAR}` is [an internal attribute that the AttributeNormalizer uses](https://github.com/eclipse/jetty.project/blob/jetty-9.3.13.v20161014/jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/AttributeNormalizer.java#L170-L173), and that path is [provided by the QuickStartDescriptorGenerator mechanism](https://github.com/eclipse/jetty.project/blob/jetty-9.3.13.v20161014/jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartDescriptorGenerator.java#L135).

**Comment by gregw** [comment]
The quickstart test is failing in the build. Suspect this issue.
Test is expanding to jar:file:file:/...

Note that any changes to the normalization need to be backward compatible, else they break all current quickstart generated configurations.  Perhaps we need to add a version number to the quickstart file.

**Comment by gregw** [comment]
@joakime I think there is a fundamental problem with the approach taken.  Currently the normalized URIs and Paths are being handled by the same list of PathAttributes - some Paths and some URIs.  But the `normalize(Object)` method is calling `normalize(Path)` instead of `normalize(URI)` for `file:` URIs.

The result is that non URI path attributes may be substituted into URIs (Note that URI attributes can not be substituted into Paths as there is some special case protection).

To illustrate the problem, I added the following test:
```java
            // Test non war URI
            URI otherURI = new File(testJettyBase,"etc/something.xml").toURI();
            result = normalizer.normalize(otherURI);
            assertThat(result, is(otherURI.toASCIIString()));
```

which fails with:
```
java.lang.AssertionError: 
Expected: is "file:/opt/jetty-distro/demo.base/etc/something.xml"
     but: was "file:${jetty.base}/etc/something.xml"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at ...

```

It has substituted the ${jetty.base} file into a URI.  This may work on *nix but is fundamentally broken in a portable sense.   We simply should not be mixing types.  Paths are Paths and URIs are URIs. 

A URI that references the `jetty.base` should not be normalized unless we define a `jetty.base.uri` attribute that has a different value to jetty.base and the above test would expand to `${jetty.base.uri}/etc/something.xml`
 
I'll give this a go... standby...

@ludoch this should not change the behaviour you see... I'm just future proofing this a bit more.

**Comment by gregw** [comment]
I've done a moderate refactor  of the normalization:
 - I removed lots of the tests that were incorrectly checking for things like: `jar:file:${jetty.base}/path~/path`
 - rather than add and then sort the attributes, I just add them in the order that we wish to check them
 - There is now an root Attribute which is polymorhic to PathAttribute and URIAttribute
 - The paths and uris ordered lists are used to create a map from key to Attribute
 - The URI matching is now not by ascii path, but instead does explicit checking of scheme, host and path. This allows issues like `file:/some/path` and `file:///s%6fme/path` to be resolved.
 - URI prefixes must be on / boundaries, so `file:/webapps/FOO` no longer is matched within `file:/webapps/FOOBAR`
 - new tests added for the above.

**Comment by joakime** [comment]
The changes you made breaks one of the fundamental features it used to have.
The sorting, and weights existed to handle overlapping paths.

If you have overlapping in the paths, like this:

    jetty.base = /opt/jetty/app
    jetty.home = /opt/jetty/app/dist

then the submitted `normalize(/opt/jetty/app/dist/foo)` is now `${jetty.base}/dist/foo` when in the previous implementation it would correctly resolve to `{jetty.home}/foo`

this is because in the case of overlapping paths, the longer attribute's path was chosen. (very servlet url-pattern-esque)

if the two uris in the matching, are both `file:` uris, then the matching must be by `Path` (its the only safe way), otherwise it will fail on Windows (for things like short-vs-long and case `file:/c:/program%20files/jetty-distribution` and `file:/C:/Progra~1/Jetty-~1`) and OSX (for things like case differences `file:///Users/joakim/Jetty/dist` against `file:/Users/joakim/jetty/dist`)

even on linux, the following will fail: create a directory, using the command line `mkdir a%2fb` and attempt to use it with this new code (note the old code handled it via Path comparison, so it worked fine)

**Comment by joakime** [comment]
Lets skip the MS WIndows and OSX issue on case differences, because if this is a concern, then the problem shouldn't be solved in AttributeNormalizer.

Rationale: since the case difference can occur in the following ...

```
System Properties
jetty.home = D:\apps\jetty-dist
jetty.base = D:\apps\ourbase

AttributeNormalizer
WAR = D:\apps\ourbase\webapps\FOO

.normalize("d:\apps\OurBase\webapps\FOO\deep\reference") = ??
```

If this happens, then I would argue that either:

 1. the System properties for `jetty.home` and `jetty.base` haven't been normalized for the actual filesystem paths
 2. the WAR path hasn't been normalized before handing it off to AttributeNormalizer constructor
 3. or the path passed into `normalize()` hasn't been cleaned up before attempting to be used.

**Comment by gregw** [comment]
@joakime ah yes,  the current sorting is only on weight.  So we need to add back a length sort.

The URL matching is done in such a way to avoid file:/// vs file:/ issues and path comparisons are always on normalized non-raw paths, so I'm not so worried about that.   URIs that have %2f in them are always going to be problematic and I don't think that passing a unit test will make them workable.

In you example you have `WAR = D:\apps\ourbase\webapps\FOO`, that can never happen because `WAR` is a URI and not a path, so `WAR` can never be an OS specific path.   If was that duality in the previous impl/tests that was causing the edge case problems.

I tend to agree that normalization will occur externally to this class, but no harm doing as best as we can in unit test.   It has been working fine with all it's edgecase problems because it is mostly used within the reasonable bounds.

**Comment by joakime** [comment]
Considering this fixed.
