### ISSUE TITLE
Jetty10 inetaccess mod started error

### ISSUE THREAD

**Issue by james-z-repo** [eclipse/jetty.project#10388]
**Jetty version(s)**

10.0.152
**Jetty Environment**

**Java version/vendor** `(use: java -version)`
JDK8
**OS type/version**
win10
**Description**

the jetty-inetaccess.xml has invoke includeConnectors method，but when i used inetaccess mod, the InetAccessHandler has a Exception：

@Deprecated
    public void includeConnectors(String... names)
    {
        throw new UnsupportedOperationException();
    }

excludeConnectors javac is wrong , should write exclude()
**How to reproduce?**

**Comment by lachlan-roberts** [comment]
I can reproduce this, the module is broken because it is using the deprecated `includeConnectors` and `excludeConnectors` methods from the XML.

You can override and modify the `jetty-inetaccess.xml` in your jetty-base if you want a quick workaround. You will just need to use `include(name+"@")` instead.

I will put up a PR to get this fixed.
