### ISSUE TITLE
Introduce locking for core HTTP `Session`

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#10392]
**Jetty version(s)**
12

**Enhancement Description**
Currently the way to use core HTTP `org.eclipse.jetty.server.Session` concurrently is to use `synchronized` around it.

This is not virtual threads friendly, so we should have a mechanism such as:

* `Session.locked(Runnable)`; or
* `Session.getLock()`; or
* `Session.getAutoLock()`

**Comment by gregw** [comment]
Not that the servlet spec says that the HttpSession object is not thread safe and that applications must do their own synchronisation: https://jakarta.ee/specifications/servlet/6.0/jakarta-servlet-spec-6.0#threading-issues
It is thus likely that some/many applications also synchronize on the session object, thus if we switch to locks we not only do not mutually exclude them, but those apps will still not be virtual thread safe.

If a session is to have an internal lock, then we would need to advocate that to be a standard API and wait for all the apps that use sessions to be updated.

**Comment by sbordet** [comment]
Not sure I follow.

Servlet apps will lock using `synchronized` on a different instance, that delegates to the core `Session` object.

Core web apps, if they wish to lock, will have a clear API to use.

**Comment by janbartel** [comment]
@sbordet not sure I follow what you're advocating. None of our existing session code uses `synchronized`, we do our own locking.   

If you're talking about apps needing to synchronize usage of `HttpSession` objects, then they will most likely use `synchronized`, rather than make their app non-portable by using some jetty-specific classes to support locking.

**Comment by gregw** [comment]
@sbordet as @janbartel has just pointed out to me, there is a `public AutoLock lock()` on `ManagedSession` (but not exposed in our `Session` interface).    That is the lock that is used for internal updates of the session state (passivated, activated, id change, invalidation, etc.).

But that is not exposed to the applications.    Currently the applications just synchronize on the session object itself and they do this when setting attributes to mutually exclude other  requests doing so.   You are right that servlets will again wrap our `Session` as a `HttpSession`, so there is an issue if we mix handler and servlet code.   But ultimately applications are generally beyond our control and they are going to synchronize on session.   We can change our authenticators to use the internal AutoLock, but that will not make sessions much more virtual thread safe, because applications are beyond our control.     

Actually, we should change our authenticators to synchronize on `Session.getAPI()`, so we do use the servlet API wrappers if they are present.


I just don't see how we can pave over this deficiency of virtual threads when we are invoking application code beyond our control?

**Comment by sbordet** [comment]
@gregw @janbartel I am talking about core-only web applications.

```java
public boolean handle(Request req, Response rsp, Callback cbk) {
    Session session = req.getSession(true);
    // How to make sure access to the session is thread-safe.
    // Don't want to use synchronized.
}
```

**Comment by janbartel** [comment]
@sbordet well, I guess users of core sessions can cast the `Session` returned by `request.getSession(true)` to a `ManagedSession` and then use the existing `ManagedSession.lock()` method in a `try-with-resources` block to ensure that multiple calls to `Session.setAttribute()` will be synchronized.  However, I don't reeeeally want that lock exposed to applications who could mess it up. It could potentially be made package private, but I'm hesitant to exclude the use of it by the eeX `SessionHandler`s - not sure we actually have any usages outside of the core package at the moment, so I'm just being cautious.

**Comment by sbordet** [comment]
@janbartel do you see a problem adding a `Session.getLock()` method to the API `Session` interface?

**Comment by siepkes** [comment]
This issue _might_ be solved by [JEP 491](https://openjdk.org/jeps/491) without requiring access to this lock if the JEP gets implemented. Since one could then synchronize on the session instance like we used to before virtual-threads.

**Comment by sbordet** [comment]
@siepkes but it would require Java 24 or later to work, so using a `Lock` is present and future proof.

**Comment by siepkes** [comment]
@sbordet While it's true that it would require (at least) Java 24, a lot of the stuff which makes virtual-threads usable (structured concurrency, scoped values, etc.) will require Java 24. Personally, I don't know if I wanted to do a virtual-threads thing with just Java 21 instead of 24. 

Also I don't think using a `Lock` from Jetty's `Session` class is that future proof since it's Jetty API, not Servlet API. Having to use Jetty specific API in a class which just needs to do some session related things seems undesirable. Using the existing `ManagedSession.lock()` vs something like `Session.getAutoLock()` does not seem to make a real difference to me in that regard.

**Comment by janbartel** [comment]
@sbordet adding a `getLock()` method to the `Session` api can be misleading to users: it's only useful iff you're using the `DefaultSessionCache` where session objects are shared. If you're using the `NullSessionCache` then each request has their own copy of the session object anyway. That's a nuance that could be easily missed. Casting to `ManagedSession` implies the user has at least done some homework so _may_ be more aware of such nuances. Putting the `getLock()` method onto `Session` still isn't sitting right with me, particularly if it's really just to accommodate virtual threads before the generic problem of the use of `synchronized` is solved (via JEP-491 apparently).

**Comment by gregw** [comment]
An extra complication of exposing the lock is that session may invoke user code in the form of listener.

Currently those listeners are invoked with code like:
```
Object setAttribute(String name, Object value)
{
    Object old;
    try(Lock lock = _lock.lock())
    {
        checkStatus();
        old = _sessionData.setAttribute(name, value);
    } 

    callListeners(name, old, value);
}
```

If we expose that lock, then users may lock it before calling such methods, and then we end up calling arbitrary user code with the lock held.

Just don't think Session have a good enough semantic to do any serious synchronization on.    Our core sessions do not need synchronization.   If applications want to mutually exclude query/updates on sessions, then they can use their own locks.   They do not need to synchronize on the session, nor do they need to use the same lock that sessions use internally.

There is no guarantee about the actual instance given back by req.getSession, so synchronization on the session instance itself is not a good idea (and we should stop doing that if we are).   But replacing with an explicit lock is also doomed to being inadequate depending on the session manager and the nature of the cluster.    Best not to pretend that session are the right mechanism for that.   Applications can put a lock into a context attribute if they want to share a lock between requests, or in the session itself or on the request - all depending on the scope they want.

**Comment by gregw** [comment]
Our Authenticators are using synchronized, so we can stop them doing that.
