### ISSUE TITLE
Add multiple FilterHolder to a ServletContextHandler may cause problems

### ISSUE THREAD

**Issue by WangTaoTheTonic** [eclipse/jetty.project#1050]
As codes shown, every time we use `addFilter` in `ServletContextHanlder` to add `FilterHolder`, it will add the `FilterHolder` object into `_filters` of its ServletHandler and trigger the ServletHanlder initialization.

That is to say, if we add multiple handlers into a `ServletContextHandler`, the earlier one handler being added, the more it will be initialized which is triggered by `initialize` methods in it ServletHandler.

But for some filters like [Cas20ProxyReceivingTicketValidationFilter](https://github.com/apereo/java-cas-client/blob/master/cas-client-core/src/main/java/org/jasig/cas/client/validation/Cas20ProxyReceivingTicketValidationFilter.java#L119), they are not allowed to be initialized multiple times or it will throw exception.

Now we have problems caused by repeated initialization, but the reason is just calling `ServletContextHandler.addFilter` more than one time. I think adding more than one filter is a normal case and see there is an method called `setFilters` in `ServletHandler`, maybe we should call `ServletContextHandler.getServletHandler.setFilters` instead?

I am a rookie about jetty, please guide me if you guys have any ideas, thanks.

Here is [how we add filters in Spark](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/ui/JettyUtils.scala#L257).

**Comment by joakime** [comment]
Are you adding filters to an already started Jetty?
Or are you adding the filters, then starting Jetty?

This is important to understand, as the behavior is different.

**Comment by WangTaoTheTonic** [comment]
@joakime Thanks for you attention. We add filters to an started Jetty.

**Comment by gregw** [comment]
@WangTaoTheTonic To pragmatically add the same FilterHolder to multiple path specs, it is best to access the `ServletHandler` instance directly rather than the convenience methods on `ServletContextHandler`.  You can get the `ServletHandler` instance with `servletContextHandler.getServletHandler()`.

Then you should explicitly add the holder with 'servletHandler.addFilter(FilterHolder)` and then you can add multiple filter mappings with multiple calls to `servletHandler.addFilterMapping(FilterMapping)`.

However, I accept that it is a bug that the convenience method on ServletContextHandler does not check if the holder is already added.      So we should be able to fix the next release so your current code should work - but the code above will work now.

**Comment by WangTaoTheTonic** [comment]
Thanks @gregw . Do we need a ticket to track this issue?

**Comment by gregw** [comment]
No. this ticket will do to track the fix.

**Comment by janbartel** [comment]
The problem is that the FilterHolder.initialize() method does not check to see if it has already been initialized, as does eg the ServletHolder. Added protection in jetty-9.3.x and above.

**Comment by gregw** [comment]
I think we need to do a bit more than check for double init.  I think we need to avoid adding duplicate Holders.   So addFilterWithMapping and similar methods need to check if the holder has already been added and if so then not add it again.

**Comment by janbartel** [comment]
Checks for duplicate FilterHolder and ServletHolder objects done.  In jetty-9.3.x and above.

**Comment by Mohit-jindal** [comment]
i want to configure DoSFilter in jetty.xml. please help

**Comment by joakime** [comment]
@Mohit-jindal a random comment in a long ago closed issue is not the best way to get help.

Please use the [`jetty-users` mailing list](https://accounts.eclipse.org/mailing-list/jetty-users) for help using Jetty.
