### ISSUE TITLE
I see two different threads processing Handler code and RequestLog code 

### ISSUE THREAD

**Issue by SarathChandraRS** [eclipse/jetty.project#10530]
Jetty Version : 9.4.43

Java Version : JDK 11 

Question : We are using Jetty 9 in our product. We are seeing an issue in production. 
After little bit of triage we see sometimes the thread that has processed the request is different from the thread that is executing the request log. This is observed when an exception is raised in request processing thread. 
My understanding is that the thread that process is the request will always be the thread that executes RequestLog code as well. 
Can you help me understand why two different threads are processing the request and request log ? and when exactly this behavior is observed ? I am not able to reproduce this in my local system.

**Comment by joakime** [comment]
First, Jetty 9.x is now at End of Community Support.

* #7958 

Jetty is a 100% async server, there is no model of 1 thread per 1 request.
A single request can go thru 1..n threads.

**Comment by SarathChandraRS** [comment]
Thank you for the response. 
We have upgraded the jetty to 10.x in our latest version of the product. 
Is there any document where we can find when does the Request and RequestLog has different threads ? 
When we run in the local, we always see the same thread running both Request and RequestLog. 
The same is happening in production as well for success cases. 
Only for some specific error(backend process timed out) cases we see different threads are running for Request and RequestLog. 

Thanks.

**Comment by joakime** [comment]
> Is there any document where we can find when does the Request and RequestLog has different threads ?

Since Jetty is 100% async you have to code accordingly.

Work with the assumption that the thread that starts processing a Request will not be the same thread that is used throughout the entire processing of the request.

This means you cannot, and should not, use ThreadLocals.
If you need to track things throughout a request, use the Request Attributes.

> When we run in the local, we always see the same thread running both Request and RequestLog.
> The same is happening in production as well for success cases.

Small request/response exchanges, fast exchanges, etc have increased odds of being the same thread, but it's not guaranteed, and you should not code making that assumption, countless thousands of events can cause the threading to be different for your requests (load, low resources, network, backpressure, cpu cache, jvm code, os behaviors, networking drivers, networking intermediaries, ssl/tls behaviors, etc.  it's a looong list of things)

**Comment by joakime** [comment]
A common reason we get this question (esp with RequestLog in the mix) is because of use of logback-access. (and wanting to use things like MDC / NDC in the logging layer)

Do not use logback-access with Jetty 10+

It has several unfixed bugs that will cause bad behaviors, and incorrect/invalid results in your output logs (status codes will be wrong, query parameters from other request, use after free errors, url parameter use can cause a failure in logback-access resulting in no output and sometimes a crash, url parameter access causing a read from the network during requestlog processing, information from subsequent requests reported incorrectly as belonging to the request being logged, etc)

MDC and NDC work in Jetty, but under the limited scope of a single Thread execution of whatever step/stage/scope of the request you are currently processing and those MDC/NDC values should not be expected to carry over throughout the entire Request processing.

**Comment by SarathChandraRS** [comment]
Thank you for quick help.
We are using Thread Local to generate and store the request id. This is causing issue for us. 
We will make the changes to use the Request object to store the request ID.

**Comment by sbordet** [comment]
If you use Jetty 12 and Jakarta EE 10, you won't need to generate the request ID because `getRequestId()` has been added to the Servlet API.

**Comment by joakime** [comment]
Link the the relevant API in Servlet 6.0

https://github.com/jakartaee/servlet/blob/6.0.0-RELEASE/api/src/main/java/jakarta/servlet/ServletRequest.java#L572-L581

**Comment by SarathChandraRS** [comment]
Thank you. As of now we have upgraded to Jetty 10.x. 
Once we will upgrade Jetty 12.x we will move to inbuilt methods to use request Id generate logic.

**Comment by janbartel** [comment]
Closing this question as it appears to have been answered.
