### ISSUE TITLE
Cannot customize Executor on WebSocketClient

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#10547]
**Jetty version(s)**
10.0.16

**Jetty Environment**
n/a

**Java version/vendor** `(use: java -version)`
All

**OS type/version**
All

**Description**
If a developer wants to customize the Executor of the WebSocketClient, it is not possible, as the internal final WebSocketComponents is initialized with a new Executor from scratch, not using the one from the HttpClient (or other common / shared locations)

**Comment by sbordet** [comment]
The fix for this issue in #10548 is not optimal, because we are now exposing explicitly 2 ways of passing executors, which is more confusing than before.
Furthermore, it break JPMS.

We should hide the fact that `WebSocketComponents` is necessary, also because it is a WebSocket core class that should not be necessary when creating instance of the upper-layer WebSocket APIs.
`WebSocketComponents` is only for implementation use.
