### ISSUE TITLE
Unix Domain Socket connections are stuck on Mac with Apple silicon 

### ISSUE THREAD

**Issue by damar-block** [eclipse/jetty.project#10552]
**Jetty version(s)**
10.0.15

**Jetty Environment**
N/A

**Java version/vendor** `(use: java -version)`
jdk-17.0.8_7

**OS type/version**
MacOS 13.5.2 running on Apple M1 Max

**Description**
Incoming requests on UDS are stuck. This seems to only happen on Mac with Apple silicon - the test (see reproduce section) works fine on older Macs with Intel silicon

**How to reproduce?**
Reproduce on Mac with Apple silicon:
* Clone https://github.com/duduamar/jettyUds
* Install `socat` - `brew install socat`
* Run `gradlew run` to start Jetty server
* Run `socat TCP-LISTEN:8091,reuseaddr,fork UNIX-CLIENT:/tmp/jetty_test.sock` in separate terminal
* Run `curl localhost:8091/status` - should return { "status": "ok"} on success - this gets stuck
* To compare, run `localhost:8090/status` to connect to Jetty using HTTP/TCP instead of UDS

**Comment by joakime** [comment]
The `org.eclipse.jetty.unixsocket.server.UnixSocketConnector` is deprecated.

https://github.com/eclipse/jetty.project/blob/jetty-10.0.16/jetty-unixsocket/jetty-unixsocket-server/src/main/java/org/eclipse/jetty/unixsocket/server/UnixSocketConnector.java#L56-L58

https://github.com/eclipse/jetty.project/blob/a2735a9ae9d1afc124974253f1e223e5678be1f4/jetty-unixsocket/jetty-unixsocket-server/src/main/java/org/eclipse/jetty/unixsocket/server/UnixSocketConnector.java#L51-L58

This implementation requires a JNA layer from com.github.jnr:jnr-unixsocket and is the likely cause of your issues.

We recommend using the `org.eclipse.jetty.unixdomain.server.UnixDomainServerConnector` together with Java 17 (or later).

https://github.com/eclipse/jetty.project/blob/jetty-10.0.16/jetty-unixdomain-server/src/main/java/org/eclipse/jetty/unixdomain/server/UnixDomainServerConnector.java

Going this way makes the JVM responsible for providing basic Unix Domain Socket behaviors, and is far more reliable, esp on non-x86 platforms (like yours).

**Comment by staktrace** [comment]
Thanks for the quick response! Can you expand a bit on the Java 17 requirement here? In particular, does it only require the Java 17 JDK at compile time, or does it also require setting a compile target of Java 17? (Our setup uses JDK 17 to compile but for compat reasons we are targeting Java 11 in the generated bytecode).

Also if there are any alternatives that don't require upgrading to Java 17 I'd be interested to hear them. 🙇

**Comment by joakime** [comment]
You need to target Java 17 (or greater).

Jetty's `UnixDomainServerConnector` uses the Unix Socket support built into the JVM since JDK 16 (released early 2021)

* [`java.net.UnixDomainSocketAddress`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/UnixDomainSocketAddress.html) 
* [`java.nio.channels.ServerSocketChannel.open(ProtocolFamily)`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/channels/ServerSocketChannel.html#open(java.net.ProtocolFamily))
* [`java.net.StandardProtocolFamily.UNIX`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/StandardProtocolFamily.html#UNIX)

There are no reliable alternatives for UnixSocket (any OS) with JDK 11.

Be aware that JDK 11 support in various cloud providers is going away soon (some as soon as Jan 2024, the rest by Jan 2025).
Few open source libraries are still supporting JDK 11 anymore.
BTW, JDK 21 (GA) was released a few days ago, and many groups have already announced min SDK requirements with JDK 21.
(Jakarta EE 11 is JDK 21 minimum, Tomcat is now JDK 21 minimum, Spring & Spring Boot are JDK 21 without a commercial support contract, etc)

**Comment by sbordet** [comment]
Java 17 is required at runtime because support for Unix-Domain socket in the JDK has been added in Java 16.

In Jetty 10/11 we use reflection to access the new Unix-Domain APIs, to maintain compatibility with Java 11 at the source level.

In Jetty 12 Java 17 is the minimum requirement, and we recommend you to upgrade, especially now that Java 21 is out.

**Comment by staktrace** [comment]
Thanks for the additional detail! We would very much love to move to Java 17 but some of our common libraries are used in Flink applications which currently only supports Java 11. Once Java 17 support lands for that we will definitely upgrade.

**Comment by sbordet** [comment]
Closing, as upgrading to Java 16+ solves the issue.
