### ISSUE TITLE
Jetty startup so slow

### ISSUE THREAD

**Issue by nguyennhatdung** [eclipse/jetty.project#10610]
**Jetty Version**
12

**Jetty Environment**
ee10

**Java Version**
Debian 11 64bit, OpenJDK 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)

**Question**
Jetty startup so slow, for me it tock ~17 sec , how to reduce it ?

> Java start @ 28/09/2023 12:20:00
> WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
> [main] INFO org.eclipse.jetty.server.Server - jetty-12.0.0; built: 2023-08-07T17:14:07.160Z; git: 52d94174e2c7a6e794c6377dcf9cd3ed0b9e1806; jvm 20.0.1+9-29
> [main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started oeje10s.ServletContextHandler@5be067de{ROOT,/,b=null,a=AVAILABLE,h=oeje10s.ServletHandler@7383eae2{STARTED}}
> [main] INFO org.eclipse.jetty.ee10.servlet.ServletContextHandler - Started oeje10s.ServletContextHandler@5be067de{ROOT,/,b=null,a=AVAILABLE,h=oeje10s.ServletHandler@7383eae2{STARTED}}
> [main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@44c79f32{HTTP/1.1, (http/1.1)}{127.0.0.1:7071}
> [main] INFO org.eclipse.jetty.server.Server - Started oejs.Server@207ea13{STARTING}[12.0.0,sto=0] @17339ms
> 2023-09-28 12:20:17.891 INFO [Main.java] [loginfo] [20] - Server is running

**Comment by gregw** [comment]
Typically such slow starts are caused by web applications that have many jars in WEB-INF/lib that need to be scanned for annotations, TLDs etc.
Do you have many jars in WEB-INF/lib?
Can you try deploying a simple webapp with fewer jars and confirming if the start time is faster?


If this is the cause, then you can look at the [quickstart mechanism](https://eclipse.dev/jetty/documentation/jetty-12/operations-guide/index.html#og-quickstart) to do one slow start and generate a quickstart-web.xml, so that subsequent starts are much faster (typically much less than 1s).

**Comment by nguyennhatdung** [comment]
You're right, i just try deploying a simple webapp and starttime ~1-2sec. seem this slow is somewhere cause by other jar in my app.

Thanks!

**Comment by dVenkatNaveen** [comment]
I am also facing a similar issue, were first time its taking more time to load.

with jetty 11
- localhost - - [14/Oct/2025:10:00:11 +0000] "GET /api/example / HTTP/1.1" 200 95004 1370ms 

with jetty 12 its takes more time to load  8794ms
- localhost - - [14/Oct/2025:09:45:05 +0000] "GET /api/example / HTTP/1.1" 200 12139 8794ms

I am also setting WebAppContext.setExtractWAR(true) during my webAppContext creation.

Thanks
