### ISSUE TITLE
Regression in DefaultServlet handling results in redirect loop

### ISSUE THREAD

**Issue by kohlschuetter** [eclipse/jetty.project#10652]
**Jetty version(s)**
12.0.0.beta4 or newer

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
any

**OS type/version**
any

**Description**
Since 12.0.0.beta4, my embedded Jetty application no longer loads certain files, resulting in a redirect loop from {@code file.js} to {@code file.js/} to {@code file.js}, etc.

This is due to the check for `isDefaultMapping` in `DefaultServlet.getEncodedPathInContext` returning `false`, which then turns to wrongly encoding a path from `req.getPathInfo` (which is `null` in my case).

The code in question was introduced in 248354f64aaf84995832abc61088874c49c368b5, in order to fix https://github.com/eclipse/jetty.project/issues/9910

The new code breaks because in my setup, I have a caching servlet mapping for *.js that refers back to DefaultServlet whenever necessary.

I was able to get it working again by changing `DefaultServlet.isDefaultMapping` to return `true` not only for `MappingMatch.DEFAULT` but also for `MappingMatch.EXTENSION`. All tests pass.

**How to reproduce?**

```
git clone https://github.com/kohlschuetter/dumbo.git
git checkout f60828bd8f7b59b8d0dcd9ecc366ce32e183857e
cd dumbo
mvn clean install
cd dumbo-helloworld
mvn exec:java -DmainClass=com.kohlschutter.dumbo.helloworld.console.ConsoleDemoApp
```
Open `http://127.0.0.1:8081/consoleDemo.jsp` in browser.

An interactive webpage should show, no errors.
Instead, due to the bug, the app is broken.
Downgrade jetty to 12.0.0.beta3 in dumbo-core/pom.xm (and rebuild) to confirm.

**Comment by janbartel** [comment]
@kohlschuetter unfortunately that project doesn't build - the `dumbo-jabsorb` module is missing. I tried just looking at the code, but it's a little complex to work out what's going on. Could you please just post:

-  a summary of all servlets you have mapped along with their mappings
- a sample request and how you expect it to be handled (ie forwards/includes/redirects sequences)

**Comment by kohlschuetter** [comment]
@janbartel Oh, looks like the dumbo-jabsorb module was not public, and some snapshot dependencies need to be resolved by enabling a certain Maven profile.

Please try again, and run the following command instead:

```
git clone https://github.com/kohlschuetter/dumbo.git
cd dumbo
git submodule update --init --force --depth=1
git checkout f60828bd8f7b59b8d0dcd9ecc366ce32e183857e
mvn clean install -Duse-snapshots
cd dumbo-helloworld
mvn exec:java -DmainClass=com.kohlschutter.dumbo.helloworld.console.ConsoleDemoApp
```

**Comment by kohlschuetter** [comment]
@janbartel If you want to inspect code, please look at `dumbo-core/src/main/java/com/kohlschutter/dumbo/JspJsServlet`, which is registered for `*.js`, and then calls out to the `DefaultServlet` on certain conditions.

Registration happens in `dumbo-core/src/main/java/com/kohlschutter/dumbo/AppHTTPServer`, method `mapServlets`; the mapping itself is defined via Java annotations in `dumbo-core/src/main/java/com/kohlschutter/dumbo/BaseSupport`.

**Comment by kohlschuetter** [comment]
FWIW, I was now able to workaround this breaking change by changing my Servlet to a Filter (which is the right thing anyways).

**Comment by janbartel** [comment]
> @janbartel Oh, looks like the dumbo-jabsorb module was not public, and some snapshot dependencies need to be resolved by enabling a certain Maven profile.
> 
> Please try again, and run the following command instead:
> 
> ```
> git clone https://github.com/kohlschuetter/dumbo.git
> cd dumbo
> git submodule update --init --force --depth=1
> git checkout f60828bd8f7b59b8d0dcd9ecc366ce32e183857e
> mvn clean install -Duse-snapshots
> cd dumbo-helloworld
> mvn exec:java -DmainClass=com.kohlschutter.dumbo.helloworld.console.ConsoleDemoApp
> ```

@kohlschuetter thanks for those updated instructions. I can now run the demo. It works fine for me with no infinite redirects. ISTR that an early beta of jetty-12 may have had that issue, so simply updating to the most recent release may have done the trick. However, yes, I think it would be better if you changed your code a little rather than calling the `service()` methods of other servlets directly.

Whilst I was investigating this, I enabled a `dumpAfterStart` on the `Server` and discovered this:

```
|     |  |  |  +> servletMappings oeje10s.ServletHandler@55ab5a0b{STARTED} size=5
|     |  |  |  |  +> [/]=>org.eclipse.jetty.ee10.servlet.DefaultServlet-ad72ea0
|     |  |  |  |  +> [*.jsp]=>com.kohlschutter.dumbo.JspCachingServlet-26dae73f
|     |  |  |  |  +> [*.js]=>com.kohlschutter.dumbo.JspJsServlet-370cd29e
|     |  |  |  |  +> [/]=>default
|     |  |  |  |  +> [*.jsp, *.jspf, *.jspx, *.xsp, *.JSP, *.JSPF, *.JSPX, *.XSP]=>jsp
```

This seems very wrong: there should not be different servlets mapped to the same patterns, as has occurred for `/` and `.jsp`.  I can see that the first ones come from your use of the jetty api to define the servlets. The others come from the webapp's parsing of `webdefault.xml`. Really, jetty should prevent these duplications from happening, so I have raised this issue to track it:   #10661

**Comment by kohlschuetter** [comment]
@janbartel When you run the commands, do you see 

```
This is a test message
Exception
javaClass
Exception Message
```

when you open the page int the browser? If so, you're hitting the bug.

Open the browser's network inspector to see which files were requested, and which didn't succeed to load (there are several failures)

Also try to `curl -i http://127.0.0.1:8081/js/consoleDemo.js` and see that it 302-redirects to `http://127.0.0.1:8081/js/consoleDemo.js/` (with a trailing slash), but then fails with 404.

**Comment by janbartel** [comment]
@kohlschuetter yes, I see those messages. I see the failures in the browser network inspector.

Your application is very complex, you have multiple `WebAppContexts` and lots of special handling eg invoking `service()`  methods directly which is making it really hard to pinpoint a particular problem.

I think some of your problem is caused by the multiple definitions for the same servlet mapping from  your use of the jetty api, and then the application of `webdefault-ee10.xml` as I outlined earlier. You could try making sure that for those contexts where you want _your_ default servlet and _your_ jsp servlet  that the default `webdefault-ee10.xml` is not applied by defining your own, minus the `DefaultServlet` and `JettyJspServlet`.

To get any further here I really need the smallest, simplest reproducer project.

**Comment by kohlschuetter** [comment]
Thanks for looking into it, @janbartel.

Since I've found a workaround (use a filter, don't invoke service on a directly referenced `DefaultServlet`), this issue can be closed. It's likely that this is an edge case.
