### ISSUE TITLE
Multiple identical `Set-Cookie` response lines produced

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#10797]
**Jetty version(s)**
Jetty 12

**Jetty Environment**
All: ee10, ee9, ee8

**Java version/vendor** `(use: java -version)`
OpenJDK 17

**OS type/version**
Linux / Ubuntu

**Description**
Multiple `Set-Cookie` response lines produced.

**How to reproduce?**

When testing for the bug reported in issue #10794 it was noticed that the response produces multiple `Set-Cookie` lines.
See below, testing with Jetty 12.0.2 with ee10-demos, using curl.

```
[tmp]$ curl -vvv http://localhost:8080/ee10-test?a=b
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /ee10-test?a=b HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Server: Jetty(12.0.2)
< Set-Cookie: visited=yes
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Set-Cookie: visited=yes
< Set-Cookie: visited=yes
< Location: /ee10-test/;a=b
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

This produced 3 identical `Set-Cookie: visited=yes` lines.

**Comment by gregw** [comment]
@joakime 
The `org.eclipse.jetty.server.Response` class has two methods:  `static void addCookie(Response response, HttpCookie cookie)` and `static void replaceCookie(Response response, HttpCookie cookie)`.  The javadoc for `replaceCookie` says: "Replaces (if already exists, otherwise adds) an HTTP cookie to the response."

We are apparently using `addCookie` instead of `replaceCookie` in many/most places.

Simple fix is to change all the calls.... but that will not avoid the mistake being made again in future.  Thus I propose that we:

1. rename `replaceCookie` to `putCookie`, as this matches the add/put semantics of response headers.
2. use `putCookie` in almost every place.
3. add a deprecated `replaceCookie` that calls `putCookie`.

or maybe we should just make addCookie and replaceCookie do the same thing?
