### ISSUE TITLE
Is there a equivalent method for (org.eclipse.jetty.server.Request) request.getConnection().getConnector().getHost() in latest jetty version?

### ISSUE THREAD

**Issue by arjunballa** [eclipse/jetty.project#10894]
https://github.com/jetty/jetty.project/issues/10887

**Comment by joakime** [comment]
The correct way to do this is for the load balancer to add a header to the request before forwarding to the downstream servers.

The correct way is to use the `Forwarded` header Spec -> https://datatracker.ietf.org/doc/html/rfc7239

Your load balancer will just be the earliest address (and port) on the list.

Then the information can be obtained via the `Request` object.
The `Request` object can even be customized with the information from the `Forwarded` by using the [`ForwardedRequestCustomizer`](https://eclipse.dev/jetty/documentation/jetty-12/operations-guide/index.html#og-module-http-forwarded)

A different approach could be be something simple like having the load balancer add a `X-Load-Balancer: lb-myapp.com` header.

**Comment by arjunballa** [comment]
@joakime Thanks for the response. I think there is a little misunderstanding of the question. I want `node1-myapp.com` or `node2-myapp.com` not `lb-myapp.com`. The load balancer is already setting `X-Forwarded-Host` and `X-Forwarded-Port`.

Based on your answer I assume it is not wrong to have load balancer to set a custom header say `X-Forwarded-To:node1-myapp.com` or `X-Backend:node1-myapp.com`.

**Comment by joakime** [comment]
> @joakime Thanks for the response. I think there is a little misunderstanding of the question. I want node1-myapp.com or node2-myapp.com not lb-myapp.com. The load balancer is already setting `X-Forwarded-Host` and `X-Forwarded-Port`.

Both of those Headers are deprecated and have no spec defining them.
Use the Spec defined in RFC-7239 (`Forwarded` header) instead.
That allows for proper chaining of how the request was forwarded, and from there you can get the information you want.

> Is there a equivalent method for (org.eclipse.jetty.server.Request) request.getConnection().getConnector().getHost() in latest jetty version?

That hasn't existed since Jetty 7.1/8.0 days.
That's many major versions of Jetty and even the various specs (ietf and servlet) ago.

That API is deep in the internals of Jetty, and wasn't meant to be used by web applications.

Now, Jetty 12 supports HTTP/1.1, HTTP/2, HTTP/3, FastCGI, UnixSockets, etc ...
The changes in Jetty to support the up to date specs, and new HTTP protocols, and new Servlet specs, and new Java releases, and new Jakarta EE specs, make this kind of deep usage of Jetty internals not viable.

There has also been tremendous effort to never perform a DNS lookup within Jetty. (this is for IP Address to Host, and Host to IP Address).
The best you can hope for is a `SocketAddress` (not even an `InetSocketAddress`) from the `Request` object.

For example the recommended way is to use [`Request.getLocalAddr(Request request)`](https://eclipse.dev/jetty/javadoc/jetty-12/org/eclipse/jetty/server/Request.html#getLocalAddr(org.eclipse.jetty.server.Request)) or [`Request.getRemoteAddr(Request request)`](https://eclipse.dev/jetty/javadoc/jetty-12/org/eclipse/jetty/server/Request.html#getRemoteAddr(org.eclipse.jetty.server.Request)) methods, but they return a `String`, as that's the best way to describe the endpoint details for those connections that don't use IP addresses.

You could even use the [`Request.getConnectionMetaData()`](https://eclipse.dev/jetty/javadoc/jetty-12/org/eclipse/jetty/server/Request.html#getConnectionMetaData()) to access the raw `SocketAddress` for the local / remote (but keep in mind that these can return a null!) - 

Reminder, there's no DNS performed in Jetty, that's up to you to handle.

**Comment by arjunballa** [comment]
@joakime So it was intentional to make `Request.getLocalAddr(Request request)` or `Request.getRemoteAddr(Request request)` return `ipaddress`?

Are there any cases where the above 2 methods return `hostname`? In all the different scenarios I tested including hitting the node directly, routing via load balancer both the methods always returned `ipaddress`.

**Comment by joakime** [comment]
The best choice, and by that I mean **the best choice for you**, is to _not rely on server side connection, or local-addr, or remote-addr_, or whatever.
As all of those choices but a large burden of effort on you to get right (including all of the corner cases and weird values that you can get).
Use the forwarding headers on your load balancer to modify the request to include exactly what the load-balancer has the knowledge of, it's own host name.
This about as close to 100% reliable and brain dead simple for you on the server side as you can get.

> was intentional to make `Request.getLocalAddr(Request request)` or `Request.getRemoteAddr(Request request)` return `ipaddress`?

The concept of local-addr and remote-addr can be _anything_ represented by a String.

Some real world examples:

* null
* blank
* all whitespace
* ipv4 address (any spec format that can be represented by a String: decimal, hex, octal, binary, byte-array, subnet, multicast, with port, without port, etc)
* ipv6 address (any spec format that can be represented by a String: long, short, with brackets, without brackets, with port, without port, abbreviated, subnet, local, global, link, site, etc)
* ip literal
* filesystem pathname to socket
* numerical socket reference
* filesystem descriptor id to socket
* logical named end point
* UUID to end point
* any string, of any size and any content (an entire sentence describing the endpoint, sure, why not?  I've even seen a json string describing the endpoint returned here)

> Are there any cases where the above 2 methods return `hostname`? In all the different scenarios I tested including hitting the node directly, routing via load balancer both the methods always returned `ipaddress`.

Careful, "ipaddress" is not a thing to Java.  Even in the limited scope of TCP/IP, you have ...

 * `InetAddress` a representation of an Internet Address, it can be IPv4, or IPv6, or IP Literal
 * `Inet4Address` a representation of a single IPv4 address, doesn't handle many IPv4 string representations. (eg: subnet, with port, etc)
 * `Inet6Address` a representation of a single IPv6 address, doesn't handle many IPv6 string representations. (eg: global, link, with port, etc)
 * `InetSocketAddress` a representation of an connected Internet Address (eg: IPv4, IPv6, etc)

The thing you are referring to as "ipaddress" is probably the `Inet4Address.getHostAddress()` string.

As for host name, there is no DNS performed by Jetty.  

An old school IPv4 connection contains no host name information (never has), it only has a `InetSocketAddress` for both the remote and local sides (each of which is a `InetAddress` and port number)

If you want the hostname, you either have to pass it in via the forwarding request headers (_the best choice, and I cannot emphasize that enough_), or perform the DNS lookup yourself (which is horrible for performance and reliability).

Do not rely on your limited testing and assumptions on how `Request.getRemoteAddr(Request request)` work, please do it properly with the forwarding request headers on the load balancer.
It is easy, far less work/effort, and far more reliable than any other choice.
