### ISSUE TITLE
Review ServletChannelState.asyncError()

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#10933]
**Jetty version(s)**
12

**Description**
`ServletChannelState.asyncError()` is currently not called, but we could wire it again so that if a Servlet calls startAsync(), we register a failure listener that calls `asyncError()` so Servlet may be notified of asynchronous errors.

**Comment by gregw** [comment]
@sbordet @janbartel @lorban @lachlan-roberts 

In core, we use the `ErrorHandler` when the `Callback` passed to `handle(...)` is completed unsuccessfully (either failed directly or succeed call in a bad state (e.g insufficient content written).   To call the `ErrorHandler`, we:
 + wrap the `response` with an `HttpChannelState.ErrorResponse`, which ignores channel failures so a response can be written
 + creates a new `HttpChannelState.ErrorCallback`
 + calls `Response#writeError(request, errorResponse, errorCallback, int, java.lang.String, java.lang.Throwable)`
 + wrap the `request` with `ErrorHandler.ErrorRequest`, which adds error attributes and disables the read API
 + calls the `ErrorHandler.handle(...)` method

This allows core to write an error response even if there has been a failure.

However, in ee10 Servlets, we do not use this mechanism.  Instead handling SEND_ERROR calls the ErrorHandler directly with the unwrapped response and a new `Callback` that calls `ServletChannelState#errorHandlingComplete`. 
The problem here, is that because the response is not wrapped, any core failures will make the write fail.   We could consider doing the same kind of wrapping as in core, but in ee10, we don't really have the ability to bypass and go directly to the HttpStream.

Moreover, that does not help with the use-case of a `HttpChannel.onFailure` being passed to an `AsyncListener.onError` method that wishes to write an error response, but can't be all writes fail because of the core HttpChannel failure, which is not ignored.

The problem with the async use-case, is that the async listener will use the original request/response object and thus cannot be given any wrapper.    So if we do use an `ErrorResponse` approach, then it needs to be inserted underneath the `ServletApiResponse` to be used by the servlet API once we are in error handling mode.

**Comment by sbordet** [comment]
Fixed by #10949.
