### ISSUE TITLE
AbstractNCSARequestLog reports too much of the Request URI

### ISSUE THREAD

**Issue by hjoliveira** [eclipse/jetty.project#1103]
Hello,

AbstractNCSARequestLog uses request.getHttpURI() to determine the requested resource: https://github.com/eclipse/jetty.project/blob/83f868e473908f6f46d425d6cdda1351a2505334/jetty-server/src/main/java/org/eclipse/jetty/server/AbstractNCSARequestLog.java#L142

My interpretation of the NCSA log format (http://publib.boulder.ibm.com/tividd/td/ITWSA/ITWSA_info45/en_US/HTML/guide/c-logs.html#ncsa) is that this should be the path to the resource and not the full request URI.

Is this an issue, or is my understanding of the format wrong?

Thanks!

**Comment by joakime** [comment]
The "requested resource" field of the NCSA log format is the piece of information that was requested, if the entire URI was requested (including host, port, path, and query), then that is what is represented by `request.getHttpURI()`.

What information in the HTTP URI are you concerned about?

**Comment by hjoliveira** [comment]
I'm using AbstractNCSARequestLog to generate access logs on a Spring Boot application and am expecting only the relative path to the resource to be logged. However, I am seeing the full URI, including protocol, host and port. For example, I am getting: `http://host:port/resource/id` instead of: `resource/id`.

Right now this is causing some issues down the line when parsing the access log, so I am trying to understand if it is an issue while logging, or if our parser should be relaxed to accept the full URI.

**Comment by joakime** [comment]
The example in your NCSA access logging document shows a HTTP/1.0 request for a simple resource. 

    GET /index.html HTTP/1.0

Since its HTTP/1.0 it doesn't have/require a `Host` header, which means the requested resource is host-less, scheme-less, port-less, and relative to whatever is the root context of that web server.

In contrast, a HTTP/1.1 request would look like this ...

    GET /index.html HTTP/1.1
    Host: localhost:8080
    Connection: close

That "requested resource" would have a host, port, and path.  Since we have the port, we know what the scheme will be from the provided `HttpConfiguration` startup objects.   This results in a complete "requested resource" of `http://localhost:8080/index.html`

**Comment by hjoliveira** [comment]
I think that link was a bad example. I can't really find a concrete spec for the NCSA format, but I've seen other examples using HTTP 1.1 where the log line includes only the relative resource path:

http://www.eclipse.org/jetty/documentation/9.3.x/configuring-jetty-request-logs.html
http://www.loganalyzer.net/log-analyzer/apache-combined-log.html 

In my particular case the scheme is what's causing my parsing problems. The scheme doesn't show up for all requests though. Is there anything else Jetty looks at to determine if the scheme should be logged?

**Comment by gregw** [comment]
It is because of the development of HTTP/2 that we have become more explicit in our request logs.

With HTTP/1.0, there was a clear difference between:

```HTTP
GET /some/path HTTP/1.0

```
and
```HTTP
GET http://somehost/some/path HTTP/1.0

```

With HTTP/1.1 things became a little more murky with all of the following being options

```HTTP
GET /some/path HTTP/1.1
Host: somehost

```

```HTTP
GET http://somehost/some/path HTTP/1.0
Host: somehost

```

```HTTP
GET http://somehost/some/path HTTP/1.0
Host: wronghost

```

With HTTP/2 there is no longer a distinction between if a host is supplied or if the URI is absolute or not. All requests effectively come as:
```
:method: GET
:host: somehost
:path: /some/path

```

Logging in full is the best and simplest solution.    If this is a problem for you down stream, it should be simple to post process the log files to throw away the absolute parts of the URI.     

If you wanted to give us a PR, where the log optionally does the work to strip that off, then we would consider it.

But generally speaking, URIs are best represented as absolute

**Comment by gregw** [comment]
Actually looking at this I think we can do better in 9.4... stand by

**Comment by gregw** [comment]
the ed14d73 commit is a bit of a mixed bag commit (oops) but in there is a change as to how the original URL is captured (which is used for logging).

If it is absolute and the request is not HTTP2, then the full URI is captured (and logged).  Otherwise only the relative path and query are captured and logged.

I'm not overly fond of this solution, but I'm not sure we can do better with the redundant information that can be in HTTP <2 ie the host can be in the URI and/or headers and that the scheme may be defaulted or in the headers.

**Comment by hjoliveira** [comment]
Awesome, thanks for the answers and the changes guys!

In the end I changed my downstream parser as well as I agree it should be more robust.
