### ISSUE TITLE
Add testcase for WSUF for stop/start of the Server

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1114]
There are reports from the CometD side that changes in issue #854 has broken the ability to stop/start the server when WebSocketUpgradeFilter is in use.

Reports of Destroyed WSUF not being able to be restarted.

**Comment by joakime** [comment]
@sbordet I found a simpler solution then a new API.  Just persist mappings that were added before the configuration was started.  (Configurations added after start are reset/cleared)

See branch/commit

**Comment by sbordet** [comment]
@joakime that is what we called "magic" solution, which I am not opposed to.

However, the implementation looks weird; I would have added another field, say `NativeWebSocketConfiguration.persistentMappings`, that would not have required `removeIf()`, a wrapper `WebSocketCreator`, etc.
There would be a problem if you had a persistent mapping _and_ an application mapping for the same path spec ? I don't think, since I don't see any checks for duplicate mappings.

Do we really need `exportConfiguration` now ? It does not matter much if the configuration is exported because now the differentiation is made in `addMapping()` testing whether it is running or not.

**Comment by joakime** [comment]
Merged into jetty-9.3.x, considering this finished/closed.
