### ISSUE TITLE
Jetty12 doesn't set the Date response header when using localhost

### ISSUE THREAD

**Issue by wodeidaiga** [eclipse/jetty.project#11292]
**Jetty Version**
12.03
**Jetty Environment**

ee10
**Java Version**
17.0.9
**Question**

Jetty doesn't set the Date response header when using localhost.
If using the domain name to access it the response Date header will be set.
Is it an expected behavior or some additional configuration needs to be configured?
Thanks!

**Comment by joakime** [comment]
Check your `HttpConfiguration`.

See if your `.setSendDateHeader(true)` is set. (it defaults to true, so if you don't set it, it should remain true).

But this doesn't explain the difference in behavior you are seeing between calling a handler with `Host: localhost` vs `Host: example.org` vs `Host: 192.168.1.1`

**Comment by joakime** [comment]
Was able to replicate the fact that the `Date` header is not present when using Standlone / jetty-home.
But I was unable to replicate the differences when making the same request to the same server but using different Host names.
Opened PR #11293 for what I was able to find.

**Comment by janbartel** [comment]
@chiqiu  can you provide a reproduction test case that makes clear how the hostname difference affects the `Date` header, as it is not obvious. As @joakime says, when using embedded mode, by default jetty will send the `Date` header, but when using the distro the default is not to send the `Date` header. Not an ideal situation, but it's been that way since at least jetty-9.4.  But either way, I don't see the involvement of the hostname, so a repro test case will be necessary.

**Comment by janbartel** [comment]
@chiqiu nudge?

**Comment by wodeidaiga** [comment]
> @chiqiu nudge?
Sorry,
I will try to upload a test , I was too busy these two days
Thanks
