### ISSUE TITLE
empty host in redirect

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1131]
For request without a host specified, redirections have an empty host!

```
[2000] telnet www.webtide.com 80
Trying 107.22.210.238...
Connected to webtide.com.
Escape character is '^]'.
GET / HTTP/1.0

HTTP/1.1 301 Moved Permanently
Content-length: 0
Location: https:///
Connection: close

Connection closed by foreign host.
```

**Comment by gregw** [comment]
@sbordet I can't reproduce on just jetty.  It must be something about the way haproxy is setting the host on webtide.com.      Can you have a look at this?

**Comment by sbordet** [comment]
```
$ telnet webtide.com 80
Trying 107.22.210.238...
Connected to webtide.com.
Escape character is '^]'.
GET / HTTP/1.1
Host: webtide.com

HTTP/1.1 301 Moved Permanently
Content-length: 0
Location: https://webtide.com/
Connection: close
```

Also:

```
telnet webtide.com 80
Trying 107.22.210.238...
Connected to webtide.com.
Escape character is '^]'.
GET / HTTP/1.1
Host: foo.com

HTTP/1.1 301 Moved Permanently
Content-length: 0
Location: https://foo.com/
Connection: close
```

**Comment by sbordet** [comment]
It's a normal behavior for HAProxy because we use the `redirect scheme` directive, see http://cbonte.github.io/haproxy-dconv/1.6/configuration.html#4.2-redirect%20scheme.

> If no "Host" header is found, then an empty host component will be
   returned, which most recent browsers interpret as redirecting to
   the same host.

@gregw, is this a problem for you ?
We can fancy up the `redirect` directive if needed.

**Comment by gregw** [comment]
OK nothing to do with Jetty! still a bit strange!
