### ISSUE TITLE
Jetty 12.0.5 source code  build failed

### ISSUE THREAD

**Issue by Helly987** [eclipse/jetty.project#11311]
Jetty 12.0.5 build failed
with build command: mvn -Pfast clean install
mvn -v  3.9.6
java --version 21.0.1
![image](https://github.com/jetty/jetty.project/assets/150114018/b0f001c6-0d51-438f-b5e2-92343c0e5400)
![image](https://github.com/jetty/jetty.project/assets/150114018/4281e6c8-57b1-4c11-9f40-164d5fb569e1)
![image](https://github.com/jetty/jetty.project/assets/150114018/a23f923f-75ee-4795-9acb-323e060525eb)

Please check this issue, thanks.

**Comment by joakime** [comment]
Fixed in `jetty-12.0.x` HEAD for Jetty 12.0.6-SNAPSHOT via commit 6ae676c7d6c960685011f57a4fb6e14c088ee7c9

**Comment by joakime** [comment]
Note that it is quite common for the tests to fail on Microsoft Windows.

This is commonly due to the large variety of ways people clone the repo into unique and interesting directory locations, but also due to other system factors (like locales, encodings, etc)

(in directories that are too deep and you trigger path size limits on windows, in hardlinks and triggering alias handling, in softlinks and triggering different alias handling, in directories with unicode characters and triggering yet another form of alias handling, in directories with spaces and triggering bugs in the build tools & libs themselves, with highly unusual locales, etc)

**Comment by Helly987** [comment]
> Fixed in `jetty-12.0.x` HEAD for Jetty 12.0.6-SNAPSHOT via commit [6ae676c](https://github.com/jetty/jetty.project/commit/6ae676c7d6c960685011f57a4fb6e14c088ee7c9)

Yes, correct.
git checkout 12.0.x, 
build jetty-home-12.0.6-SNAPSHOT successfully. 
Thanks a lot.
