### ISSUE TITLE
A single ScheduledExecutorScheduler should be used

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1141]
Currently, it seems that every Connector instantiates its own ScheduledExecutorScheduler.

WebSocket also needs access to a Scheduler, and creates its own ScheduledExecutorScheduler.

It would be nice to have access to a server-wide ScheduledExecutorScheduler in the same way we can access the server wide Executor/ThreadPool

``` java
// What we have already
Executor executor = server.getExecutor();
// What would be a nice to have
Scheduler scheduler = server.getScheduler();
```

**Comment by joakime** [comment]
@sbordet this is the issue for the concern you raised during the websocket review.

**Comment by sbordet** [comment]
Connectors can be created sharing a  `Scheduler` using the constructor that takes a `Scheduler` parameter. If this parameter is `null`, then `AbstractConnector`'s constructor looks up a `Scheduler` bean on the `Server` instance and if still `null` it creates one (per connector instance).

`ThreadPool` is treated differently from `Scheduler` and `ByteBufferPool`, but I agree that it would make sense to have a centralized place (`Server`) to configure both the `Scheduler` and the `ByteBufferPool` that other component can pull using getters, rather than bean lookups.

**Comment by sbordet** [comment]
Fixed in 12.
