### ISSUE TITLE
Add UriCompliance rules that follow the HTTP / URI / Servlet specs for illegal & suspicious characters

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#11495]
**Jetty version(s)**
12.0.7

**Jetty Environment**
Any (esp ee10)

**Java version/vendor** `(use: java -version)`
Any

**OS type/version**
Any

**Description**
The URI spec, HTTP spec, and Servlet Spec have rules around what are allowed characters in the Request-Target of an HTTP request, and the path portion of a URI.
We are too permissive with our HttpURI implementation.

Add UriCompliance rule(s) to follow the spec behaviors, but allow those behaviors to be overridden with configuration.

See:
 * https://jakarta.ee/specifications/servlet/6.0/jakarta-servlet-spec-6.0.html#uri-path-canonicalization
 * https://datatracker.ietf.org/doc/html/rfc3986#section-3.3
 * https://datatracker.ietf.org/doc/html/rfc7230#section-5.3

**Comment by luelueking** [comment]
Because of the time difference, I may need to sleep now. I will be very grateful if you can debug the code carefully or review what I said. I will check the latest status tomorrow morning. :) I think the most fundamental reason is that spring uriutils decode is not up to standard, which will face more potential security issues
