### ISSUE TITLE
Multi-level context path

### ISSUE THREAD

**Issue by flopma** [eclipse/jetty.project#1158]
Hi,

We are in need to setup a Jetty instance (under Karaf), with a multi-level context path, such as /foo/bar (doc for [Tomcat](http://tomcat.apache.org/tomcat-8.0-doc/config/context.html#Naming))

Is this possible for Jetty v9.3.7? I couldn't find a documented way to do this.

Many thanks in advance.

**Comment by janbartel** [comment]
@flopma I think this is more of a question rather than a bug report, so it probably belongs over on the jetty-users@eclipse.org mailing list.

But while we're here ...

Here's the link to the jetty-9.3 doc on setting context paths: 
https://www.eclipse.org/jetty/documentation/9.3.x/configuring-contexts.html#setting-context-path

Here's an example of setting a context path of "/foo/bar" using xml:
```xml
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
  <Set name="contextPath">/foo/bar</Set>
</Configure>
```

If you've got a more specific question, with more information I urge you to ask it over on the mailing list.

**Comment by flopma** [comment]
@janbartel thx a lot for your reply. Going to check this out
