### ISSUE TITLE
Document Jetty 10 changes to Websocket

### ISSUE THREAD

**Issue by WalkerWatch** [eclipse/jetty.project#1165]
Update documentation for Websocket to reflect 9.4 changes.

Includes:
* HttpClient Integration
* WebSocketUpgradeFilter used in WEB-INF/web.xml

**Comment by WalkerWatch** [comment]
Closing for now until Websocket changes are finished.

**Comment by joakime** [comment]
Discussing some important changes in 9.4.7 with @sbordet that will definitely need to be documented.

Add Configuring WebSocketClient on JSR356 to the list.

**Comment by sbordet** [comment]
@WalkerWatch I think this issue should be renamed, as the changes are now happening on 10.0.x ?

**Comment by lachlan-roberts** [comment]
Just looked through the current WebSocket documentation in jetty-10.0.x and picked up a few things which should be updated because of the recent changes.

**Enabling WebSocket**
- enable key should be `org.eclipse.jetty.websocket.javax` not `org.eclipse.jetty.websocket.jsr356` which is now deprecated
- `org.eclipse.jetty.websocket.jsr356.server.deploy.WebSocketServerContainerInitializer` does not exist anymore, that would be `org.eclipse.jetty.websocket.javax.server.JavaxWebSocketServletContainerInitializer`

**WebSocket Session**
- `session.getRemoteAddress()` now returns only `SocketAddress` not `InetSocketAddress`
- `session.setIdleTimeout(long)` now takes `Duration`

**Send Messages to Remote Endpoint**
- Async Send Message
    - sendByFuture methods are now deprecated, use the methods taking `WriteCallback` instead

**Jetty WebSocket Server API**
- `JettyWebSocketServlet` instead of `WebSocketServlet`
- `JettyWebSocketCreator` instead of `WebSocketCreator`
- `JettyWebSocketServletFactory` instead of `WebSocketServletFactory`
- broken link on bottom of page

**Comment by lachlan-roberts** [comment]
@WalkerWatch do you want me to work on make these changes

**Comment by WalkerWatch** [comment]
Fixed with #4172
