### ISSUE TITLE
Please specify Eclipse-SourceReferences

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse/jetty.project#1177]
During work on [bug 484004](https://bugs.eclipse.org/484004) I noticed that jetty artifacts do not specify Eclipse-SourceReferences as is recommended.

To wit: jetty appears in the negative list in https://hudson.eclipse.org/simrel/job/simrel.neon.runaggregator.BUILD__CLEAN/lastSuccessfulBuild/artifact/aggregation/final/buildInfo/reporeports/reports/esdata.txt

See also http://wiki.eclipse.org/PDE/UI/SourceReferences

For now, could s.o. please provide the repository location and Neon.2 release tag for the following bundles?

   org.eclipse.jetty.continuation
   org.eclipse.jetty.http
   org.eclipse.jetty.io
   org.eclipse.jetty.util
   org.eclipse.jetty.security
   org.eclipse.jetty.server
   org.eclipse.jetty.servlet

For now I will "manually" insert this required information into pom.xml before publishing to Maven Central.

Future builds should have it automated via MANIFEST.MF

Additionally, the above list might be incomplete. It was created by aggregating the Eclipse SDK feature. Does jetty have a more complete feature which should be included in repository aggregation for publishing in Maven Central?

thanks

**Comment by joakime** [comment]
scm information is most definitely present in the poms for all jetty releases.
there was a short amount of time when it was inaccurate when we moved from git.eclipse.org to github.com as our primary scm location, but otherwise it was present and would still function.

```
$ git remote show origin | grep URL
  Fetch URL: git@github.com:eclipse/jetty.project.git
  Push  URL: git@github.com:eclipse/jetty.project.git
$ mvn -N help:effective-pom | grep scm
  <scm>
    <connection>scm:git:https://github.com/eclipse/jetty.project.git</connection>
    <developerConnection>scm:git:git@github.com:eclipse/jetty.project.git</developerConnection>
  </scm>
```

We also do not participate in the Eclipse Release Train, we are often too far ahead of Eclipse itself in terms of minimum requirements.

**Comment by stephan-herrmann** [comment]
Thanks for answering. Still we seem to be speaking about slightly different topics.

Let me start by asking: how are jetty artifacts published? I don't see them on Maven Central (in recent versions), right? OTOH, jetty is part of the Eclipse Project release (aka SDK), which only publishes (products plus) a p2 repository, no maven artifacts.
My problem now is: I'm working from the Eclipse p2 repo, which has no poms, and this repo I'm converting into a Maven repo. Here I only have p2 data + MANIFEST.MF as my input.
Most other projects provide the scm information by the recommended Eclipse-SourceReferences mechanism via MANIFEST.MF.

If all jetty artifacts are hosted in the same repo, I can insert that url "manually". Additionally I'd like to add the tag for those versions that are part of Neon.2. Could you please provide that? Or even better: how can that information be retrieved automatically (in particular for future releases)?

About not participating in SimRel sounds strange to me, given that jetty artifacts are contained in that repo, but that's a different story ...

**Comment by joakime** [comment]
Reading the provided links, this request has nothing to do with Maven, the Maven Pom, or Maven Central.

Its seemingly a request to duplicate information that's already present in every maven artifact already (the build/scm details in the pom included in the artifact. a requirement to even publish to the global repository system) as a new `META-INF/MANIFEST.MF` header.

New Header:
```
Eclipse-SourceReferences: scm:git:https://github.com/eclipse/jetty.project.git
```

Why?

Shouldn't Eclipse PDE be smart enough to utilize the more popular source for this information? (The use of Eclipse Aether gives you this already)
What is the purpose of this information? (the PDE/UI/SourceReferences stated goal of being able to see the source is unique and is utilizing none of the effort already spent in Eclipse Aether and Eclipse IDE for the same stated goal)
This information has nothing to do with OSGi or the bundle concept, why pollute the META-INF/MANIFEST.MF with it?
This information will also be identical in all Eclipse Jetty artifacts.  
Due to the nature of how a Maven release process works, the tag information (as seen in your linked PDE/UI/SourceReferences) cannot be inserted into this `Eclipse-SourceReference` header at all, leaving this to be tag-less for all releases.

You know that to publish on Maven Central, the oss.sonatype.org rules specify that the artifact *must* also have an associated `-source.jar` too, right?  Why can't Eclipse PDE use that far more common and accessible feature of Maven Central?  Why reinvent the wheel here?

Should this be added to Eclipse Jetty, then it will show up starting in Jetty 9.3.x and onwards (which has a Java 8 minimum requirement).  When will Eclipse start to use Jetty 9.3?

Note: our current stable releases are Jetty 9.4.x and we are working on Jetty 10 (Java 9 / Servlet 4 minimum requirement) ATM.

**Comment by joakime** [comment]
Eclipse Jetty releases to Maven Central already (every single release in the history of Eclipse Jetty is there, including pre-Eclipse Jetty releases back many years)

http://search.maven.org/#search%7Cga%7C1%7Cg%3Aorg.eclipse.jetty

Note: while we do publish a p2 repository, it is currently only on-demand (someone requests it).

**Comment by stephan-herrmann** [comment]
Several of the questions you raise can probably answered only by the corresponding PMC, which I'm not a member of. I just try to implement a solution so that artifacts can be published to Maven Central.

For one, Eclipse-SourceReferences pre-dates the use of tycho, which should answer the "why", at least in historical terms :)

And the build tools used at Eclipse.org are all able to insert the release tag into the manifest header during build.

The issue is also orthogonal to -sources.jar, but here the term "source" just seems to be overloaded.

But seeing jetty on Maven Central actually resolves the issue for me: I should simply exclude jetty from the repo I'm preparing for publishing, since it's already there. I did search for jetty on search.maven.org, but apparently my search-fu didn't suffice, as the newest I could find was from 2007. Thanks for the reference!

**Comment by joakime** [comment]
The Eclipse Jetty build is too advanced to utilize the build tooling at Eclipse.org.

We are consistently a few years ahead of what the majority of Eclipse utilizes, they'll catch up with us eventually :-)

We utilize the "Maven Release Process" (a well defined/documented process at maven.apache.org) which tags on its own, outside of the build/knowledge.   While the published information on maven central could be levered (nasty git tricksess) to include the tag in the META-INF/MANIFEST.MF, the associated source files on that tag would not reflect that tag information.  Would this be acceptable?

**Comment by jmcc0nn3ll** [comment]
We publish a P2 repository as a convenience for some users, it is comprised of a selection of our published artifacts from maven central and is generated using artifacts that are downloaded from maven central.  We do that build from [1].  It draws the build bits from [2] which is a maven wrapper using tycho to grab artifacts from maven and run them through that weird pack/unpack/pack 200 process eclipse whipped up.

1. https://hudson.eclipse.org/shared/view/Jetty-RT/job/jetty-rt-bundles-9/
2. org.eclipse.jetty.releng.bundles.git (eclipse repo, can't get direct link atm, eclipse page is messed up)

If you have changes to Jetty metadata you want made in our manifests we are happy to look into it, we use the maven bundle plugin to generate the lion share of what is needed osgi wise and so long as we can do something using that system then we are generally open to it.  We support the usage of Jetty in osgi systems as much as we reasonably can.

I'll close this issue out for the time being, if there is something else you need along these lines feel free to reopen or make a new one and reference back.
