### ISSUE TITLE
client: Allow AsyncContentListener.onContent to throw checked Exceptions

### ISSUE THREAD

**Issue by mperktold** [eclipse/jetty.project#11800]
**Jetty version(s)**
Jetty 12.x

**Enhancement Description**
[`AsyncContentListener` implements `ContentSourceListener.onContentSource`](https://github.com/jetty/jetty.project/blob/a9b2da533f64b923cf06306b5f5faf2c5132f7ce/jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/Response.java#L181) and delegates to its own hook called `onContent`. Exceptions (or any Throwable really) thrown from onContent are catched and handled inside AsyncContentListener.onContentSource.

Now I have an implementation of `AsyncContentListener.onContent` that writes the content to a file, which can fail with an `IOException`. I would like to let these exceptions bubble up to `onContentSource`, which would handle it nicely. But this is not possible since `IOException` is a checked exception.

There are two workarounds:
One is to wrap the `IOException` in a `RuntimeException` and before rethrowing it.
The other is to completely handle the exception myself, basically copying the `catch` block from `AsyncContentListener .onContentSource`.

**Comment by mperktold** [comment]
The same would apply to `ContentListener`, which in implements AsyncContentListener.onContent and delegates to its own onContent hook.

Here, I see that the default implementation indeed catches the exception and just aborts the response. `AsyncContentListener.onContentSource` would also notify the content source about the failure, but the source isn't available in `onContent`, so that's not possible there. Is that a problem?

If so, that would be a strong argument for allowing these hooks to throw checked exceptions, such that the failure can be properly detected and forwarded to the source. Otherwise, I guess catching the exception and aborting the response manually could be acceptable as well.

**Comment by lorban** [comment]
I've created a PR to modify the `ContentListener` and `AsyncContentListener` contracts to allow throwing `Exception` as that would be safe and backward compatible: https://github.com/jetty/jetty.project/pull/11825

The fact that `ContentListener` does not fail the source would still make `onContent` be called for all remaining contents despite the fact that the response was aborted. While correct, I believe a more sane default would be to fail the original `Content.Source` so that the flow of content would stop, so the above PR changes that too.

Thanks for the suggestion!
