### ISSUE TITLE
README link is broken

### ISSUE THREAD

**Issue by wendigo** [eclipse/jetty.project#11872]
https://eclipse.dev/jetty/ redirects to https://jetty.org// which renders `HTTP ERROR 400 Ambiguous URI empty segment` 😢

**Comment by stephendnicholas** [comment]
I've just experienced a related issue where https://eclipse.dev/jetty/configure_10_0.dtd is redirecting to https://jetty.org//configure_10_0.dtd, which is causing a web app to fail to start up:

![image](https://github.com/jetty/jetty.project/assets/842691/158dfc54-9568-4cd9-a0f0-2ae40ec9d856)

**Comment by joakime** [comment]
@stephendnicholas you have three things to address.

1. You are using an End of Community Support version of Jetty.

* #10485 
* #7958 

    You should be using a supported version of Jetty.  Which is Jetty 12.0.x at this point in time.

2. you have something wrong with your jetty-xml jar, it shouldn't be going out onto the internet for the configure.dtd.

3. you have a XML that is referencing a 10.0 dtd, but are running a Jetty 9.4.49 version of Jetty (that will never work)

**Comment by jmcc0nn3ll** [comment]
I believe Eclipse is fixing the redirect. I'll post here when I get confirmation.

**Comment by stephendnicholas** [comment]
Thanks for the reply @joakime 

I'm using the Eclipse Jetty integration (https://eclipse-jetty.github.io/) with its out of the box configuration, which I believe has 9.4 bundled inside, and specifies the 10.0 dtd automatically

I could probably look to reconfigure things to try and target a newer version of Jetty, which may then be configured differently, but I don't believe that's directly related to the issue here, and I just wanted to comment to give you a heads-up that the potential impact of this is larger than just a link in a readme (as I imagine a lot of people might be using the Eclipse integration in the same way I am)

**Comment by joakime** [comment]
@stephendnicholas that project is not run by the group here.

It's a standalone project with a different group of developers / committers.

**Comment by joakime** [comment]
@wendigo the redirect should be fixed.
