### ISSUE TITLE
Behavioural change in Jetty 12: POST /non-existing returns 405, instead of 404 (GET /non-existing still returns 404)

### ISSUE THREAD

**Issue by davido** [eclipse/jetty.project#11889]
**Jetty version(s)**
Jetty 12.0.10

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
JDK21

**OS type/version**
Linux

**Description**

We are migrating Gerrit Code Review project to Jetty 12.
This is a non-trivial migration, with many changes in core dependencies, like servlet API and `Google Guice`.

The migration path is:

Jetty 9 => Jetty 10 => Jetty 11 => Jetty 12 (ee10)

In the last migration step: Jetty 11 => Jetty 12 (ee10), we see unit test failures with HTTP status code mismatch: 405 (new) instead of expected 404 status (old):

javatests/com/google/gerrit/acceptance/rest/NotFoundIT.java
```java
  @Test
  public void nonExistingRootCollectionPost() throws Exception {
    RestResponse response = adminRestSession.post("/non-existing/");
    assertThat(response.getStatusCode()).isEqualTo(SC_NOT_FOUND);
    assertThat(response.getEntityContent()).isEqualTo("Not Found");
  }
```

To make the test pass, I have to replace HTTP status 404 with 405:

```java
  @Test
  public void nonExistingRootCollectionPost() throws Exception {
    RestResponse response = adminRestSession.post("/non-existing/");
    assertThat(response.getStatusCode()).isEqualTo(SC_METHOD_NOT_ALLOWED);
    assertThat(response.getEntityContent()).isEqualTo("Method Not Allowed");
  }
```

Note that the `GET /non-existing` still returns 404 in Jetty 12, so that this test is still passing:

```java
  @Test
  public void nonExistingRootCollectionGet() throws Exception {
    RestResponse response = adminRestSession.get("/non-existing/");
    assertThat(response.getStatusCode()).isEqualTo(SC_NOT_FOUND);
    assertThat(response.getEntityContent()).isEqualTo("Not Found");
  }
```

Also note, that in Jetty 11 migration step all Gerrit unit tests were passing.

We have investigated this unit test breakage and concluded, that there was a subtle behavioural change in Jetty 12 compared to Jetty 11 in `DefaultServlet.java`.

./jetty-ee9/jetty-ee9-servlet/src/main/java/org/eclipse/jetty/ee9/servlet/DefaultServlet.java
```java
[...]
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException
    {
        if (!_resourceService.doGet(request, response))
            response.sendError(404);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException
    {
        doGet(request, response);
    }
[...]
```

It can be seen, that both methods: `doGet` and `doPost` are overridden from the  base class (`jakarta.servlet.http.HttpServlet`), and for both methods: `POST` and `GET` HTTP status 404 is returned.

This has been changed in Jetty12 (ee10):

./jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/DefaultServlet.java
```java
[...]
    @Override
    protected void doGet(HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse) throws ServletException, IOException
    {
        String includedServletPath = (String)httpServletRequest.getAttribute(RequestDispatcher.INCLUDE_SERVLET_PATH);
        String encodedPathInContext = getEncodedPathInContext(httpServletRequest, includedServletPath);
        boolean included = includedServletPath != null;

        if (LOG.isDebugEnabled())
            LOG.debug("doGet(hsReq={}, hsResp={}) pathInContext={}, included={}", httpServletRequest, httpServletResponse, encodedPathInContext, included);

        try
        {
            HttpContent content = _resourceService.getContent(encodedPathInContext, ServletContextRequest.getServletContextRequest(httpServletRequest));
            if (LOG.isDebugEnabled())
                LOG.debug("content = {}", content);

            if (content == null || Resources.missing(content.getResource()))
            {
                if (included)
                {
                    /* https://github.com/jakartaee/servlet/blob/6.0.0-RELEASE/spec/src/main/asciidoc/servlet-spec-body.adoc#93-the-include-method
                     * 9.3 - If the default servlet is the target of a RequestDispatch.include() and the requested
                     * resource does not exist, then the default servlet MUST throw FileNotFoundException.
                     * If the exception isn’t caught and handled, and the response
                     * hasn’t been committed, the status code MUST be set to 500.
                     */
                    throw new FileNotFoundException(encodedPathInContext);
                }

                // no content
                httpServletResponse.sendError(404);
[...]
```

^^^ In `doGet` method HTTP status 404 is still returned.

However, `doPost` from the base class is not overridden any more, so that HTTP status 405 is returned from the default implementation:

jakarta/servlet/http/HttpServlet.java
```java
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String protocol = req.getProtocol();
        String msg = lStrings.getString("http.method_post_not_supported");
        resp.sendError(getMethodNotSupportedCode(protocol), msg);
    }
```

Note, that if the `doGet` method from the base class wouldn't be overridden,
then the default implementation from the `HttpServlet` would also return HTTP status 405 for GET /non-existing:

jakarta/servlet/http/HttpServlet.java
```java
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String protocol = req.getProtocol();
        String msg = lStrings.getString("http.method_get_not_supported");
        resp.sendError(getMethodNotSupportedCode(protocol), msg);
    }
```

**How to reproduce?**

Clone gerrit code review [project](https://gerrit.googlesource.com/gerrit), apply this pending [CL](https://gerrit-review.googlesource.com/c/gerrit/+/424580) and run:

```
  $> bazel test //javatests/com/google/gerrit/acceptance/rest:rest_bindings_collection
```

**Comment by joakime** [comment]
DefaultServlet is the "last resort" servlet.

If nothing else matches in the servlet context / webapp, then DefaultServlet is called.
Typically it means some kind of static resource is being requested.

But if a request arrives that isn't GET then it's 405 method-not-allowed.
That means any HTTP methods (that isn't GET or HEAD) will result in a 405 method-not-allowed.

So any of the following HTTP methods would result in a 405 method-not-allowed.
https://www.iana.org/assignments/http-methods/http-methods.xhtml

POST is no more special than any other HTTP method in this regard.

In Jetty versions 11 and older, POST was treated special, but that "special" nature was also a bug that was fixed in Jetty 12.

Either all non GET/HEAD methods against DefaultServlet are 404, or 405.
We chose 405, as the rationale is that you are basically calling `/` as "the servlet" in this case.
That doesn't support POST, PUT, MOVE, MKCOL, DELETE, etc... so returning a 405 made sense.

**Comment by davido** [comment]
Thanks for clarifying.

Other people also noticed that subtle change in Jetty 12 behaviour: #10231
Should this behavioural change be documented somewhere?

**Comment by gregw** [comment]
@davido perhaps this kind of change could have been better documented, but I struggle to think of a form of documentation that a developer would find before their test actually failed with a 405 rather than a 404.  Once that get the 405, surely their next step is to check the doco for that status, which is clearly saying that the method is not supported.  So hopefully that will be understandable for them, that their POST method is not supported.  In fact, you asking the question in this issue is probably the best documentation for issues of this kind (so thank you) as users and AIs are likely to search issues before release notes.

We do try to limit such changes to major versions.  Hence this was done in a 12.0.0 release and not a 11.0.39.

As you can see in the discussion in #10231, it was a strange for the DefaultServlet to handle a POST method as a get and there are complexities with the OPTIONS method of representing that a method might handled when it will not be.
