### ISSUE TITLE
org.eclipse.jetty.http.QuotedCSV  has relation and comply to CSV RFC-4180?

### ISSUE THREAD

**Issue by vfahrenheit** [eclipse/jetty.project#12002]
**Jetty Version** : 12

**Jetty Environment**

core

**Java Version**
17

**Question**
Why org.eclipse.jetty.http.QuotedCSV named as CSV, does it has relation and comply to CSV RFC-4180?

For I try to use a CSV data string, it can not handle escaped DQUOTE just stated in RFC-4180:

` String eic0 = "\"\"\"I, in cvs format\"\"\",\"Hi, A\",\"Hi, B\"";`
`   

    System.out.println("original string: " + eic0);

    try {

      System.out.println("trying jetty util");

      QuotedCSV csv = new QuotedCSV(eic0);

      List<String> values = csv.getValues();

      int i = 0;

      for (String v : values) {

        System.out.println("Column " + i + ": " + v);

        i++;

      }

    } catch (Exception e) {

      e.printStackTrace();

    }`

the output is: 
`Column 0: """I, in cvs format"""

Column 1: "Hi, A"

Column 2: "Hi, B"`

but according to RFC-4180.  for column0 it should be:

Column 0: "I, in cvs format"

**Comment by gregw** [comment]
Because, as the javadoc says it:
 >  Implements a quoted comma separated list of values in accordance with RFC7230.

So it is a different specification of comma separated values for a different purpose than RFC-4180 (and RFC7230 has now been obsoleted by https://datatracker.ietf.org/doc/html/rfc9110#name-quoted-strings)

Now as to why the HTTP spec is so "special" about quotes.... that needs some history investigation.  No idea why, but it is!

**Comment by vfahrenheit** [comment]
thanks for clarification~
