### ISSUE TITLE
IllegalStateException when HTTP/2 push is disabled

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1209]
The client sent a SETTINGS frame with push disabled on connection establishment:

```
2016-12-31 07:39:09.496:DBUG:oejh.HTTP2Session:qtp486994287-279: Received SettingsFrame@ad59ecd,reply=false:{2=0, 3=100}
2016-12-31 07:39:09.496:DBUG:oejh.HTTP2Session:qtp486994287-279: Disable push for HTTP2ServerSession@50edb5e3{l:/<local>:443 <-> r:/<remote>:18510,queueSize=0,sendWindow=65535,recvWindow=65535,s
treams=0,NOT_CLOSED}
```

However, `PushCacheFilter` tries to push anyway. In Jetty 9.3.x this was silently ignored, but in 9.4.x we throw an `IllegalStateException`:

```
java.lang.IllegalStateException: Request(GET https://webtide.com/blogs/)@b0e464c,push=false,channel=ServerHttpChannelOverHTTP2@5517de55{r=3,c=false,a=DISPATCHED,uri=https://webtide.com/blogs/}#5
        at org.eclipse.jetty.server.Request.getPushBuilder(Request.java:278)
        at org.eclipse.jetty.servlets.PushCacheFilter.doFilter(PushCacheFilter.java:261)
```

This is too aggressive, we must just ignore the attempt to push.

**Comment by sbordet** [comment]
@gregw, this is for consideration in Servlet 4.0.

Currently, we guard the call to `Request.getPushBuilder()` by checking if the request is _not_ a pushed request via `Request.isPush()`, since the common interpretation is that only real requests from the client can trigger the push of other resources.

However, the application may not have an API to ask the container if HTTP/2 push has been disabled by a SETTINGS frame for that particular connection.
Does this API exist in Servlet 4.0 ? We kind-of have it in Jetty as `Request.isPushSupported()`.

Therefore currently there are 2 cases, if we guard only with `Request.isPush()`: either `Request.getPushBuilder()` returns `null`, and applications need to perform a null check before using the `PushBuilder`, or a fake `PushBuilder` is returned so that it does nothing when `PushBuilder.push()` is called.

Returning `null` has the advantage that it allows the application to save some computation (for example, iterating over the resources to push).

**Comment by sbordet** [comment]
This has been fixed in `PushCacheFilter` by guarding with `Request.isPushSupported()` rather than with just `Request.isPush()`.

The issue related to Servlet 4.0 remains.

**Comment by gregw** [comment]
See servlet EG discussion on this matter at https://java.net/projects/servlet-spec/lists/jsr369-experts/archive/2016-03/thread/1#00000
Also latest API and javadoc is available at https://svn.java.net/svn/glassfish~svn/trunk/api/javaee-api/javax.servlet

My understanding of the current API is that getting a PushBuilder should return a `javax/servlet/http/NoOpPushBuilder` if push is not enabled.   If a real push builder is returned a subsequent call to `push()` cannot proceed, then it is silently ignored and an ISE is not thrown.  An ISE is only thrown if the error is due to the user not previously setting up the push builder correctly.

We should update our copy of the API to match the latest and update the behaviour.

**Comment by sbordet** [comment]
@gregw you have a definitive behavior from Servlet 4.0 for this ?

**Comment by gregw** [comment]
It has been decided and I believe the javadoc has been updated... will check soon.
