### ISSUE TITLE
AbstractSessionIdManager can't atomically check for uniqueness of new session ID

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#123]
migrated from Bugzilla [#414348](https://bugs.eclipse.org/bugs/show_bug.cgi?id=414348)
status ASSIGNED severity _normal_ in component _server_ for _9.0.x_
Reported in version _9.0.4_ on platform _PC_
Assigned to: Greg Wilkins

On 2013-08-02 21:49:16 -0400, Eli Bishop wrote:

> This is a race condition so unlikely that I can't think how you could go about reproducing the problem, but I think the code is pretty obviously flawed.
> 
> In AbstractSessionIdManager.newSessionId(HttpServletRequest, long), there is a while loop with the condition "id==null||id.length()==0||idInUse(id)"; it continues generating new random session IDs until "idInUse" returns false; then at some point later, it saves the new session using the last ID generated.
> 
> However, that doesn't actually ensure that the session ID is unique-- just that it was unique at the top of the loop. If another thread/process happens to generate the same ID at roughly the same time, they will both end up trying to use it.
> 
> What is really needed there is an atomic test-and-set - check whether the session ID exists and, if it didn't exist, store some data indicating that it's now in use even though there isn't yet a corresponding session. Unfortunately, the SessionIdManager interface has no method with those semantics, and it wouldn't be safe to redefine idInUse() to work that way because idInUse() is also used elsewhere in a context where you do _not_ want to create that ID. So this would probably have to be a backward-incompatible interface change.

On 2013-08-02 22:34:27 -0400, Eli Bishop wrote:

> Note that an attempt by the developer of "jetty-nosql-memcached" to work around this issue - by overriding idInUse() to do what I described in my last paragraph - caused a much more blatant bug (https://github.com/yyuu/jetty-nosql-memcached/issues/18). I don't think there is any valid workaround for this issue in the current Jetty architecture.

**Comment by janbartel** [comment]
In jetty-9.4 the session architecture has changed substantially. The SessionIdManager no longer keeps in memory or persistent storage any session ids.   

In order to find out if a session id had already been generated and used, the SessionIdManager would have to ask all of the SessionHandlers if they either have a session with that id either in memory or in persistent store. That would have to be a stop-the-world operation, which would be bad for performance. Worse, there's still race conditions in there: another thread may have just generated an id, but has not had time to create a session with it yet.

If the likelihood of duplicate ids being generated is vanishingly small, I think we don't need to go to heroic and unperformant measures to try and prevent it.  So I'm minded to close this as a won't-fix - thoughts?

**Comment by sbordet** [comment]
@janbartel I would not mind a walk-through with you about this. `SessionIdManager.newSessionId(HttpServletRequest, long)` synchronizes on the instance, so that is a global lock.
Furthermore, if session ids are generated using strong cryptography, there basically is no chance for duplicates, so I miss what would use would be `isIdInUse()` - wouldn't always return false ?

**Comment by janbartel** [comment]
@sbordet isIdInUse() is now only used when request.getSession(true) is called and the request has a sessionid on it, but no session with that id exists on that context: in this case, the session will only be created with that id iff another context has a session with that id. Basically it supports re-use of session ids (but not session contents) cross-context as per the servlet spec.

**Comment by sbordet** [comment]
@janbartel ok then can you please review usages of `SessionIdManager.newSessionId(long)` ?
It uses a `SecureRandom` to generate the ids, which is not thread safe, so the call to `newSessionId(long)` needs to be protected by a lock.

**Comment by janbartel** [comment]
@sbordet I tightened the scope of the synchronization: removed the sync in DefaultSessionIdManager.newHttpSession(Request, boolean) method and synchronized on the _random field in DefaultSessionIdManager.newSessionId(long) instead.
