### ISSUE TITLE
Response compression does not work when the `Accept-Encoding: *` request header is used.

### ISSUE THREAD

**Issue by toffeegryphon** [eclipse/jetty.project#12324]
**Jetty version(s)**
Up to 12.0.x

**Jetty Environment**
core

**Java version/vendor** `(use: java -version)`
Not relevant

**OS type/version**
Not relevant

**Description**
This doesn't really affect anything, but it is unexpected. According to [RF9110 12.5.3](https://www.rfc-editor.org/rfc/rfc9110.html#section-12.5.3-6),
> The asterisk "*" symbol in an Accept-Encoding field matches any available content coding not explicitly listed in the field.

However, the `HttpField` class' `contains` [method](https://github.com/jetty/jetty.project/blob/jetty-12.0.x/jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java#L203) does not check for a lone `*` character. So when `Accept-Encoding: *` is passed as a request header, the `GzipHandler`'s `getDeflaterEntry` believes that `gzip` is not accepted, and returns `null`. 

**How to reproduce?**
Run a simple web server with the `GzipHandler` installed, and send a request with `Accept-Encoding: *`. The response will not contain the `Content-Encoding: gzip` header, and the body will not be compressed.

**Comment by joakime** [comment]
Legit bug.

The `*` value is valid for `Accept-Encoding` on the request side.
Used to be a common setting, seen in many browsers.

But since the world of gzip + brotli + zstandard is now a reality, that kind of usage has fallen out of favor as the user-agent (client) can get a `Content-Encoding` response it really doesn't understand what to do with.

That, and when we have multiple encodings that the server can support, we currently don't have a way to configure for preferred encoding.

I need to fix this `*` value and preferred encoding (with order) configuration to the #12075 effort (on Jetty 12.1.x)

Using `*` also would make supporting compression dictionaries really awkward, as those can be compression encoder specific.

**Comment by gregw** [comment]
As a work around until we fully support *, use a rewrite customiser that replaced the * with the servers preferred encoding

**Comment by gregw** [comment]
@joakime should we support this only in the new compression handler?

**Comment by joakime** [comment]
@gregw yes, I think that's a better place for supporting this issue.

**Comment by joakime** [comment]
The fix for this is has been started for the `CompressionHandler` in Jetty 12.1.x on PR #12449

**Comment by joakime** [comment]
Merged 

* #12449

Fixed in `CompressionHandler` via a `compressPreferredEncoderOrder` configurable.
