### ISSUE TITLE
Review `requires org.eclipse.jetty.jndi;` in jetty-ee10/jetty-ee10-plus/src/main/java/module-info.java

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#12422]
As pointed out by @robinvanpraet in https://github.com/jetty/jetty.project/issues/12094#issuecomment-2431300461

>  This change added an explicit `require` statement to jetty jndi in the module-info. A dependency that has been excluded by Spring Boot Starter Jetty for a long time. This means that a Spring Boot project, using Jetty, cannot start anymore using the Java Module system. I think the `require` statement should have been a `require static`.

We should review this change from PR #12107, to see if we can soften this declaration some.

**Comment by janbartel** [comment]
@robinvanpraet how long has `org.eclipse.jetty.jndi` been excluded by Spring Boot? Previous versions of `jetty-plus` `module-info.java` have had `requires org.eclipse.jetty.jndi;` - for example see jetty-11.  For jetty-12 we refactored the `jndi` code to live in a core module, rather than have duplicate code in each `eeX` module. When fixing the problem above, we needed to explicitly call a class from this core `jndi` module inside the `EnvConfiguration` class, which (re)introduced the dependency on core `jndi` module. I'm dubious that this could be a `require static`, because why would you be enabling the `jetty-ee10-plus` module if you are not using the `EnvConfiguration` class or the `PlusConfiguration` class? In fact the service loader inside the `jetty-ee10-plus` will automatically place those classes on the list of configurations that get executed when an ee10 webapp starts. I'll make this same comment over on the new issue.

**Comment by robinvanpraet** [comment]
Hello @janbartel, thanks for your reply.
It did some investigation and can see the following:

- Spring Boot 3.3.0 until recent (3.3.4) using jetty 12.0.9 until 12.0.13 all exclude `org.eclipse.jetty:jetty-jndi`
- All Spring Boot versions 3.x.x before 3.3.0 are not excluding this dependency. Even though in the 3.2.x range for example they are using to the same jetty versions. 3.1.x and older is using jetty 11.
- However, in Spring Boot 2.7.x and 2.6.x versions (I did not check the older ones) they are excluding this dependency while using jetty 9.4.x versions.

**Comment by janbartel** [comment]
@robinvanpraet so  sounds like what you're saying is that we need to ask SpringBoot to remove their exclusion? Any idea why they excluded it?

**Comment by robinvanpraet** [comment]
@janbartel I think they actually don't use any of it. I'm working on an simple example application that can be used as a case. They will release a new Spring Boot version today though.

**Comment by robinvanpraet** [comment]
@janbartel 
After some more investigation... Spring does not provide module-info for their jars. So they become automatic modules on the module-path. As long as you do not have an explicit require on the jetty modules this works just fine, even without jetty-jndi. Now our project is a bit off, and we do have explicit require statements on some jetty modules. Therefore the module system is checking the added require statement and failing since jetty-jndi is not present on the module-path. 

Since Spring can run Jetty without the dependency I don't think it is really needed unless under specific conditions. For me it's ok either way, I need to solve the issue on my project specifically.

**Comment by janbartel** [comment]
@robinvanpraet IIUC you will modify your project, and thus we can close this issue?

**Comment by robinvanpraet** [comment]
I'm explicitly adding the missing dependency in my project. I think this issue can be closed indeed.

**Comment by janbartel** [comment]
Thanks, closing.
