### ISSUE TITLE
How to register WebFilters whose urlPatterns have been set in annotation  ?

### ISSUE THREAD

**Issue by zcattacz** [eclipse/jetty.project#12566]
**Jetty Version**
Jetty 12

**Jetty Environment**

ee10

**Java Version**
JDK17

**Question**
I am embedding Jetty 12 into a existing standard spring 6 project, which has been developed and run under tomcat. The login filter is created with annotation:
```
@WebFilter(urlPatterns = {"url1", "url2", "url3", ...})
class AuthFilter implements Fitler {... }
```
This was automatically registered in Tomcat10. so I never thought of how these can be manually added to a ServletContext. With jetty, the examples I can are like below:
```
~~ Pattern 1
server.addFitler(AuthFilter.class, "url1", null);
~~ Pattern 2
var fh = FilterHolder(AuthFilter.class)
var fm = FilterMapping("url1");
server.addFitler(fh, fm);
```
I have tried `server.addFitler(AuthFilter.class, null, null);` without success. I can confirm the filter `init()` is executed, but url patterns configured in annotation are not triggered. I have also `server.addFitler(AuthFilter.class, "/", null);` which is triggered for every request.

I wonder if there is any way to register a @WebFitler annotated filter class with url patterns already set in annotation,  without specifying its pattern again in addFitler call?

**Comment by janbartel** [comment]
@zcattacz you can use the standard servlet api annotations to register your servlets, filters and listeners with jetty too. Just make sure that you have enabled the `ee10-annotations` module.

If you actually do want to switch to using embedded setup rather than via annotations have a look at https://jetty.org/docs/jetty/12/programming-guide/server/http.html#handler-use-servlet. There's some examples to show you how to define servlets/filters etc and add them to your `ServletContextHandler/WebAppContext`.

**Comment by zcattacz** [comment]
Hi @janbartel, thank you for the comments, `ee10-annotations` is what the project lacks. 

Yes I want to embed jetty, but I also want the project to be able to deploy as it was, so I'd prefer the standard way that both tomcat and jetty supports.
