### ISSUE TITLE
BufferUtil.isMappedBuffer() uses reflection on private JDK fields

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1262]
@gregw you recall the reason to use reflection on JDK's `MappedByteBuffer.fd` private field ?

It is broken in JDK 9.

**Comment by joakime** [comment]
Isn't the check that its an instance of MappedByteBuffer enough?

Also, it seems that the `.isMappedBuffer()` method is only used by the `ResourceCache` object.

**Comment by sbordet** [comment]
We have tests that fail when run in JDK 9 because `isMappedBuffer()` would return false - as the reflection hack would generate exceptions.

**Comment by gregw** [comment]
From the comments in the source of `MappedByteBuffer`:
```
    // This is a little bit backwards: By rights MappedByteBuffer should be a
    // subclass of DirectByteBuffer, but to keep the spec clear and simple, and
    // for optimization purposes, it's easier to do it the other way around.
    // This works because DirectByteBuffer is a package-private class.

    // For mapped buffers, a FileDescriptor that may be used for mapping
    // operations if valid; null if the buffer is not mapped.
    private final FileDescriptor fd;
```

So a test for `instanceof` `MappedByteBuffer` will return true for all `DirectBuffers`!   I have no idea how they can think that is 'clear and simple'!!!

Maybe testing for `instanceof MappedByteBuffer` and `!Instanceof DirectBuffer` would be sufficient?

**Comment by gregw** [comment]
Nope that wont work, all MappedByteBuffers are DirectBuffers.   But I think we can call isLoaded and it will throw an exception if it is not mapped.   Perhaps a bit of an expensive test??

**Comment by sbordet** [comment]
> It is a moderately important semantic for the content cache as filemapped buffers do not count towards the cache size.

Why is that ? The current definition of `DefaultServlet.maxCacheSize` does not say anything about whether it's heap, direct or mapped. Currently, both heap and direct contribute to the cache size, so I don't see why mapped should be treated differently ?

**Comment by gregw** [comment]
Because a memory mapped file does not "consume" memory allocated to the process, either from heap or as off heap storage.   It is essentially just swap space, which is not per process. So if a file can be memory mapped, then we can afford to have a lot "larger" cache then if it is loaded into heap and/or kernel space.  The whole point of memory mapping files, is to make the sending of your exemplar 10GB file possible, which we don't want to cause the entire resource cache to be flushed for it.

Now the whole issue of how we cache static content and how we serve it probably does need review, specially with HTTP/2 and SSL etc.   But that is a different issue and until we can have a comprehensive investigation into that, I'd like to keep the behaviour the same.

Maybe we could split out the behaviour from `ByteBuffer getDirectBuffer(Resource resource)` into a separate `ByteBuffer getMappedBuffer(Resource resource)`, which we could then know without asking that a non null return is a mapped buffer?  This would avoid the check altogether (but I still think we should implement it with the isLoaded and catch mechanism).

**Comment by gregw** [comment]
I'll rework this today.
