### ISSUE TITLE
`ContextScopeListenerTest.testAsyncServletAsyncAfterDoGetExit()` is flaky

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#12636]
**Jetty version(s)**
12.0.x, 12.1.x

**Jetty Environment**
ee10, ee11

**Description**

`testAsyncServletAsyncAfterDoGetExit()` sometimes fails with:

```
java.lang.AssertionError: 
Expected :<[enterScope /initialPath, doGet, enterScope /initialPath, exitScope /initialPath, asyncRunnable, exitScope /initialPath, enterScope /initialPath, asyncDispatch, exitScope /initialPath]>
Actual   :<[enterScope /initialPath, doGet, enterScope /initialPath, exitScope /initialPath, asyncRunnable, enterScope /initialPath, exitScope /initialPath, asyncDispatch, exitScope /initialPath]>
```

See: https://github.com/jetty/jetty.project/pull/12635/checks?check_run_id=34325977342

**Comment by gregw** [comment]
I fixed some flakyness of this test in 12.1.x as part of an unrelated PR: https://github.com/jetty/jetty.project/pull/12622/commits/af40148f32b99cd08c3b9097b8eecb6e13fa68c6

I realize now that this should be backported to 12.0.x.   The symptoms were similar to your failure, but not identical.  The issue is that without my fix, we are leaving threads in the thread pool with the server context set, so it can effect enter/exit logic.

**Comment by gregw** [comment]
@lorban Do you have a way to trigger the flakyness to see if the backport helped?

**Comment by lorban** [comment]
@gregw when I configure Intellij to run the test until failure and load my machine a bit, it usually fails within less than a minute. That's the best I have.
