### ISSUE TITLE
Jetty HTTP/2 client keep alive

### ISSUE THREAD

**Issue by sxam** [eclipse/jetty.project#1280]
Hi,
Is there a need to configure Keep Alive for Jetty Http client when using HTTP/2 ? It seems that keep alive more relevant for HTTP/1.1 protocol but still I want to be sure.

**Comment by sbordet** [comment]
Keep alive was only relevant for HTTP/1.0.

HTTP/1.1 and HTTP/2 default to keep the connection open until explicitly closed by either the client or the server.
Remember that a server can close the connection at any time as it sees fit (e.g. overloading, idle timeout, etc.).

In Jetty, closing of the connections on both client and server is typically due to idle timeout, so you want to pay attention to configure that via `ServerConnector.setIdleTimeout(long)` and `HttpClient.setIdleTimeout(long)` or `HTTP2Client.setIdleTimeout(long)`.
