### ISSUE TITLE
SOAP Unmarshalling issue with Java 8, Spring 4 and Jetty 9

### ISSUE THREAD

**Issue by ksahootm** [eclipse/jetty.project#1294]
Hi,

Recently we upgraded our application from Java 6, Spring 3.2 and Jetty 8 to Java 8, Spring 4.2, Jetty 9.
After the upgrade we are facing the issue with converting SOAP response to java objects. We have not got any error or exception but in debug we see only primitive data types from XML copied but not user defined objects. Please help here.
Thanks

**Comment by janbartel** [comment]
@ksahootm I think this should be posted to the jetty user group on jetty-users@eclipse.org, as you are generally asking for help rather than reporting a bug with jetty. When you post, please ensure that you have turned up your application logging and jetty logging to debug level and report all relevant log lines and stack traces. Snippets of code and info on how the SOAP message is converted to java would be useful to those trying to help you.

**Comment by ksahootm** [comment]
@janbartel Thank you for your suggestion!!
