### ISSUE TITLE
Consider implementing a jemalloc-style buffer pool

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#133]
migrated from Bugzilla [#424607](https://bugs.eclipse.org/bugs/show_bug.cgi?id=424607)
status ASSIGNED severity _enhancement_ in component _server_ for _9.1.x_
Reported in version _9.1.0_ on platform _PC_
Assigned to: Project Inbox

On 2013-12-23 06:05:10 -0500, Simone Bordet wrote:

> We already have two implementations of buffer pools in Jetty, but it would be worth to look at jemalloc-style too, see http://stackoverflow.com/questions/1624726/how-does-jemalloc-work-what-are-the-benefits (reference to a PDF paper and an implementation in Firefox).
> 
> See also how Facebook engineering used it: https://www.facebook.com/notes/facebook-engineering/scalable-memory-allocation-using-jemalloc/480222803919
> 
> There are a lot of Google hits for jemalloc for further information.

**Comment by gregw** [comment]
jemalloc is not a buffer pool.  It is a buffer allocation mechanism.

The idea of a buffer pool is to reduce the need to allocate/free memory.  For a server, it makes very little sense freeing IO buffers of standard size, because they will just need to allocate another one when the next request comes in.     For other programs with a more varied use of memory, freeing buffers can be worthwhile as they may not be needed again.

So I see an efficient buffer pool as a way to avoid the complexities of buffer allocation and thus the need for a good allocater

**Comment by gregw** [comment]
will not implement
