### ISSUE TITLE
Return 413 Request entity too large instead of 500 for upload exceeding max upload size

### ISSUE THREAD

**Issue by lpandzic** [eclipse/jetty.project#1382]
Would it be possible for jetty to return status 413 instead of 500 when uploaded file exceeds max file size?

**Comment by gregw** [comment]
Jetty is not directly sending a 500. Instead it is throwing an ISE when getParts (or similar) is called.  The application is able to catch this and itself send a 413, but if it does not catch the exception then a 500 is sent, just as any other uncaught exception from the application.

I potentially jetty could catch the ISE and turn it into:
```
throw new BadMessageException(HttpStatus.BAD_REQUEST_400,ise.getMessage(),ise)
```

Note that would be a 400 rather than a 413, as there could be ISE's other than size related ones.    Alternately we could through more typed exceptions from the multi-part parser, but I'm reluctant to make changes there as it soon needs to be rewritten to be fully async.

@janbartel your thoughts?

**Comment by joakime** [comment]
We now have some servlet calls throwing BadMessageException for similar reasons.
See description at PR #1330

**Comment by joakime** [comment]
Closing, this is how current `jetty-9.4.x` functions.
