### ISSUE TITLE
NPE:at org.eclipse.jetty.util.StringUtil.asciiToLowerCase

### ISSUE THREAD

**Issue by JulyDev** [eclipse/jetty.project#1393]
Hi:
 When Jetty server start(jetty8),it crashed:
Caused by: java.lang.NullPointerException
at org.eclipse.jetty.util.StringUtil.asciiToLowerCase(StringUtil.java:106)
 at org.eclipse.jetty.http.MimeTypes.<clinit>(MimeTypes.java:138)
 at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:711) 
 at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) 
at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95) 
at org.eclipse.jetty.server.Server.doStart(Server.java:282) 
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) 

The method StringUtil.asciiToLowerCase() is invoked in static code block:
static
    {
        try
        {
            ResourceBundle mime = ResourceBundle.getBundle("org/eclipse/jetty/http/mime");
            Enumeration i = mime.getKeys();
            while(i.hasMoreElements())
            {
                String ext = (String)i.nextElement();
                String m = mime.getString(ext);
                __dftMimeMap.put(StringUtil.asciiToLowerCase(ext),normalizeMimeType(m));
            }
        }
........
    public static String asciiToLowerCase(String s)
    {
        char[] c = null;
        int i=s.length();

        // look for first conversion
        while (i-->0)
        {
            char c1=s.charAt(i);
            if (c1<=127)
            {
                char c2=lowercases[c1];
                if (c1!=c2)
                {
                    c=s.toCharArray();
                    c[i]=c2;
                    break;
                }
            }
        }

        while (i-->0)
        {
           // NullPointerException
            if(c[i]<=127)
                c[i] = lowercases[c[i]];
        }
        
        return c==null?s:new String(c);
    }

**Comment by joakime** [comment]
[Jetty 8 is EOL (End of Life)](https://dev.eclipse.org/mhonarc/lists/jetty-announce/msg00069.html), consider upgrading to something supported.

Link to current jetty-8.1.x HEAD for StringUtil line 106.

https://github.com/eclipse/jetty.project/blob/jetty-8.1.x/jetty-util/src/main/java/org/eclipse/jetty/util/StringUtil.java#L106

The only way I can think of to make that NPE occur is to pass an empty string into that method.

As for your specific error, it seems like your mime.properties either doesn't exist in your environment, is empty, or contains empty strings.

Either way, this was fixed in Issues #720 and #797 a while ago. (both available in Jetty 9.3.12+)

**Comment by JulyDev** [comment]
Thank you very much!
