### ISSUE TITLE
Re-evalute jetty osgi bundling and manifests

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#1397]
See #1365 .

The standard jetty jars include appropriate osgi manifest headers so that users can deploy the normal jars and have all jetty functionality work.  This introduces some overhead, namely the requirement to deploy Aries/spifly to mesh the use of java SerivceLoader with the osgi environment.  For users wanting a simple, minimal http deployment this introduces some overheads.

**Comment by mbooth101** [comment]
I'm not convinced that making such dependencies on Aries optional is a terrible solution. I mean, you still get all the functionality if you deploy all the right bundles and at the same time users can avoid deploying unnecessary bundles. Do you know of any downsides?

I understand what you mean about "swimming against the tide of progress" but until the time comes that jetty has hard requirement on Aries in order to function, I'd like to avoid introducing unnecessary transitive dependencies and the bureaucracy that brings.
