### ISSUE TITLE
For async servlet, request forwarding is broken

### ISSUE THREAD

**Issue by chiru0307** [eclipse/jetty.project#1459]
Servlet Request forwarding is broken with async servlets.

If servlet A forwards request to servlet B, the request received inside the async context of servlet B is the original base request and not the expected forwarded request.

Uploading the test war below. It has the Java source as well.

URL post deployment: http://localhost:8080/TestServletForward

[TestServletForward.zip](https://github.com/eclipse/jetty.project/files/905476/TestServletForward.zip)

**Comment by joakime** [comment]
See discussion in jetty-users for more details about this issue

http://dev.eclipse.org/mhonarc/lists/jetty-users/msg07720.html

**Comment by janbartel** [comment]
When accessing the AsyncContext in a thread other than the request processing thread, the contents of the request are undefined, as you are not within the scope of any context or servlet. The current servlet spec does not clearly state that, however the expert group is working on wording to clarify the inherently racy nature of calls to request object from dispatched threads vs user threads.

**Comment by chiru0307** [comment]
Well, even if I use the container provided `ThreadPoolExecutor` by invoking the `AsyncContext#start(java.lang.Runnable)` method, the outcome is the same.

If we refer to [this](https://docs.oracle.com/javaee/7/tutorial/servlets012.htm) example, the doc states that upon invoking `AsyncContext#getRequest()` API the request used to initialize the asynchronous context should be returned (which is currently not happening).

The dogma of asynchronous processing is processing in a separate thread than the request thread to free up container to be able to serve requests faster. The example I shared is a simple blocking I/O implementation of the Asynchronous Servlet processing. That should work.

Since the issue is marked as a bug and has been closed, could someone please educate if there's some way to get this working?

**Comment by joakime** [comment]
I have personally never seen "The dogma of asynchronous processing is processing in a separate thread than the request thread to free up container to be able to serve requests faster." as a statement from anyone.

Where did you get this servlet anti-pattern from?

**Comment by chiru0307** [comment]
Check this [link](https://docs.oracle.com/javaee/7/tutorial/servlets012.htm)

Here's the relevant part:

`Asynchronous processing refers to assigning these blocking operations to a new thread and returning the thread associated with the request immediately to the container.`

If you say that I've been working with a servlet anti-pattern, could you please point me to a proper way please? That'd help me learn it properly. Thanks!

**Comment by gregw** [comment]
@chiru0307 I think the fundamental misunderstanding you have is when you say: "the request received inside the async context of servlet B is the original base request and not the expected forwarded request".

There is only one request instance and a new request object is not created when forwarding the request to a new servlet.   The instance itself is changed by the forwarding so that it's methods for things like `getServletPath()` and `getPathInfo()` will return the altered values.

This means that another thread observing the request object (no matter from where it was obtained - either as a passed reference of from the `AsyncContext` will see different values returned from these methods as the request is handled by the various servlets.     So using another thread to look at the request object is vulnerable to a race condition in that it may see different values depending on small timing changes and/or memory barriers.

The only solution for this is to not use an async thread to observe the request. Instead any async processing must first extract all the required information from the request prior to the original dispatch returning (or being forwarded on).

Not also, that there is NO benefit of executing normal servlet code in another thread and you will just introduce latency and extra memory usage for no gain.   The only reason to go async is if there is some kind of event (eg response from a remote service) that you need to wait for and you wish to wait without blocking a thread.    If there is no threadless waiting, then don't go async.

**Comment by chiru0307** [comment]
Thank you @gregw for the explanation. That helps.
There indeed is a blocking operation because of which I went with asynchronous implementation of the servlet.
The surprising thing is, the same piece of code was working when we were using Wildfly 8.2.0 and stopped working when we moved to Jetty (which I believe uses the Glassfish implementation of the servlet API).

**Comment by gregw** [comment]
On 12 April 2017 at 14:58, Chiranjib <notifications@github.com> wrote:

> The surprising thing is, the same piece of code was working when we were
> using Wildfly 8.2.0 and stopped working when we moved to Jetty (which I
> believe uses the Glassfish implementation of the servlet API).
>
>
That is the nature of races.  They can just work depending on very small
changes in timing and then if something small changes, they just fail all
the time.    There are also big differences between containers for what
values are returned from methods like getServletPath when a request is not
dispatched at all - because that is not part of the specification. Jetty
returns null, where other containers return the last non-null value.

regards



-- 
Greg Wilkins <gregw@webtide.com> CTO http://webtide.com
