### ISSUE TITLE
Jetty Client should allow preemptive basic auth to be completely disabled

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#147]
migrated from Bugzilla [#432943](https://bugs.eclipse.org/bugs/show_bug.cgi?id=432943)
status ASSIGNED severity *normal* in component *client* for *9.1.x*
Reported in version *unspecified* on platform *PC*
Assigned to: Simone Bordet

On 2014-04-16 11:28:25 -0400, Mark Mielke wrote:

> By default, Jetty Client will try the request without basic auth. Then, upon authorization failure, it will try the request with basic auth. If basic auth succeeds, it "remembers" this for future via an AuthenticationResult that gets cached.
> 
> For my scenario, which is actually "login to a JIRA backed by LDAP authentication", when I issue HTTP basic auth requests with username and password, the requests complete in around 250 milliseconds. Once authenticated, the user's session (identified using a cookie), the request can complete in 7 milliseconds or less.
> 
> When I use Jetty Client to authenticate, all requests are completing in the 250 millisecond range. This is because all future requests continue to include the username and password.
> 
> I added a listener using httpClient.getRequestListeners.add() that has "onQueued" defined as:
> 
> httpClient.getAuthenticationStore().clearAuthenticationResults();
> 
> This forces the authentication results cache to always be reset before every request. After this, only the first request takes 250 milliseconds, and all future requests (until the cookie expires) complete in 7 milliseconds or less.
> 
> This also has the added "security" feature that the password is not being sent with every request.
> 
> I don't know how much of a "special case" this scenario is. I think Apache HttpClient may behave the same way. I'm trying to upgrade from Jersey Client 1.x / Apache HttpClient 2.2.x and my custom Jersey 1.x method of authentication handling is now broken. Getting Jersey Client 2.x to work "properly" has been painful. I finally threw out Jersey and went direct to Jetty Client as I have enjoyed working with your product so far.
> 
> The above work-around "works". I may go production with it. But, I'm concerned about the long-term behaviour of the function, and the inherent race condition. That is, there is a race between when the Jetty Client authentication protocol handler stores the authentication results, and where the onQueued method clears it, so any concurrent queries run at the same time may re-use the authentication results. Also, I would like to know that the behaviour of the authenticator won't change in a future release that would cause the above work-around to fail. If there was a specific feature to provide this capability, then I wouldn't have to be concerned about either of these?
> 
> In terms of implementation, I think I am asking for a documented interface to disable the newRequest.onResponseSuccess() code described below:
> 
> AuthenticationProtocolHandler.AuthenticationListener.onComplete():
> 
>             newRequest.onResponseSuccess(new Response.SuccessListener()
>             {
>                 @Override
>                 public void onSuccess(Response response)
>                 {
>                     client.getAuthenticationStore().addAuthenticationResult(authnResult);
>                 }
>             }).send(null);
> 
> Thanks!

**Comment by sbordet** [comment]
@MarkMielke (I hope you are the original reporter of this issue and not an homonym),

if I understand correctly, you have two authentication mechanisms in place: one that uses Basic authentication, and one that uses a cookie.

You first perform the Basic authentication, which sets the cookie.
Subsequent requests contain the cookie, and you can therefore skip Basic authentication.
By skipping Basic authentication verification you go from 250 ms to 7 ms request time.

There are multiple ways of dealing with this.

The first is the workaround you found.
However, rather than clearing the `AuthenticationStore` for every request, you can perhaps just clear it after the first Basic authenticated request.
Once cleared, it won't send anymore the Basic authentication header, and you will be just using the cookie.
Note that now you can preempt basic authentication (see #409).

The second is to override `HttpClient.getAuthenticationStore()` and return a custom subclass that does not store authentication results.

I feel you have enough workarounds for your particular case; I am not that keen to add another boolean configuration parameter to disable the store of authentication results - seems a pretty uncommon case.

Feel free to reopen this issue if you have more convincing arguments, or if I misunderstood the issue.

**Comment by MarkMielke** [comment]
Hi Simone:

For your first suggested work-around, I don't think that will work. While a cookie is valid for a period of time, it eventually expires, and the next request needs to respond correctly to the basic authentication by providing the login again.

For your second suggested work-around, that might work. I will try it.

Thanks.

**Comment by MarkMielke** [comment]
Oh... BTW... The uncommon case is "login to a JIRA backed by LDAP authentication". I don't think it is that uncommon. But, probably many people don't mind waiting 250 ms, and haven't yet noticed.

**Comment by sbordet** [comment]
@MarkMielke there is one thing that I don't understand. 

You skip the login to JIRA if there is the cookie, so I don't understand how having the authentication result in the store (which adds the `Authorization` header) is making any difference.

Unless you _always_ login to JIRA if you find the `Authorization` header, but that would be an application mistake.

**Comment by MarkMielke** [comment]
@sbordet I think just over thinking it... :-)

Preemptive authentication is a problem, because it sends the username + password with EVERY request. Unless the server implements sort of caching to detect "hey, the user sent the same basic authentication 2 seconds ago, and I approved it then, so let's automatically approve it now", then it needs to re-authenticate the username + password with EVERY request. This is what costs. Authentication locally is usually expensive (processing power), but fast. Authentication with an external service such as LDAP can be much more expensive, as it may require first lookup of the user (LDAP bind + search) and then login (LDAP bind).

If we don't use preemptive authentication, then there are these four states:

1) Initially, the request is not authorized at all. No basic authentication. No cookie. The server returns HTTP 401 Unauthorized. The client retries with basic authorization specifying the username and password. The server authorizes the request and returns the response with a cookie.

2) For a period of time, the cookie can now be used to authenticate the request. The cookie ends up being a very fast hash lookup to identify the session data, which includes recognition of the autohrized user. Requests in these situations are authorized and processed quickly.

3) After a period of time, the cookie expires on the server. The session data is ignored or forgotten. A new session is generated. In this case, HTTP 401 Unauthorized would be returned, and the client needs to respond with basic authentication. The session is renewed. The server autohrizes the request and returns the response with the same or a new cookie.

4) After a different period of time, the client recognizes that the cookie has expired and stops sending it. This situation then becomes the same as state #1.

I think this sort of issue happens a lot more than most people realize. It is just that very often, people don't understand why their requests are slow, and they don't realize it is due to authentication overhead. They likely attribute the slow performance with an assumption that the request processing is slow, rather than the request authorization.

I know some servers do cache basic authentication to work around this. I know that JIRA does not. If I specify the username + password, it checks it. (Although there has been JIRA versions since I raised this, and it is possible it is "fixed" now with caching... I would have to test to see...)

**Comment by MarkMielke** [comment]
@sbordet I finally found the time to try out your second suggestion. It does work, however, it is a bit uncomfortable. I had to implement:

1. AuthenticationStore implementation which delegated all methods except for addAuthenticationResult()
2. HttpClient implementation which extends HttpClient, and overrides getAuthenticationStore() to return the AuthenticationStore delegate.

HttpClient has hard coded references to the authenticationStore field member instead of getAuthenticationStore() method, so to preserve these calls, I chose the delegate method instead of creating an entirely separate AuthenticationStore.

I think this successfully addresses the race. However, it makes me uncertain about API evolution and whether this method is sustainable. It still seems like this one choice of "should authentication results be cached or not?" could be very easily made into a boolean configuration parameter that is likely something that users should have control over. As I mentioned previously - if users don't ask for this, it could just be that they don't realize that this is a real problem.
