### ISSUE TITLE
TypeUtil.getLoadedFrom(Class) should never check System ClassLoader

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1489]
If the class instance handed to the `TypeUtil.getLoadedFrom(Class)` has no valid 
`class.ProtectionDomain.CodeSource.Location`, then an attempt is made to load the class via `ClassLoader.getResource()` to determine its location.

If the Class itself has no ClassLoader, then this check should stop there.
As using the System ClassLoader can return an invalid location for the actual provided class.

ClassLoaders that perform dynamic creation of classes, class proxies, bytecode manipulation, aop, etc, then the Class being handed to `.getLoadedFrom()` has no location, and should be treated as such.

Also, if the ClassLoader isn't null, and is of a type that does not implement `.getResource()` for Classes, then this should also be taken into account.

**Comment by joakime** [comment]
@gregw please see commit 0f29508 (on branch `issue-1489`) for what I mean about how `getLoadedFrom()` should work to be sane.

**Comment by joakime** [comment]
Found a simpler approach for class lookup in commit d7b20da but its not the silver bullet we need to solve for issue #1448, just reduces the complexity of the existing solution.

**Comment by joakime** [comment]
After a review with @sbordet we think this is not going to work with JDK9.

We also have non-filesystem paths being reported. aka "jrt://<module>/<classname>"

**Comment by gregw** [comment]
I don't think  excluding classes loaded from the system classloader is satisfactory, primarily because with start.jar, we put all the discovered classes on the system classloader.

As discussed on hangouts,  the point of this feature is not to know the location the class is loaded from, but to provide a mechanism that allows bulk classes to easily be included/excluded from the system/server path determination in the context loader.      For JDK < 9 we used location because it is easy for a module to create a `$JETTY_BASE/lib/foobar` directory, add `$JETTY_BASE/lib/foobar/*.jar` to the classpath and set a property so that `$JETTY_BASE/lib/foobar` is included in the server classes.

If this is not possible in JDK9, then we simply need to find another mechanism for how a module can group dependencies and handle them in bulk.   Prior to jetty 9.4, we had to list out all the packages and/or classnames explicitly and that was fragile and overly verbose.

For JDK<9, the location is mostly good.... except for classes that are used to implement the classloader and thus a checked on load, but the checking needs to load them etc.

**Comment by joakime** [comment]
Issue #1448 has a workaround for the StackOverflowError which changes the behavior of `getLoadedFrom()` to eliminate `new URL()` + `URI.toURL()` + jetty-util `Resource` usage.

The basic logic of the original `getLoadedFrom()` are still there, but some of the jetty-util `Resource` magic has been removed to make it more sane/stable in the various places it is used from.
