### ISSUE TITLE
tck test suite for session management implementations

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#1572]
Currently all implementations have their own test with some duplicate code.
We can have a shared tck test suite which can reuse.
Maybe 2 types:
* SessionDataStore 
* SessionDataMap

**Comment by janbartel** [comment]
Not sure exactly what you're thinking here? There are tests that are shared in test-sessions-common. There are concrete test classes in there that deal with interfaces as you suggest. However there are also other abstract classes in there that are shared code for tests of specific impls of SessionDataStore (eg for infinispan, mongo, jdbc etc etc).  As each concrete impl of SessionDataStore will have specific behaviour, we do need to have tests for each of them.

**Comment by olamy** [comment]
oh ok everything is there... 
while implementing #1571 I was writing the test in the implementation module.
I'm just a bit confused to have separate module for the implementation and the tests.
What is the reason?

**Comment by janbartel** [comment]
Well, they're a bit more than unit tests, they're more like integration tests because its a suite of classes that are being tested.  If you have some unit tests where you're really only testing 1 class then you could put them into the impl module - just be sure that if you need a local installation of hazelcast the tests can be selectively enabled (disabled by default).

**Comment by olamy** [comment]
ok make sense.
Close it as not an issue.
