### ISSUE TITLE
RolloverFileOutputStream not functioning in Jetty 9.2.21+

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1590]
As reported in jetty-dev ...

https://dev.eclipse.org/mhonarc/lists/jetty-dev/msg03020.html

The RolloverFileOutputStream is not rolling to new files at midnight anymore.

I have confirmed this bug with an overnight test of the distribution.

**Comment by joakime** [comment]
Did a cherry-pick backport of the commits related to RolloverFileOutputStream in 9.3.x to 9.2.x.
Work is being performed in the `issue-1590-rfos` branch.

**Comment by joakime** [comment]
The Java 1.8 features of the 9.3.x RolloverFileOutputStream now have to be removed.
https://jenkins.webtide.net/job/jetty.project/job/issue-1590-rfos/1/console

**Comment by joakime** [comment]
Java 1.8 class usage has been reverted in backported RolloverFileOutputStream.
Testcase also updated.

**Comment by joakime** [comment]
Merged back into `jetty-9.2.x`. closing.

**Comment by WalkerWatch** [comment]
As a closing note, the logs files themselves now roll over on the defined Time Zone, irrespective of the local time on the server. For example, I am in `America/New_York`, but the server is configured to `Asia/Rangoon`, the logs will roll over when `Asia/Rangoon` changes dates. It is important to note, however, that time entries in the log file itself will reflect the local time of the server, and this cannot be configured. As such I would recommend that best practices would dictate the server should be configured to the local timezone unless business practices dictate otherwise.

**Comment by joakime** [comment]
I filed a new issue #1596 to address the concerns discovered with the 2 different TimeZones discovered during testing.
