### ISSUE TITLE
AbstractProxyServlet onProxyResponseFailure Error

### ISSUE THREAD

**Issue by wangyunai** [eclipse/jetty.project#1661]
I user tomcat8+servlet3.1+jetty-proxy9.3.20.v20170531, when run in method AbstractProxyServlet.onProxyResponseFailure, if (proxyResponse.isCommitted()) ,  proxyResponse.sendError(-1) throws an IllegalStateException ,and  asyncContext.complete() will not be execute.
the souce code :

```java
 if (proxyResponse.isCommitted())
        {
            try
            {
                // Use Jetty specific behavior to close connection.
                proxyResponse.sendError(-1);
                if (clientRequest.isAsyncStarted())
                {
                    AsyncContext asyncContext = clientRequest.getAsyncContext();
                    asyncContext.complete();
                }
            }
            catch (Throwable x)
            {
                if (_log.isDebugEnabled())
                    _log.debug(getRequestId(clientRequest) + " could not close the connection", failure);
            }
        }
```

**Comment by wangyunai** [comment]
thanks, i will catch this excepiton and let the asyncContext complete,if the re is committed,how can i clean the buffer of the response? should have to ?

**Comment by sbordet** [comment]
@gregw I don't think we need the `sendError(-1)` anymore, as I believe that if we try again a `sendError()` we already abort the channel. I will need to check this though.

**Comment by gregw** [comment]
@sbordet correct, we now internally convert to -1 then abort if the response is already committed.   I'll update proxy accordingly...

**Comment by gregw** [comment]
@sbordet Can you review this fix?

I have updated sendProxyResponseError to call complete in a finally block, so it will be called even if the error handling has a problem. 

However, I have needed to change the behaviour a little bit, as it now always uses sendError rather than setStatus.   This means that an error body message is sent for failures like 504 rather than an empty body and I have had to update the org.eclipse.jetty.proxy.ProxyServletTest.testProxyRequestFailureInTheMiddleOfProxyingSmallContent() test accordingly.

Is there a reason that proxy errors were being sent without a body?

**Comment by sbordet** [comment]
@gregw looks good to me. If the response is already committed, calling `sendError()` causes the connection to be closed by aborting the channel, which is what we want.
The test changes you made are okay.
