### ISSUE TITLE
WebSocket support in App Engine Standard

### ISSUE THREAD

**Issue by ludoch** [eclipse/jetty.project#1665]
Let's use this bug to discuss our progress regarding adding WebSocket support in App Engine Standard Java8....

GAE Standard does not use the HttpConnection mechanism but defines a new RCPConnection mechanism (Greg knows about this....)

Registering the websocket jars, I can go up to a point where I get (with Jetty 9.3.18.v20170406):
java.lang.NullPointerException
        at org.eclipse.jetty.websocket.server.WebSocketServerFactory.upgrade(WebSocketServerFactory.java:559)
        at org.eclipse.jetty.websocket.server.WebSocketServerFactory.acceptWebSocket(WebSocketServerFactory.java:232)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:236)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)

There, the http variable is null:
       EndPoint endp = http.getEndPoint();
        Connector connector = http.getConnector();
from    
	 // Get the original HTTPConnection
            HttpConnection connection = (HttpConnection) request.getAttribute("org.eclipse.jetty.server.HttpConnection");

For GAE Standard,  http Should be a GAE rcpconnection, not httpconnection.

I could provide the 2 methods on our rpc connection for getEndpoint() and getConnector(), assuming I pass the correct object via a request attribute (either "org.eclipse.jetty.server.HttpConnection"  or something more generic).

If we cannot do this change, I am starting investigating how I could override the creation of WebSocketServerFactory with some changes in the acceptWebSocket() implementation, but it seems quick complicated with overriding service loaders services...

I could also attack the issue with changing the RUNTIME_IMPL value in 
public interface WebSocketServletFactory
{
    class Loader
    {
        final static String DEFAULT_IMPL = "org.eclipse.jetty.websocket.server.WebSocketServerFactory";
          
            
But it is final, and I do not see a way to change the implementation there of
        public static WebSocketServletFactory load(ServletContext ctx, WebSocketPolicy policy)
I would understand you do not have the cycles to work or help on this as this point, but I want to describe the issues I am currently facing.

Hopefully we can collaborate again on making clean changes in the Jetty code base to accomodate the GAE needs.
Cheers

**Comment by gregw** [comment]
@ludoch Can you give us a bit more detail of how the websocket stream will be delivered?

With standard Jetty, we have the concept of a HttpConnection, HttpChannel and HttpRequest.  With HTTP/1.0 these were 1:1:1,  HTTP/1.1 they are 1:1:n and HTTP/2 1:n:m.     The differences for HTTP are not important because each request is stand alone and the applications have little or no knowledge of the concept of channel and/or connection (which are essentially transport optimisations).    

The current GAE standard most closely resembles HTTP/1.0, where for each GAE UPRequest received a 1:1:1 HttpConnection:HttpChannel:HttpRequest is constructed that is backed by the UPRequest.

However, with Websocket, the concept of connection does become important for the applications.  Firstly  a websocket connection is initiated by an upgrade from a HttpRequest, which remains associated with every message received on the subsequent connection. eg. it is possible to access the associated HttpSession of that request from a websocket message handler.  More importantly, the websocket messages received on a connection are ordered and must be handled in order.

So I assume with GAE that the websocket messages will be delivered as a sequence of UPRequest RPCs.    So the main questions I have are:
- How is a websocket RPC UPRequest object associated with the HttpRequest that was sent from the client to upgrade to websocket?  Will jetty even see that request or will the upgrade be handled by the GFE,  or will jetty be given the request and an opportunity to accept/reject the upgrade? If the former, we will need to at least be given the headers and URI of the initial HttpRequest.
- How is each websocket RPC UPRequest object associated with a stream of websocket messages?  How is order established?  Will it be via a connection ID and sequence number or will their be an RPC object created that represents the stream from which messages will be received?

Once we know a bit more about how the RPCs are structured, we'll be able to say more about how to map those to Jetty Connection abstractions and the factory mechanisms to create them.

**Comment by joakime** [comment]
Note, when discussion WebSocket upgrade, its limited to HTTP/1.1 (RFC6455 does not support n HTTP/1.0 or HTTP/2)

**Comment by joakime** [comment]
Some thoughts on the WebSocket upgrade process ...

I don't think GFE can do the upgrade process, unless you put some serious restrictions in place for WebSockets.

Take this example request from a user agent.

``` http
GET /foo HTTP/1.1
Host: myapp.com
Connection: Upgrade
Upgrade: WebSocket
Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==
Sec-WebSocket-Origin: ws://myapp.com/
Sec-WebSocket-Version: 13
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits; client_no_context_takeover
Sec-WebSocket-Protocol: general, discussion, chat
```

This can result in any of the following replies at the HTTP side

``` http
HTTP/1.1 200 OK
Content-Type: text/html
Connection: close

<html>
<h1>Hey, use something else</h1>
</html>
```

A request for Upgrade can result in a normal HTTP response (and there are many scenarios where it does)

``` http
HTTP/1.1 403 Forbidden
Connection: close

<html>
<h3>You don't have permission to access this</h3>
</html>
```

The http layer is rejecting your attempt at upgrading

``` http
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=
Sec-WebSocket-Protocol: chat
```

The endpoint upgraded to websocket, choosing the `chat` protocol and rejecting all extensions.
The websocket layer in Jetty, along with the specific WebSocketCreator and its associated endpoints were interrogated to know how to respond.

``` http
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=
Sec-WebSocket-Protocol: general
Sec-WebSocket-Extensions: permessage-deflate
```

The endpoint upgraded to websocket, choosing the `general` protocol and accepting the extension but without specialized configuration of extension.
The websocket layer in Jetty, along with the specific WebSocketCreator and its associated endpoints were interrogated to know how to respond.

The above are just a few of the paths the upgrade request can take, there are many others not outlined here, but hopefully this sampling will be enough to frame the discussion on where and when the upgrade to websocket occurs should take place.

The need for upgrade step from HTTP to WebSocket to interrogate the HTTP layer, then the WebSocket layer, then the WebSocket endpoint makes it difficult to have GFE perform the upgrade.

The actual websocket endpoint implementation (the end users declared websocket) can change depending on URI template variables, HttpSession information, header details, protocol choices, and any other factors (like a configuration setting in a database)

You could have GFE perform the upgrade, but then you restrict websocket to never using protocols or extensions, and always the same websocket endpoint for the desired URI.
If you go this route, then the WebSocket endpoints never have knowledge of the HTTP layer it was upgraded from (such as HttpSession details).

We briefly discussed having websocket just be another connection type at the low level Jetty connection layer, but that was quickly abandoned as the need to communicate with the webapp + websocket layer + websocket creator + websocket endpoint prevented this simple connection layer upgrade.

**Comment by gregw** [comment]
@joakime note that when I say `GFE` I'm really saying `All parts of the Google cloud that are not part of GAE instance, including but not limited to the GFE`.

More over, the actual upgrade will always be done by the `GFE` as that is where the HTTP protocol terminated and converted to RPC.  So the question really is how consultative will the `GFE` be when doing that accept?

Note that GAE already does offload some webapp logic into the other parts of the google infrastructure. eg for security and static content.  It does this by parsing the web.xml and learning about what security constraints and servlets are defined and configuring the non-GAE parts of the infrastructure accordingly.

So it would be possible for a similar approach to be taken, scanning for annotations and learning about what WebSocket endpoints exist.   Thus I think it would be possible for the upgrade to be offloaded to the `GFE` in many cases.   

However, there are going to be some cases where the accept logic is unable to be offloaded (NP-complete problem).    Even in the cases that the logic able to be offloaded, jetty will still need access to information that was in the headers/URI of the upgrade request.

So the upgrade request (converted to an RPC) will have to be made available to jetty somehow.  Potentially it could be carried with every websocket message RPC so that individual websocket messages are not statefully related to a connection (other than by sequence).

Which actually raises another question - will websocket message streams be sticky to a single instance or will they be statelessly distributed like HTTP requests

**Comment by ludoch** [comment]
Thanks for the good debate and the good definition of the GFE by Greg:-) 

I started some internal threads and here is what I can say:
"
The UPRequest/UPResponse rpc path will not be supported. It does not use bidirectional streaming and currently doesn't have appropriate fields for to proxy WebSocket traffic over. We haven't done a thorough analysis, but trying to reuse the UPRequest/UPResponse path will probably require equivalent levels of work to writing a new alternative path.

The plan we have in mind is to deliver the WebSocket traffic directly to the clone. At the GFE level we can read the initial headers to see if it is WebSocket upgrade request. If it is, then we will forward all the bytes through a new data path (under development) directly to the Java clone where the Java runtime can consume the bytes by listening on a port. The data path can either be to a new port or the existing port that the Java 8 clone listens for gRPC.

Therefore if the Java 8 runtime listens on this port it will see the full WebSocket session, that any open source conforming WebSocket implementation should be able to work with. In other words it will see something like this:
1) Browser makes a HTTP request with a request headers "Connection: Upgrade" and "Upgrade: websocket" and some other required headers. Java 8 runtime will see something like:

GET ws://example.com HTTP/1.1
Host: example.com
Sec-WebSocket-Key: alsdkfjlkasjldfj
Upgrade: websocket
Connection: Upgrade  
Sec-WebSocket-Version: 13 

2) Java8 runtime responds with acceptance of protocol upgrade. Example:

HTTP/1.1 101 Switching Protocols
Connection: Upgrade
Sec-WebSocket-Accept: asdflsaflsdf
Upgrade: websocket
 
3) Either side can start exchanging frames.

      0                   1                   2                   3
      0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
     +-+-+-+-+-------+-+-------------+-------------------------------+
     |F|R|R|R| opcode|M| Payload len |    Extended payload length    |
     |I|S|S|S|  (4)  |A|     (7)     |             (16/64)           |
     |N|V|V|V|       |S|             |   (if payload len==126/127)   |
     | |1|2|3|       |K|             |                               |
     +-+-+-+-+-------+-+-------------+ - - - - - - - - - - - - - - - +
     |     Extended payload length continued, if payload len == 127  |
     + - - - - - - - - - - - - - - - +-------------------------------+
     |                               |Masking-key, if MASK set to 1  |
     +-------------------------------+-------------------------------+
     | Masking-key (continued)       |          Payload Data         |
     +-------------------------------- - - - - - - - - - - - - - - - +
     :                     Payload Data continued ...                :
     + - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
     |                     Payload Data continued ...                |
     +---------------------------------------------------------------+

4) (In general) If client sends opcode 0x08 (Close), server will send back frame with opcode 0x08 and immediately close the connection. If the server wants to close the connection it will send 0x08, and immediately close the connection.
"
This is what I got so far, on the short discussion period.

I will be good when we can resume our discussions. Obviously we cannot reuse the current Jetty implementation as is, but I think we have the things we need and we need to find the minimal and clean integration point between our 2 layers...

**Comment by joakime** [comment]
Here's a breakdown of the existing WebSocket server steps.
Thinking about this, I think the best solution would be for a GRPCEndPoint to be used by Jetty (Http + WebSocket), not a new GRPCConnection (which would needlessly complicate things at that level)

> Key:  
>  ▲ (user's deployed webapp code)
>  ◻ (http layer)
>  ◇ (websocket layer)

1. ◻ Http Request (Version: 1.1 | Connection: Upgrade | Upgrade: WebSocket) received
1. Jetty.EndPoint exist
1. ◻ Jetty.HttpConnection using Jetty.EndPoint
1. ◻ Request parsed
1. ◻ Request dispatched to WebApp
1. ◻ WebSocketUpgradeFilter sees Upgrade
    1. ◻ WebSocketServerFactory.acceptWebSocket(creator,request,response)
        1. ▲◇  WebSocketCreator.createWebSocket(ServletUpgradeRequest, ServletUpgradeResponse)
        1. ◇   JsrCreator (JSR-356 logic)
            1. ▲◇     ServerEndpointConfig.userProperties initialized
            1. ▲◇     userProperties populated with: request local address. request remote address, and request locale.
            1. ▲◇     ServerEndpointConfig.Configurator grabbed
            1. ▲◇       boolean configurator.checkOrigin()
            1. ▲◇       usedSubprotocol = configurator.getNegotiatedSubprotocol(supported,requested)
            1. ▲◇       usedExtensions = configurator.getNegotiatedExtensions(installed,requested)
            1. ▲◇       configurator.modifyHandshake(config,request,response)
            1. ▲◇       Object wsEndpoint = configurator.getEndpointInstance(endpointClass)

        1. ▲◇   return wsEndpoint instance to use

    1. ◇ WebSocketServerFactory.upgrade(connection, request, response, wsEndpoint)
        1. ◇ RFC6455 upgrade rules checked
        1. ◇ Extension Stack initialized
        1.  Jetty.EndPoint grabbed from Jetty.HttpConnection
        1. ◇ WebSocket.Connection (AbstractWebSocketConnection) initialized from
            1.    Jetty.Endpoint
            1.    Jetty.Executor
            1. ◇    WebSocketPolicy
            1.    Jetty.BufferPool
            1. ◇   extensionStack
        1. ◇  WebSocket.Generator created
        1. ◇ WebSocket.Parser created
        1. ◇ WebSocket.Session (WebSocketSession) created from
            1. ◻   Request.URI
            1. ◇   wsEndpoint
            1. ◇   WebSocket.Connection
    1. ◻ Notify Jetty.HttpConnection that upgrade is valid
1. ◻ Send Http Upgrade Response
1. ◇ WebSocketSession.open (Connection.open + wsEndpoint.onOpen)

**Comment by joakime** [comment]
Another idea, if the whole point of the GRPC layer is to know what's going in WebSocket, perhaps using a non-negotiated WebSocket extension (not a spec concept, but a built in debug-ish layer in Jetty websocket), to relay the websocket frames through, would give enough information to the layers outside of WebSocket.

**Comment by xlfe** [comment]
@ludoch @joakime thanks - I think I now understand why this doesn't work currently. Just wondering if there's been any progress in the last 6 months ? 

Thanks!
