### ISSUE TITLE
DeploymentManagerMBean not usable through JMX

### ISSUE THREAD

**Issue by rothskeller** [eclipse/jetty.project#1679]
JMX calls to various methods of the DeploymentManager fail due to NotSerializableException.  For example, when sending a getApps() request to the DeploymentManager mbean, the response is a NotSerializableException for org.eclipse.jetty.deploy.App.

After some code analysis, I believe the reason for this is that DeploymentManager has the "@ManagedObject" annotation, and its getApps method has the "@ManagedAttribute" annotation.  But that method returns a Collection<App>, and App is not serializable, so it cannot be sent back to the JMX caller.  The JMX calls _should_ be handled by DeploymentManagerMBean; its getApps method returns Collection<String>.  But DeploymentManagerMBean doesn't have the same annotations, so it is ignored.

This problem was found on Jetty 9.2.22.  But the offending code is unchanged in the current Jetty versions.

**Comment by gregw** [comment]
method purely for management need to be on the MBean class... in this case it is missing annotations

**Comment by joakime** [comment]
Adding @ManagedObject to App means we need to implement serializable for it, CollectionHandler, WebAppContext, and everything that WebAppContext has too (which they currently do not).

There is no point exposing the whole App object anyway for JMX, its too detailed, and make it more difficult for other JMX methods to use as well.

I explored having it return the MBean reference to the WebAppContext, this is unsupported by jetty-jmx, and is not something that I wanted to get into right now.

Also, the WebAppContext alone is insufficient to communicate the role of App for the other methods on the DeploymentManager.

**Comment by gregw** [comment]
@joakime You are misunderstanding me.   I'm not saying return the App objects.   I'm saying that when we add methods that are just there for JMX, do not add them to the main class.  Instead add them to the MBean class.

The MBean class exists in this case, but is not being correctly used because it has not been correctly annotated.     So either the MBean class needs to be fixed or it needs to be removed.    As there are methods that exist only for JMX, then it is best to keep the MBean class.

Now I think there is a question that does need to be answered, in that when we added the management mbeans, I'm not sure if just the MBean class or both the normal and MBean class need to be annotated.  If both (as we have in other examples I have looked at (eg Server and ServerMBean)), then we get two descriptions for the mbean - which is used?

So perhaps we should change the ManagedObject code so that if class `Foo` is annotated as managed, we don't need to annotate the class `FooMBean` and it is just used for additional methods & fields.

**Comment by joakime** [comment]
Ah, gotcha, you are talking about the `.jmx.<Class>MBean` specific implementation of the DeploymentManager, not the generic MBean implementation stuff.

**Comment by rothskeller** [comment]
@gregw, if both classes are annotated, the methods and attributes of the MBean class take precedence, but annotated methods and attributes on the main class will be used if the MBean doesn't have equivalents for them.  (Also, annotated methods and attributes on the superclasses of either MBean or the main class, likewise.)
