### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: no cipher suites in common

### ISSUE THREAD

**Issue by Horcrux7** [eclipse/jetty.project#1684]
The method org.eclipse.jetty.util.ssl.SniX509ExtendedKeyManager.chooseServerAlias() should never return null because this result in a "javax.net.ssl.SSLHandshakeException: no cipher suites in common"

See also at https://stackoverflow.com/questions/41293778/jetty-javax-net-ssl-sslhandshakeexception-no-cipher-suites-in-common for details.

If this is a configuration error then is should throw an exception. If this valid then it should return NO_MATCHERS.

**Comment by gregw** [comment]
I'm not sure it is true that `chooseServerAlias()` should NEVER return null.   Return of null is the default implementation and is what the javadoc says should be returned "if there are no matches".

The `SniX509ExtendedKeyManager` is a wrapper around a standard `X509ExtendedKeyManager` and it's internal `chooseServerAlias` can return either:
 - null to say there were no aliases matching in the delegate manager, thus there can be no matches.
 - NO_MATCHES, is a flag to say that no SNI alias match were available, so instead attempt a non SNI based match on the delegate manager
 - null if an SNI match was found, but failed to match any of the allowable aliases returned from the delegate
 - the alias of the SNI match

Thus null is only return if there are no aliases, or there are aliases, but none of them were matched by SNI.  I don't think in either case it is valid to go on and try a default non SNI match.  Specifically if there is a certificate that matches SNI, but it is not an allowed alias, then for that SNI name there are no ciphers in suites common.     Perhaps we could give more debug on that, but I'm not sure it is valid proceed to match a certificate just because it has a cipher in common, but could potentially of a non matching SNI host name!

@joakime sanity check please?

**Comment by joakime** [comment]
oof, so we have normal, sni, extended, and alternate implementations (bouncycastle, conscrypt, etc) to investigate this behavior for.

**Comment by gregw** [comment]
@joakime well investigating specific implementations is probably good... but we can start with a thought experiment...

If we have SNI matchers  AND an SNI match for a host name, but that certificate is not in the list of allowable aliases.... then SHOULD we return null or NO_MATCHES?     

If we return NO_MATCHES, then we will delegate to the normal manager, which will attempt to match any certificate with appropriate ciphers, ignoring all SNI info!  So it can match a certificate that is for another host!     I think that is just wrong?  No???

I think the no cipher suites in common message is a little confusing, but it is actually true - for the given SNI match, there are no cipher suites in common.    However, for the original OP, there actually were, but because they had a wrong alias, the match was not completed.

**Comment by joakime** [comment]
Javadoc (Java 10) for [javax.net.ssl.X509KeyManager#chooseServerAlias(String, Principal, Socket)](https://docs.oracle.com/javase/10/docs/api/javax/net/ssl/X509KeyManager.html#chooseServerAlias(java.lang.String,java.security.Principal%5B%5D,java.net.Socket))

**Comment by joakime** [comment]
Other discussions around Jetty's use of `chooseServerAlias()`

* https://stackoverflow.com/questions/10425306/if-theres-more-than-one-certificate-in-jettys-key-store-how-does-it-choose
* https://stackoverflow.com/questions/50700662/how-java-sslsocketfactory-choose-the-server-certificate-and-private-key-during-s
