### ISSUE TITLE
Jetty build fail due to jetty-servlets

### ISSUE THREAD

**Issue by chenweiii** [eclipse/jetty.project#1701]
Hey guys,

I just want to build jetty (execute "mvn -Dmaven.test.skip=true install") 
But the following message comes to me

[ERROR]
Failed to execute goal on project jetty-servlets: Could not resolve dependencies for project org.eclipse.jetty:jetty-servlets:jar:9.4.7-SNAPSHOT: Failure to find org.eclipse.jetty:jetty-servlet:jar:tests:9.4.7-SNAPSHOT in http://oss.sonatype.org/content/repositories/jetty-snapshots was cached in the local repository, resolution will not be reattempted until the update interval of jetty-snapshots has elapsed or updates are forced

Can anybody help me, or just a bug?

**Comment by joakime** [comment]
You cannot skip the test compile & install, just the test execution.
This is because the test classes from one project are used to compile the test classes for another project.
Using `-Dmaven.test.skip=true` will skip the compile & install of those test classes.

Use `mvn clean install -Dtest=None` instead.

**Comment by chenweiii** [comment]
@joakime Thank you very much! I finally build successfully.
