### ISSUE TITLE
Refactor jetty maven plugin goals to be more orthogonal

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#1743]
Reduce proliferation of maven goals, and make configuration options orthogonal across the board.

**Comment by sbordet** [comment]
I like in general the current status of the new implementation behind this issue.

My notes:

1. Make `https` configuration simpler and via `pom.xml` rather than external XML. 
Given HTTP/2, it would not be uncommon to want to try HTTP/2 and an external XML file seems too much of a burden.

1. Mixed feelings about `loginServices`, as it seems to me (very) advanced configuration that requires external XML. Some of them can be configured via a `*.properties` file (so easy to setup from the plugin), some cannot.
If we do `LoginService`s, we can certainly do `https` connectors.

1. Would be possible to specify the `deployMode` on command line, as in `mvn jetty:run -DdeployMode=FORK`?

1. `FORK` mode should be easy to configure in case of ALPN bootclasspath.

1. Would it be possible to run the plugin on the Java 11 module-path, rather than the class-path?

1. I would remove the `server` element, seems confusing and only for advanced usages, where you can use the XMLs

1. I would remove the overlay feature, the one of the `maven-war-plugin` seems enough to me.

1. Do we still need `jetty:stop`? I ask because Java 11 has more powerful APIs for controlling processes and child processes, so `ctrl+c` in the spawning console should be enough. Given that you need to be on the machine that runs the Jetty Plugin to issue `jetty:stop` (as there is no `stopHost`), a `kill -TERM <pid>` should also do the job.

**Comment by joakime** [comment]
> 1. Make `https` configuration simpler and via plugin rather than external XML.

What do you mean by "plugin" in this context

> 7. I would remove the overlay feature, the one of the `maven-war-plugin` seems enough to me.

I agree, overlay is handled better by existing plugins.

> 8. Do we still need `jetty:stop`? I ask because Java 11 has more powerful APIs for controlling processes and child processes, so `ctrl+c` in the spawning console should be enough. Given that you need to be on the machine that runs the Jetty Plugin to issue `jetty:stop` (as there is no `stopHost`), a `kill -TERM <pid>` should also do the job.

Can the proposed Java 11 APIs be used to handle proper Jetty shutdown?
What about graceful shutdown testing?
If the answer isn't a resounding "Yes", then we need `jetty:stop`, as proper (and graceful) shutdown cases are important to many people.

**Comment by sbordet** [comment]
I don't think we want graceful shutdown (as in "stop incoming connections + stop incoming requests + wait for all requests to be finished + close connector, selector, pools, server") for the Jetty plugin - it's a dev tool.

AFAIU, we only want a way to stop the forked JVM, which prior to Java 11 could have been difficult for lack of APIs.

**Comment by janbartel** [comment]
Committed to jetty-10 branch.
