### ISSUE TITLE
[Question] Why org.eclipse.jetty.util.security.Password.java main function takes username, but use it as salt?

### ISSUE THREAD

**Issue by alvinlin123** [eclipse/jetty.project#1762]
From my code reading I see that `org.eclipse.jetty.util.securit.Password.java` takes in 2 arguments, username (optional) and password. However if I trace trough the code, the username eventually become the salt (by taking the first 2 character) for hashing password. 

So I am wondering why does `org.eclipse.jetty.util.securit.Password.java` document the first optional argument as "username"; why not just document it as "salt"?

**Comment by joakime** [comment]
The `main()` method entry point is used on command line only to generate passwords (OBF style) for configuration files (xml and ini).

These kinds of passwords show up most often for keystore/truststore based configuration of SSL.

While the Password object does support 1-way crypts, (where a salt is most useful) those kinds of passwords are generally not useful for the role that `Password#main()` exists for.

**Comment by alvinlin123** [comment]
Thanks for replying @joakime, you definitely gave me some useful insight. 

I am using the `Password` class to 1-way crypts password for basic HTTP authentication. The crypted password is store in the `jetty-realms.properties`. Should we not use the `Password` class for this use case?

By the way, I guess my original question was more about the documentation of `Password#main` method. It looks like username is used as salt so how come the documentation didn't say something like ` System.err.println("Usage - java " + Password.class.getName() + " [<salt>] <password>");`. I am worry about this because I have a script that uses the `Password#main` to encrypt password and because I read the code, instead of using username as first argument, I am generating random string as the first argument (so basically I didn't follow the documentation of using username). So, in the later release of Jetty, would it ever be possible that you actually HAVE TO use username as the argument, else the HTTP auth will stop working?

**Comment by gregw** [comment]
@alvinlin123 The behaviour around Crypt is taken from the normal usage of that algorithm in unix password handling where the username is used as salt for the password (so that different users, using the same password don't have the same encyrpted password).

So while the algorithm calls that parameter salt, the usage of that algorithm as a user password protection mechanism uses the username as the salt parameter.  Hence the parameter at that level is correctly called username.

You should pass in username at that point and not some other salt.   This has been this way for over 10 years and there is no intention of changing, so it is a stable interface.

If you use the Crypt class directly for other purposes, you are free to provide whatever you like as salt, but using it for Password, the username should be used as the salt.

**Comment by alvinlin123** [comment]
@gregw  thanks for the answer :)
