### ISSUE TITLE
Async getContextPath()/getPathInfo()

### ISSUE THREAD

**Issue by LeviticusMB** [eclipse/jetty.project#1780]
In the following example, the value returned by `getContextPath()`/`getPathInfo()` depends on when the call is made (sync or async). Is that really the intended behavior?

What else can I not trust in the request or response objects when accessed outside the `service()` method?

```java
import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.AsyncContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.eclipse.jetty.server.LocalConnector;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.servlet.ServletContextHandler;
import org.eclipse.jetty.servlet.ServletHolder;
import org.junit.*;

public class AsyncServletTest {
    static { org.apache.log4j.BasicConfigurator.configure(); }
    private static final org.slf4j.Logger logger = org.slf4j.LoggerFactory.getLogger(TillServer.class);

    @Test
    public void testAsyncServlet() throws Exception {
        Server server = new Server();

        LocalConnector connector = new LocalConnector(server);
        server.addConnector(connector);

        ServletContextHandler handler = new ServletContextHandler(server, "/v1/", false, false);
        handler.addServlet(new ServletHolder(new HttpServlet() {
            @Override
            protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
                AsyncContext cx = req.startAsync();
                String cp = req.getContextPath();
                String pi = req.getPathInfo();

                logger.info("doGet: {} {}", req.getContextPath(), req.getPathInfo());

                new Thread(() -> {
                    try {
                        Thread.sleep(100);

                        logger.info("Thread: {} {}", req.getContextPath(), req.getPathInfo());

                        new PrintWriter(resp.getOutputStream())
                            .append(cp).append("\r\n")
                            .append(pi).append("\r\n")
                            .append(req.getContextPath()).append("\r\n")
                            .append(req.getPathInfo()).append("\r\n")
                            .close();
                    }
                    catch (Exception ex) {
                        logger.error("Thread failed", ex);
                    }
                    finally {
                        cx.complete();
                    }
                }).start();
            }
        }), "/*");

        server.setHandler(handler);
        server.start();

        String[] response = connector.getResponse("GET /v1/foo HTTP/1.0\r\n\r\n").split("\r\n");

        Assert.assertEquals("Sync getContextPath",  "/v1",  response[response.length - 4]);
        Assert.assertEquals("Sync getPathInfo",     "/foo", response[response.length - 3]);
        Assert.assertEquals("Async getContextPath", "/v1",  response[response.length - 2]);
        Assert.assertEquals("Async getPathInfo",    "/foo", response[response.length - 1]);
    }
}
```

**Comment by LeviticusMB** [comment]
I should add the the issue i have is that in the thread, the context is null and the path info is the full HTTP path including /v1.

**Comment by gregw** [comment]
I'm not sure if "intended" is the right word, but it is "emergent" behaviour that evolved with the specification.  A mutable request instance is probably an un intended consequence of decisions made long ago in a single threaded servlet view.

The problem is that the servlet spec long  long ago mandated that the instances of request/response passed into a call to RequestDispatcher forward/include are the same instances that will be used for the resulting dispatch.  This means that there is no opportunity for the container to wrap the request and lock it a set of contextPath/servletPath/pathInfo values.  All fine in a single threaded world, but it means that in a multi threaded application a non container thread that observes a request instance is looking at a very mutable object that can change as it is dispatched and returns from those dispatches.

In fact there are few methods on the request object that are thread safe and I think a note to that effect was added in the 3.1 servlet specification.

If starting from scratch now, I would very much argue that request instances should be immutable and that dispatching/rewriting/etc. operations should just create new instances that wrap and change the fields they need to.... but that is not what we have.   Request instances are mutable and not safe to look at from other threads.   

My advice is to extract all the information you need from the request as you startAsync.  You can store it in a request Attribute if needed, as they are pretty thread safe (for lookup at least).
