### ISSUE TITLE
Servlet Spec 4.0 / JSP369 support

### ISSUE THREAD

**Issue by phax** [eclipse/jetty.project#1799]
Hi guys!
Short question: what release of Jetty will start targeting Servlet Spec 4.0 as defined in https://jcp.org/en/jsr/detail?id=369 
The final release of the spec was on September 5th.

Thanks!

**Comment by gregw** [comment]
Philip,

Jetty 10 will be servlet 4.0.  This is our master branch and can already be
built and run. We will do a beta release within weeks and hopooe to gave
the stable release before the end of the year.

Regards


On 8 Sep 2017 00:12, "Philip Helger" <notifications@github.com> wrote:

Hi guys!
Short question: what release of Jetty will start targeting Servlet Spec 4.0
as defined in https://jcp.org/en/jsr/detail?id=369
The final release of the spec was on September 5th.

Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/eclipse/jetty.project/issues/1799>, or mute the thread

**Comment by joakime** [comment]
Following our normal versioning guidelines ...

```
<servlet_support>.<major_version>.<minor_version>

 7.x = Servlet 2.5
 8.x = Servlet 3.0
 9.x = Servlet 3.1
10.x = Servlet 4.0
```
