### ISSUE TITLE
JstlTest failure with JDK 9

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1817]
@janbartel, can you please review `JstlTest` when using JDK 9 to run the tests ? It fails with:

```
org.apache.jasper.JasperException: The absolute uri: http://java.sun.com/jsp/jstl/core cannot be resolved in either web.xml or the jar files deployed with this application
```

I have currently "disabled" the test for JDK 9 only using JUnit's `Assume`. Feel free to remove it when the test works with JDK 9 as well

**Comment by janbartel** [comment]
The test will need to remain disabled in jetty-9.

The problem is that with jdk-9, the system classloader is **not** a URLClassLoader and thus cannot be interrogated for its urls. This is a technique that our o.e.j.webapp.WebInfConfiguration class uses to find the urls of jars on the server's classpath, and apply user-defined patterns that control the ordering/inclusions of jars to scan for tags, resources, web-fragment.xmls and annotations.

This works fine with jdk-9 for the jetty-maven plugin because maven's ClassRealm classloader is a URLClassLoader. The distribution also works fine with jdk-9 because start.jar creates its own URLClassloader to be the parent of the webapp.

However it will fail on probably almost every embedded environment.

This will need some thought to fix, and probably help from jdk-9 apis, so won't be possible to fix in jetty-9.

**Comment by gregw** [comment]
I'm guessing it will also fail if start.jar runs in exec mode, as it will not have the URLClassloader.

So with java9, we cannot scan any jars that are on the system classpath?  Hmmm we may need to reconsider our basic class loading and start mechanism more than we'd thought :(

**Comment by janbartel** [comment]
Re-established the JstTest after fixing issue #1933

**Comment by BoilerTom90** [comment]
I'm using version jetty-9.3.0.v20150612 in an OSGI environment, with v2.5 of the Servlet specification.  I've inherited a mass/mess of old Java Servlet code that works, that is replete with security issues.  I'm trying to address some of the XSS issues by using JSTL.  I've added the required JSTL directive at the top of the JSP files:

`<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>`

But when I first access this jsp page, it fails and I see the following in the error log:

2019-01-08 20:44:44,606 qtp1697835528-134 WARN  org.eclipse.jetty.servlet.ServletHandler  -

```
org.apache.jasper.JasperException: /jsp/applicationsChoice.jsp(1,63) PWC6188: The absolute uri: http://java.sun.com/jsp/jstl/core cannot be resolved in either web.xml or the jar files deployed with this application
        at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:92)
```
I've seen many old references that suggest there were at one point in time issues with JSTL and the Jetty 9.x release. Is this old information? Can someone supply a pointer or two?

Thanks much!
Tom Hoffman
