### ISSUE TITLE
Logging modules should not force --exec

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1822]
Currently the new logging modules always force --exec because they set the org.eclipse.jetty.util.log.Log=<logging-impl> via a system property setting.

This should be changed to create a ${jetty.base}/resources/jetty-logging.properties instead.

**Comment by gregw** [comment]
This is a good idea, but the semantic of the start.jar mechanism is not sufficient for switching between implementations.   So while enabling an initial logging module could be made to work fine (and create the jetty-logging.properties file), if the user then switched to a different logging module, the existence of the jetty-logging.properties file would prevent it being recreated with the correct settings.   If we force creation of the properties file, we could overwrite logging configuration that the user wanted.

Instead we probably need create/search/replace semantic on the files mechanism like:

```
replace:org.eclipse.jetty.util.log.class=.*|org.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StdErrLog|resources/jetty-logging.properties
```

where the semantic is that if the file `resources/jetty-logging.properties` exists, then any line matching the regex `org.eclipse.jetty.util.log.class=.*` will be replaced with the line `org.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StdErrLog`.  If the file does not exist, then it will be created with the single line `org.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StdErrLog`

**Comment by gregw** [comment]
We should either do this now for jetty-10, or close as not going to be implemented.  @joakime @olamy @sbordet @janbartel thoughts?

**Comment by sbordet** [comment]
IMHO not worth to be implemented. Perhaps we can have an example on (or document) how to create your own logging module without `--exec`.

**Comment by joakime** [comment]
Just modify the jetty-logging.properties and be done with it.  '--exec' should be avoided if at all possible.

**Comment by joakime** [comment]
This is the technique I think we should go with ...

1. If the user picks a logging framework, and the `resources/jetty-logging.properties` exists, make a backup of that file (`resources/jetty-logging.properties.backup.<timestamp>`).
2. Notify the user that a backup has been made (including the filename of the backup).
3. Create a new `resources/jetty-logging.properties` with the single line necessary for this newly selected logging framework.

The rationale here is that if you select a different logging framework, nothing in the existing `resources/jetty-logging.properties` is relevant, there's no point attempting to modify/use it.

This follows the behavior found in various linux packaging utilities as well.

**Comment by gregw** [comment]
So to trigger the backup mechanism, we still need some new syntax in the mod file.  Currently to create a logging module specific properties file, we need to do:
```
basehome:modules/logging-xyz.d/jetty-logging.properties|resources/jetty-logging.properties
```
But the problem with this, is that once created for one logging module, it would not be created again if a different module is enabled.   So I think we need to add a check of the contents of the target file:

```
basehome:modules/logging-xyz.d/jetty-logging.properties|resources/jetty-logging.properties{org.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StdErrLog}
```
So this says that the file `resources/jetty-logging.properties` must exist and must contain `org.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StdErrLog`, otherwise it will be replaced by `modules/logging-xyz.d/jetty-logging.properties`.  When replacing a file that exists, then we can create a backup as @joakime describes above.

**Comment by sbordet** [comment]
I'm not sure we want to look at content, as users may have specified they own custom implementation and we'll never match.
I'd stay simple and if there, backup, otherwise create.
Add a `+` before the file to signal that?

`basehome:modules/logging-xyz.d/jetty-logging.properties|+resources/jetty-logging.properties`

**Comment by gregw** [comment]
@sbordet I'm concerned that a replace always approach will not be able to distinguish between an explicit enabling of a module, a transitive enabling and a check to see if the dependencies are there.  Thus we will probably replace the file whenever any change is made to the modules, even for unrelated modules.

So I think we do need to look at content, but perhaps looking for a comment is more flexible than looking for a specific class?

**Comment by sbordet** [comment]
@gregw a check should not modify anything. Explicit vs transitive, I don't see the difference.
If adding another unrelated module will re-do the backup then that is not good and at that point yes we need to look at content: look at current `jetty-logging.properties` content and if it has a special marker don't backup it.
Or perhaps: look for backup file: if it exists, just recreate the current one - so you won't have to look at the content.

**Comment by WalkerWatch** [comment]
If a user switches logging frameworks several times, will/can this result then in the creation of several backup `jetty-logging.properties` files? I would assume/hope that it would, so as to preserve work/changes that had been made in the files prior to switching frameworks.

**Comment by sbordet** [comment]
@WalkerWatch a customized `jetty-logging.properties` would only exist if the user uses the Jetty logging.

When the user decides to move to any other logging library, `jetty-logging.properties` would just have 1 line that indicates to the Jetty logging where to forward the logs to, something like:

`org.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.JavaUtilLog`

The configuration file for the chosen logging library will have all the customization.

So we only need to backup once, in case the user was using the Jetty logging and `jetty-logging.properties` was customized.

**Comment by gregw** [comment]
@sbordet the way it is implemented, we do a check for files for all modules that are in the enabled set and their transitive dependencies.  At anytime the check can fail and the file will be recreated (if adding new modules or using the --create-files) option.   If we don't check the contents, we have no way of telling the if the file that is there is the right one or not, so we will have to continually make backups of it.
Thus I still see the contents check as the simplest way of achieving this.

The only other alternative I can think of is to have the files for different logging setups in different file names and then to pass in the filename as a system property.  So instead of having `jetty-logging.properties`, we will have a lot `jetty-XYZ-logging.properties` files and a system property like `-Dorg.eclipse.jetty.util.logging.properties=jetty-XYZ-logging.properties`.  That's a bit yuck as well.
