### ISSUE TITLE
Serving static compressed files even if non-compressed version doesn't exist

### ISSUE THREAD

**Issue by MarceloMadruga** [eclipse/jetty.project#1862]
Hello,

I created a simple embedded server with a ServletContext to serve static files in which few of them are pre-compressed. You may find it under this repository [jetty-gzip](https://github.com/MarceloMadruga/jetty-gzip). I'm able to resolve *.gz files when both exists in file system, but I'm not able to serve the file when only the compressed file exist. I'm not sure if it is a bug o if there is a missing configuration to map some-file.css to some-file.css.gz where some-file.css does not exist. While debugging I end up at [ResourceContentFactory.load](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceContentFactory.java#L66) which expects both files to exists prior to serving only the compressed one.
If you run the example from my repo, you can server [localhost:8080/style.css](url) which contains both compressed and decompressed files, but not [localhost:8080/gstyle.css](url) which contains only compressed file. Well, I might have misunderstood the feature, but I really expected it to work without needing decompressed one.

**Comment by joakime** [comment]
_This sounds familiar, like a previous issue I recall (but cannot find)._

The implementation is designed to use both files, as there are many clients that do not support gzip compression.

Note: the statically compressed versions also support compression format other then gzip (such as brotli).

**Comment by joakime** [comment]
Ah, previous issue #313 was the duplicate (imported from [bugs.eclipse.org/481438](https://bugs.eclipse.org/481438))

**Comment by MarceloMadruga** [comment]
Hey @joakime, thanks for quick reply. So is there any chance of relaxing the decompressed file check and try to resolve any of pre-compressed files (br; gzip; or any other specified in _precompressedFileFormats) instead?
[line 69](https://github.com/eclipse/jetty.project/blob/c2bcdd5ed48612e6a68239c1045ddb0375db7e95/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceContentFactory.java#L69)
`if (resource==null || !resource.exists())
            return null;
`
and [line 85](https://github.com/eclipse/jetty.project/blob/c2bcdd5ed48612e6a68239c1045ddb0375db7e95/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceContentFactory.java#L85)

`if (compressedResource != null && compressedResource.exists() && compressedResource.lastModified() >= resource.lastModified()
                        && compressedResource.length() < resource.length())
`

I tried to find a workaround, like adding headers to the request once it hits Jetty to resolve to compressed files. But it doesn't sound right.

**Comment by gregw** [comment]
While I can see the argument that we should serve a resource even if it is only available in compressed form, I see that as more of a feature rather than a bug.

The problem is that without a gz file, we can always provide a response because uncompressed is a valid response to a request that allows compressed.   But if only the compressed is available, we cannot send that as a response to a request that does not accept compressed.

Currently the resource cache is keyed off the primary resource, so we cannot easily change to support compressed only.    To make the change could be a bit of restructuring and we have to be careful not to slow down the 99.999% of requests that do not need this feature.

So we do intend to resolve, but this is very low priority... I would just create the uncompressed file for now.

**Comment by MarceloMadruga** [comment]
Thanks @gregw. Sorry about flagging it as a bug. I understand your concerns about this change. I'll do what you suggested for now.

**Comment by gregw** [comment]
no intention of supporting this for now
