### ISSUE TITLE
Unable to change thread pool configuration in jetty 9

### ISSUE THREAD

**Issue by rajeevvs2007** [eclipse/jetty.project#1872]
In jetty.xml , i am trying to change the thread pool configuration from unbounded to bounded queue.I am getting an error during thr server startup.

**Exception** 

```
java.lang.IllegalStateException: No suitable constructor: <New id="threadpool" class="org.eclipse.jetty.util.thread.QueuedThreadPool"><Arg name="maxThreads">10</Arg><Arg name="minThreads">500</Arg><Arg name="idleTimeout">10000</Arg><Arg name="queue">|        <New class="org.eclipse.jetty.util.BlockingArrayQueue"><Arg type="int">5</Arg></New>|      </Arg></New> on null
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:794)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1235)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1140)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:335)
	at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:259)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1499)
```

**My configuration** 

```
 <Arg name="threadpool">
    <New id="threadpool" class="org.eclipse.jetty.util.thread.QueuedThreadPool">
      <Arg name="maxThreads">10</Arg>
      <Arg name="minThreads">500</Arg>
      <Arg name="idleTimeout">10000</Arg>
      <Arg name="queue">
        <New class="org.eclipse.jetty.util.BlockingArrayQueue">
	        <Arg type="int">5</Arg>
	 </New>
      </Arg>
    </New>
  </Arg>
```

**Comment by gregw** [comment]
@rajeevvs2007 this error indicates that a prior XML has already constructed the server instance and set the thread pool on it.    So use the --dry-run arg to see the order of the XML files and set this arg in the first one that defines the Server.

Note that we STRONGLY recommend to not have a blocking limited queue on the threadpool.   The item size of the job queue is very small and memory is best constrained by limiting connections or simultaneous requests rather than putting a limit on the job queue.     

Rejected execution exceptions and/or blocking puts to the job queue can be fatal or at least very harmful to server stability.

If you are seeing large job queues, then I suggest you diagnose the cause rather than try to prevent the symptom.

**Comment by rajeevvs2007** [comment]
@gregw Thanks for the explanation.I have added the configuration in jetty.xml which is the first file loaded by server.
