### ISSUE TITLE
HttpParser error 400 can expose previous buffer contents in log file

### ISSUE THREAD

**Issue by ArslanIbnDaud** [eclipse/jetty.project#1874]
This is a follow-up to former bug 460642 AKA CVE-2015-2080:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=460642#c17

Wouldn't it be more secure to simply not allow the sensitive info from a previous HTTP request (AKA the contents of the buffer from limit to capacity in BufferUtil.appendDebugString()) to be logged at all?  Granted not sending it over the web is a good idea, but not saving it in a log message is an even better idea.  Leaving this info in the server logs mandates that all Jetty users trust their sysadmins to not use this info, and protect it from attackers. While this may be a convention in the Jetty community, I see no written documentation stating this.

A patch would be to simply remove lines 1076 - 1087 in jetty.project/jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java:

                  }
              }
              buf.append(">>>");
-             int limit = buffer.limit();
...
-             buffer.limit(limit);
        }
        catch(Throwable x)
        {

**Comment by gregw** [comment]
Being able to view the contents of a buffer either side of the position and limit is a valuable debugging tool.  This information is not routinely logged and is only visible if debug logging is on.    Access to debug logging has to be a trusted exercise because lots of sensitive information is logged in debug: session IDs, TLS sessions, usernames etc.

To make debug log secure would be to render it near useless, as it could only contain public information.

**Comment by joakime** [comment]
Closing this issue.
If you have untrusted users that can access the debug logs, then you have more fundamental security issue.

The CVE linked was not about debug logs, but rather a report of this information over the HTTP protocol itself (the 400 error response).  That specific behavior was only present in Jetty versions 9.2.3 thru 9.2.8 and has been corrected in Jetty 9.2.9 and newer releases.
