### ISSUE TITLE
[jetty-client] Reusing connection for 2 subsequent requests is not possible

### ISSUE THREAD

**Issue by korobochka** [eclipse/jetty.project#1907]
I am using `HttpClient` instance from multiple threads to send HTTP requests. Each thread has to send 2 subsequent requests on the same connection (Keep-Alive) due to protocol quirks.

I was not able to find a way to do so: connections are reused between all threads in random order.
Is it possible to implement this without either making `HttpClient` thread-local or setting maxRequestsPerDestination to 1?

### Background
I am using jetty-client 9.4.7 (stable) to communicate with some legacy SOAP service. This service is using NTML auth. Basic flow for this auth is: send HTTP request with "type1" auth token in Authorization header, server will respond with 401 that contains "type2" token in WWW-Authenticate header, then you send first request again with "type3" token that is generated from "type2".
I successfully implemented this auth flow and it works well. The issue is that NTLM is a connection based auth: you have to use Keep-Alive and send "type3" token on the same connection as "type1".
My implementation works when I use HTTP client from single thread, but quickly breaks in muti-threaded scenario: another thread snatches a connection between "type1" and "type3" requests, new connection is opened and auth does not work.
I looked at the source of `AuthenticationProtocolHandler` and there are some lines that take `Connection` from `Request` attributes, but this does not work, attributes are always empty.

I asked this question in IRC and @joakime suggested to open an issue here.

**Comment by sbordet** [comment]
NTLM is completely broken from the point of view of HTTP, since it mandates that a particular TCP connection is authenticated, making the exchange stateful, violating the fact that HTTP is stateless.
See for example: https://lists.w3.org/Archives/Public/ietf-http-wg/2014OctDec/0048.html.

Best solution in this case is to use direct `Connection` objects from `Destination`s, rather than relying on `HttpClient` connection pooling. Even better will be avoid using NTLM.

Note that NTLM is completely broken in HTTP/2, and not even Microsoft is supporting it (see https://blogs.iis.net/davidso/http2).

All of the above are the reasons we did not implement NTLM in `HttpClient`.
Whether is doable I'm not sure. Is your code publicly available to look at ?

**Comment by korobochka** [comment]
@sbordet Thanks.
Yes, I am not happy about using NTLM (and understand why it is broken), but I have to integrate with legacy service, _what can you do_?..

My code is not public (due to enterprise reasons) but here is a sample:
```java
ContentResponse send(Request request) throws Exception {
    Client ntlm = new Client(null, "hostname", login, domain, password.toCharArray()); // com.sun.security.ntlm.Client
    String type1 = "NTLM " + Base64.getEncoder().encodeToString(ntlm.type1());
    ContentResponse response = request.header(HttpHeader.AUTHORIZATION, type1).send();

    String challenge = response.getHeaders().get(HttpHeader.WWW_AUTHENTICATE)
        .substring(5); // skipping "NTLM "
    byte[] type2 = Base64.getDecoder().decode(challenge);
    byte[] nonce = new byte[8]; // fill with random
    String type3 = "NTLM " + Base64.getEncoder().encodeToString(ntlm.type3(type2, nonce));

    Request newRequest = copyRequest(request);
    newRequest.header(HttpHeader.AUTHORIZATION, type3);
    return newRequest.send();
}
```

I also had to remove default `WWWAuthenticationProtocolHandler` since the regex in `AuthenticationProtocolHandler` requires realm and fails on the first send().

Works quite well with single thread.

**Comment by sbordet** [comment]
Can you please try the following: instead of using `Request.send()` which will use the connection pool mechanism in `HttpClient`, use `Connection.send(Request, CompleteListener)`, where you can control the connection you use:

```java
HttpClient httpClient = ...;
Destination destination = httpClient.getDestination(scheme, "hostname", port);
FuturePromise<Connection> p = new FuturePromise<>();
destination.newConnection(p);
Connection connection = p.get(5, SECONDS);
Request request = ...; // Add NTLM headers
FutureResponseListener l = new FutureResponseListener();
connection.send(request, l);
ContentResponse response = l.get(5, SECONDS);
```

The downside of this is that now you have to take control of connections yourself: store them somewhere, make sure that the connection is open before sending a request, close them when you are done with them, etc.

However, if a single client does not need more than 1 connection, you can probably get by easily by allocating a single connection per client, and this will solve the concurrency issues you have with the connection pool. It's less efficient (one connection per client, rather than fewer connections that a connection pool may use), but still fully asynchronous (threadless waits on I/O).

**Comment by korobochka** [comment]
Thanks, this approach worked, I am getting consistently successful results.

I am opening single connection per thread. Only thing that worries me: can this single connection become stale? Is there a way to test it and reopen if needed. I can see that ConnectionPools have some related logic, can it be somehow reused?

**Comment by sbordet** [comment]
The connection may be closed at any time by the server, or by the HTTP header `Connection: close`.
On the client, it can also be closed by the idle timeout mechanism.

You cannot reopen a connection, but you can open another one and perform the NTLM authentication again.

I'm afraid there is no way to tell safely if a connection is closed: you check and find it open, and a moment later the server closes it.
This is unavoidable, and clients have to be prepared to handle such case and possibly open a new connection and retry the request.

What connection pool logic are you referring to ?

**Comment by korobochka** [comment]
I was referring to `ValidatingConnectionPool`.

**Comment by sbordet** [comment]
`ValidatingConnectionPool` solves the problem of badly behaving servers that do not send the `Connection: close` header, but then they close the connection immediately after a response.

Note that it's a best effort, because the connection may be closed by the server immediately after the connection has exited the quarantine imposed by `ValidatingConnectionPool`.

**Comment by korobochka** [comment]
Also there is the issue of "half-closed" connections: server can close socket without sending anything and the only way to check that this TCP connection is dead is to `send` something.

I think you have answered all my questions, and the workaround with `Connection.send()` is working well for me.
Thanks for the help!

**Comment by sbordet** [comment]
> Also there is the issue of "half-closed" connections: server can close socket without sending anything and the only way to check that this TCP connection is dead is to send something.

Yes, and clients have to be prepared to this situation, as servers are entitled at closing the connection at any time.

You can close the issue if it's solved for you.
