### ISSUE TITLE
AsyncMiddleManServlet set the content-length as null if the upload file size is above 4k and without Expect: 100-continue header

### ISSUE THREAD

**Issue by gsiva** [eclipse/jetty.project#1929]
I've tried to upload a file (>=4k) through the AsyncMiddleManServlet and there is no Expect:100-continue header in that request call. During this time noticed that the content-length header is wiped out in the proxy request. At the other end its reaches with the content-header as null.

line: 412-416

                if (!expects100Continue)
                {
                    proxyRequest.header(HttpHeader.CONTENT_LENGTH, null);
                    sendProxyRequest(clientRequest, proxyResponse, proxyRequest);
                }

**Comment by sbordet** [comment]
This is by design. `AsyncMiddleManServlet` does not know whether you will be doing content transformations, so it must reset the `Content-Length` header.

**Comment by gsiva** [comment]
Is there anyway to handle this ie., to keep the Content-Length header

**Comment by sbordet** [comment]
With smaller content lengths, `AsyncMiddleManServlet` is able to perform the transformation and see that the whole content has been transformed before sending the request to the server, so it is able to know the exact content length after the transformation, and therefore it can add the `Content-Length` header.

With larger content lengths, `AsyncMiddleManServlet` must send the request to the server before the whole content has been transformed, so it cannot know the content length.

If you're not transforming content, use `AsyncProxyServlet` instead of `AsyncMiddleManServlet`, so that the content length should be preserved.

**Comment by gsiva** [comment]
Thanks again @sbordet .  I am doing content transforming that is the reason why I suppose to stick with  AsyncMiddleManServlet. Is there any way to over come this?

**Comment by sbordet** [comment]
Why is the lack of `Content-Length` header a problem for you ?
