### ISSUE TITLE
Use CLASSPATH for scanning java9 system classes

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1933]
In java8, the system classloader is a URLClassloader, so jar locations could be discovered when scanning for annotations.  In java9, the classloader is no longer a URLClassloader, so when scanning system jars if a non URLClassloader parent loader is discovered, the System.property classpath should be used to find jars to scan.

This problem should be raised with the appropriate java mailing list to ask how are system jars meant to be scanned for discovered annotations?

**Comment by gregw** [comment]
Alternately use something like:
```java
        Optional<ModuleReference> moduleRef = ModuleFinder.ofSystem().find("java.base");
        if (moduleRef.isPresent())
        {
            ModuleReader reader = moduleRef.get().open();
            String collect = reader.list()
                    .sorted()
                    .collect(Collectors.joining(System.lineSeparator()));
            System.err.println(collect);
        }
```

**Comment by janbartel** [comment]
I don't think these are mutually exclusive alternatives. According to "java --help" , -cp is still a valid argument, but they have also added:

- --module-path
- --upgrade-module-path

According to the javadoc, you can retrieve these as system properties:

- java.class.path
- jdk.module.path
- jdk.module.upgrade.path

So IIUC, one must examine both the classpath and the module path in order to discover annotations.

**Comment by janbartel** [comment]
Committed to jetty-9.4.x and master branches.
