### ISSUE TITLE
Jetty deadlock with session persistence

### ISSUE THREAD

**Issue by lgangloff** [eclipse/jetty.project#1947]
Hello,
We're have an issue under high load test with the lastest snapshot 9.4.8-20171107.091315 (same behavior with 9.4.7).
We're using jetty-runner with this xml config (maxThreads & requestHeaderSize were uppered)

```
<Get name="ThreadPool">
	<Set name="minThreads" type="int"><SystemProperty name="threads.min" default="50"/></Set>
	<Set name="maxThreads" type="int"><SystemProperty name="threads.max" default="350"/></Set>
	<Set name="idleTimeout" type="int"><SystemProperty name="threads.timeout" default="60000"/></Set>
	<Set name="detailedDump">false</Set>
</Get>

<New id="httpConfig" class="org.eclipse.jetty.server.HttpConfiguration">
	<Set name="secureScheme">https</Set>
	<Set name="outputBufferSize">32768</Set>
	<Set name="requestHeaderSize">16384</Set>
	<Set name="responseHeaderSize">8192</Set>

	<Call name="addCustomizer">
		<Arg>
			<New class="org.eclipse.jetty.server.ForwardedRequestCustomizer" />
		</Arg>
	</Call>
</New>

<Call name="addConnector">
	<Arg>
		<New id="httpConnector" class="org.eclipse.jetty.server.ServerConnector">
			<Arg name="server"><Ref refid="Server" /></Arg>
			<Arg name="acceptors" type="int"><Property name="jetty.http.acceptors" default="-1"/></Arg>
			<Arg name="selectors" type="int"><Property name="jetty.http.selectors" default="-1"/></Arg>
			<Arg name="factories">
				<Array type="org.eclipse.jetty.server.ConnectionFactory">
					<Item>
						<New class="org.eclipse.jetty.server.HttpConnectionFactory">
							<Arg name="config"><Ref refid="httpConfig" /></Arg>
						</New>
					</Item>
				</Array>
			</Arg>
			<Set name="host"><Property name="jetty.http.host" /></Set>
			<Set name="port"><SystemProperty name="jetty.http.port" default="8080" /></Set>
			<Set name="idleTimeout"><Property name="jetty.http.idleTimeout" default="30000"/></Set>
			<Set name="soLingerTime"><Property name="jetty.http.soLingerTime" default="-1"/></Set>
			<Set name="acceptorPriorityDelta"><Property name="jetty.http.acceptorPriorityDelta" default="0"/></Set>
			<Set name="acceptQueueSize"><Property name="jetty.http.acceptQueueSize" default="0"/></Set>
		</New>
	</Arg>
</Call>
```

We have 2 virtual server each hosting 3 Jetty instance (on port 8080/8081/8082) having 1 webapp per instance. 
Requests are load balanced with haproxy and the sticky session strategy. We store the session data under PostgreSQL with a JDBCSessionDataStore. This store use a jndi dbcp2 datasource (Our class FileBasedPropertyDataSource extends BasicDataSource and a property file contains datasource information for each worker).
Here are the xml config of the session persistence:

 ```
<New id="sessionDataSource" class="org.eclipse.jetty.plus.jndi.Resource">
	<Arg></Arg>
	<Arg>jdbc/sessionDataSource</Arg>
	<Arg>
		<New id="jettyDS" class="custom.FileBasedPropertyDataSource">
			<Arg><SystemProperty name="jetty.session.config" default="/etc/jetty.session.properties"/></Arg>
			<Arg><SystemProperty name="jetty.session.workerName" default="s1"/></Arg>
		</New>
	</Arg>
</New>

<Set name="sessionIdManager">
	<New id="idMgr" class="org.eclipse.jetty.server.session.DefaultSessionIdManager">
		<Arg> <Ref refid="Server"/> </Arg>
		<Set name="workerName"><SystemProperty name="jetty.session.workerName" default="s1"/></Set>	 
	</New>
</Set>

<Call name="addBean">
	<Arg>
		<New id="sessionCacheFactory" class="org.eclipse.jetty.server.session.DefaultSessionCacheFactory">
			<Set name="saveOnCreate">
				<SystemProperty name="jetty.session.saveOnCreate" default="false" />
			</Set>
			<Set name="saveOnInactiveEvict">
				<SystemProperty name="jetty.session.saveOnInactiveEvict" default="false" />
			</Set>
			<Set name="saveOnInactiveEvict">
				<SystemProperty name="jetty.session.saveOnInactiveEvict" default="false" />
			</Set>
			<Set name="evictionPolicy">
				<SystemProperty name="jetty.session.evictionPolicy" default="1800" />
			</Set>
			<Set name="removeUnloadableSessions">
				<SystemProperty name="jetty.session.removeUnloadableSessions" default="true" />
			</Set>
		</New>
	</Arg>
</Call>

<New id="databaseAdaptor" class="org.eclipse.jetty.server.session.DatabaseAdaptor">
	<Set name="DatasourceName">jdbc/sessionDataSource</Set>
</New>

<Call name="addBean">
	<Arg>
		<New id="sessionDataStoreFactory" class="org.eclipse.jetty.server.session.JDBCSessionDataStoreFactory">
			<Set name="gracePeriodSec">
				<SystemProperty name="jetty.session.gracePeriod.seconds" default="4400" />
			</Set>
			<Set name="savePeriodSec">
				<SystemProperty name="jetty.session.savePeriod.seconds" default="7200" />
			</Set>
			<Set name="databaseAdaptor">
				<Ref id="databaseAdaptor"/>
			</Set>
		</New>
	</Arg>
</Call>
```

Here are the thread dumps that shows:
- 1 deadlock
"qtp1143839598-374":  waiting for ownable synchronizer 0x0000000706a177c8,  
  which is held by "qtp1143839598-81"
 "qtp1143839598-81":  waiting for ownable synchronizer 0x00000007065af760,
  which is held by "qtp1143839598-15"
 "qtp1143839598-15":  waiting for ownable synchronizer 0x00000007065f7e78,
  which is held by "qtp1143839598-29"
 "qtp1143839598-29":  waiting for ownable synchronizer 0x00000007065af760,
  which is held by "qtp1143839598-15"

- 2 threads locking monitors
 qtp1143839598-356
 qtp1143839598-279

Our high load test reaches the maxThreads and Jetty doesn't respond anymore.
Note that if we disable the session persistence, everything works fine.

Let me know if you need more information and thanks for your reply.

[thread-dump-out.zip](https://github.com/eclipse/jetty.project/files/1449632/thread-dump-out.zip)

**Comment by sbordet** [comment]
@janbartel please review locking in the session manager code.

For example, `AbstractSessionCache.put(...)` grabs the session lock, but then invokes user code from `session.didActivate()`, which calls `HttpSessionActivationListener` methods implemented by user code while holding the session lock.

I am guessing the same happens with passivation (for example, `AbstractSessionCache.checkInactiveSession(...)`.

Note also that `DefaultSessionCache.shutdown()` calls the same methods without holding the session lock.

**Comment by janbartel** [comment]
@lgangloff  whilst I debug this, can you confirm my suspicion that your application code is holding a list of Session objects?   Looks like when your passivation listener is called, it is iterating over a set of Session objects to do something with them??  I'm referring to the code in net.bull.javamelody.SessionListener.removeSessionsWithChangedId. FYI application code should not hold references to Session objects as their lifecycle is controlled by the container. I'm still looking into how to prevent the deadlock situation.

**Comment by janbartel** [comment]
@lgangloff  I found https://github.com/javamelody/javamelody.  As I said before, it would not be a good idea for an application to maintain a list of HttpSession objects : the servlet spec as regards sessions is very underspecified. It does not even mandate, for example, that 2 calls by different threads to Request.getSession() return exactly the same session object, just that the internal datastructures must be manipulated in a thread safe manner.  

If we were to remove the restriction that calls to the HttpSessionActivationListener occurred without the lock being held, we could have the situation where another concurrent request could operate on the session and potentially delete it while the passivation is in progress causing the session to magically re-appear, or cause duplicate session objects in the cache when a session is being re-activated after being evicted from the cache.

The passivation and activation callbacks are particularly problematic as they invoke user code and invite session mutation during a complex process of writing/reading a session from a persistent store.  We have to apply mutual exclusion to ensure that no other inbound requests give access during these processes.

Thus, it is even more difficult to support the use-case whereby user code keeps references to session objects out side of the scope of a request handling and accesses them asynchronously.   We are faced with a choice between holding a lock during passivation/activation and risking deadlock with such use-case or letting the lock go and risking concurrent access to the sessions by other valid requests during the passivation/activation.     

Given the poor nature of the specification, I think we have to go with supporting the 99.999% use-case of mutually excluding normal inbound requests rather than the small use-case of allowing passivation/activation code to arbitrarily access references to other sessions.

**Comment by lgangloff** [comment]
Thanks for your detailed reply !
I tried to remove the javamelody session listener, and you're totally right, there is no more deadlock.

Anyway, i don't understrand why the deadlock appears only when session persistence is enabled ? When i dont persist the sessions, using javamelody session listener or not, everything works fine.

**Comment by gregw** [comment]
Without session persistence, there is no need to passivate sessions so the
listener will not be called.

**Comment by janbartel** [comment]
@lgangloff regretfully I'm going to close this issue - I'd like to support this edge use-case, but as explained previously, it would expose the other 99% of use cases to concurrency problems.
