### ISSUE TITLE
Add comment to Issues included in release

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1962]
When updating theVERSION.txt file during a release process, a comment should automatically be appended to all included issues so we know which releases contains fixes for a given issue.

**Comment by joakime** [comment]
This would need to be a task that executes once the release has been promoted to maven central.

**Comment by joakime** [comment]
Perhaps we could have 2 updates to the issues ...

1. Once the release has been staged and closed.  "This issue is being tested in version [blah] present in staged repository [blahurl]"
2. Once the release has been promoted to maven central. "This issue is present in release [blahversion] now present in maven central."

**Comment by joakime** [comment]
Of course, if the issue spans multiple releases of jetty this is kinda messy.

The commits themselves already contain the information on which branches and tags the commit is present in.  That could be enough.

**Comment by joakime** [comment]
We could also use github more appropriately and create a proper milestone for a release, and close it once the release has been promoted to maven central.   

This proposed feature could then change to being a reconciliation of the found commits/issues to the milestone (ensure the issue has the milestone assigned properly)

Again, if the issue spans multiple releases of jetty this is complicated.
Perhaps we should never reopen a released issue, instead open a new github issue for more fixes once the original issue has been released.

**Comment by WalkerWatch** [comment]
> Perhaps we should never reopen a released issue, instead open a new github issue for more fixes once the original issue has been released.

+1 For this, regardless of what we decide on for the other bits.

**Comment by gregw** [comment]
@joakime I think we should start simple.  While changes to our github usage should be considered (and we are already changing to more PR-centric approach), I think this feature should follow rather than drive that.

I understand that we sometime build & stage releases that never go public, but I think we can live with that for now.

So initially I would suggest that if an issue has been identified for inclusion in VERSION.txt, then a simple comment on the issue to the effect of:  "This issue has been referenced in release X.Y.Z. ".  If we really wanted to be precise we could then also say "Releases are staged [here](http://some.link) and may be dropped or promoted to a public release [here](http://some.link)"

**Comment by joakime** [comment]
The two new mojos identified in discussion with @olamy about this feature ...

**Mojo: jetty-version:stage-closed**
Event: On staged version close.
Run: manually
Action: Add comment to each issue found in VERSION.txt which says ...

This issue is now available for testing in staged release [jetty-version] available in staging repository [url]

**Mojo: jetty-version:stage-released**
Event: On staged promoted/released
Run: manually
Actions:  3 main actions

1. Create github milestone for released [jetty-version]
2. For each issue found in VERSION.txt for release:"
2a. Add comment: "This issue is now available in maven central in release [jetty-version]"
2b. Assign github milestone created above
3. Close github milestone

**Comment by gregw** [comment]
sounds great!

**Comment by gregw** [comment]
Actually, I'm a bit cautious about creating milestones.  Currently we have just a few milestone that we can look at to see what is outstanding for 9.4.x etc.    If we create lots of milestones per release, that might crowd out that feature?  But maybe not....  just a note of caution.

**Comment by olamy** [comment]
here with milestone you must understand jetty version (i.e 9.4.7.v20170914 ) so users can get issues resolved per version by using the github ui (well can be an optional feature)

**Comment by joakime** [comment]
In github, milestones have a state, open/closed.
To see this state in action, you can use this issue, scroll up to the milestone selection on the top right, click the gear icon and you'll see this state.  

The proposed **jetty-version:stage-released** behavior would result in a new milestone being created, but then that milestone would be auto-closed, making it only appear in the "closed" tab.

**Comment by gregw** [comment]
OK I'm back to the "sounds great"!

make it so!

**Comment by olamy** [comment]
missing this one https://github.com/kohsuke/github-api/pull/397

**Comment by olamy** [comment]
stage closed implemented. sample here https://github.com/olamy/foo-bar-test/issues/10
Note the comment is configurable.
Current default value 
```
"This issue is now available for testing in staged release ${jettyVersion} available in staging repository ${stageRepositoryUrl}
```

**Comment by joakime** [comment]
We should investigate implementing a Github App for this functionality.
