### ISSUE TITLE
Improve warning for incompatible ALPN processor

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1983]
When running with JDK 9 but only have the JDK 8 `ALPNProcessor` in the server classpath, no warning is issued that the server configuration is bad, and no connection can be established.

We should check also other combinations (e.g. running with JDK 8 but having only JDK 9's `ALPNProcessor` in the classpath).

**Comment by sbordet** [comment]
We want the warning to be as soon as possible, hopefully at startup time, because we don't want a warning line for every connection that cannot be established - that will just trash the logs.

**Comment by sbordet** [comment]
So we do emit an `IllegalStateException` at startup if we don't have any valid `ALPNProcessor`.

However, there is an edge case where we have the Conscrypt `ALPNProcessor`, but `SslContextFactory` is not configured to use Conscrypt.
Because the `ALPNServerConnectionFactory` does not have a reference to the `SslConnectionFactory` (it may not even be created yet), we will only know that there is something wrong when we try to first create a connection.
`ServerConnector` won't be able to do such checks because it has no knowledge of concrete `ConnectionFactory` implementations, it only sees them via the interface.
`SslConnectionFactory` does not really know what is the "next" `ConnectionFactory` it delegates to, nor we can access `ALPNServerConnectionFactory` from `SslConnectionFactory` (will create a module dependency of `jetty-server` to `jetty-alpn-server`).

**Comment by sbordet** [comment]
@gregw, ideas ?

**Comment by gregw** [comment]
@sbordet because we ask each provider `appliesTo(SslEngine)` and the logic behind that is opaque and extensible, there is always the chance that we will have providers, but they will all say no.  Thus we do throw the ISE in [newServerConnection](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-alpn/jetty-alpn-server/src/main/java/org/eclipse/jetty/alpn/server/ALPNServerConnectionFactory.java#L107), so we just have to make sure that exception is logged as a warning. Perhaps we log then throw?

**Comment by sbordet** [comment]
@gregw we don't want to log exceptions for every new (failed) connection attempt, that would trash the logs.

**Comment by gregw** [comment]
It's a trashed configuration, so I don't really see a problem warning on every bad connection.  That is certainly better than not warning at all.

It will be hard to suppress subsequent warnings, because we don't no the reason for `appliesTo`  returning false and it may be different reasons for different rejections of different SslEngines/Sessions.

**Comment by sbordet** [comment]
@gregw so perhaps we can have more "fatal" exceptions that we can throw when creating connections, rather than just ISE. The `SelectorManager` will log them appropriately based on the kind of exception.
Akin to what we have now for `QuietException`, but the opposite... WDYT ?

**Comment by gregw** [comment]
I pushed a fix that warns on connection failures (string only - no stack) and provides more information in the message, with even more available with debug if necessary.

If this becomes too verbose, I'd rather wrap the verbose exceptions as quiet ones rather than white list the exceptions that we will report.
