### ISSUE TITLE
ServletInputStream.isReady not registering interest when it should

### ISSUE THREAD

**Issue by jroper** [eclipse/jetty.project#2006]
This affects the HEAD of the jetty 9.4.x branch, and 9.4.7. I haven't tested any other versions.

I haven't fully got to the bottom of this issue, but I have observed what appears to be a race condition, where `isReady` is not registering interest in reads, due to the channel state being `ASYNC_WOKEN`, as I understand it, when it shouldn't be. As it's a race condition and at the moment I can reproduce it once every 20 or so requests, I haven't been able to observe it entirely in a debugger, I've got to this stage by scattering the code with printlns.

Here's what I've observed.

* I have a client that is making a POST request, and writing data one byte at a time, at random intervals between 0 and 10 milliseconds. I am fairly confident that it is doing this correctly because I have swapped out Jetty for Tomcat and in Tomcat, I don't see the same problem.
* I'm using the async IO APIs.
* After receiving the request, asynchronously, my process does an invocation of `isReady`, which returns `true`, and then I subsequently successfully read one byte (I only request to read one byte at a time).
* My process then does another invocation of `isReady`, this time, it returns `false`. Tracing inside the method reveals that it invokes `HttpChannelState.onReadUnready`, and in that, `HttpChannelState._asyncRead` is `READY`, but `HttpChannelState._state` is `ASYNC_WOKEN`, so consequently `interested` ends up being `false`, and the channel never registers interest in reads, so when more data comes, `onDataAvailable` never gets invoked.

I added some more tracing to find out what is setting `ASYNC_WOKEN` and when (I added a println before each place where `_state` is set to it), and found that it's being set to that before my first invocation of `isReady`, and is not being set again. So presumably there is either a missing `_state = ASYNC_WAIT`, or a race between `_state = ASYNC_WAIT` being invoked and `onReadUnready` reading it.

At this stage I'm kind of stabbing in the dark to know what to look at next, because I'm not that familiar with the code base, if from my description it's not obvious where the bug is, I'd appreciate pointers as to what debugging I should insert next. Where would you expect `_state` to be being set to `ASYNC_WAIT`? What methods should I look at to determine why it's not being set?

**Comment by gregw** [comment]
James,

Dang!  as we were saying... async is hard :(

So it is strange that state is being set to ASYNC_WOKEN by your first isReady call and then not being reset.     I'm thinking this could be an issue with how/when setReadListener is being set (which can cause an ASYNC_WOKEN) and when onDataAvailable is be called and returned.

So it would be really good to know more precisely which threads are doing what actions during which calls:

* Does the initial dispatch to the Servlet which calls `startAsync()` also call `setReadListener`, or is that done by another thread?
* If `setReadListener` is being called by another thread, do you know on the failed tests if it makes the call before or after the initial servlet dispatch thread has returned (HttpChannelState.unhandle called is the key transition on returning).
* which thread is the initial `isReady()` and `read()` called from?   Is this within the scope of a call to `onDataAvailable()` or `onWritePossible`? If not is it before, during or after a container dispatch (to ODA or OWP) is called?     Now it is a bit strange that `onDataAvailable()` might be called at this point because you have not yet seen a false return from isReady(), how ever setting the read listener may schedule an initial call to `onDataAvailable`, so there be an invocation on the way that is racing with  your `isReady()` and `read()` thread.
* I'm not so interested in your second `isReady()` and `read()` because if we are ASYNC_WOKEN already, then something has already gone a little bit strange... but still would be good to know what thread called this and if it is within scope of `onDataAvailable`, `onWritePossible` or some other thread.

**Comment by gregw** [comment]
FYI here are the normal interactions for async IO
![jetty 9 4 x http_1 async](https://user-images.githubusercontent.com/70829/33421958-30cfb93c-d5b4-11e7-9d07-b423abbebce6.png)

**Comment by gregw** [comment]
Assuming this is your reactive stream code, I can see part of the problem [on this line](https://github.com/jroper/reactive-streams-servlet/blob/master/src/main/java/org/reactivestreams/servlet/RequestPublisher.java#L120), where you have commented that perhaps setReadListener should be called earlier.

The issue I think is that when you call setReadListener, you may schedule a callback to onDataAvailable, as you go on to call onsubscribe which may call request which may call `maybeRead`, you are now in a race between two threads calling `maybeRead`.  However, that appears well protected by your mutex, so that in itself should not be the problem.

So I still think there is a problem with jetty - but it is a grey area.  A callback to onDataAvailable has been scheduled, but you have another thread calling `isReady()` and `read()`

Could it be that you do a second call to `isReady()` which returns false, because you consumed the data already. No further call to onDataAvailable is scheduled, because one is already on the way... but before you return from reading thread, the onDataAvailable call does arrive, it sees your mutex so just queues it's lamba and returns.

Jetty is now happy that it called onDataAvailable after a call to isReady() returned false...

But the thread returning from the subscribe will eventually run the queued mutex task from the ODA callback... so it should call isReady() again and get false again... but perhaps it is already confused because of the prior onDataAvailable call....   @sbordet  need your brain on this one....

**Comment by gregw** [comment]
Found it!  the second call to `isReady()` is made in `_state==ASYNC_WOKEN`, `_async==STARTED` and `_asyncRead==READY`.  So it moves to `_asyncRead==REGISTER`, but does nothing else because it knows a handle call is coming.   However in [HttpChannelState.handling](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelState.java#L241) we do not handle `REGISTER` (as we thought that was only for unhandle), so we eventually return an action of ASYNC_WAIT, but in [HttpChannel.handle](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java#L321) we break the handle loop without calling `unhandle`!

So either we need to call unhandle or handle has to deal with the `REGISTER`.  So yes a jetty bug.

However, I still think it is wrong to call `setReadListener` and then go on to attempt an isReady()/read() rather than wait for the resulting ODA call.

**Comment by gregw** [comment]
@jroper I was able to reproduce in a unit test and fix the jetty bug (see #2009).
However, I still believe your code has a bug all we have done is move the race to the application.

The issue is that a call to `onDataAvailable` has been dispatched (in this case by a `setReadListener` call, but it could have been from an `isReady()` call returning false).    But before the dispatched thread arrives to do that work, another thread (your subscriber thread) "steals" the data by doing an `isReady()`/`read()` loop.     Once our thread arrives, it saw there was no data available anymore, so it doesn't call `onDataAvailable`, but it was incorrectly not acting on the `_asyncRead==REGISTER` state and not registering read interest before waiting.

The PR fixes this, but your code may still suffer from the same race.  If the data is "stolen" by another thread a nano second after our thread arrives to call `onDataAvailable` then you have two threads both trying to do `isReady()`/`read()` loops.   Now your mutex executor probably saves your from a bad error in this case, but you are still needlessly spinning the mechanism.

Perhaps you should not call your `maybeRead` method if you know an `onDataAvailable` call is scheduled (ie after setReadListener is called or if isReady() has returned false).

**Comment by jroper** [comment]
Hi @gregw, I've tested your fix against my tests and it seems to work fine now, thanks for the quick turn around!

I don't think we can avoid the `maybeRead` when we first start the subscription, but we can definitely avoid invoking `maybeRead` from `Subscription.request` if `demand` is already greater than zero, since that indicates that `isReady` must have returned false last time `maybeRead` was invoked.

Also, the mutex executor actually hardly spins at all - it's only in maintaining the queue that it needs to spin, it doesn't spin on waiting for a task to execute for example. And Viktor rewrote it yesterday, the opportunity for spinning has been reduced even further, the only thing that ever spins is a thread that has just finished invoking a runnable, when it's checking to see if there's a new runnable to run, it will spin if, while doing that, there is another thread concurrently submitting a task via the `execute` method.

**Comment by gregw** [comment]
By spin, I didn't mean hammering on a volatile, rather I meant that the initial executing thread will end up calling `maybeRead` over and over.

Why must you call `maybeRead` when you first start the subscription?  Once you call `setReadListener` then a call to `onDataAvailable`  WILL happen and it WILL call `maybeRead`.  So perhaps you can just return after calling `setReadListener`?
