### ISSUE TITLE
Documentation on ALPN needs updating

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#2017]
The jetty documentation for ALPN is out-of-date and needs updating, eg wrt to new ServiceLoader architecture, and proper explanation of the new module structure.

**Comment by gregw** [comment]
Pretty much all of https://www.eclipse.org/jetty/documentation/9.4.x/alpn-chapter.html needs to be reworked.

We now have 3 ALPN implementations:

openjdk8 - our own implementation that modifies the JVM with a boot jar, works for openjdk8 only.
java - uses the java >=9 API for ALPN
conscrypt - works with both java8 and java9 if using the conscrypt TLS provider.

We use the service loader to find all the client and/or server ALPN providers available on the classpath.  Some will be eliminated at start time because they cannot be loaded (eg java will not load on java8 because it uses >=9 APIs).  Thus we end up with a list of 0, 1 or more ALPN providers... 0 is an error at startup.

when we get a connection, then the actual SSL Engine instance for the connection is passed to each available provider until one of them accept it.  Thus we might have conscrypt and openjdk8 connections in the same JVM at the same time.

**Comment by sbordet** [comment]
@WalkerWatch I'll write the docs and will ask you to review.
