### ISSUE TITLE
Collect statistics per application/context

### ISSUE THREAD

**Issue by davidkarlsen** [eclipse/jetty.project#2032]
It would be nice if statistics could be collected on a per application/context/war-base - this way we could get more precise stats.

Our monitoring today is collected through a side-car application (.war) - e.g. servers run a main application .war + the monitoring one - hence monitoring traffic is included in the server overall stats - giving a Schroedingers cat / observability problem - this becomes very apparent when traffic volume for the main application is low.

**Comment by gregw** [comment]
This is already supported. The StatisticsHandler can be installed at any point in the handler tree.  Instead of installing the handler as a wrapper of the entire ContextHandlerCollection, it can be installed to wrap just a single context or even be within the context (so that rejected requests due to virtual hosts etc are not counted).

You will have to roll your own configurations/modules for this.
