### ISSUE TITLE
431 Request Header Too Large swallowed by HTTP2 Parser

### ISSUE THREAD

**Issue by ellisjoe** [eclipse/jetty.project#2040]
Sending an HTTP2 request with a header too large results in the connection being closed rather than a response with error code 431.

**Comment by sbordet** [comment]
@ellisjoe there is a larger issue here.

When parsing a hpack block that contains a very large header, we throw `BadMessageException` as soon as we encounter it (even earlier in certain cases).
AFAIU from the [spec](https://tools.ietf.org/html/rfc7540#section-10.5.1), we should instead continue parsing the hpack block until the end, if we want to be able to send a HTTP response; this is because the hpack context needs to be in sync with that of the client, and if we throw too early the only option we have is to close the connection, otherwise the hpack contexts will be out of sync.
OTOH, if we parse the hpack block until the end, we expose ourselves to an infinite buffering attack.
@gregw, your thoughts on this ?

**Comment by ellisjoe** [comment]
The wording here is pretty ambiguous:
```
   A server that receives a larger header block than it is willing to
   handle can send an HTTP 431 (Request Header Fields Too Large) status
   code  [RFC6585].
```
In particular because the alternative specified is to treat the request as malformed rather than using an error code:
```
   An endpoint can use the SETTINGS_MAX_HEADER_LIST_SIZE ...  This
   setting is only advisory, so endpoints MAY choose to send header
   blocks that exceed this limit and risk having the request or response
   being treated as malformed.
```

**Comment by ellisjoe** [comment]
It seems Netty sends to GO_AWAY frame when the limit is exceeded: https://netty.io/4.1/api/io/netty/handler/codec/http2/Http2HeadersDecoder.Configuration.html#maxHeaderListSize--

**Comment by sbordet** [comment]
"Treated as malformed" is defined by the spec [here](https://tools.ietf.org/html/rfc7540#section-8.1.2.6).

However, if the hpack context is not fully parsed, the only option is to close the connection (via a `GOAWAY` - which is what we do now); we cannot send a `RST_STREAM`.

**Comment by ellisjoe** [comment]
Ah I see. So based on:
```
   For malformed requests, a server MAY send an HTTP response prior to
   closing or resetting the stream.
```
the current implementation seems correct and sending a 431 at any point is an optional courtesy.

**Comment by gregw** [comment]
@sbordet I believe that our implementation is the best alternative.  Inflating Hpack compression is not a simple operation and will consume CPU and memory.  As too large headers are often part of DOS attacks, then the best we can do it abort the decoding and close the connection.

But thanks @ellisjoe for asking the question, always good to (re)consider these things.

**Comment by ellisjoe** [comment]
Thanks guys. Closing this out.
