### ISSUE TITLE
PathMap fails to match extension paths if default path is present

### ISSUE THREAD

**Issue by ericvergnaud** [eclipse/jetty.project#2086]
Hi,

first thanks for the great work with Jetty.

I have a bit of a problem with the current implementation of org.eclipse.jetty.http.PathMap.
Say you have a web site where you want to protect everything except static content (such as css files).
You could specify that using simply 2 contraint mappings:
 - *.css with no authentication required - roles = * (you would need one of those per static extension)
 - /* with authentication required - roles = *
However, because of /* being present, PathMap.getMatch("https://server/stylesheet.css") returns the second mapping i.e. the one that requires authentication.

I appreciate this is the intended behaviour i.e. the spec in the file header is explicit:

_Matching is performed in the following order 
 Exact match.
Longest prefix match.
Longest suffix match.
default._

However according to this google search...
https://books.google.com.hk/books?id=IRfmJf1bFaIC&pg=PA273&lpg=PA273&dq=servlet+spec+constraint+matching&source=bl&ots=WkmBccb5mh&sig=1IRrGfPL-J3V-6YSRCCKl_M-38A&hl=en&sa=X&ved=0ahUKEwjVr-SOzLHYAhXEHZQKHaulAMoQ6AEILjAB#v=onepage&q=servlet%20spec%20constraint%20matching&f=false
...it seems that the J2EE spec is not very clear about what behaviour to follow in case of multiple matches. Apparently, Tomcat picks the constraint mapping specified first. 

from there, I'm inclined to think that the above matching rule spec is a Jetty interpretation of the url-pattern specification. IMHO it is somewhat extreme since it makes it impossible to implement the above i.e. protect everything except certain extensions.

I'm aware that changing the default behaviour is impossible since it would probably introduce massive security issues, but how about making the default behaviour configurable?

If you are fine with the idea I'm happy to submit a PR.

**Comment by gregw** [comment]
@ericvergnaud I'm pretty sure that our mapping implementation is correct according to the spec.  This is something that we really test well and use 3rd party tools to verify as well.  In the presence of multiple matches, the most specific (longest) wins... but only if it is of the same type. So `/*` always beats a `*.css` pattern.

The spec itself is really badly designed for supporting the style of constraints that you wish to implement. ie it is not straight forward to constrain everything except specific resources.

But it can be done according to the spec.   Instead of `/*` use the default `/` as that will match after the `* .css`.  You find that you also need to relax the constraint on the root resource, in which case remember that the empty string matches `/` (and `/` matches everything - yes it is silly).

**Comment by ericvergnaud** [comment]
Hi,

thanks for your response, and the tip, I’ll try it out and let you know.

Eric

**Comment by ericvergnaud** [comment]
It works!
Many thanks.
As you said it's silly, who would think of the above?
