### ISSUE TITLE
Refactor WebSocket close handling

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2175]
Current Close Handshake handling is problematic and not handled correctly all known cases.

A new blank testcase in `websocket-core` was added to attempt to list all of the scenarios seen from a client point of view.

See: [ClientCloseHandshakeTest](https://github.com/eclipse/jetty.project/blob/jetty-10.0.x-websocket/jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/client/ClientCloseHandshakeTest.java)

We should evaluate these use cases, see how many apply from the server point of view as well.

**Comment by brettwooldridge** [comment]
@joakime We're encountering a WebSocket issue at a customer whereby we are seeing unexplained disconnections between our Jetty Server and Jetty Client.  Unfortunately, the client seems barely capable of understanding what a "ping" command is, so diagnosing the issue has been problematic.  Ideally, we would like a tcpdump from both side of the wire, but...

Anyway, the websocket client side is seeing its ``onClose()`` get called, but the server side never does.  We're mostly convinced that this is an infrastructure issue at the customer -- there is a firewall, IPS, etc. between the client and server -- because reconnection attempts from the client fail for several minutes, then suddenly succeed.

This happens on multiple clients simultaneously, which again makes us suspect infrastructure, however, it doesn't rule out a server-side issue either.

Long and short of it, we saw this issue open and are curious if there are specific *known* issues that might move our diagnostic attempts in one direction or another?

**Comment by joakime** [comment]
in Jetty 9.4.x onClose always gets called in normal websocket operations.
However, the issues stem from **which** close event the call is from?
It's inconsistent.

The onClose could be called from any of the following (its a racy call):
* the remote close frame is received
* the local close frame is sent
* the remote connection is closed normally
* the local connection is closed normally

This issue is to refactor the onClose handling in Jetty 10.x to ensure that the event is consistent and predictable.

The biggest unknown are all of the various flavors of abnormal connection termination behaviors.

Things behave differently over normal HTTP connections vs connections that are encrypted (TLS/SSL).
There have been reports that on some JVM & OS combos the TLS/SSL behaviors are different then normal JVM operation.

There are also a flavor of OS specific JVM bugs (in particular Microsoft Windows and JVM NIO) that concern us.

The best advice I can give for Jetty 9.4.x is ...

If you get an onClose() its a normal behavior, but don't expect to be able to do something in its call (such as send a frame)
If you get an onError() its an abnormal behavior and the connection is bad (call session.close() at least in here, and don't expect an onClose() later)

In Jetty 10.x the onClose() will occur in both normal and abnormal behaviors, the close status code will indicate the type of closure.

**Comment by brettwooldridge** [comment]
@joakime Thanks for your feedback.  I was just commenting to a collegue, after reading #1626, that we don't override ``onError()`` because we were assuming ``onClose()`` would be called in call cases.  We're going to implement ``onError()``, but it would certainly be good if there was a guarantee that ``onClose()`` is called.

**Comment by gregw** [comment]
Some major refactoring was done in #3055, but it is still not sufficient to provide non problematic close handling.  Specifically:
 + calling close may be done in parallel with an outstanding async write, which may result in a write pending exception.
 + The close state is duplicated in `WebSocketChannelState`, `FrameSequence` and `FrameFlusher`, with the corresponding risk of race conditions when updating.

Proposal for further refactoring is as follows:
 1. Remove the queue and flusher prior to the outbound extension stack.  This was primarily to serialize and mutually exclude frames passing through the extension stack.   Instead the CoreSession.sendFrame method should be synchronized so that only a single thread can be active in `sendFrame` at a given time.  The lock will be held until the frame is extended and places in the WebSocketConnection queue that is processed by the FrameFlusher.  Ideally the call to iterate could be done externally to the synchronize, but that may be difficult to achieve.. unless perhaps iterate is always dispatched?
2. The current synchronized `FrameSequence` instances for inbound and outbound will be moved into the `WebSocketChannelState` class, which will become the single state instance.  This class will be converted to using synchronization rather than `compareAndSet` as multiple states will need to be tracked.

@lachlan-roberts @joakime

**Comment by gregw** [comment]
Working on this in the https://github.com/eclipse/jetty.project/tree/jetty-10.0.x-3167-2175-websocket-close branch, based of the yet-to-be-merged #3167 changes

**Comment by gregw** [comment]
I was hoping that this refactor would also fix #3246, but unfortunately no.  It appears that is caused by the Fuzzer doing raw writes to the clients endpoint

**Comment by joakime** [comment]
This has been completed in both `jetty-9.4.x` and `jetty-10.0.x`
