### ISSUE TITLE
Problem with jetty.sh and HeapDumpOnOutOfMemoryError 

### ISSUE THREAD

**Issue by nnickoloff1234** [eclipse/jetty.project#2193]
Version: jetty-9.4.8.v20171121 - 21 November 2017
But we had this problem with older versions as well.

Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Ubuntu 16.04.3 LTS

We use bin/jetty.sh to run jetty, which in turn uses start-stop-daemon.
However when we add in JAVA_OPTIONS -XX:+HeapDumpOnOutOfMemoryError it doesn't really have any effect.

What we figured out is that java prints some stuff in stdout/stderr when it tries to create the heap dump (a couple of lines that we really don't care about). This seems to happens on low lever, not via System.out.println, so even if jetty redirect System.out/err stuff it doesn't redirect this kind of output and it is never logged anywhere. And it seems start-stop-daemon doesn't redirect/consume this output in any way which in turn causes java (for some reason) to not create any heap dump at all (which sounds like a bug on its own but for Java).

Our workaround is to change some lines in bin/jetty.sh. In essence to have something like this:

`
jetty_cmd="start-stop-daemon -S -p$JETTY_PID $CH_USER -d$JETTY_HOME -b -m -a /bin/bash -- -c \"exec $JAVA ${RUN_ARGS[@]} --daemon > /tmp/java_stderrout.log \" " 
`
`      
eval $jetty_cmd
`

Once that stdout/err stuff is consumed the heap dump starts working ok and gets generated. 

Is there are a better workaround that would not force us to fix jetty.sh every time we update? 
Or we are doing something wrong or maybe best you fix jetty.sh that is shipped by default?

**Comment by joakime** [comment]
If the jetty instance configuration found in your `${jetty.base}` needs to fork the JVM then those settings will not propagate to the forked JVM.

If you want these kinds of configurations and want it to be resilient to the forked JVM, consider using the `jvm` module in your `${jetty.base}` directory and set the `-XX:+HeapDumpOnOutOfMemoryError` argument that way.

**Comment by joakime** [comment]
Option 2 is to not use `bin/jetty.sh`, a valid decision, which hundreds of thousands of Jetty websites do every day.

systemd users find using Java directly against the `${jetty.base}` directory is far easier to control/manipulate then the older `bin/jetty.sh` script that was designed for the older unix environments with sysvinit.

**Comment by nnickoloff1234** [comment]
Thanks for the reply @joakime 

I am not sure what you mean exactly in your first comment. I don't believe i have any problem at all with passing -XX:+HeapDumpOnOutOfMemoryError or any other option. In fact I believe it is properly passed to the jvm fine, but the problem comes from the jvm not having stdout/err to write to because of something that start-stop-daemon thing is doing. At least that is my guess and that is what fixed the problem in the end - redirecting those streams. (not much of a linux expert myself)

About the second comment. Are you saying just not use bin/jetty.sh, but more or less run "java -jar start.jar" like this? or i am missing something? but we do need most of the stuff that jetty.sh provides, like start/stop arguments so it seems it might be easier for us to just fix the script every time we update jetty.

**Comment by joakime** [comment]
@nnickoloff1234 I see 2 issues.

1. The JVM can fork.
2. The startup in jetty.sh captures STDOUT and STDERR for logging reasons.

The most common reason for `-XX:+HeapDumpOnOutOfMemoryError` not functioning is the first one.  The configuration found in `${jetty.base}` is forking the JVM before it actually starts the Jetty server.

In this scenario, the forked JVM does not propagate the JVM settings to a forked JVM.
To get around this forked JVM behavior, for all things JVM (min memory, max memory, gc configuration, your `-XX:+HeapDumpOnOutOfMemoryError` setting, etc), is to specify the JVM options in the Jetty `jvm` module's configuration, not in `bin/jetty.sh` or `/etc/default/jetty` or any other pre-start location.

For the second reason, the STDOUT and STDERR not behaving as expected, this is due to the history of compatibility in the `bin/jetty.sh`.

[See Jetty 9.4.8 version of bin/jetty.sh](https://github.com/eclipse/jetty.project/blob/jetty-9.4.8.v20171121/jetty-home/src/main/resources/bin/jetty.sh)

Once the execution passes from `bin/jetty.sh` to `${jetty.home}/start.jar`, the STDOUT and STDERR are captured for itself up until formal Server logging takes over.  

So the STDOUT/STDERR lifecycle is ...

1. Shell - (normal behavior)
2. `bin/jetty.sh` script execution -  (normal behavior)
3. Java execution.  - (normal behavior)
4. `start.jar` execution begins, capture of STDOUT/STDERR to `start-log-file` location.
5. Formal server logging kicks in (whatever the `${jetty.base}` configuration states is what occurs here)

The `start-stop-daemon` has many flavors across the unix landscape, and the most compatible set of arguments is present in the `bin/jetty.sh`, and the STDOUT/STDERR behavior implemented in `${jetty.home}/start.jar` is also a result of this baseline compatibility across the unix landscape.

The existing [Jetty 9.4.8 section for `start-stop-daemon` startup](https://github.com/eclipse/jetty.project/blob/jetty-9.4.8.v20171121/jetty-home/src/main/resources/bin/jetty.sh#L453) ...

``` shell
start-stop-daemon -S -p"$JETTY_PID" $CH_USER -d"$JETTY_BASE" -b -m 
     -a "$JAVA" -- "${RUN_ARGS[@]}" start-log-file="$JETTY_START_LOG"
```

The change to `bin/jetty.sh` in your original question ...

``` shell
jetty_cmd="start-stop-daemon -S -p$JETTY_PID $CH_USER -d$JETTY_HOME -b -m -a /bin/bash -- -c \"exec $JAVA ${RUN_ARGS[@]} --daemon > /tmp/java_stderrout.log \" "
eval $jetty_cmd
```

Things that concern me about that command line:

* You are not using `${jetty.base}` properly, you are using `${jetty.home}`. Ignoring the [direct warning telling you not to](https://github.com/eclipse/jetty.project/blob/jetty-9.4.8.v20171121/jetty-server/src/main/java/org/eclipse/jetty/server/HomeBaseWarning.java#L70-L71).
* You are using a `--daemon` command line option, which doesn't exist for `start.jar` (or anything else in Jetty)
* You are not using the `start-log-file` argument to specify the output location for the captured STDOUT/STDERR
* Your change only tackles step 3 in the above mentioned lifecycle.

If you drop all of this `bin/jetty.sh` manipulation and `/etc/default/jetty` configuration and move to a formal use of `${jetty.base}` with the `jvm` module enabled.  You can edit the `${jetty.base}/start.d/jvm.ini` to include your `-XX:+HeapDumpOnOutOfMemoryError` configuration, and it will work regardless of where you are in the STDOUT/STDERR lifecycle, and/or forked JVM behavior.

**Comment by nnickoloff1234** [comment]
thanks again @joakime 

Let me bring some context. We are currently switching from jetty 7 to jetty 9. That line of code i posted actually comes from our current 'fix' for the bin/jetty.sh of jetty 7. This is also where the --daemon thing comes from which i suppose doesn't exist anymore and probably also that base vs home thing. 

I posted this issue here before we started 'fixing' the jetty 9 version of the script hoping to find another solution that will not make us fix this every time we update, assuming our problem was the same one we had in jetty 7, where all arguments were ok, but was still not working until that stdout/err redirect actually did the job. This fix actually works for jetty 7. Also we have been using exactly /etc/default/jetty to set various env variables and it also worked fine for us until now as far as passing the arguments to the jvm is concerned.

Now i actually think you are right that we have indeed a problem with those arguments not getting to the jvm. I've tried to print them during runtime and they were not set properly indeed. 

Will try the jvm.ini tomorrow and see if all works ok and if indeed the only problem was the arguments not getting to the jvm or we still have that strange behaviour i believe is caused by start-stop-daemon + java.

**Comment by joakime** [comment]
I updated our old `jetty-oome` example project for your use case.

Project: https://github.com/jetty-project/jetty-oome

Use Case: https://github.com/jetty-project/jetty-oome/tree/master/examples/heapdump-oome-base

Be sure to try the example as outlined by the `readme.md`, you'll see that it works just fine, without editing the `bin/jetty.sh`

**Comment by nnickoloff1234** [comment]
thanks. i also made a small minimal setup (with start-stop-server+oome+systemd but without jetty) to try to reproduce what we have on our test server, but when i ran it on my dev machine there was no problem, which makes me believe that maybe there is something wrong with our server. Will try to find time in near future to try what you suggest and also my thing on our test server and figure out what is going on. its very strange because we had the same behavior on both of our test servers and with both jetty 7 and 9 required that fix in jetty.sh to work.

**Comment by nnickoloff1234** [comment]
closing it anyway. if i find anything more concrete and reproducible will open a new one
