### ISSUE TITLE
Is jetty able to gzip the request body

### ISSUE THREAD

**Issue by wzl12300** [eclipse/jetty.project#2287]
I send the request using jetty-client 9.2.x, the server side is Tomcat. Is jetty-client able to gzip the request body before send to server ?  Thanks

**Comment by sbordet** [comment]
Jetty's `HttpClient` does not automatically gzip the request content, but that is easily done using `OutputStreamContentProvider` and wrapping the output stream with the JDK `GZIPOutputStream` (and adding the proper header).

However, bear in mind that in general clients do not compress content because they don't know if the server can ungzip it.
Whether the server can automatically ungzip the content is typically implementation dependent, otherwise you need to do it in the application layer.

The reverse (server gzipping content) is possible because the client tells the server whether it can ungzip the response content.
