### ISSUE TITLE
Allow to customize ErrorHandler's default error page Content-Type

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#230]
migrated from Bugzilla [#477541](https://bugs.eclipse.org/bugs/show_bug.cgi?id=477541)
status ASSIGNED severity _enhancement_ in component _server_ for _9.3.x_
Reported in version _9.3.3_ on platform _PC_
Assigned to: Simone Bordet

On 2015-09-16 05:49:58 -0400, Simone Bordet wrote:

> ErrorHandler can be overridden so that application can customize the default error page that it returns.
> 
> However, it should be possible to override also the Content-Type header, otherwise one could customize the default error page to return JSON, but the Content-Type will remain text/html.

**Comment by joakime** [comment]
Seems related to Issue #302

**Comment by dawnstrider** [comment]
Would love to see this improved. I am also trying to create a custom ErrorHandler which can produce multiple types of output (json,plain,xml) but the content is always returned as text/html.

Only solutio so far is to override handle(String target, Request baseRequest, HttpServletRequest request, HttpServletResponse response) but that involves alot of manual work since its a core method of the class.

**Comment by gregw** [comment]
@dawnstrider We are certainly open to improving the ErrorHandler so it can more easily be extended.   However, it is hard to generalize without an example.    So why don't you have a go of doing this yourself?  ie fork the jetty repo and modify the ErrorHandler so that it is extensible in the way that you need, then open a PR so we can consider bringing your changes back into the main jetty repo.    It would be best to do such an API change on the jetty-9.4.x branch.

**Comment by dawnstrider** [comment]
Tried to submit an idea but was denied since I do not have a signed eclipse CLA. 

Cannot sign the CLA since it requires me to name my **employer** which is something I am not free to divulge... so sorry no example. Don't have a problem with filling in my personal data tho...

**Comment by jmcc0nn3ll** [comment]
@dawnstrider We are at the mercy of Eclipse policy in terms of accepting a commit into the Jetty repository.  That being said you are free to submit or reference example code to illustrate a point or need either in a repository of your own or as a pull request so long as you fully understand our hands are tied in being able to _accept_ such a request.  Sorry :/

**Comment by gregw** [comment]
@dawnstrider,  I think I see what you are after, but i would provide it differently.
You already have the ability to override how error page contents are generated with methods like: [writeErrorPage](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java#L140), [writeErrorPageHead](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java#L154), etc.

But it order to serve different mime types, you really need the ability to modify/replace the [code in handle](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java#L116-L129) that looks at the accept types, sets content type and creates a writer.

I will factor that code out into another method that can easily be overridden.   So we no longer need #727 thanks

**Comment by gregw** [comment]
Oops labelled 3765efa for #727 rather than #230
@dawnstrider Is that what you are looking for?

**Comment by dawnstrider** [comment]
Well, sort of. Currently the ErrorHandler has no abstractisation whatsoever.
I was thinking of maybe providing a template (empty) method for anybody to override and fill with code. As the ErrorHandler can be set to a Context, it makes sense in my oppinion to have the possibility to add code to the errorhandler without modifying its own functionality. IMO this only works with it beeing abstract class or at least have a DO-NOTHING method that the user can override to do her own stuff.

With your commit, we DO have a new method that provides the mimetype, however the method itself conains code again which, if I want to override, will lead me to either copy&paste alot from the original method or call it with super.generateAcceptableResponse(...) which may not be the thing I want to do.

In my particular use case I want to handle JSON mimetype. So I would call super.generateAcceptableResponse(...) first in order to keep the basic functionality and then extend the new method, so that works for me :-)

**Comment by gregw** [comment]
@dawnstrider, I'm not really understanding what and empty method and/or abstract class does for you.  With the commit, if you want to handle JSON mimetype you simply override 
```
protected void generateAcceptableResponse(Request baseRequest, HttpServletRequest request, HttpServletResponse response, String mimeType)
```
and test if mimeType is the JSON mimetype.  If so, you server your response how you want, if not then either you do nothing (if you don't want to handle any other mimetypes) or call super (if you do).

Note also that the super method just sets up a writer and then calls other methods, so there is very little reason to cut&paste the code as the super method can be highly customized already.

So I need a concrete example of what is needed that this solution does not provide.

**Comment by gregw** [comment]
Actually , I realized I've made a mistake and that the `Accept` header does not contain charset and I need to separately inspect the `Accept-Charset` header for that!  Standby for a variation...

**Comment by joakime** [comment]
Closing as it appears to have been implemented.
