### ISSUE TITLE
Latest versions not available in Maven repositories & mvnrepository.com

### ISSUE THREAD

**Issue by nafets1234** [eclipse/jetty.project#2309]
Unfortunately I do not have a deep knowledge how the integration of the public maven repositories, mvnrepository.com and the artefacts is working. So if it is completely out of context, please excuse me.

What I noticed is:

1. Although jetty-9.3.23.v20180228 was released nice days ago, it's still not listed at mvnrepository.com . Still I can use it in my pom.xml 
```xml
<!-- https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-security -->
<dependency>
	<groupId>org.eclipse.jetty</groupId>
	<artifactId>jetty-security</artifactId>
	<version>9.4.8.v20171121</version>
</dependency>
```

2. jetty-9.4.9.v20180307 is out for two days now and not yet available in the public repositories. With this one I might be too impatient.

**Comment by sbordet** [comment]
Jetty is deployed to Maven Central:
http://central.maven.org/maven2/org/eclipse/jetty/jetty-security/9.3.23.v20180228/

Why it is not on `mvnrepository.com`, you should ask there.

Jetty 9.4.9.v20180307 is a staged release which means that is available for testing and once we are happy with the testing we will release it to Maven Central. This typically takes a few days.

**Comment by joakime** [comment]
I would advise not using the 3rd party mvnrepository.com

Use the official search.maven.org (it's always correct and up to date)

As for 9.4.9, that is a tag for a potential release.  One that was (it's
since been dropped) staged and was being tested.   See jetty-dev list for
up to date announcements about staged releases.  And jetty-announce list
for release announcements.
