### ISSUE TITLE
Allow form limits to be set via context-params

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2325]
Currently the two form limit configurations ...

1. `org.eclipse.jetty.server.Request.maxFormContentSize`
2. `org.eclipse.jetty.server.Request.maxFormKeys`

Can only be set via a Server attribute or a System property.
(There is also the ContextHandler methods `setMaxFormContentSize` and `setMaxFormKeys`, but that requires a context xml file to use)

This is a feature request to allow those two attributes to also be set via the `WEB-INF/web.xml` Context params.

``` xml
<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd"
  version="3.1">
  <context-param>
    <param-name>org.eclipse.jetty.server.Request.maxFormContentSize</param-name>
    <param-value>200000</param-value>
  </context-param>
  <context-param>
    <param-name>org.eclipse.jetty.server.Request.maxFormKeys</param-name>
    <param-value>100</param-value>
  </context-param>
</web-app>

```

**Comment by nlwillia** [comment]
When I run into these limits, it's usually for a tiny slice of the application.  It would be nice if there were a hook to configure them per request.  It's tricky since the parameters aren't available yet, but something with access to the URI or session could make a more granular decision than a whole server or whole context setting.  (Not really in scope for this request, but it's a use case that may be worth considering.)
