### ISSUE TITLE
Remove raw ServletHandler usage examples from documentation

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2340]
We have a few pieces of documentation that show usage of `ServletHandler` directly.

While this is a valid configuration and setup, it's highly confusing for people that actually read/use/reference the documentation.
(ServletHandler is bare, has no listeners, no webapp, no ServletContext, etc.. it's *extremely* limited in functionality)
Because of "Servlet" in the name, the assumption is that its a servlet, with everything that a servlet can do. (RequestDispatcher, sendError, AsyncContext, Filtered via a Filter, Annotations, @MultipartConfig, etc)
This is a very common assumption found on the mailing lists and on stackoverflow.

The direct usage of `ServletHandler` shouldn't be demonstrated or encouraged in our documentation or embedded examples.

We should encourage usage of the more normal `ServletContextHandler` or `WebAppContext` or even the more fundamental jetty `Handler`.

One such usage: https://www.eclipse.org/jetty/documentation/9.4.x/embedded-examples.html#embedded-minimal-servlet

**Comment by CraigEwert** [comment]
I was tripped by this recently.   I wonder if I might fix it?

I was thinking, instead of removing the document/example, we fix them?  Something like:

`    public static Server createServer(int port)
    {
        Server server = new Server(port);

        ServletContextHandler context = new ServletContextHandler(ServletContextHandler.NO_SESSIONS);
        context.setContextPath("/");
        server.setHandler(context);

        context.addServlet(HowdyServlet.class, "/*");

        return server;
    }
`

**Comment by gregw** [comment]
@CraigEwert I too prefer to retain and "fix" the examples rather than remove them.  However, your example is not a minimal servlet, as it has a context.
It is entirely valid to have a ServletHandler with no context, but as @joakime says it will be lacking many normal facilities of a standard servlet.

I'd be more inclined to add comments and code to the example that demonstrates that there are limitations (eg no session, request dispatcher).  Note that there should still be sendError, AsyncContext, Filtered via a Filter.

I think it is very important to show the absolute minimum required  to run a simple Servlet.  But we should have good pointers to how a Context is done and desirable.

**Comment by CraigEwert** [comment]
When I tested the current code, it was the lack of context that caused problems.

At ServletHolder:1261, inside newInstance(), I see this:

```
            ServletContext ctx = getServletHandler().getServletContext();
            if (ctx == null)
                return getHeldClass().getDeclaredConstructor().newInstance();
            return ctx.createServlet(getHeldClass());
```

getServletContext() returns a ContextHandler:StaticContext
When you ask it to createServlet on the held class, it logs a warning and returns null.

Moments later, at ServletHolder:657, it tries to call .init on that null servlet, which fails with NPE.

That behavior makes me believe we cant have a ServletHandler with no Context.  Maybe the code in ServletHolder or ServletHandler changed since this example was written? Would we rather ContextHandler:StaticContext have a createServlet method that creates a servlet? Or should ServletHandler have a different fallback _servletContext? Or leave _servletContext null (in doStart())?  The code in newInstance is prepared for a null ServletContext.

I cant tell from the code which alternative might be preferred.

**Comment by gregw** [comment]
Ah - so that would be a bug that we have introduced... which I will now fix!
@olamy we definitely need integration testing that fires up all our embedded examples!

**Comment by gregw** [comment]
@olamy ignore me... we do have tests... but perhaps not good enough ones... looking...

**Comment by gregw** [comment]
@CraigEwert I actually think this problem is fixed in the latest releases... however I still might tidy this up a little.

**Comment by gregw** [comment]
created #4307

**Comment by CraigEwert** [comment]
@gregw Looks good.  How latest are the releases with this fixed? 10ish? Is that released widely yet?

**Comment by gregw** [comment]
There will be a 9.4.23 release with this fix in the next week
