### ISSUE TITLE
Enhance ServerTimeoutsTest for close behavior

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2353]
While reviewing SelectChannelEndPointTest it was identified that the existing ServerTimeoutsTest was covering many idle timeout testing scenarios.

However, it was not adequately testing the close (fin?) behaviors.

**Comment by gregw** [comment]
We had a bug with closing, the sequence was meant to go:
- Server did shutdownOutput
- Client read -1 BUT DID NOT close socket
- Server times out and closes socket
- Test verifies the socket is eventually closed

But what was happening was:
- Server did shutdownOutput
- Server immediately did a close
- Client mostly read -1 (but sometimes close overtook shutdown so we got socket exception, specially for SSL), BUT DID NOT close socket
- Test verifies the server socket is eventually closed

Ie the test passed because the server socket  is closed, but it passed for the wrong reason.
