### ISSUE TITLE
how to use <resourceBases> ? 

### ISSUE THREAD

**Issue by raftonsea** [eclipse/jetty.project#2396]
I am using jetty-maven-plugin  in multiple modules maven project . Module A has a freemarker page  in /mywebapp/WEB-INF/pages/index.ftl  and module A is a jar  . I want to run jetty from Module B (a war ) , and include Module A's freemarker page , so i use 

``` xml
                  <configuration> 
                    <webApp>
                        <contextPath>/</contextPath>
                        <descriptor>${project.basedir}/WebRoot/WEB-INF/web.xml</descriptor>
                        <resourceBases>
                            ${project.basedir}/WebRoot,../moduleA/mywebapp/WEB-INF
                        </resourceBases> 
                    </webApp>
                </configuration>
```

But  that failed !!  The spring can not find the page , and throws an exception
The official saied  resourceBases is a set of directories  and is an array of directory names , i viewed the source code ,  and the comment saied :
 `Each resource string may be a comma separated list of resources` . 

Any wrong  I used ?   Thanks a lot.

**Comment by joakime** [comment]
know that jetty-maven-plugin is designed for a single war project and all dependencies are already built and available via the local repository (or reactor references)
trying to do anything else is out of scope of the jetty-maven-plugin.

looks like you are trying to do live editing of content across multiple maven projects.
know that the current war project's webroot already has your moduleA content (via the maven dependency and local repository/reactor) and will see that first, before your added resource base.

also, relative directories are always a problem in these kinds of configurations.
why?  because what is it relative to? 

on the command line:
 - if in a reactor build, its relative to the parent 
 - if in a single build, its relative to the project basedir
 - if in a restarted reactor, its relative to the restart point

if in a maven shell its relative to the directory you started the maven shell from

in an ide, its relative to the execution scope
in the intellj RemoteMavenServer, its relative to a hierarchy: the run execution working directory, the module working directory, the project working directory, and finally the RemoteMavenServer working directory. 
in a ci, its relative to the threaded execution (which could be a different directory in your overall project each execution)

**Comment by raftonsea** [comment]
@joakime  thanks a lot , i resolved the question with another way .  And i am confusing now ,   i am using a hot swap tool : jreloader  in my project  . I enabled  maven-jetty  config :  "scanIntervalSeconds" and added classpath to  "extraClasspath"  . But the jetty restart  when any source code changed .   I  want jreload   aware code changed  , and hot swap   rather than server restart   . What should i do  ?  Thants .

**Comment by janbartel** [comment]
@raftonsea  if you're using the jetty-maven-plugin, it only restarts the webapp when a dependency jar or class changes, not the whole server. 

Can you provide the output to show what is happening?

**Comment by raftonsea** [comment]
@janbartel    Sorry ,  i was wrong ,  it only restarts the webapp  .  But restarts the webapp also costs a lot of time  , can i avoid restart and  as  jreloader  is  monitoring  the classpath ,  can i  just  notify  jreloader ?

**Comment by janbartel** [comment]
@raftonsea if you wish to use jreloader, then I suggest you don't use the jetty-maven-plugin, as the whole purpose of the plugin is to monitor your classes and redeploy the webapp on changes.  You could write a main class instead to start the jetty server and your webapp, and invoke it at the appropriate place in your build.
