### ISSUE TITLE
Remove HTTP/2 data copy

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2439]
Currently, the HTTP/2 implementation performs a data copy in the following places:

Client side: `HttpReceiverOverHTTP2.onData(...)`
Server side: `HttpChannelOverHTTP2.onRequestContent(...)`

The pro of copying data is that the implementation is simpler; the con is that there is data copy.

**Comment by sbordet** [comment]
A possible solution would entail reference counting the network buffer, so that we reuse it for the next read only if all buffers sliced from it have been consumed.

This requires a `retain()` and `release()` API, along with storing aside unreleased buffers that will be released asynchronously later.

The current API only expose a `Callback` to applications, with the semantic that calling `succeeded()` indicates both demand for the next chunk of content _and_ that the current content has been consumed.

This mechanism is remarkably similar to #2429 where we want to expose to application both semantics of demand and consumption separately.
Issue #2429 is however only on the client side, while this issue would require fixing the server side too - although HTTP/2 being so symmetric the changes to the server side should be minimal once the common mechanism is implemented.

**Comment by sbordet** [comment]
In details, the idea would be to provide a special callback, tentatively called `BackPressureCallback` with additional APIs:
```java
interface BackPressureCallback extends Callback {
  void demand(long);
  void release();
}
```
Method `demand(long)` would have the same semantic of ReactiveStreams `request(long)` (using `demand` to avoid confusion with the HTTP request concept).
Method `release()` would allow an application to say when the content is consumed.
Method `succeeded()` would be `release()+demand(1)` - same semantic as now.

The implementation would call `retain()` (not exposed to applications) on the `BackPressureCallback` implementation object before calling the application - the application would call `release()` on it, possibly asynchronously.
The retention will need to be forwarded all the way back to the network buffer so that the typical `fill()+parse()` loop in `onFillable()` will know if it can reuse the network buffer for the next read, or it has to store it away and allocate another network buffer.

```
onFillable()
  netBuf = new NetBuf()
  fill(netBuf.byteBuffer)
  parse(netBuf.byteBuffer)
    slice = sliceOf(netBuf.byteBuffer);
    parserListener.onContent(slice)
      netBuf.retain();
      bPCB = new BackPressureCallbackImpl(netBuf);
      channel.onContent(slice, bPCB);
        forEach appListener
          slice_i = sliceOf(slice)
          bPCB.retain()
            netBuf.retain()
          appListener.onContent(slice_i, bPCB) 
            // user code here
            bPCB.release() // content consumed
            bPCB.demand(1) // ask for more content
```

For just solving the data copying issue `bPCB.succeeded()` (i.e. `release()+demand(1)`) would be enough.

**Comment by sbordet** [comment]
@gregw what do you think of the above ?

**Comment by gregw** [comment]
Can you better describe why retain is needed? Why isn't it just a release semantic?

**Comment by sbordet** [comment]
@gregw we need a `retain()` every time we make a slice of the `netBuf`.
The receiver may have multiple content subscribers; you want to give each a different slice, because each of them may store it away and only later call `release()`.
When we move to upper layers from the network, we only deal with slices (no direct reference to `netBuf`), so we use the `BackPressureCallback` to call `retain()`, which forwards it to `netBuf` because the callback was created in the network layer.

**Comment by gregw** [comment]
OK, but now I don't like the asymmetry of demand(long)/release().   It should be something like:
 - demand(long)/release(long)
 - reserve(long)/release(long)
 - reserve(long) // negative does release
 - reserve()/release()
 - Closeable reserve()

I'm also dubious it is worth to complexity of a reactive like demand mechanism.  We simply cannot do the reactive semantic because prior to any demand(1) call, we are already committed to creating enough buffers to store an entire HTTP/2 stream window.  We have no mechanism to stop the data coming.

So a simple retain()/release() semantic on NetBuf should be sufficient.

**Comment by sbordet** [comment]
@gregw `demand(long)` and `release()` have different semantic; since they do different things, they don't need to be symmetric.

For this particular issue, the only one needed is `release()`. However, this is already implied by the current `succeeded()` semantic, so for this issue there is no need of a `demand(long)` API.

However, this issue and #2429 are very similar; there, `demand(long)` is required.

So perhaps I have mixed up a bit what is required for this issue with what's required for #2429.

If you re-read the first comments ignoring `demand(long)` and assuming that `release()` is `succeeded()` does it make more sense ?

**Comment by gregw** [comment]
I've been thinking about this problem in the abstract and thought I'd write a few thoughts to move the conversation along.   Essentially the problem is that we have several examples of asynchronous events that look like:
```
void onData(DataFrame frame, CallBack callback);
```
We have existing code that is written to this style of API and the basic contract is that from the time the `onData` is called until the time either `succeeded()` or `failed(Throwable)` are called that:
 - The data within the frame is available and underlying buffer will not be recycled.
 - Flow control is exerted and more calls to `onData` will not be made.

We would like to separate those concerns, so that passed buffer may be retain after or recycled before the flow control completion signal.  However, it needs to be done in such a way that existing code will work seamlessly without need for an update.

One idea is to make the CallBack instance passed polymorphic so that instead of just being:
```java
interface CallBack
{
    void succeeded();
    void failed(Throwable failure);
}
```
It could be something like:
```java
interface ReleaseableCallBack
{
    void finished();
    void release();
    default void succeeded() { finished(); release(); }
    void failed(Throwable failure);
}
```
Code implementing `onData` could continue to call `suceeded()` as before, or it could down cast and call `finished()` and `release()` independently.    There would need to be some further complexity to handle strange code that calls `finished()` or `release()` and then `succeeded()` or `failed(Throwable)` to ensure that double handling is not done.

This does work, but the problem is that it does not cope well with wrapping of callbacks, which is frequently done in our code base.   When callbacks are fanned out, aggregated or wrapped, the type of the callback is hidden and we essentially have a multiple inheritance problem to keep all the concerns on the callback.


more thinking......

**Comment by sbordet** [comment]
Moved the split of demand and release to #3951.
