### ISSUE TITLE
Jetty 9.4.9v20 HttpOutput.java does not log IOException if level is above DEBUG

### ISSUE THREAD

**Issue by DagBertelsen** [eclipse/jetty.project#2443]
In HttpOutput.java L:302

```java
// Do a normal close by writing the aggregate buffer or an empty buffer. If we are
// not including, then indicate this is the last write.
try
{
    write(BufferUtil.hasContent(_aggregate) ? _aggregate : BufferUtil.EMPTY_BUFFER, !_channel.getResponse().isIncluding());
}
catch (IOException x)
{
    LOG.ignore(x); // Ignore it, it's been already logged in write().
}
finally
{
    releaseBuffer();
}
```

But in write:

```
private void write(ByteBuffer content, boolean complete) throws IOException
{
    try (Blocker blocker = _writeBlocker.acquire())
    {
        write(content, complete, blocker);
        blocker.block();
    }
    catch (Exception failure)
    {
        if (LOG.isDebugEnabled())
            LOG.debug(failure);
        abort(failure);
        if (failure instanceof IOException)
            throw failure;
        throw new IOException(failure);
    }
}
```

This causes the 500 error to not log if you have included a too large header during a redirect.

**Comment by sbordet** [comment]
I'm not sure I understand. The error will be logged at DEBUG level and rethrown.
What would you like to happen, exactly ?

**Comment by sbordet** [comment]
@DagBertelsen it is deliberate that we log those exceptions at DEBUG level (and that the rethrown is ignored).

Your logs will be filled up of exceptions from write failures to clients that decided to close connections - and this happens _a lot_.

Can you please describe _exactly_ what you're doing ? You mentioned a redirect, etc.
We are focusing on a line of code, but I don't know yet what the problem is _exactly_.

**Comment by joakime** [comment]
@gregw how do you want to handle this?
Since this is a server side issue (too many headers produced on response), I don't see the old arguments about DoS attack vector on the logs being valid anymore.
But I also don't see this as something to be addressed / logged in HttpOutput.
This seems like a HttpGenerator specific logging task. (to log the BadMessageException)
