### ISSUE TITLE
Cannot run Jetty 9.2.x with Java Security Manager

### ISSUE THREAD

**Issue by MattyChambad** [eclipse/jetty.project#2486]
When using jetty with Java Security Manager enabled I'm unable to run due to the `System.getProperty` in `jetty.util.log.Log.java`. The `java.policy` in question I am unable to change so can't get around it by amending that appropriately.  Running it provides me with a `java.security.AccessControlException: access denied ("java.util.PropertyPermission" "*" "read,write")`.

**Comment by sbordet** [comment]
@MattyChambad I would guess that the permission in class `Log` is the tip of the iceberg.
Jetty would require permissions for sockets, threads, class loading, etc. so you would need to be able to modify the policy file not only for property permissions, but for many other permissions.

**Comment by joakime** [comment]
Also note that Jetty 9.2.x is EOL (End of Life) now.

* https://www.eclipse.org/jetty/documentation/9.4.x/what-jetty-version.html
* https://dev.eclipse.org/mhonarc/lists/jetty-dev/msg02726.html

**Comment by MattyChambad** [comment]
@joakime I understand it is EOL but changing versions at this point wouldn't solve my issue. This has occurred while using Jetty with an embedded system we have no control over, hence why I've raised the issue..

**Comment by MattyChambad** [comment]
@gregw that was my final thought, just wanted would raise this before having to go for that. Thanks for your help.

**Comment by joakime** [comment]
@MattyChambad Why are you attempting to run Jetty with a Java Security Manager enabled?

**Comment by MattyChambad** [comment]
@joakime we are running it on an embedded system that run's java security manager that we have no influence over. This includes turning it off or the policy associated with it.

**Comment by joakime** [comment]
Gotcha.  

Note that even if the `AccessController.doPrivileged(new PrivilegedAction<Object>()` fails due to your security manager ... 

https://github.com/eclipse/jetty.project/blob/d7ce334f8fd19e08410a79c0bc60ff0a3a5d1489/jetty-util/src/main/java/org/eclipse/jetty/util/log/Log.java#L85-L130

... you can still manually initialize the Logging with a call to ...

``` java
org.eclipse.jetty.util.log.Log.setLog(new JavaUtilLog()); // or StdErrLog or Slf4jLog
````

Does this embedded system at least support the compact3 JRE microprofile?

Note: Depending on the security manager, you might not be able to use the majority of Jetty (jsps, compilers, bytecode scanning, annotation scanning, work directories, memory mapped static file serving, servlet classloader behaviors, etc)

**Comment by joakime** [comment]
Closing.
