### ISSUE TITLE
Implement HTTP CONNECT for HTTP/2

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#250]
migrated from Bugzilla [#481459](https://bugs.eclipse.org/bugs/show_bug.cgi?id=481459)
status NEW severity _enhancement_ in component _http2_ for _9.3.x_
Reported in version _9.3.5_ on platform _PC_
Assigned to: Simone Bordet

On 2015-11-04 16:48:22 -0500, Simone Bordet wrote:

> https://tools.ietf.org/html/rfc7540#section-8.3

On 2016-01-07 15:18:18 -0500, Simone Bordet wrote:

> See also https://tools.ietf.org/html/rfc7639

**Comment by sbordet** [comment]
The issue is more complicated than initially thought.

After discussion with @gregw, need to check whether browsers already support it.
If so, then we need at least to have the server side working.

For the server side, the idea is that we change the HTTP parser to consider a CONNECT request to have an infinite request content, rather than being considered a request without content.
Similarly, it will have an infinite response content.
Then, `ConnectHandler` needs to be changed in a way that it reads content either via the request's `InputStream` or via the transport directly. In this way, the transport does the un-framing, so that the HTTP/1.1 transport does not do any un-framing (it will consider the request content to be delimited by EOF), while the HTTP/2 transport does the DATA un-framing (i.e. receives a DATA frame and passes its payload to the application - in this case to the `ConnectHandler`).
Similarly, `ConnectHandler` will receive content from the server and then either write it via the response `OutputStream` or directly via the transport, so that the HTTP/1.1 transport will just send the bytes as is, while the HTTP/2 transport will frame the bytes into DATA frames.

On the client side, things may be even more complicated. We would need to support mixed modes where the client needs to talk HTTP/2 to the forward proxy, but HTTP/1.1 to the server, or viceversa.
This hints for the client to support the transport dynamically, e.g. to choose the transport based on the ALPN protocol.
