### ISSUE TITLE
Suspected flaky test SslConnectionTest/testHelloWorld

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#2595]
https://jenkins.webtide.net/job/jetty.project/view/change-requests/job/PR-2242/lastCompletedBuild/testReport/org.eclipse.jetty.io/SslConnectionTest/testHelloWorld/

**Comment by sbordet** [comment]
All right, this test failed for a PR against `jetty-9.2.x`. 
The assert that failed in 9.2.x is not present in 9.4.x.

It was an assert on the number of jobs submitted to a thread pool used by the `SelectorManager` (on the server), and given the thread strategy changes in 9.4.x we don't assert it anymore.

I think we can close this issue and tolerate failures, since they are on 9.2.x.
