### ISSUE TITLE
Sessions saved when dirty regardless of savePeriod configuration

### ISSUE THREAD

**Issue by tallpsmith** [eclipse/jetty.project#2638]
I'd would treat this as an enhancement, but I would like to share some experience we've had migrating from a legacy J2EE container to Jetty.

It is most noticeable under load.  From my understanding of the way the Session is persisted, at the end of a request, if any of the below state is true, the Session is persisted to the Session store:

```
        if (data.isDirty() || (lastSave <= 0) || ((System.currentTimeMillis()-lastSave) > savePeriodMs))
```
see #1386 for related recent changes in this area to introduce the savePeriod.

Jetty is behaving with good intent here; if the Session has been modified, it does make _sense_  to want to persist this to the backing store.  The `savePeriod` though is being ignored, and is eagerly persisted.

In a clustered environment that _doesn't_ use Sticky Sessions this behaviour makes a lot of sense - you'd want the session state stored so that another node will get a consistent use of it. In a sticky-session case (or single node) though, this is probably not strictly required.  There's no option to let the savePeriod drive the decision here; dirty always wins.

Other J2EE containers have saved the Session state to longer term storage once a "passivation" threshold reaches - say, the Session has been idle for 15 minutes.  This event triggers a save to long term store and removal from in-memory.  There's no current way in Jetty (that I can find anyway) that allows this sort of relaxed behaviour to exist.

Under high load, when requests commonly modify a Session attribute (even just one), the session is being persisted at the end of the request.  

What I'm hoping might be considered possible is for the following, which is a combination of working behaviour with the Session Store and the Session Cache:

* Sessions that are active are in memory in the Session Cache 
* Sessions that become 'idle' are evicted from the Session cache, and _then_ stored to long term storage

An alternative mechanism might be to treat the persistence of Sessions as asynchronous, though this could introduce it's own threading/queueing problem under load as well (so many sessions needing to be updated that the background persister can't keep up).

I recognize that any Jetty node failure here will lose an active, but perhaps not-yet-saved Session.  It's possible that the Session store would have inconsistent state.

I'm wondering how high traffic sites that use Jetty with a persistent session store actually cope under load, as the Session store becomes a key bottleneck in the response time cycle of the request.

Anyone got any thoughts?

**Comment by janbartel** [comment]
@tallpsmith a slight correction here:  it is not on *every* request exit that the session is saved, it is only saved (if dirty, new or savePeriod expired) when the *last concurrent* request exits. On a highly loaded server, that is a big difference. 

There is also an existing config combo for idle-eviction: you can configure the cache to evict a session that has been idle longer than the specified time, and then also configure the cache to forcibly write that session out regardless of dirty state before eviction.  However, with the current cache implementation, as you say, you cannot avoid also doing one write when the session attributes have been modified during  (any simultaneous) requests. I could look at refactoring the AbstractSessionCache slightly to extract the decision on whether to do the write or not to a method that could be overriden by subclasses - that way you can probably implement a cache that does whatever kind of behaviour you want.

I would say that that the semantics of sessions are a very poorly defined part of the servlet specification. There is a lot of latitude for containers to interpret the gaps in the spec in various different ways. I would recommend that if you have data that is mostly-write rather than mostly-read you are probably better off not storing it in a session, but rather storing it in your own persistence mechanism where you can follow whatever save strategy is best for you. That way you will also get consistent behaviour when you port across containers, and avoid the overhead of the session mechanism. The latter is not insignificant: a lot of session overhead comes in having to deal with shared session ids between contexts - if you're not doing that, then why pay the overhead if you have a heavy load application?

**Comment by gregw** [comment]
@janbartel is there any scope in either us or @tallpsmith implementing a SessionDataStore that wraps other SessionDataStores and implements don't-always-write-me-unless-I'm-passed-some-timeout semantic?      That might be able to be done against the current release so @tallpsmith can have a work around immediately

**Comment by tallpsmith** [comment]
Thanks @janbartel, yes I had muddled my words, as it turns out it's (nearly) every request in our case.. :)

I know in reality we need to modify our app but we're still trying to track down where all these 'dirty writes' are happening. I actually believe the 'write' we're doing is probably pretty useless - but we're trying to migrate off the legacy container first.  I've written a SessionAttributeListener to try to track down which keys are being updated constantly to see if I can tune this behaviour down.   I suspect the values are being updated to the same value...

I just thought I'd point out this 'gap' in the way the configuration doesn't _quite_ work out as per the `savePeriod` (or at least the _spirit_ of what I thought the savePeriod was).

I'd prefer to go stateless and avoid Sessions altogether, but in this case, that's a massive job...

I like the idea that @gregw mentions - some sort of Strategy pattern that can be used to determine _if/when_ a Session ought to be saved.

**Comment by janbartel** [comment]
@gregw @tallpsmith can already write such a wrapping SessionDataStore - the AbstractSessionDataStore is the one that makes the decision whether to actually store the session or not inside its store() method. So he can override that method and decide under what circumstances to call super.store(). 

Be very careful though if you're not always writing the session out when it's dirty :  if you subsequently decide to also enable session cache eviction on request exit you can wind up with the session data not having been persisted at all. There would have to be some extra rework of sessions to prevent such a situation.

**Comment by tallpsmith** [comment]
>if you subsequently decide to also enable session cache eviction on request exit you can wind up with the session data not having been persisted at all. 

I had thought I'd worked around that by setting the:

```
jetty.session.evictionPolicy=900
jetty.session.saveOnInactiveEvict=true
```

on 15 minutes idle, kick out of memory, BUT save to persistent store.

additionally:

```
jetty.session.savePeriod.seconds=900
```

This is where I tried to set the "don't bother saving for 15 minutes" - but the `dirty` is effectively forcing it to save a lot.

**Comment by joakime** [comment]
@janbartel what's the status on this one now that Session has had a thorough going over?
