### ISSUE TITLE
Cleanup behavior of JMX MBean discovery

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#2727]
For particularly large classpath situations the current JMX MBean lookup has the potential to be a source of startup slowdown by unnecessary classloading calls.  Worth looking into an alternate way to do this given the new modular stuff as well if we haven't.

**Comment by joakime** [comment]
The implementation already filters based on the existence of the `@ManagedObject` annotation, so the scope of impact is just those classes.

We could add an optimization to the `@ManagedObject` annotation that allows you to specify the `MBean` object class to use for it.

``` java
// example
@ManagedObject(mbean=org.eclipse.jetty.client.jmx.HttpClientMBean)
public class HttpClient {
```

However, the multiple classloader hits on different scopes (parent vs child classloader) will still exist.

**Comment by jmcc0nn3ll** [comment]
I wonder if some sort of MBean ServiceLoader could be configured to do all this without that broad lookup approach.

**Comment by joakime** [comment]
ServiceLoader would be the wrong choice here.
That's for 1 interface and many possible implementations.
Plus it complicates things for OSGi

Just skip the broad lookup by declaring it in the `@ManagedObject` annotation instead.

**Comment by sbordet** [comment]
@joakime I don't see how adding the class name to `@ManagedObject` would solve the issue.

The MBean class is constructed as a string (thus achieving the same as the proposed `@ManagedObject` attribute) and then loaded.

If you have 100s of jars, the classloading should crack open each of them to find it, both with the current mechanism and with the `@ManagedObject` attribute.

Am I missing something?

**Comment by jmcc0nn3ll** [comment]
@joakime You are not wrong, the ServiceLoader would only be pulling up a single item as we currently have things but it could support folks extending the MBeans we offer (albeit unlikely in any sort of common case).  It does seem well suited to being declared within a single jar container jar which is sort of the goal here I think.  Then OSGI rears its ugly head, but I thought we were using ServiceLoader in other places or do those not interfere with osgi at all?  I'll take a peak.

**Comment by janbartel** [comment]
We do use ServiceLoader with OSGi in many places. To use it, you need appropriate manifest declarations in both the provider of the interface implementation and the consumer of it.

**Comment by olamy** [comment]
building an "index file" at build time sounds a good idea.

**Comment by gregw** [comment]
I'm a bit -1 on the concept of "syntectic"  (was that meant to be synthetic or syntactic or a deliberate merge of the two???).  To me it over complicates what is essentially a simple thing - we follow the type hierarchy to discover MBeans and their attributes.

Rather than change the semantic of our `@ManagedObject`, can't we just have a pre-scan process that put's it's results in a properties file. When we initialise our JMX container, it can look for the properties file and if found can have a cache of pre-prepared meta data for mbeans.  If there is no properties file, or a class does not hit the cache, then we scan as normal.

**Comment by sbordet** [comment]
The point of annotation scanning was exactly to remove properties files that existed before.
If we reintroduce them, now we need to keep 2 places in sync, annotations and properties file, which we'll forget.

It is following the type hierarchy in presence of large classpaths that slows down things because there is no negative caching of classes by classloaders.

We currently have 100+ `@ManagedObject` beans. Most of them extend either `ContainerLifeCycle` or `AbstractLifeCycle`.
That means the discovery will attempt to load `ContainerLifeCycleMBean` 100+ times, to find out that nope, the class is not there. Ditto for `AbstractLifeCycleMBean`. Ditto (currently) for `java.lang.jmx.ObjectMBean` (we should fix this regardless).

The idea is that if we can make the JMX machinery aware of those 2 component classes, then we create their JMX metadata once and then reuse it all the times, saving the classloading attempt 99+ times and saving allocation.

The problem is where to put this cache in a way that it is friendly to classloader recycling (so that we don't leak the classloader in case of webapp redeploy).

**Comment by gregw** [comment]
I am not proposing a properties file that has to be maintained.  It should be generated and used to preload a cache of metadata.

But why not just have a normal cache, so the first time ContainerLifeCycle or AbstractLifeCycle are loaded, their meta data is scanned and cached.  I don't understand why an extra attribute is needed to make this happen?  If it really is, then I don't understand the name  you are giving it? sure it should just be `cached=true|false`?

**Comment by jmcc0nn3ll** [comment]
There were two different optimizations in my post, the one that @sbordet is talking about (pre-caching the two most common lookup results) and the lesser involving the added attribute that is just a directive to not bother looking for a corresponding jmx.*MBean implementation.  I think Simone is not keen on that second one though, I mention it mostly because we talked about it and I kinda liked the idea, albeit it with a wart or two.

**Comment by joakime** [comment]
In a pathological test of a stupidly large war totally 595MB, with 517 jar files in WEB-INF/lib/, consisting of 326,685 JAR file entries the following was observed.
We'll call this `stupidly.war`..

Using 9.4.12.v20180830 the deployment of `stupidly.war` took @50126ms

The code from PR #2926 (at commit 2673ae98c2d44c1253366e7d3205109ae0f6d4b8) deployment of `stupidly.war` took @21873ms

I'd say that's a nice improvement.

**Comment by sbordet** [comment]
Done.
