### ISSUE TITLE
Proxy support in Jetty client using Java's normal outbound proxy params

### ISSUE THREAD

**Issue by bradical** [eclipse/jetty.project#2728]
Hi, I have an app deployed to Tomcat 9 on Java 8 with an embedded Jetty client that we use for making outbound connections for a variety of reasons.

I'm trying to figure out why the Jetty client doesn't seem to respect the outbound proxy settings I've set as `JAVA_OPTS` when booting Tomcat.

```
/usr/bin/java -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Xmx1024M -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Dhttp.proxyHost=proxy.us.org -Dhttp.proxyPort=3128 -Dhttps.proxyHost=proxy.us.org -Dhttps.proxyPort=3128 -Dhttp.nonProxyHosts=app.us.org|localhost -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dignore.endorsed.dirs= -classpath /usr/tomcat/bin/bootstrap.jar:/usr//tomcat/bin/tomcat-juli.jar -Dcatalina.base=/usr/tomcat -Dcatalina.home=/usr/tomcat -Djava.io.tmpdir=/usr/tomcat/temp org.apache.catalina.startup.Bootstrap start
```

I did see [this article](https://www.eclipse.org/jetty/documentation/9.4.x/http-client-proxy.html) but I wasn't clear if that was specifically referring to using an outbound internet proxy or if Jetty would still inherit settings like the ones above: ` -Dhttp.proxyHost=proxy.us.org -Dhttp.proxyPort=3128 -Dhttps.proxyHost=proxy.us.org -Dhttps.proxyPort=3128 -Dhttp.nonProxyHosts=app.us.org|localhost `

I read the [contributing guidelines](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/CONTRIBUTING.md) and couldn't figure out if this was even the appropriate place to post this since it's technically more of a question at this point. Please feel free to redirect me to the appropriate place.

Thanks!

**Comment by donniexyz** [comment]
Fast forward to jetty 12. Stumbled to this ticket after having issue during running `java -jar $JETTY_HOME/start.jar --add-module=demos` , stuck in

> ...
INFO  : copy ${jetty.home}\modules\demo.d\ee9-demo-jetty.properties to ${jetty.base}\webapps\ee9-demo-jetty.properties
INFO  : download https://repo1.maven.org/maven2/org/eclipse/jetty/ee9/demos/jetty-ee9-demo-jetty-webapp/12.0.8/jetty-ee9-demo-jetty-webapp-12.0.8.war to ${jetty.base}\webapps\ee9-demo-jetty.war
... (stuck there)

because the computer need to use proxy to access internet.

And it was solved by adding `-Dhttp.proxyHost=proxy.us.org -Dhttp.proxyPort=3128 -Dhttps.proxyHost=proxy.us.org -Dhttps.proxyPort=3128` as @bradical mentioned on his post.

**Comment by sbordet** [comment]
@donniexyz sorry, do I understand correctly that by adding the system properties, the Jetty client works properly?

**Comment by donniexyz** [comment]
@sbordet yes, adding the system properties solved the issue.

**Comment by iiliev2** [comment]
@donniexyz [The code](https://github.com/jetty/jetty.project/blob/cd4a09bc104757b350237729690838bc0016ac1f/jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/fileinits/DownloadFileInitializer.java#L45) you are referring to is using `java.net.http.HttpClient`, this issue is about `org.eclipse.jetty.client.HttpClient`. The jetty client does not have integration with `ProxySelector`.
@sbordet Is this a feature that you are planning on adding?

**Comment by sbordet** [comment]
No, we will not support `ProxySelector`, since Jetty's `HttpClient` has a different, possibly more powerful, support for forward proxies, via `HttpClient.getProxyConfiguration()` APIs.

We could support the system properties, and automatically add a proxy to Jetty's `HttpClient`, but this is currently not done.

@iiliev2, if you are interested, please open a new issue, and maybe a pull request?

**Comment by iiliev2** [comment]
We have lots of code which integrates with `ProxySelector` and we are interested in integrating jetty with that. I am assuming we need to implement `ProxyConfiguration.Proxy`, similar to `HttpProxy`.

**Comment by sbordet** [comment]
@iiliev2 please open a new issue and let's discuss it there.
