### ISSUE TITLE
Remove unused exception from WebSocketClient.connect()

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#2743]
`WebSocketClient.connect(Object websocket, URI toUri)` declares it might throw `IOException` but if you dig through its dependencies you will find it never actually does so. The same might also be true for the other `connect()` overloads.

I see that the method invokes `WebSocketClient.init()` which `throws IOException` but in fact that method never actually throws `IOException` either.

Being a checked exception, it would be helpful if you could remove this from the prototype so we don't have to catch it for nothing.

If you expect users to catch some other sort of exception, please document it. Obviously this method can fail but it's not clear what exceptions will be thrown. The documentation claims it will be `IOException` but that doesn't seem to be the case.

**Comment by joakime** [comment]
This will not be changed in Jetty 9.x - it would break backward compatibility.

The early history of the WebSocketClient was that it performed all of its own HTTP behaviors internally, using standard blocking connect and whatnot.
Back then, the `IOException` on `.connect()` was required.

Since then, we've ripped out the one-off HTTP behaviors and introduced jetty's own `HttpClient` to the mix, with this being 100% async, the `IOException` on `connect()` is no longer relevant, but we couldn't remove it now, due to backward compat reasons.

This has been corrected in the big websocket core refactor in Jetty 10.x already.
You will see this in the future.
