### ISSUE TITLE
JDBCSessionDataStore schema potential performance issue

### ISSUE THREAD

**Issue by tallpsmith** [eclipse/jetty.project#2745]
This is likely to be a SQL Server specific issue, but I thought I would highlight the discovery we had with Jetty's JDBC schema and query performance out of the box.

At the moment, `JDBCSessionDataStore` creates the schema using `varchar` as the default string type for the `contextpath` and `virtualhost` columns.  No real issue there on the surface of it because these columns are unlikely to have non-ASCII text in there.

The PreparedStatement used to query/update the session tables has 2 problems:

1. Potential mismatch in datatypes
2. Inefficient query when in _many_ cases  there is only ever one Context/Virtualhost 

### Data type Mismatch

Certain drivers, such as JTDS for SQL Server seem to default to using `nvarchar` when issuing a `sp_preparecall` for the Prepare Statement under most conditions (relatively short text such as the virtualhost/contextpath columns).   

When SQL Server sees the mismatch between the Prepare call (`nvarchar`) and the actual schema (`varchar`) it seems to downgrade to an inefficient Index Scan (walks the entire index) instead of an Index Seek (much faster lookup).  In SQL Servers case this can tend to involve higher lock contention as well.

the `getCreateStatementAsString` already supports differing types for the Blob and Long type - this might be a place to allow overrides for the String type too.

I'm not sure what other drivers do, they could be smarter. Just pointing out this in case someone else runs into similar performance issues.  (see #2638 for some background on how we got to where we are discovering this one too).

### Default case of only ever 1 virtualhost/context path
This one is more controversial, but I'm bettering many Jetty installations only ever have one Contextpath/virtualhost.  The schema/index is now a lot fatter and the index lookup could be faster if we know this in advance.  The lookups (select, update,delete) would be loads faster if it's just on sessionid.  

I wonder if it's just better to encode the virtualhost/contextpath in the sessionID and then it's just one column making the primary key for the session.

----

I think the above only comes out under higher loadedsystems such as ours.  I thought I'd leave this trail here anyway, even if I am not sure this one would really get much of a prioritisation given the fairly narrow band.  Always better to share/highlight this than not.

**Comment by janbartel** [comment]
@tallpsmith I'm happy to look at adding a getter/setter to DatabaseAdaptor for using nvarchar instead of varchar to allow maximum flexibility - although so far there have not been any reports of problems with multibyte characters in context path, which would be a better reason for doing the change than a somewhat dodgy driver :)

As for the single context situation, do you have any firm numbers to indicate the performance differential between keying off just the session id string vs a composite key? If there is a substantial saving, and user demand,  I'm happy to offer a different flavour of JDBCSessionDataStore that only works with a single context.
