### ISSUE TITLE
Proxy servlet does not handle HTTP status 100 correctly

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#277]
migrated from Bugzilla [#485601](https://bugs.eclipse.org/bugs/show_bug.cgi?id=485601)
status NEW severity *normal* in component *proxy* for *9.3.x*
Reported in version *9.3.6* on platform *PC*
Assigned to: Simone Bordet

On 2016-01-12 03:25:24 -0500, Lukas Krecan wrote:

> Jetty HTTP client handles 100 Continue using ContinueProtocolHandler. AbstractProxyServlet removes all protocol handlers to "pass everything to the client." The problem is that 100 Continue is handled by the servlet container, so it does not make sense to pass 100 response to the client.
> 
> The flow is following:
> 1. Client sends request headers without body containing Except: 100-continue
> 2. Jetty server accepts the request and passes it to the proxy
> 3. Proxy sends the request to the endpoint
> 4. Endpoint returns 100
> 5. Proxy returns 100
> 6. Servlet container returns 100
> 7. We have lost all context and can not continue with the request since the request has already been processed (in the servlet container)
> 
> It's not clear what the correct behavior should be. We can either 
> a) Not forward Except header
> b) Use ContinueProtocolHandler in the proxy

**Comment by sbordet** [comment]
Bug is confirmed, solution is tricky. 

Reference behavior:
https://tools.ietf.org/html/rfc7231#section-5.1.1

Thinking out loud below.

When the proxy forwards the request to the server, it installs a `ContentProvider` and in order to do so it calls `request.getInputStream()` which is bad because it sends the `100 Continue` to the client.
We need to delay the call to `request.getInputStream()` until the server replies with a `100 Continue` to the proxy.

Which brings another issue: how does the proxy's `HttpClient` know that the server sent a `100 Continue` ?
Currently this is handled all internally via `ContinueProtocolHandler` calling `HttpChannel.proceed(..)`.
However, we would need to call some application code, so that the proxy could perform some action to call `request.getInputStream()` and communicate back to the client the `100 Continue`.

**Comment by xd101x** [comment]
Hi,
I've just come across the same issue and as a quick test, I removed the Expect header before forwarding the request to the server upstream as suggested in the previous thread.

That seems to work, but I just wanted to know what are the actual implications of removing the header.  

Thanks,
David.

**Comment by nishantmonu51** [comment]
Any plans to backport the fix to 9.2.x ?

**Comment by jmcc0nn3ll** [comment]
@nishantmonu51 No hard plans on backporting to jetty-9.2.x, focus is mostly on jetty 9.4.x out the door and the longer that java 7 is EOL (1.5 yrs now) the more infrequent updates on there will be.

If it is critical you could try and backport @sbordet's fix and then make a pull request against 9.2.x, so long as the tests came along with it then it would be pretty straight forward PR to process. No plans on the next 9.2.x release but given some community interest in a new release we will certainly run them. 

recommend updating to 9.3.x though!
