### ISSUE TITLE
When warning about conflicting servlet mappings, detail where each mapping comes from

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#282]
migrated from Bugzilla [#485971](https://bugs.eclipse.org/bugs/show_bug.cgi?id=485971)
status ASSIGNED severity *enhancement* in component *servlet-3.1* for *9.3.x*
Reported in version *9.3.5* on platform *All*
Assigned to: Jan Bartel

On 2016-01-15 14:32:06 -0500, Joakim Erdfelt wrote:

> The current warning about duplicate mappings ...
> 
> Failed startup of context o.e.j.w.WebAppContext@79d22080{/demo-base,[file:///home/user/code/demo-base/, file:///home/user/code/demo-base/],STARTâ¦} java.lang.IllegalStateException: Multiple servlets map to path: *.jsp: DemoServlet,JSPServlet
> 
> does not indicate where each mapping is found, and how to debug/troubleshoot these conflicting mappings.
> 
> The warning and/or ISE should output the paths (and indication if from defaults, override, or webapp's WEB-INF/web.xml descriptors) for each entry in the conflict to better understand where to fix the problem.

**Comment by janbartel** [comment]
Fixed in jetty-9.4 and above.

If there is a conflict, you will see log lines like:

java.lang.IllegalStateException: Multiple servlets map to path /multi/*: Multi[mapped:DESCRIPTOR:file:///home/janb/src/jetty-eclipse/jetty-9.4.x/tests/test-webapps/test-servlet-spec/test-spec-webapp/src/main/webapp/WEB-INF/web.xml],Fragment[mapped:DESCRIPTOR:jar:file:///home/janb/.m2/repository/org/eclipse/jetty/tests/test-web-fragment/9.4.0-SNAPSHOT/test-web-fragment-9.4.0-SNAPSHOT.jar!/META-INF/web-fragment.xml]
