### ISSUE TITLE
SNI matching does not work in certain cases when there is only one CN certificate in the keystore

### ISSUE THREAD

**Issue by dremon** [eclipse/jetty.project#2886]
Jetty version 9.4.12.

Conditions:
* keystore contains two certificates: one CN certificate with subjectAltNames configured and alias "cert1", and one certificate without CN, with alias "default".
* SslContextFactory configured with certAlias set to "default", so it will fallback if SNI matching fails.

Expected behaviour:
SNI matching works and "cert1" is selected correctly when connecting to it's host name.

Observed behaviour:
"default" certificate is always selected unless a second CN certificate is added to the keystore.

I think this is related to commit 8660055574026ed963f4f5b7aa2e8a16ad292f50.

**Comment by gregw** [comment]
Thanks for this report and the diagnosis! looking...

**Comment by sbordet** [comment]
@dremon I don't think we have enough information.

For commit 8660055 to make a difference for your case, you would need to have exactly 1 non-wildcard host and zero wildcard hosts, so that before commit 8660055 the expression would evaluate to `true` and after would evaluate to `false`.
I doubt that you have such case with 2 certificates in the keystore.

@gregw while #2888 may be an improvement for that expression, but I'm not sure it changes anything for the OP of this issue.

**Comment by sbordet** [comment]
@gregw how can a certificate with CN _and_ subjectAltNames and another with no CN (but presumably subjectAltNames) yield just one entry in `_certHosts`?
The only possibility is that they all point to the same host name, and so they are misconfigured: if there is only one name there is no need for SNI.

**Comment by dremon** [comment]
To clarify:

keystore contains 1 SNI certificate (CN + subjectAltNames) and 1 non-SNI certificate (CN=localhost, no subjectAltNames).

This non-SNI certificate is always selected (incorrectly) even when connecting to the host name which matches first SNI certificate, unless a second SNI certificate is added (then it works).

**Comment by gregw** [comment]
@dremon if you could test the PR #2888 that would be good.  Although we have added a unit test that duplicated your problem so we are moderately confident we've fixed it.
