### ISSUE TITLE
Change getLogger(String) to getLogger(Class)

### ISSUE THREAD

**Issue by PashaTurok** [eclipse/jetty.project#2947]
When Jetty(util) works with loggers it works with loggers by their string class names. For example:
```
public class AcceptRateLimit {
    private static final Logger LOG = Log.getLogger(AcceptRateLimit.class);
   ...
}

public class Log {
  public static Logger getLogger(Class<?> clazz)
    {
        return getLogger(clazz.getName()); // THIS LINE!
    }
  ...
}
```
And when jetty uses other logging frameworks it calls their getLogger(String). This solution has some problems - in external logging networks we can not get classes and take important information about class JPMS module and JPMS layer. Such information can be very useful if we want to create log files per module/layer. That's why I suggest to work with logger by class but not class string name.

**Comment by joakime** [comment]
While overwhelming number of use cases are for `getLogger(Class)` that is not the only way loggers are created.
There are many use cases where just a simple String is used. (to name just a few: package level logging, request logging, security logging, audit logging, etc)

For the majority of logging frameworks that Jetty can link to, the logger name is just a String.
The fact that it happens to conform to a package structure is just convenient, not a requirement.

The following logging frameworks use String to track their logger names (not classes).
* slf4j
* java.util.logging
* log4j
* jetty logging

Note: We've encountered a few speciality (re: commercial) slf4j implementations that insist on Class references only, Those always fail on Jetty, Jasper, JSTL, ECJ, etc..

Also note that most logging frameworks are singletons, at the System ClassLoader level (an attempt to initialize another logger from a nested layer will only result in the reference from the system level being returned)
If logging by layer is your goal, that is typically accomplished using an MDC/NDC feature (or equivalent) within a logging framework.
To get layered logging, you would pay attention to where the logging event was emitted from, not from where the logger was initialized.
For example, our Centralized WebApp Logging example uses the slf4j MDC to setup references for when the events are emitted from a dispatched request within a webapp.
See: https://github.com/jetty-project/jetty-webapp-logging/blob/master/src/main/java/org/eclipse/jetty/webapp/logging/ContextLogHandler.java

But if you feel that this isn't what you have in mind, then feel free to submit a PR on your proposal, we'll review it and see what you have in mind.

**Comment by PashaTurok** [comment]
@joakime Yes, logging by module and layer is my goal. Could you explain `If logging by layer is your goal, that is typically accomplished using an MDC/NDC feature (or equivalent) within a logging framework.`. For example I modified SLF4 in `LoggerFactory.getLogger(Class)` method I get Class and from this class I get do `Class#getModule()`. How should I get Module if `LoggerFactory.getLogger(String)` is used.

**Comment by joakime** [comment]
Logging by layer is an artifact of WHERE the logging event is emitted from (the specific occurrence of log.warn / log.info / log.debug / etc).
Under what scenario? what thread stack? what classloader? what request? what virtual host? what specific instance of said class that is producing the log?
It's up to you to hook into the MDC/NDC concepts (or similar) with your chosen logging framework at the appropriate place.
Using `getLogger(String)` or `getLogger(Class)` is a dead end, and will not get you what you are interested in.

I included a slf4j reference in the prior comment demonstrating the slf4j approach.
If you are using say java.util.logging, then your java.util.logging.Handler could use the [java.util.logging.LogRecord](https://docs.oracle.com/javase/10/docs/api/java/util/logging/LogRecord.html) and it's information to provide this layering.
Or you can write your own MDC/NDC concepts for java.util.logging (this has been done countless times in various other open source projects).
Or you can use logback and it's log slicer against it's own MDC/NDC to provide said layering.
Or you can use log4j2 with its NDC to identify the layers and then the RoutingAppender to split it up later.

**Comment by PashaTurok** [comment]
@joakime Thank you for your explanation, but it seems that there is a little misunderstanding between us. So full example - I have three JPMS layers:

1. Boot layer with my modified SLF4J library (API + Simple).
2. Jetty layer (this layer is child of boot)
3. ZApplication layer (this layer is child of boot).

In my modified SLF4J I want to log messages from jetty layer to jetty.log and messages from ZApplication to zapplication.log. So, I need in my modified SLF4J get int layerHashCode of the the log message sender. In zallication, when I call SLF4J I do `getLogger(Class)` so I have all the necessary information. But Jetty does `getLogger(String)`. If I understand MDC Jetty could provide int layerHashCode in MDC, but does Jetty do it?

**Comment by joakime** [comment]
MDC / NDC are logger specific concepts, slf4j is a generic facade for the specific implementations.
Understand what MDC / NDC are capable of in your chosen logger implementation first.
Note: slf4j doesn't need to be modified in order to accomplish your goals.
slf4j and the logging frameworks have figured all of this out years ago for CDI / OSGi / Spring / Guice / Plexus / JBoss Modules / etc ...

"Layers" isn't unique to JPMS, there's nothing unique about JPMS or your arbitrary application structure when it comes to logging.
Getting events from the loggers to be associated to a specific behaviors ("Layers" in your language) already exists.  Use them.

Take this simple example ...

Your Jetty layer initializes a static logger for `org.eclipse.jetty.server.Request`
A specific Request instance is created at the Jetty layer, and handed off to the ZApplication layer.
Logging events occurring in the specific Request instance while in the ZApplication layer will not be associated with your ZApplication layer in your efforts, it will be associated with the Jetty layer, even though the event was triggered by behavior in your ZApplication layer.
Then the Request object is handed back to the Jetty layer and there's events triggered by Jetty, outside of your ZApplication execution scope, that would definitely belong to the Jetty layer.
Now scale that up, to multiple ZApplication layers.
Where did that event occur?  What ZApplication caused it?
This where the existing logging frameworks live and breathe, they have figured this out already, years ago.

Creating scope / context for logging can be any arbitrary set of "layers". 

As an example, a common setup for scoped/context logging with Jetty is ... Server > Connector [1..n] > Connection [1..n] > Request [1..n] / Response [1..n] / AsyncContext [0..1] > WebApp [0..n] > Security [0..n] > Session [0..n] > Filters [0..n] > Servlet [0..n] > Application Code.

The Centralized WebApp Logging example (from prior comment) sets up the WebApp scope / context (or "layer" in your language).
Note that the in none of these examples do we care about the Logger instance. (using String or Class)
The context / scope of the events are determined using other features of the Logging frameworks.

**Comment by PashaTurok** [comment]
@joakime Ok. But let me ask you some details. Are you speaking about messages that come from web application that is deployed in Jetty? Or are you speaking about Jetty messages (messages that come from classes that are in jetty modules(for example from org.eclipse.jetty.security.authentication.DeferredAuthentication))? I am speaking about Jetty messages.

**Comment by PashaTurok** [comment]
It seems that there is only solution - to use JDK 9 StackWalker API. So I am closing this issue.
