### ISSUE TITLE
Servlet spec specifies that filter and servlet are run in the same thread

### ISSUE THREAD

**Issue by zenbones** [eclipse/jetty.project#2972]
Looks like Jetty will switch threads between execution of filters and the servlet, for any one request, which violates the servlet specification. For my project, I would like to transfer some information from the http request onto thread local variables within the servlet call. The proper place for that processing would be in a filter, which, according to the spec should be fine, but this breaks under Jetty's threading.

**Comment by joakime** [comment]
Pretty sure Jetty will not switch threads unless you are using Async processing (AsyncContext from Servlet 3.0) or Async I/O (Servlet 3.1) from the servlet spec.

**Comment by joakime** [comment]
Also of note, the `javax.servlet.SingleThreadModel` from Servlet 2.3 (and older) was deprecated in Servlet 2.4 and has no replacement.

**Comment by joakime** [comment]
Whipped up a simple testcase for this report ...

https://gist.github.com/joakime/e3ee7ccb5323be228d1de9fb9967a0cd

Then sent 10 million requests at it via ApacheBench.
If the report is true, then an error status 409 and a "Whoops" should have printed.
It did not.

At this point we need a reproducer.

**Comment by joakime** [comment]
Alternatively, you can use the HttpServletRequest attributes to move information around within the same Request to different parts of your code.
That will work regardless of Async Processing, Filters, Async I/O usage, custom threading of your own, 3rd party libraries, etc.

**Comment by joakime** [comment]
The reference in `servlet-3_1-final.pdf` to the spec that the OP mentions is ...

>## 6.2.1 Filter Lifecycle
>  **4.** ... The `service` method is required to run in the same thread as all filters that apply to the servlet.

**Comment by zenbones** [comment]
Thanks for testing this. I'm at least semi-sure of what I'm seeing as I whipped up a test case of my own but it's currently embedded in the detritus of our environment. Before I go through the trouble of freeing it for independent testing and review, we're using DropWizard, and I have a suspicion that DropWizard might be adding the Jersey servlet as asynch capable. My understanding Jetty internals is that would make the entire chain filters/servlet asynch capable. Now, my reading of 6.2.1 above means to me that synchronous or not, a servlet and its filters run in the same thread context. If you tell me that's true for Jetty I'll put my test in a condition where it can run independently. If you know that's not true for asynch capable servlets, I'll go confirm my suspicion about DropWizard. I'd understand if, 6.2.1 not-withstanding, you leave thread context switching under asynch capable conditions as it stands, but I do need to know what the truth is so I can react accordingly.

Thanks for your time in this matter.

**Comment by gregw** [comment]
Once dispatched to a filter chain and servlet, the same thread will be used by jetty, although within the filter chain it is possible for a filter to use another thread to call `chain.doFilter`, but that is contrary to the servlet spec if they do.
Anywhere in the filter chain or in the servlet, async processing can be started and the thread will return through the part of the chain already entered.
Async processing can then complete entirely async and the filter chain and servlet are never entered again.
Or Async processing can dispatch the asyncContext, so that a filter chain and servlet are re-entered by a potentially new thread to generate the response.
Note that for async processing, a filter may not be tagged to act on async dispatches, so it may be bypassed
