### ISSUE TITLE
How to modify the content of the response to visit the HTTPS web site?

### ISSUE THREAD

**Issue by ToBeAMonk** [eclipse/jetty.project#2981]
I started the proxy server jetty-proxy with embedded jetty and added my own filter to Proxy Server. The main thing this filter does is make some modifications to the returned content. When I visit the HTTP address, the returned result will pass through my filter, but when the HTTPS address is visited, it seems to have gone another way A channel does not go through my filter. How can I solve this problem?

**Comment by ToBeAMonk** [comment]
Please forgive my English level! I'm using jetty-proxy and adding my own filter project in an embedded way. The code is as follows: 
`public class ProxyServer
{
	public static void main(String[] args) throws Exception
	{
		Server server = new Server();
        ServerConnector connector = new ServerConnector(server);
        connector.setPort(8888);
        server.addConnector(connector);
        // Setup proxy handler to handle CONNECT methods
        ConnectHandler proxy = new ConnectHandler();
//        proxy.setWhite(new String[]{"mail.google.com"});
//        proxy.addWhitelistHost("www.google.com");
        server.setHandler(proxy);

        // Setup proxy servlet
        ServletContextHandler context = new ServletContextHandler(proxy, "/", ServletContextHandler.SESSIONS);
        ServletHolder proxyServlet = new ServletHolder(ProxyServlet.class);
//        proxyServlet.setInitParameter("whiteList", "google.com, www.eclipse.org, localhost");
//        proxyServlet.setInitParameter("blackList", "google.com/calendar/*, www.eclipse.org/committers/");
        context.addServlet(proxyServlet, "/*");
       
 //add my filter
		ServletHandler handler = new ServletHandler();
		FilterHolder fh = handler.addFilterWithMapping((Class<? extends Filter>) OTLFilter.class, "/*", EnumSet.of(DispatcherType.REQUEST));
		context.addFilter(fh, "/*", EnumSet.of(DispatcherType.REQUEST));
		server.start();
	}
}`

OTLFilter is the gateway to the entire filter project. You can see that I set port 8888. When I modify the browser's proxy port, all requests are proxied. So the problem is that HTTP requests are filtered by OTLFilter, HTTPS requests are not. I looked at the code for ConnectHandler:
`  @Override
    public void handle(String target, Request baseRequest, HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
    {
        if (HttpMethod.CONNECT.is(request.getMethod()))
        {
            String serverAddress = request.getRequestURI();
            if (LOG.isDebugEnabled())
                LOG.debug("CONNECT request for {}", serverAddress);
            handleConnect(baseRequest, request, response, serverAddress);
        }
        else
        {
            super.handle(target, baseRequest, request, response);
        }
    }`
 HTTPS executes handleConnect (), HTTP executes super. handle (), and when super. handle (), the access results are filtered, and when handleConnect () is executed, it is not. I don't know if I described it clearly enough.

**Comment by sbordet** [comment]
You are setting up a forward proxy, since you say that you modify the browser configuration to point to your proxy address.

Such proxy cannot intercept encrypted traffic to other sites.

As I have already said in #2956, you cannot intercept encrypted traffic to other websites.

**Comment by sbordet** [comment]
I don't know how else to tell you. 

It's IMPOSSIBLE.

It does not depend on Jetty: you don't be able to do this with any other server or library.

The browser will encrypt the request with a public key coming from a remote server such as `google.com`. 
In your proxy, you cannot decrypt those bytes because you don't have `google.com` private key.

What Jetty's `ConnectHandler` does is to take the bytes from the browser and pass them to `google.com`, and viceversa. You cannot decrypt them, you cannot modify them.

**Comment by aalku** [comment]
I think you can do this if you make a reverse proxy. A reverse proxy is when you put an intermediate domain with it's own certificate and the proxy server receives the requests and make a new one to the final server and proxy the response back to the client. Client<-->https://myproxydomain.org<-->https://finalserver.com. That's two independent https communications and you could theoretically change the contents. I'm trying to do it right now. 😅

**Comment by sbordet** [comment]
@aalku you can only do it with a reverse proxy if you control the DNS of your domain(s) for both `myproxydomain.org` _and_ `finalserver.com`.
Otherwise you cannot.

For example, if the final server is `google.com` or any other website for which you don't own the domain you cannot do it, unless you have a custom client that does not do any client-side certificate verification (i.e. an insecure client).
No browser will allow this relaying, for example.

**Comment by aalku** [comment]
No. That's not right.

A reverse proxy works like this. In my home I have a standard Chrome browser with standard configuration and I enter https://myproxydomain.org and it receives some content and that's it from it's point of view. It will inspect that the myproxydomain.org certificate used in the key exchange, of course and it will match myproxydomain.org.

If that domain has a reverse proxy then that's a web server which content is not stored or generated there but it's obtained by making a request to https://google.com, for example. That proxy is working both as a client and a server. The client side is negotiating it's own SSL with it's own key echange with google.com and it can inspect google.com certificate etc. It receives the google.com content, it can modify it and it return it to the client that requested https://myproxydomain.org. Modified and "signed" as myproxydomain.org, not as google.com of course.

From the browser point of view the content comes from myproxydomain.org so nobody (apart from google.com) needs the private key of google.com for this to work.

I'm doing it right now but I need to extend Jetty because I need to tunnel the second part to reach private networks but for a basic scenario where everyhing is in the Internet you wouldn't need to extend much. You can use a AsyncMiddleManServlet configuring the url rewrite in it's TransparentDelegate I think. If I'm wrong then you might need to extend the AsyncMiddleManServlet class as I'm doing.

**Comment by sbordet** [comment]
Are you saying that people that wants to use a browser to talk to `google.com` should instead remember to put in the address bar `myproxydomain.org`?
And that you have a different `myproxydomainXYZ.org` for every possible other domain out there?

**Comment by aalku** [comment]
No. I'm saying that that's possible, but you could invent some rewriting rule or any other way to tell the same server what to proxy like myproxydomain.org/google.com/
It can use always the same myproxydomain.org name and the same myproxydomain.org certificate.
