### ISSUE TITLE
External jars that must be converted to JPMS

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2989]
Jetty has a number of dependencies on external jars that needs to be converted to JPMS before Jetty itself can be converted to proper JPMS modules.

**Comment by sbordet** [comment]
See #2978.

**Comment by sbordet** [comment]
`javax.servlet:javax.servlet-api`

**Comment by sbordet** [comment]
`org.conscrypt:conscrypt-openjdk-uber`

See google/conscrypt#554.

**Comment by sbordet** [comment]
`javax.mail:javax.mail-api`

This has been published to Maven Central by Oracle, but without JPMS metadata.

See https://github.com/eclipse-ee4j/javamail - unfortunately not yet published to Maven Central.

**Comment by joakime** [comment]
`javax.websocket:websocket-api`

See eclipse-ee4j/websocket-api#260

**Comment by joakime** [comment]
Keep in mind that the JPMS names for `eclipse-ee4j` jars are likely to be changed en-masse to start with `jakarta.*` in the future.

**Comment by joakime** [comment]
Ugh, `java.mail` [requires `java.desktop`](https://github.com/eclipse-ee4j/javamail/blob/EE4J_8/mailapi/src/main/java/module-info.java#L30), wonder how that will work on headless JVMs?

**Comment by joakime** [comment]
The `eclipse-ee4j` module naming effort:
 * for specs is at https://github.com/eclipse-ee4j/ee4j/issues/34
 * for implementations is at https://github.com/eclipse-ee4j/ee4j/issues/35

**Comment by sbordet** [comment]
`javax.security.auth.message:javax.security.auth.message-api`.

See https://github.com/eclipse-ee4j/jaspic

The module name (see the project's `pom.xml` file) has been defined as `java.security.auth.message` but not released yet to Maven Central.

**Comment by sbordet** [comment]
`com.github.jnr:jnr-unixsocket`

See jnr/jnr-unixsocket#61

**Comment by bowbahdoe** [comment]
Re-opening to ask if this work is complete or not

**Comment by sbordet** [comment]
@bowbahdoe with EE 10, I believe all spec jars have a proper `module-info`.

Out of curiosity, do you use JPMS?
If so, can you detail how?

**Comment by bowbahdoe** [comment]
> do you use JPMS? If so, can you detail how?

I'm gonna give a pretty annoying answer to this I think.

Yeah, I use modules - but mostly because i write up little libraries. With few or zero dependencies there is no reason not to have a `module-info`.

I have some thoughts about the jlink/jpackage "workflow", how that _could_ be part of a simpler overall workflow for the ecosystem writ. large, how it seems like the leyden work is going to want module descriptors, and I do like running `jlink` and `du -sh` on my small toy projects and seeing 20-30mb. Feels clean.

But, professionally I've spent most of my JVM time in Clojure. The clojure world does not care about modules. I am very used to zipping everything into an uberjar and putting that uberjar in a docker image with the full jdk.

...does that make sense?
