### ISSUE TITLE
Update Jetty 10 to use non-LEGACY Compliance Modes

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3009]
Historically, in Jetty 9.x we used `LEGACY` as the default operational mode for the various Compliance modes.

Starting in Jetty 10.x we should default to the current spec RFC.

This will impact Jetty code using ...

* org.eclipse.jetty.http.HttpCompliance
* org.eclipse.jetty.server.MultiPartFormDataCompliance
* org.eclipse.jetty.http.CookieCompliance

**Comment by joakime** [comment]
Proposed new default usage:

* org.eclipse.jetty.http.HttpCompliance.RFC7230
* org.eclipse.jetty.server.MultiPartFormDataCompliance.RFC7578
* org.eclipse.jetty.http.CookieCompliance.RFC6265

**Comment by joakime** [comment]
PR #3015 opened

**Comment by joakime** [comment]
Closing, completed in commit e908df97a3d63320c15361d977480d4db72ce87e

**Comment by smitagarg1** [comment]
API requests are failing with 403 AWS Signature Mismatch error post Jetty 10.0.12 upgrade .Setting HttpCompliance.LEGACY used to solve this error as shown below 

https://github.com/gaul/s3proxy/commit/2e61c3862656419f2a0452d9ceab22be311e84fb

But now it fails in Jetty 10 again 
This is because the content type that we are sending "Content-Type: application/x-www-form-urlencoded; charset=**utf-8**" is converted in to uppercase "application/x-www-form-urlencoded; charset=**UTF-8**" .

What exactly should be used to resolve this error in Jetty 10 ? org.eclipse.jetty.http.HttpCompliance.RFC7230 doesn't seem to help here

**Comment by joakime** [comment]
@smitagarg1 I opened Issue #9674 to track this new concern
