### ISSUE TITLE
Move Session implementations to new /jetty-sessions/ top level module

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3013]
In Jetty 10.x, create a new top level module called `/jetty-sessions/` which is a parent for the various session implementations.

Eg: jetty-hazelcast, jetty-infinispan, jetty-gcloud?

**Comment by sbordet** [comment]
@janbartel, currently we have:

- `jetty-gcloud` with a single child module `jetty-gcloud-session-manager`, package `org.eclipse.jetty.gcloud.session`
- `jetty-hazelcast`, package `org.eclipse.jetty.hazelcast.session`
- `jetty-infinispan`, package `org.eclipse.jetty.session.infinispan`
- `jetty-nosql` package `org.eclipse.jetty.nosql.mongodb`

They have a mix of package names which I think it's a good time to make consistent.
Either `o.e.j.session.<impl>` like `jetty-infinispan`, or `o.e.j.<impl>.session` like others.
Module `jetty-nosql` is the strangest and should be normalized too (perhaps drop `nosql` and just call it `mongodb`).

I like `o.e.j.session.<impl>` better than the others.

**Comment by joakime** [comment]
Open Question: Do we want to move existing core/default Session handling into this new `/jetty-sessions/` top level?

**Comment by janbartel** [comment]
I don't mind normalizing the package names.

I'm not really in favour of moving the session stuff into its own toplevel project. This is because there may be more than one use of a particular library in jetty, not just for sessions. Using a distinct top-level project for each library, and a subproject under each for session usage keeps the versioning and usage of the library neatly in one place rather than scattered throughout the code.

**Comment by olamy** [comment]
` o.e.j.session.<impl> `
+1
I like the idea about a top level module as well. Moving  ` test-sessions ` as well?

**Comment by sbordet** [comment]
@janbartel we are proposing to have a `jetty-session` parent module, and many sub-modules like they are now under the root module:
```
jetty-session/
  /jetty-gcloud
  /jetty-infinispan
  ...
```

If e.g. `jetty-gcloud` needs itself to be a parent module, so be it.

The goal is to clean the root module so that all session related stuff is in one place rather than scattered around.

+1 to extract the JDBC part out of `jetty-server`. But then why not extract everything out of it?

**Comment by janbartel** [comment]
@sbordet, I understand the proposal. My point was that if eg gcloud was used in more places than just sessions, it would not be a good idea for that other use to be inside jetty-sessions, nor would it be a good idea to have to put it in a different top level module and thereby scatter gcloud around the repository

Also, we don't marshall any of the other implementations of jetty interfaces into a top level project with many subprojects Eg, we don't have jetty-connectors with various different submodules in that; we don't have jetty-protocols with subprojects jetty-websocket, jetty-http, jetty-http2 etc etc.

**Comment by jmcc0nn3ll** [comment]
@janbartel has a point, Jetty 10 is the solid time to reorganize layout. With a push to reorganize sessions, does it make sense to further break up the largely flat structure we currently have?  Or are all the various sessions related artifacts we have these days simply mean sessions are prominent enough they should be grouped together.

**Comment by janbartel** [comment]
What would be the "proper" jetty grouping? We have an n x n matrix of features x integrations, so you have to slice and dice it some way into a hierarchical project structure - any choice isn't "proper", it's just a choice.
