### ISSUE TITLE
ALPN module not found: modules/alpn-impl/alpn-1.8.0_191.mod

### ISSUE THREAD

**Issue by lorthirk** [eclipse/jetty.project#3028]
Hello all,

As discovered at eclipse/kapua#2139, It seems that Jetty cannot start on OpenJDK 1.8.0_191 because of a missing `modules/alpn-impl/alpn-1.8.0_191.mod`:

```
java.lang.IllegalStateException: Cannot read file: modules/alpn-impl/alpn-1.8.0_191.mod
	at org.eclipse.jetty.start.Modules.registerModule(Modules.java:202)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:355)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:360)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:377)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:377)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:286)
	at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:129)
	at org.eclipse.jetty.start.Main.start(Main.java:435)
	at org.eclipse.jetty.start.Main.main(Main.java:77)

Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
       java -jar $JETTY_HOME/start.jar --help  # for more information
```

It worked fine when using OpenJDK 1.8.0_181, but now _191 is installed as default from yum in CentOS 7 (docker image centos:7).

In the meanwhile, is it safe to just symlink alpn-1.8.0_181 to alpn-1.8.0_191?

**Comment by sbordet** [comment]
I'm guessing you are using an older version of Jetty that was released before 8u191.

It's not safe to symlink `alpn-1.8.0_181` to `alpn-1.8.0_191` because 8u191 and 8u192 require a different `alpn-boot` jar than 8u181.

I recommend that you pick up the current `alpn-1.8.0_191` file from branch `jetty-9.4.x` - and do so in the future as well, as symlinking is not guaranteed to work (like in this case).

We'll release Jetty 9.4.13 in the next days with the updated ALPN files - you just hit that period in-between Jetty releases with a new JDK version that requires a different `alpn-boot` jar.

**Comment by lorthirk** [comment]
I'm using the latest available version, 9.4.12.v20180830. I'll wait for 9.4.13... but since I'm building a Docker image with OpenJDK downloaded via yum and Jetty downloaded from eclipse.org, this means I somehow have to keep in sync manually Jetty and OpenJDK versions in the future?

**Comment by sbordet** [comment]
> Since I'm building a Docker image with OpenJDK downloaded via yum and Jetty downloaded from eclipse.org, this means I somehow have to keep in sync manually Jetty and OpenJDK versions in the future?

Unfortunately, yes.
Most of the times there is nothing to do, but when there are ALPN changes in between Jetty releases like it happened this time, you have to patch the old Jetty or wait for the new one.

Your other option is to drop Java 8 and move to Java 9+ (possibly Java 11) where you don't need this manual sync since the ALPN features are in the JDK.

**Comment by lorthirk** [comment]
> Your other option is to drop Java 8 and move to Java 9+ (possibly Java 11) where you don't need this manual sync since the ALPN features are in the JDK.

This looks like a viable long term option. In the meanwhile I could just drop `http2` module since we don't actually use it. I'm having some troubles doing this, because of 
```
36108 [main] WARN  o.e.jetty.xml.XmlConfiguration -
java.lang.IllegalStateException: No default protocol for ServerConnector@954b04f{null,[]}{0.0.0.0:8443}
```
but that's another story I guess :) Thanks for the hint.

**Comment by joakime** [comment]
@lorthirk Jetty version `9.4.13.v20181111` is now available on Maven Central.

**Comment by lorthirk** [comment]
Thanks! We'll update this as soon as possible.
