### ISSUE TITLE
google cloud and support needs better customer attitude

### ISSUE THREAD

**Issue by iatomic** [eclipse/jetty.project#3032]
Ali Muqaddas <notifications@github.com>
To:GoogleCloudPlatform/nodejs-getting-started
Cc:iatomic
Comment
Oct 25 at 2:02 AM
Such a pathetic response from Google :/ No any solution anywhere !!!

I agree. Even more. I am shocked how bad quality of service we are getting as customers.
We built all and got it all running on our own without the eclipse tools, if we can call it that are
so primitive that I would assume they are being built by interns that have absolutely no idea about
tools for developers. on top of this. command line tools are not exactly tools for IDEs.
We got all running but I frankly think most of the problems are that google has no decent tools
for the cloud. You can sure close the thread, just keep open the ones that tell you how great what you build is.

**Comment by joakime** [comment]
What is your question for eclipse/jetty.project ??

**Comment by iatomic** [comment]
we have solved the problem fine with command line tools. What we would like to know at this point. The toolsets do not seem to suppor custom environments. None of them asks for Dockerfiles...

How do you use a Dockerfile, yaml and war file to deploy with those tools

**Comment by jmcc0nn3ll** [comment]
@iatomic Just to be clear since this appears to have very little context for us, you opened a bug in the eclipse/jetty.project github project with the original message. 

See:  https://github.com/eclipse/jetty.project/issues/3032

If this is in error feel free to close the issue, but as @joakime says, if you have a concern or issue with Jetty itself please elaborate further.

**Comment by iatomic** [comment]
all fine lets close the thread.
