### ISSUE TITLE
How to handle 'connect' request for SSL with Jetty ProxyServlet

### ISSUE THREAD

**Issue by ToBeAMonk** [eclipse/jetty.project#3042]
I read a lot on the Internet about the problem of jetty-proxy handling HTTPS, which I encountered myself. I don't know how to solve it, and I wonder if you can give some specific solutions.
![image](https://user-images.githubusercontent.com/43089848/47784256-00734580-dd40-11e8-80a3-6583d47fba46.png)

**Comment by sbordet** [comment]
If your problem is to tunnel HTTPS requests to an upstream server, then you use the `ConnectHandler` and you are done. The only thing you can know with the `ConnectHandler` is the host to connect to - nothing about subsequent requests made to that host.

If your problem is to try to decrypt HTTPS requests to upstream servers you do not own (and therefore you don't have their private cryptographic keys), then it's impossible.

**Comment by joakime** [comment]
The search performed by OP: https://stackoverflow.com/search?q=jetty+ConnectHandler

The 4 questions that OP shows in screenshot:

1. https://stackoverflow.com/questions/49840535/jetty-connecthandler-with-upstream-proxy - asking how to have ConnectHandler forward requests to another proxy
2. https://stackoverflow.com/questions/34312126/handling-https-request-by-jetty - asking how to write a SSL MITM where they decrypt the traffic with their own certificate
3. https://stackoverflow.com/questions/50121262/how-to-handle-connect-request-for-ssl-with-jetty-proxyservlet - asking how to support CONNECT from AsyncProxyServlet
4. https://stackoverflow.com/questions/9852056/jetty-proxyservlet-with-ssl-support - asking how to support CONNECT from Jetty 8.x

Of the 4 linked questions on Stackoverflow, questions 2 and 3 are what @sbordet pointed out (MITM with CONNECT), which isn't possible.
Question 1 is about modifying CONNECT behavior (not MITM), but still not supported.
Question 4 is an old question about supporting CONNECT with Jetty 8.x (which is now EOL/End Of Life) - `ConnectHandler` did exist back then, it was introduced in Jetty 7.2.0, and was in a different package `org.eclipse.jetty.server.handler` (since Jetty 9.0.0 it was moved to `org.eclipse.jetty.proxy`)

**Comment by santhoshTpixler** [comment]
Hi, I am using Jetty 9x. I need a proxy server out of embedded jetty. I was able to successfully proxy request via Jetty for http. But http 301 redirects are not handled. Is there any way to handle redirects. Also can it follow http -> https redirect?

**Comment by sbordet** [comment]
@santhoshTpixler redirects are handled properly, we have a [test](https://github.com/eclipse/jetty.project/blob/jetty-9.4.14.v20181114/jetty-proxy/src/test/java/org/eclipse/jetty/proxy/ProxyServletTest.java#L862) that proves it.

Following http -> https is done by the clients, not by the Jetty server.

If you still have problems, you have to be way more precise describing your case, and detailing what you have done, what does not work, and what do you expect instead.
