### ISSUE TITLE
Warn on common SslContextFactory vulnerable configurations

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#3049]
It is possible to badly configure SslContextFactory to be vulnerable. Produce a warning on common vulnerabilities unless explicitly told not to.

**Comment by joakime** [comment]
Closing, as it was merged into jetty-9.4.x on commit bb045f641e1da5ab9c61db870858a2dafce815f2

**Comment by sford** [comment]
I noticed the following warning that I think is related to this issue (added by PR #3050 ):

```
No Client EndPointIdentificationAlgorithm configured for SslContextFactory@2cf92418[provider=null,keyStore=file:///.....,trustStore=null]
```

👍for warning on insecure SSL configuration. I would like to fix any warnings that come up, but is this actually actionable for a basic jetty server that uses SSL? The warning mentions "client", so is this only an issue when client certs are in use?

**Comment by joakime** [comment]
The `SslContextFactory` is generic, and a single instance can be used in many places, some server, some client, etc...

If you are confident that you have no client behaviors, (direct Jetty HttpClient use? Http2Client use? Proxy usage? AsyncMiddleManServlet usage? WebSocketClient usage? JSR356 Client usage?) then feel free to ignore that warning.

Alternatively, you could make that warning go away by just declaring a EndPointIdentificationAlgorithm (such as `HTTPS`) on the `SslContextFactory.setEndpointIdentificationAlgorithm(String)`

**Comment by sford** [comment]
@joakime Thanks for the quick response.

Yeah, there are no client behaviors. Unfortunately I can't just ignore it easily because we have automated alerting when warnings crop up in our logs to detect potential problems like this when we upgrade libraries.

It sounds like we will need to take the latter approach and just set this to clear the warning even though it doesn't appear to impact us.
