### ISSUE TITLE
Reformat all code at New Years

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3059]
Based on an internal discussion with the various developers on the project, we've tentatively settled on using the Spring/Google style guide and will reformat (and resort) all code on New Years.

The process worked out is currently as follows.

1. Establish Eclipse and IntelliJ style/format imports (xml?) for this new reality
2. Reformat (and reorganize) all code in `jetty-9.4.x` branch
3. Reformat (and reorganize) all code in `jetty-10.0.x` branch
4. Perform a merge from new `jetty-9.4.x` HEAD to `jetty-10.0.x` HEAD (accepting `jetty-10.0.x` on all merge conflicts. aka `ours`)
5. Update Year on `jetty-9.4.x` for 2019.
6. Merge up from `jetty-9.4.x` to `jetty-10.0.x`

**Comment by gregw** [comment]
I don't think the Spring/Google style guide is entirely settled, tentatively or otherwise.
I'd like to consider using them as a basis but keeping balanced {} 

The most important thing is to have a style that we can apply uniformly... being the same as other projects is not so important.
As these things tend to become religious wars, I think a minimal change approach is good to adopt, so where there is a style enforced in jetty code we should keep it.  Where there is not (eg in spacing), then by all means, let's adopt a style from other common projects.

**Comment by joakime** [comment]
We should also reformat all of the XML files.

This XML format could also be a syntax definition in the various IDEs that could use a syntax file.

**Comment by sbordet** [comment]
For XML, given some have a quite deep nesting, I think it's best for 2 spaces as default indentation.

**Comment by joakime** [comment]
Completed by olamy a while ago.
