### ISSUE TITLE
java.nio.Buffer.position() IllegalArgumentException

### ISSUE THREAD

**Issue by panghy** [eclipse/jetty.project#3060]
We seem to be getting the following exception under high loads which leads to the socket leaking (and direct buffers growing) until we run out of fds.

Jetty 9.4.12.v20180830
Java 1.8_u191

```
java.lang.IllegalArgumentException: null
! at java.nio.Buffer.position(Buffer.java:244)
! at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:96)
! at sun.nio.ch.IOUtil.write(IOUtil.java:51)
! at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
! at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:264)
! at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:393)
! at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:349)
! at org.eclipse.jetty.io.ChannelEndPoint$3.run(ChannelEndPoint.java:133)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:295)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
! at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
! at java.lang.Thread.run(Thread.java:748)
```

**Comment by gregw** [comment]
I bit more info would be good.  What type of traffic, what size of responses? How are they written?  
Better yet, can we get a thread dump and a [server dump](https://www.eclipse.org/jetty/documentation/9.4.x/jetty-dump-tool.html)

**Comment by panghy** [comment]
http/1 traffic (unencrypted), dropwizard 1.3.2. The request and response sizes should be small (JSON). The response is a JAX-RS streaming response.

**Comment by panghy** [comment]
The problem is that the moment this happens, the server will crash (not even jstack would respond) when file descriptors run out quickly. We could up the process limit (4096) to see if we can have a bit more time to catch it happening.

**Comment by gregw** [comment]
I'm pretty sure we should be catching `Throwable` in `WriteFlusher`, so I've gone ahead and updated that code with d455ac6
@panghy if you could test against your own build of that commit, that might tell us more about what is going on, plus make the server more resilient to failures.    We have a release coming out later this week, so you could wait... but then any problem we subsequently discover wont get fixed until the following release.

**Comment by panghy** [comment]
Thanks so much, we'll take a look and see if we can get a reproduction

**Comment by panghy** [comment]
The IAE is thrown by:

```
if ((newPosition > limit) || (newPosition < 0))
    throw new IllegalArgumentException();
```
in `Buffer position(int newPosition)`at line 244 of Buffer.java. I think java 9 is already changing it so that it throws with a more useful message

**Comment by panghy** [comment]
And, yeah, when you run out of FDs, the JVM gets very sad (can't resolve DNS, jstack doesn't work, debuggers can't attach, etc.).

**Comment by gregw** [comment]
@panghy Ah yes 244 not 224.    So looking at the code in [IOUtil](https://github.com/openjdk-mirror/jdk/blob/jdk8u/jdk8u/master/src/share/classes/sun/nio/ch/IOUtil.java#L80-L97) the only way that IAE is going to happen is if another thread is concurrently changing limit (or maybe position).... so it looks like there could be a buffer pool problem!

The problem with that, is the exception is again probably symptom rather than cause.    If this was a common problem, then we'd be getting lots of reports... so something rare is happening which is potentially returning a buffer to the pool either twice or once and keeping a reference to it.   So what we need is for you to run with our [Leak Tracking ByteBufferPool](http://www.eclipse.org/jetty/javadoc/9.4.12.v20180830/index.html?org/eclipse/jetty/io/LeakTrackingByteBufferPool.html)

How to you instantiate and configure your server/connectors?

**Comment by panghy** [comment]
I see, so it's possible that there's a concurrent flush of sorts against a Jersey StreamingOutput perhaps.

**Comment by panghy** [comment]
It's otherwise just a generic dropwizard/jersey application (streaming output and SSE).

**Comment by sbordet** [comment]
It could be that there are concurrent writes to the same output, especially when SSE (which is asynchronous by nature) is involved, or some other async write such as error pages, or - like shown in the OP stack trace - in case of pending writes that are completed upon a NIO event.

The semantic of `OutputStream.write()` is that concurrent writes are safe because when a write is in progress, other writer threads will wait on a lock; I don't think we protect from concurrent writes in this way, as it should be application responsibility to not do those.

So if it's concurrent writes to the same output, the buffers will be modified concurrently, leading to the exceptions seen by the OP.

@panghy I would recommend that you double check your application for concurrent writes.

@gregw does the Servlet specification say something about protecting concurrent writes with a lock?
Perhaps open an issue at the Servlet specification to clarify this?

**Comment by sbordet** [comment]
@panghy could also be that DropWizard is not using the Servlet 3.1 async I/O APIs correctly and that leads to concurrent writes (so it's not your application fault, but the framework you use).

Have you tried the latest DropWizard?

**Comment by panghy** [comment]
We should be on latest drop wizard and I am not sure it does anything beyond just using jetty and Jersey. Concurrent writes are certainly possible but I recall patching Jersey myself on this issue but maybe there are other issues (could try latest Jersey at least). In any case I am not sure if there's a better failure mode here other than leaking the socket (it also seems like once it starts to happen, fds start to leak massively).

**Comment by panghy** [comment]
For ChunkedOutput in Jersey, the synchronization seems to be right when it flushes: https://github.com/jersey/jersey/blob/master/core-server/src/main/java/org/glassfish/jersey/server/ChunkedOutput.java#L225

**Comment by sbordet** [comment]
@panghy the latest Jersey seems to use an old Jetty version, 9.4.7. Can you force it to use the latest 9.4.12 (e.g. by forcing Maven dependencies or similar)?

**Comment by panghy** [comment]
We are on DW 1.3.7 (that's latest). We dependency manage Jetty to 9.4.12.v20180830. Jersey is 2.25.1.

**Comment by panghy** [comment]
Hm, perhaps writing to the OutputStream in StreamingOutput (https://docs.oracle.com/javaee/7/api/javax/ws/rs/core/StreamingOutput.html) does need synchronization?

We have been writing to that stream concurrently for the longest time but it could be a rare race condition.

**Comment by gregw** [comment]
@sbordet The servlet spec says this:
```
Other than the startAsync and complete methods, implementations of the request
and response objects are not guaranteed to be thread safe. This means that they
should either only be used within the scope of the request handling thread or the
application must ensure that access to the request and response objects are thread
safe.
If a thread created by the application uses the container-managed objects, such as the
request or response object, those objects must be accessed only within the object’s
life cycle as defined in sections Section 3.13, “Lifetime of the Request Object” on
page 3-32 and Section 5.8, “Lifetime of the Response Object” on page 5-51
respectively. Be aware that other than the startAsync, and complete methods, the
request and response objects are not thread safe. If those objects were accessed in the
multiple threads, the access should be synchronized or be done through a wrapper
to add the thread safety, for instance, synchronizing the call of the methods to access
the request attribute, or using a local output stream for the response object within a
thread.
```

So it explicitly calls out accessing the output stream as not being thread safe. However, that verbage pre-dates the async IO API, so it can't really be held too.  Ie it has to be safe for different threads to call output stream methods without synchronization.... but perhaps not concurrently.

So I think jetty is correct in it's current usage to not protect against concurrent access... but then perhaps it would be sensible for us to do so, given the hard nature of async programming.  We could do this either by:
1. converting the output state from an atomic reference to a locked state, so that concurrent calls would be excluded and some threads could block waiting for the lock
2. adding non-blocking protection to the write, flush and close methods to explicitly detect concurrent access and throw an exception if detected.

I kind of like option 2 as the most helpful with least behaviour chance... but it would be just be extra work... perhaps it could be optionally added with a wrapper?
Option 1 probably has least performance impact as it replaces one mechanism with another... but it will also change behaviour as calls can now block rather than just react to the current state.

**Comment by sbordet** [comment]
@panghy how can you write concurrently to `StreamingOutput` without the output being garbled and written in out-of-order chunks?

**Comment by panghy** [comment]
Yeah, I think for what we are doing, the concurrent writes are order independent (meaning we call write() like a stream and only when a single atom is ready). We are assuming that a single call to write() or flush() is atomic and theadsafe (and it has seem to be so for a long time).

**Comment by gregw** [comment]
@panghy concurrent writes have never been atomic nor threadsafe, they have just mostly been fast.  I note your exception is occurring when waking up from a blocked write, so potentially it only occurs when the network slows down the writes.

I'm going to ponder if we should do more in jetty (see comment above), but for now can you either explicitly synchronize... or perhaps install a filter that wraps the outputstream with a synchronized one?

cheers

**Comment by panghy** [comment]
Sure, that's what we'll be doing to prevent this (mostly now trying to repro this so that we can test the fix). It's just odd that the failure scenario is so spectacular :)

**Comment by panghy** [comment]
I'll close this for now pending some further testing. Upon closer inspection, this was only the case for about 11 months but since @gregw thanks for pointing out that it might be a slow network that this occurs (will definitely be trying that out).

I'd still say that the error is consistent across machines so it does seem like one failure scenario (not sure how common is a handful of samples) is that it would fail inside Buffer.position(). Not sure if @gregw's change would at least make it less likely to go into a tail-spin at least.

Thanks for jumping in and helping @gregw and @sbordet!

**Comment by panghy** [comment]
As a quick follow-up, you can repro the issue by hitting http://localhost:8080/ running the following app: https://github.com/panghy/jettybufferissue/blob/master/src/main/java/com/github/panghy/api/TestApi.java

Eventually it'll hit the Buffer.position() IAE. But again, you just can't write concurrently to the stream (even with StreamingOutput). SSE is safe, however, Jersey ChunkedOutput protects that.
