### ISSUE TITLE
Promise<Connection> is not resolved when SSL Connection is closed during TLS handshake

### ISSUE THREAD

**Issue by esamudera** [eclipse/jetty.project#3153]
When using Jetty version `9.4.11.v20180605`, HTTP/2 and `RoundRobinConnectionPool`, we experienced a bug where `AbstractConnectionPool` failed to create a new connection. From the logs, we found out that the `Promise<Connection>` instantiated in the `tryCreate` method never succeeded nor failed.

We followed the code trails and later compiled this log describing the anomaly: https://gist.github.com/andnej/57d8c35541df2f5fed46a1e6de21ea98

In this log, our application is having a TLS handshake when suddenly the SSL Connection is closed near the end of the log file. From there, we didn't find any `HTTP2Session` activity at all, suggesting that the `HTTP2ClientConnection@failed` might never get called. And since they're not called, our `Promise<Connection>` was stuck.

However, we're not sure if this hypothesis is correct or if this bug is already fixed or being fixed, so we would appreciate your input on this.

Thanks!

**Comment by joakime** [comment]
There's been a number of improvements surrounding close/failure conditions in newer releases of Jetty, can you try again with Jetty `9.4.14.v20181114` please?

**Comment by sbordet** [comment]
The OP case seems indeed a case that was definitely improved in 9.4.12 and later with the fix for #2233.

From the logs a `flush()` happens during the handshake which moves the state to `NEED_UNWRAP`; at that point we attempt a `fill()` but we don't check the return value (which the logs shows to be -1); therefore we don't realize that something was wrong, and likely we end up in a idle state.

**Comment by esamudera** [comment]
Okay, thanks! We will update our Jetty dependency and will monitor for some time if the bug still appears or not.
