### ISSUE TITLE
Add support for javax.net.ssl.HostnameVerifier to HttpClient

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3154]
Currently `javax.net.ssl.HostnameVerifier` is a way to perform Hostname verification within the following libraries (but not Jetty's `HttpClient`) ...

### Java itself

``` java
  HostnameVerifier hv = new TrustAllHostnameVerifier();
  HttpsURLConnection.setDefaultSSLSocketFactory(sc.getSocketFactory());
```

### OkHttp

``` java
  SslClient sslClient = SslClient.localhost();
  SSLSocketFactory socketFactory = sslClient.socketFactory;
  HostnameVerifier hostnameVerifier = new HostnameVerifier() {
    @Override public boolean verify(String s, SSLSession session) {
      return true;
    }
  };

  client = new OkHttpClient.Builder()
        .sslSocketFactory(socketFactory, sslClient.trustManager)
        .hostnameVerifier(hostnameVerifier)
        .build();
```

### Apache HttpClient 3.x

``` java
  HostnameVerifier hostnameVerifier = SSLConnectionSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER;
  SSLConnectionSocketFactory sslsf = new SSLConnectionSocketFactory(builder.build(), hostnameVerifier);
  CloseableHttpClient httpclient = HttpClients.custom().setSSLSocketFactory(sslsf).build();
```

### Apache HttpClient 4.x

``` java
  HttpClientBuilder b = HttpClientBuilder.create();
  SSLContext sslContext = new SSLContextBuilder().loadTrustMaterial(null, new TrustStrategy() {
         public boolean isTrusted(X509Certificate[] arg0, String arg1) throws CertificateException {
            return true;
         }
      }).build();
  b.setSslcontext(sslContext);
  HostnameVerifier hostnameVerifier = SSLConnectionSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER;
  SSLConnectionSocketFactory sslSocketFactory = new SSLConnectionSocketFactory(sslContext, hostnameVerifier);
  PoolingHttpClientConnectionManager connMgr = new PoolingHttpClientConnectionManager(RegistryBuilder.<ConnectionSocketFactory> create()
    .register("http", PlainConnectionSocketFactory.getSocketFactory()).register("https", sslSocketFactory).build());
  b.setConnectionManager(connMgr);
  HttpClient client = b.build();
```

Investigate if we should offer this in Jetty's HttpClient as well.

**Comment by nikhilahuja** [comment]
I was looking for it. It would be really helpful if this could be added as an easy-to-use built-in feature just like Apache HttpClient. We have our own implementation of HostnameVerifier (it takes into consideration various options configured by the user) that we were using with Apache HttpClient for HTTP/1.1 support. Since the current implementation of Apache HttpClient with HTTP/2 support (version 5.0) is still in beta, we decided to go with Jetty. 

A simple way I would have liked to use it would have been:
```
final SslContextFactory sslContextFactory = new SslContextFactory();
sslContextFactory.setHostnameVerifier(new HostnameVerifier() {
    @Override
     public boolean verify(String s, SSLSession sslSession) {
         // My code for verification
     }
});

final HttpClientTransport transport = new HttpClientTransportOverHTTP2(new HTTP2Client());
final HttpClient httpClient = new HttpClient(transport, sslContextFactory);
```

**Comment by sbordet** [comment]
Can I ask what is the use case here?

You want to allow certain hosts that don't match the certificate **and** at the same time disallow other hosts that _also_ don't match the certificate?

I ask because in the expression `(allow some && disallow others)` the first half alone (before the `&&`) and the second half alone (after the `&&`) can already be done.

Can you detail a case where you need both?

**Comment by sbordet** [comment]
Would be great if you guys can test the code with this issue fixed and report if it works fine for you.

**Comment by sbordet** [comment]
The current work on commit 8964608 calls the verifier _only_ at the moment the connection is established.

For your case, when the connection is not good for your settings, have you tried to close the connection and return `null` from `acquire()`?
This would trigger the opening of a new connection that you can check again with the verifier, and should be much simpler.
