### ISSUE TITLE
JavaxWebSocketServerContainerInitializer always creates a HttpClient

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#3167]
A HttpClient is always created per context when javax websockets are enabled.  This is very wasteful of resources, specially when it is a very rare case that the websocket client container is ever actually used within a server.
We need to either do some/all of the following:
+ make the HttpClient instantiated lazily when needed
+ create the HttpClient initially, but only start it when first used.
+ have an optional configuration that is required to be enabled before the client is available (must work well for webapps and embedded usage)

**Comment by joakime** [comment]
We used to have lazy initialization, but it was migrated away from for many reasons (see various details in source control commit messages against `WebSocketClient`).

The simple fact is that as soon as a `ServerContainer` exists, it's added to the `ServletContext` attributes (per spec) and any changes made to it must be represented in the `ClientContainer` as well, which means the `WebSocketClient` is also updated, which means the `HttpClient` is also updated.

The way we get around "waste" is not by lazy init anymore, it's by using a common `HttpClient` instead, accessed via Server attributes.

We also briefly talked about having `ServerContainer` itself be lazy init'd when first accessed from `ServletContext.getAttribute("javax.websocket.server.ServerContainer")`, an act that indicates intent to use.

Since this is only an issue with JSR356, the lazy init of `ServerContainer` is probably a more reasonable approach.
This could prove useful with the `JavaxWebSocketServerContainerInitializer` as well, so that if it doesn't get a list of classes (for endpoints or application configs), it never accesses the ServletContext attributes, hence no-discovered JSR356 endpoints, no `ServerContainer` was instantiated.

**Comment by gregw** [comment]
I still think it is crazy to create a HttpClient with all it's selectors etc. when it is almost never used.  No taxation without representation!
I just fiddled the JavaxWSSCI to not create the WebsocketClient unless it found a HttpClient set as an attribute.  All but 2 tests passed!  Those test just need to set a HttpClient and they pass.   I think this is a fair indication of how underutilized the client-in-container feature is.      There are many many websocket apps that will never use the client, so having a default configuration that gives them an UnsupportedOperationException if they try is not a big deal... so long as we have a very simple way to turn on the client for those contexts that need it.

**Comment by lachlan-roberts** [comment]
@gregw this issue can be closed now 3bcb4d822943a029442cb4f016d884c21cb0dd46 has been merged to 10

**Comment by lachlan-roberts** [comment]
we now use a `Supplier<WebSocketCoreClient>` to create the `WebSocketCoreClient` lazily, when it is created, a pre-existing shared `HttpClient` and `Executor` are looked for using the `ServletContext`
