### ISSUE TITLE
Session Cookie "secure" flag is incorrectly set to true by default.

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3173]
In Jetty 9.4.x (and 10.x), the `SessionHandler` will set all Cookies it produces with the `secure` flag present on all TLS requests, regardless of descriptor settings.

The following pattern is responsible ...

https://github.com/eclipse/jetty.project/blob/b4ab8a07c12cd8c3bd5f242b02ab37c61ab06676/jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java#L727-L736

Note that the "secure" flag on a Cookie is false by default on the following Cookie usages ...

* java.net.HttpCookie
* javax.servlet.http.Cookie
* org.eclipse.jetty.http.HttpCookie
* javax\servlet\resources\web-common_3_1.xsd - (undeclared `javaee:true-falseType` value defaults to false)
* javax\servlet\resources\web-common_4_0.xsd - (undeclared `javaee:true-falseType` value defaults to false)

The behavior in `SessionHandler` should also not make the `secure` flag on by default, even for TLS.
This needs to be configured to true, either in the `SessionHandler.setSecureRequestOnly(true)` or the `WEB-INF/web.xml`

``` xml
<session-config>
  <cookie-config>
    <http-only>true</http-only>
    <secure>true</secure>
  </cookie-config>
</session-config>
```

With the current defaults, if a user changes their descriptor to say ...

``` xml
<session-config>
  <cookie-config>
    <http-only>true</http-only>
    <secure>false</secure> <!-- intentionally set false -->
  </cookie-config>
</session-config>
```

Then the `secure` flag will still be produced.

**Comment by gregw** [comment]
The javadoc for `SessionCookieConfig#isSecure` says:
```
     * Checks if the session tracking cookies created on behalf of the
     * application represented by the <tt>ServletContext</tt> from which
     * this <tt>SessionCookieConfig</tt> was acquired will be marked as
     * <i>secure</i> even if the request that initiated the corresponding
     * session is using plain HTTP instead of HTTPS.
     *
     * @return true if the session tracking cookies created on behalf of the
     * application represented by the <tt>ServletContext</tt> from which
     * this <tt>SessionCookieConfig</tt> was acquired will be marked as
     * <i>secure</i> even if the request that initiated the corresponding
     * session is using plain HTTP instead of HTTPS, and false if they will
     * be marked as <i>secure</i> only if the request that initiated the
     * corresponding session was also secure
```

Note the: ` false if they will be marked as <i>secure</i> only if the request that initiated the corresponding session was also secure`

So my reading of that is that if set to false, then the cookie will be marked secure if the request initiating the session was also secure.   So I think our current implementation may be correct?

**Comment by janbartel** [comment]
I'd also point out that this is not new behaviour in jetty-9.4.x - it's been this way for a very long time in jetty, so any change is likely to be a surprise for users.

**Comment by joakime** [comment]
We (oddly) just had a user in `jetty-users` ask about this topic a few hours after I filed this.

https://www.eclipse.org/lists/jetty-users/msg08691.html

**Comment by sumanthm95** [comment]
We have recently performed an upgrade from Jetty 4.2.24 to Jetty 9.2.25 which involves servlet upgrade as well from 2.4 to 3.1.
Before upgrade, we were able to access the application smoothly as expected using both HTTP & HTTPS for below mentioned scenarios:
(1) Login to the application through HTTP then close the browser tab upon successful login and re-login to same application using HTTPS.
(2) Login to the application through HTTPS then close the browser tab upon successful login and re-login to same application using HTTP.
(3) Login to the application through HTTP at first and simultaneously login again to application from another browser tab using HTTPS.
(4) Login to the application through HTTPS at first and simultaneously login again to application from another browser tab using HTTP.

But, after the upgrade there is a change of behavior witnessed in site-data/cookie handling due to which Scenarios (1) & (3) holds good as expected while scenarios (2) & (4) showed a different observation -

For scenario 2; When we login to application though HTTPS at first; a secure cookie gets created. After closing the browser tab, when we try to login through HTTP, the login fails due to the presence of secure cookie. When we try to login again after deleting this secure cookie; we were able to login into the application successfully which creates an insecure cookie (with "Send for - Any kind of connection").


Likewise for scenario 4; When we login to application though HTTPS at first; a secure cookie gets created. When we try to login simultaneously from another browser tab through HTTP,  here the HTTP login fails due to the presence of secure cookie again. So Here again, we may be in position to delete the secure cookie which got created to gain access through HTTP.


From above, it is inferred that the end-user will be in the position to delete cookies at times to gain access to the application through HTTP & HTTPS subsequently. This becomes a new manual overhead after performing the Jetty upgrade.


Fix we tried :

We tried to fix this behavior internally following Jetty documentation (https://www.eclipse.org/jetty/documentation/9.2.22.v20170531/session-management.html topic:Session Cookie Configuration) & few forum posts to make use of \<secure\>false\</secure\> under \<session-config\> \n \<cookie-config\> \n.

But, we ended up here into Specs..

Also, it was understood that 
When \<secure\> is configured true in web.xml -
(1) Login into application through HTTP at first creates a secure cookie due to which login fails all the time. Later, When we try to login through HTTPS, login goes successful. 

(2) Login into application through HTTPS at first creates a secure cookie and the login goes successful. Later, When we try to login through HTTP, login fails all the time. 


When \<secure\> is configured false in web.xml -
(1) Login into application through HTTP at first creates an INSECURE cookie and login goes successful. Later, When we try to login through HTTPS, this INSECURE cookie gets updated/modified to SECURE cookie and HTTPS login also goes successful. Now, if we login again through HTTP without deleting this cookie, HTTP login fails.

(2) Login into application through HTTPS at first creates a SECURE cookie since the connection request is through HTTPS and the login goes successful. Later, When we try to login through HTTP without deleting this cookie, login fails.

**From this thread and its discussion, We understand that the recent behavior is as per Servlet Spec but we really wanted to know the reason why this kind of requirement was stipulated in the Spec. Say for example, Was there any vulnerability reported earlier ? Or Is it stipulated for a security enhancement to avert specific attacks or hijacks ?**

**Comment by joakime** [comment]
@sumanthm95 the servlet spec has recommended using HTTPS for Cookie references that contain login credentials for quite a while.

Having a single server with both HTTP and HTTPS is very old school thinking.
Even the changes in the current crop of Web Browsers tells you this (marking your HTTP site as insecure and warning on all form submission)

**Comment by janbartel** [comment]
As @joakime has said, sending session information in the clear in cookies on http requests is inherently unsecure, so you should probably reconsider your application's usage of http and https wrt to sessions.
