### ISSUE TITLE
Persist session Changes

### ISSUE THREAD

**Issue by smanikim** [eclipse/jetty.project#3179]
We are using custom session storage with jetty 9.4.14. We do need to set some Attribute on session.  Code says we mark sessionData as dirty at this point and call HttpSessionAttributeListeners.
I don't see which API should I call to make it propagate to session storage as Cache put only works if pending requesting are 0.

Would be great if you can point me to some code/example which suggest how to write HttpSessionAttributeListeners and methods should I call so that changes propagate to SessionCache and SessionDataStore Both. ( We dont use sticky Behavior in our environment)

Also, I am using `setSaveOnCreate` true in my SessionCache and changes some session attributes after session creation. if sever requesting current session dies, Would I get updated on another server SessionCache.

**Comment by janbartel** [comment]
@smanikim if none of the shrinkwrapped session storage mechanisms provided by jetty suit you, you can always implement your own. All you need to implement is an AbstractSessionDataStore. You should not implement anything to do with calling listeners - all that is taken care of by the SessionHandler and a SessionCache implementation. If you have no sticky load balancer then you can configure the NullSessionCache to ensure that every time a request accesses a session, it is fetched fresh from the persistent storage. However, the downside of this approach is that if your application does a lot of mutation of session attributes, then you are going to wind up with non-deterministic session contents due to the non-atomic nature of the servlet session specification.

**Comment by smanikim** [comment]
I tried using NullSessionCache. After that when I call session.setAttribute(key, newValue) and call myDataStore.getSession(sessionid).session.getAttribute(key) , I still get old value.

( I am extending AbstractSessionDataStore here)

**Comment by janbartel** [comment]
By design the attributes of the session will be persisted when the last request exits the session. There is no expectation on behalf of the servlet spec that attributes are persisted as soon as set is called. Indeed it would be horrendously inefficient. Why do you want to do this?

**Comment by smanikim** [comment]
Because my request can go to any server due to non-sticky behavior

**Comment by smanikim** [comment]
I read the servlet specification. It said "Within an application marked as distributable, all requests that are part of a session must be handled by one JVM at a time."  Though this is bit surprising to me as I dont understand what happens in non-sticky behavior. Closing issue
