### ISSUE TITLE
jetty-maven plugin in multi-module project not using files from /target folders of sister projects

### ISSUE THREAD

**Issue by ggruber4711** [eclipse/jetty.project#3202]
I have a big multi-module maven project, with ~80 modules. The webapp project hosts the jetty-maven plugin and running jetty:run works fine, so that the whole app is started up.

Rough Project outline:
+ project root
   + module a
   + module b
   + parent
   + webapp

Webapp depends on on all the modules.  The parent is in a seperate subfolder.

However the class and resource files of the dependent modules **are not loaded directly from the /target directories** of the sister modules, but instead from their built jar files in the local maven repository.

According to the latest documentation I was expecting, that the class files and resources of the depenent modules would be loaded directly from their /target directory.

My current config looks like this
```
<plugin>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-maven-plugin</artifactId>
    <version>9.4.14.v20181114</version>
    <configuration>
        <webAppSourceDirectory>${deploy.dir}</webAppSourceDirectory>
        <webApp>
            <contextPath>/</contextPath>
            <!-- definitions are needed to exlude the scanning of servlet 3.0 annotations on classpath jar files -->
            <webInfIncludeJarPattern>^$</webInfIncludeJarPattern>
            <containerIncludeJarPattern>^$</containerIncludeJarPattern>					  
        </webApp>		
        <useTestScope>true</useTestScope>
        <jvmArgs>-Xmx1280m</jvmArgs>
    </configuration>
</plugin>
```

**Comment by olamy** [comment]
@ggruber4711 we have an integration test for this feature and it seems to pass. do you have any test project to reproduce?

**Comment by ggruber4711** [comment]
Thanks for your feedback from Brisbane (Austria loves Australia :-)

Found out that running `mvn jetty:run` at root of multi-module project works as expected, while running it inside the webapp project does not use the files from the target directory of the dependent modules.

**Comment by olamy** [comment]
no worries mate!
Yes it's the intended behaviour and not other way...
project C (war) depends on project A (jar) and project B (war).
Maven knows A and B as dependencies of C.
Running from top project Maven knows build directories of A and B because Maven just builds it.
Running from C Maven only knows dependencies (i.e installed jar/war of A and B) as Maven just didn't build those projects so it's just dependencies as any others.
In your case I guess A and B are stable and you just want change C so maybe do a quick install from top then debug/run only C
