### ISSUE TITLE
Server can't upgrade from h1 to h2c

### ISSUE THREAD

**Issue by kptfh** [eclipse/jetty.project#3235]
While running [testFeignJava11H2cWithPayload](https://github.com/Playtika/feign-reactive/blob/feature/java11/feign-reactor-benchmarks/src/test/java/reactivefeign/benchmarks/RealParallelRequestBenchmarksTest.java#L57) test using Java 11 http client
get `GOAWAY` frame with `Debugdata: invalid_preface`
Here is how Jetty server configured: [Jetty H2c](https://github.com/Playtika/feign-reactive/blob/feature/java11/feign-reactor-benchmarks/src/main/java/reactivefeign/benchmarks/RealRequestBenchmarks.java#L168)

**Comment by kptfh** [comment]
Figured out that `HTTP2Connection` is trying to parse h1 (Upgrade:h2c) message and throws `java.io.IOException: 1/invalid_preface`

**Comment by kptfh** [comment]
Narrowing scope of issue got that upgade from h1.1 to h2c goes well for GET requests but fails for POST

**Comment by joakime** [comment]
https://tools.ietf.org/html/rfc7540#section-3.2

Looks like the HTTP/2 spec would support methods other then GET.
It is also not recommended to have request body content during the upgrade (as the request body content will block the upgrade and not be performed via HTTP/2).

**Comment by sbordet** [comment]
The HTTP/2 spec delegates to the HTTP/1.1 spec for the upgrade, which does not mandate the use of the GET method.
However, I have never seen an upgrade that is not a GET - not sure we want to support that, especially reading a request content that may never arrive.
@kptfh I would suggest that you change the test - if that's ok you can close this issue.

**Comment by tomakehurst** [comment]
Sorry to do a drive-by on a closed issue, but it looks like the JDK will attempt an upgrade by default on a PUT and with plain text and chunked request body this blows up.

This test illustrates this:
https://github.com/wiremock/wiremock/blob/http2-plaintext-upgrade-problem/src/test/java/com/github/tomakehurst/wiremock/jetty11/Http2AcceptanceTest.java#L70

Not sure whether this is a Jetty or JDK client issue, but since there are many clients that wrap it it'd be good to know if there's a way forward other than disabling HTTP/2 completely on the server.

**Comment by sbordet** [comment]
@tomakehurst can you please open a new issue?

**Comment by tomakehurst** [comment]
Sure: https://github.com/jetty/jetty.project/issues/11588
