### ISSUE TITLE
Make debugging osgi unit tests easier

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#3250]
Currently there is an @Ignored test case in each of the osgi unit test classes which is useful for debugging. To make it easier to debug, we should use a system property to invoke that test behaviour, rather than having to change the @Ignored to @test in the source.

**Comment by joakime** [comment]
Perhaps instead of `@Ignored` or `@Disabled` we use ...

``` java
@EnabledIfSystemProperty(named = "osgi.debug", matches = "true")
```

https://junit.org/junit5/docs/current/user-guide/#writing-tests-conditional-execution-system-properties

We use this currently in 2 places.

https://github.com/eclipse/jetty.project/blob/9b7afd8a0341f4712031abd322ab8669f07f5c5b/jetty-util/src/test/java/org/eclipse/jetty/util/URLEncodedTest.java#L205

and

https://github.com/eclipse/jetty.project/blob/9b7afd8a0341f4712031abd322ab8669f07f5c5b/jetty-webapp/src/test/java/org/eclipse/jetty/webapp/WebInfConfigurationTest.java#L76

**Comment by janbartel** [comment]
Merged.
