### ISSUE TITLE
session not invalidated when using NullSessionCache and HazelcastSessionDataStore

### ISSUE THREAD

**Issue by vivekmalhotragithub** [eclipse/jetty.project#3277]
I am using jetty 9.4.x with Hazelcast 3.11 for session replication. We also used NullSessionCache and disable HouseKeeping since it does not work with it.

We had a scenario where we were invalidating the session by removing it directly from sessionMap in hazelcast. So:
```
IMap.remove(sessionId);
```
However, 
This removes session intermittently since in an ongoing request on the same session org.eclipse.jetty.server.session.SessionHandler#complete(javax.servlet.http.HttpSession) puts the session back into the hazelcast. 

We also tried invalidating the session using 

```
sessionHandler.invalidate(sessionId)
```

But this also does not work because session objects are not shared in case of NullSessionCache and thus session is not invalidated.

This breaks the very purpose of session invalidation in Jetty when using NullSessionCache and Hazelcast.

**Comment by janbartel** [comment]
The behaviour you describe is exactly as expected: because each copy of the session is independent, and you have multiple simultaneous requests for the same session id, then depending on timing you can resurrect an invalidated session.  Why do you want to use the NullSessionCache when you have multiple simultaneous requests, the DefaultSessionCache would be a better solution.

**Comment by janbartel** [comment]
Non sticky sessions are not ideal, full stop.  Particularly if the session is being mutated by requests.  If you don't have a sticky load balancer, then I would move whatever data you're keeping and mutating in the session out into your own storage mechanism that you can safeguard with appropriate ACID transactions.
