### ISSUE TITLE
Some sessions never destroyed with DefaultSessionCache+NullSessionDataStore defaults

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#3284]
From a post to jetty user list:

https://www.eclipse.org/lists/jetty-users/msg08742.html

**Comment by janbartel** [comment]
Some more questions  for the OP:

+ What OS, jvm are you using
+ What are the <session-config> settings in your webapp's web.xml?
+ Do you have many concurrent requests for the same session?
+ Is there any context-forwarding going on in your application?
+ Can you post a (sanitized) reproduction webapp?

**Comment by reini2150** [comment]
> Some more questions for the OP:
> 
> * What OS, jvm are you using
We are using Windows Server 2008 R2 and jdk1.8.0_111

> * What are the  settings in your webapp's web.xml?
<?xml version="1.0" encoding="UTF-8"?>
<web-app version="2.4" xmlns="http://java.sun.com/xml/ns/j2ee"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://java.sun.com/xml/ns/j2ee
http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd">

	<display-name>Web Online</display-name>
	<context-param>
		
		<param-name>tapestry.app-package</param-name>
		<param-value>at.appl.dvo</param-value>
	</context-param>


	<filter>
		<filter-name>healthCheck</filter-name>
		<filter-class>at.iqa.cof.monitor.HealthChecker</filter-class>
	</filter>

	<filter>
		<filter-name>characterEncoding</filter-name>
		<filter-class>at.appl.webutil.common.CharacterEncodingFilter</filter-class>
		<init-param>
			<param-name>charset</param-name>
			<param-value>UTF-8</param-value>
		</init-param>
	</filter>

	<filter>
		<filter-name>openSessionInView</filter-name>
		<filter-class> at.appl.webutil.hibernate.OpenSessionInView</filter-class>
	</filter>

	<filter>
		<filter-name>errorMonitor</filter-name>
		<filter-class>at.appl.monitoring.ErrorMonitor</filter-class>
	</filter>

	<filter>
		<filter-name>performanceMonitor</filter-name>
		<filter-class>at.appl.monitoring.PerformanceMonitor</filter-class>
	</filter>

	<filter>
		<filter-name>urlRemapper</filter-name>
		<filter-class>at.appl.webutil.common.RemappedUrlForwardingFilter</filter-class>
			<init-param>
			<param-name>mappingFile</param-name>
			<param-value>/forwardedExternalUrls.txt</param-value>
		</init-param>
	</filter>

	<filter>
		<filter-name>production</filter-name>
		<filter-class>org.apache.tapestry5.TapestryFilter</filter-class>
	</filter>

	<filter-mapping>
		<filter-name>characterEncoding</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>

	<filter-mapping>
		<filter-name>healthCheck</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>


	<filter-mapping>
		<filter-name>errorMonitor</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>

	<filter-mapping>
		<filter-name>performanceMonitor</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>

	<filter-mapping>
		<filter-name>openSessionInView</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>


	<filter-mapping>
		<filter-name>urlRemapper</filter-name>
		<url-pattern>/*</url-pattern>
		<dispatcher>FORWARD</dispatcher>
		<dispatcher>REQUEST</dispatcher>
	</filter-mapping>

	<filter-mapping>
		<filter-name>production</filter-name>
		<url-pattern>/*</url-pattern>
		<dispatcher>FORWARD</dispatcher>
		<dispatcher>REQUEST</dispatcher>
	</filter-mapping>
</web-app>

> * Do you have many concurrent requests for the same session?
No, I don't think so. There are also hardly any AJAX requests within this app

> * Is there any context-forwarding going on in your application?
Yes, see the filter-mappings of "production" and "urlRemapper"

> * Do you ever programmatically change the idle timeout on a session?
No

> * Can you post a full log trace showing the entire lifecycle of the session that is never deleted?
Attached you can find the "traffic" for 3 sessions. The last one actually got destroyed because
the user tried to use our webapp after session timeout.
[sessions-log.txt](https://github.com/eclipse/jetty.project/files/2787820/sessions-log.txt)

> 
> Finally, and most importantly, can you post a (sanitized) reproduction webapp? I can't seem to reproduce this with our standard test webapp.
I'm working on that.....

We are using NTP on our production servers. But NTP is also used on my local development computer (running on Windows 10) where I'm not able to reproduce the problem a single time.

**Comment by reini2150** [comment]
Pretty sure that NTP is causing this issue. Because after further investigation the problem it only happens for sessions where the corresponding machine is getting a NTP Time synch during the sessions lifetime. The sync sometimes happens only every 2 hours. Session that were created at the beginning of this time period expire normally.

**Comment by reini2150** [comment]
I guess a reproduction webapp is no longer needed, because the problem is all about when NTP synch's occur. But somehow I'm still puzzled that no one has ever reported this issue. Question is, could you guys make the expiry detection more lenient so that small NTP time corrections are no longer a problem?

**Comment by janbartel** [comment]
@reini2150 thanks for the test, good to know it works in your environment. I'll make a PR and get it reviewed, should be in for 9.4.15.

**Comment by reini2150** [comment]
Hi again!
Am I right that this issue didn't make it into the latest release 9.4.15.v20190215?

**Comment by sbordet** [comment]
@reini2150, PR #3296 has been merged so the fix is in 9.4.15.

**Comment by reini2150** [comment]
I was not able to find it  https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.15.v20190215 so I just wanted to get sure. Thank you.

**Comment by joakime** [comment]
@reini2150 the PR was merged as a single commit 169d93e790e69b7d23a2e3b9d5a6a35e6d2b55ce
Which was detected as belonging to "#3296", which is a pull request, not this issue #3284, as the commit message title is missing the critical `"#3284"` syntax the VERSION.txt looks for.
This was an error by the committer that did the merge / commit for this issue.
