### ISSUE TITLE
TLSv1.2/http2 performance during ramp up (after server restart)

### ISSUE THREAD

**Issue by mpfau** [eclipse/jetty.project#3367]
After restarting a jetty server, the most critical aspects is how many tls handshakes can be done per second (when not using tls offload). During this time, tens of or hundreds of thousands of clients try to establish new connections.

During load testing, we noted that much less tls handshakes are done when comparing http2 to http1.1. Using explorative testing, we identified the upper limits (how many handshakes can be done without a large amount of rejections?). Unfortunately, we were only able to do 55% of the handshakes via http2 (in comparison to http1.1).

We also noted, that the problem with h2 becomes even worse, if we try to overload the system under test (e.g. we constantly ask for 100 handshakes if we know that the system is capable of doing 50). This was the result:
![image](https://user-images.githubusercontent.com/227270/52944970-fb7ae600-3370-11e9-8ee9-1281425d2a07.png)
Under overload, we are able to do 37 % with http1.1 and only 11% with h2 in comparison to the max capacity of tls handshakes with http1.1 of the system.

A few more details regarding the test setup:
* all tests were executed on bare metal
* client and SUT machines were on the same LAN (short roundtrip times)
* we used jetty http client for testing with fixed TLS version and cipher suite
* the client created a new connection for each request and we counted the amount of handshakes done

I can share the real numbers privately via mail if you are interested. Just let me know if you need further information!

**Comment by sbordet** [comment]
> the client created a new connection for each request

Are you sure? Because with HTTP/2 this is typically not the case, as requests are multiplexed.

**Comment by sbordet** [comment]
Also, it's not clear what you are doing. If you are just doing TLS handshakes the number should not be different from HTTP/1.1 and HTTP/2.

If instead you are doing HTTP requests (and not only TLS handshakes like you say) then the number may be different but this may be due to other things (e.g. additional roundtrips that HTTP/2 requires, HTTP/2 flow control depending on the request content or response content, etc.).

How do you know it's not the clients that are the bottleneck? 
Meaning you cannot push the clients hard enough and they max out way before the server does.
This is quite common - I typically need 10-20 client hosts each with thousands of clients before the server breaks a sweat.

**Comment by mpfau** [comment]
@sbordet You are right. I am currently doing a handshake and a single request.

For testing, I wrote a simple client based on jetty httpclient. The client creates a new connection for each request. It looks like:
https://gist.github.com/mpfau/9fbcbee56a5911e0f1ff5e83971d5c6c#file-perftestclient-java-L95

During the tests I always maxed out the servers (full cpu load on all cores).

**Comment by mpfau** [comment]
I just found a problem with my tests. Will provide updated reports after I fixed that.

**Comment by mpfau** [comment]
@sbordet Sorry, the above tests were flawed! My bad!

The test client did not invalidate sessions. That is why the above test results not really covered session creation.

After adapting the tests, I couldn't find any meaningful difference between h2 and http1.1. Max tls handshakes were on par for both tests and roughly at 50% of what is possible with haproxy on the same hardware.

I also did a set of overload tests (200% load while 100% is the max that jetty is capable of on this hardware). Jetty performed fine during the tests. What puzzles me is server load remained very high after the test: I overloaded jetty by 200% for 90 seconds. After the test was over, Jetty continued to fully use all CPUs for than 80 seconds.

It seems like jetty was still doing SSL calculations for connections that were closed already. Is that expected?

Just for comparison: haproxy cpu usage drops to zero within seconds after the load test has been finished.

**Comment by sbordet** [comment]
> I overloaded jetty by 200% for 90 seconds. After the test was over, Jetty continued to fully use all CPUs for more than 80 seconds.

That is not expected and should not happen.
Can you please make sure that you're using 9.4.15, and after having stopped the load test - with the CPU still high - can you take a Server dump?
If you can, just call `server.dump()` say 5 seconds after the test finishes; otherwise see how to take a Server dump from JMX  (see instructions [here](https://www.eclipse.org/jetty/documentation/9.4.x/jetty-dump-tool.html)).

**Comment by mpfau** [comment]
I was using 9.4.14 and will upgrade now to see if I can reproduce it with the latest release.

**Comment by mpfau** [comment]
I was able to reproduce with 9.4.15. The dump was created 5-10 seconds after the test was done (all clients were killed). 
[jetty-dump.txt](https://github.com/eclipse/jetty.project/files/2880611/jetty-dump.txt)

**Comment by joakime** [comment]
Ah, JDK 11.0.2. (the JVM that introduced TLS/1.3)
We've encountered some TLS strangeness on JDK 11.x as well.
Please give JDK 12 a try (we don't experience the TLS issues on JDK 12, like we do on JDK 11).
http://jdk.java.net/12/

**Comment by sbordet** [comment]
@mpfau the dump shows that all free Jetty threads are actually busy performing TLS code, and many of them are actually blocked waiting for a lock.
The dump also shows that the Jetty thread pool has ~34K tasks queued, which means that the system is heavily underconfigured (which is expected as this is exactly the test you are performing), especially in light of all this TLS blockage.

I'm guessing that the delay you see in CPU going down is the TLS code finishing up, and draining those 34K tasks in the thread pool.

This again points the finger to a less than optimal TLS implementation in the JDK, while the native implementation in HAProxy is faster.

Have you tried using Jetty with the Conscrypt provider?

And @joakime is right - you should give JDK 12 a try as JDK 11's TLS code is less stable.

**Comment by mpfau** [comment]
Just tried JDK 11, JDK 12 and JDK 1.8. While the problem persists within all tested JDKs, JDK 11 and 12 performed roughly the same regarding the handshake performance. JDK 1.8 was only capable of doing around 45% of the handshakes.

I also did some sampling during the "cool down" after the tests were finished: Nearly two thirds of the CPU time were spent in `java.math.BigInteger.oddModPow ()`. That means that JDKs SSL implementation indeed continues to do RSA calculations for the handshakes of connections that were dropped already...which obviously makes no sense at all and could be very harmful.

I also tested Conscrypt:
* Without overload, I could do around 20% more Handshakes with Conscrypt than with JDK 11 and 12.
* Under overload, only 50% Handshakes were done with Conscrypt which is substantially lower than with JDK 11 and 12.
* The "cool down" took even longer with Conscrypt (nearly 140s) While the CPUs weren't fully exhausted, the Conscrypt implementation spent nearly 60% of its CPU time on `org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct[native] ()`. Seems like the Conscrypt implementation is also doing work for already closed connections...

**Comment by sbordet** [comment]
@mpfau the problem is that we cannot interrupt the threads that do `oddModPow()` - we have to wait that they finish.
Even if we call `Thread.interrupt()`, the JDK code is not checking for the interrupted status and will continue.

All in all I don't think this is a Jetty issue. We always recommended to offload TLS using HAProxy for serious deployments, and your tests confirm that the behavior of HAProxy is better.

I'm inclined to close this issue.

**Comment by mpfau** [comment]
@sbordet sure! This is not a jetty but a JDK issue. I posted a bug report to them...

**Comment by joakime** [comment]
@mpfau once you have a public jdk bug assigned, can you send us a link to it?

**Comment by mpfau** [comment]
@joakime sure!

**Comment by mpfau** [comment]
Just found a similar issue: https://github.com/netty/netty/issues/7020

@normanmaurer implemented a "partial fix" for this with https://github.com/netty/netty/pull/8847.

It would be interesting to know if this would be of any help here. Would it enable cancelling queued SSL connections that are already closed/timed-out?

**Comment by sbordet** [comment]
@mpfau it won't help. Jetty does not have dedicated selector threads, so when a connection is running TLS code, another thread picks up selection.
The problem here is that your test open so many connections that the thread pool will run out of threads. 
Netty moving the execution of the TLS code to an Executor would have the same problem (running out of threads in the Executor).
One a thread runs, there is no way to stop it, unless it collaborates (and it does not collaborate when running the TLS code).
This is worth a JDK bug report. Let us know if you're willing to open it, otherwise we will do it.

**Comment by mpfau** [comment]
@sbordet Thanks for explaining! I understand that those tasks already running can't be stopped. However, all tasks for connections that are queued and already closed/timed-out should never get executed.

I already posted the JDK bug report yesterday.

**Comment by sbordet** [comment]
Can you please report here the JDK bug number when you have it?

**Comment by mpfau** [comment]
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8219617
