### ISSUE TITLE
EOFException Disconnected

### ISSUE THREAD

**Issue by dan335** [eclipse/jetty.project#3386]
I keep seeing this error in the logs.  Can't find any info about it.  Not sure how to reproduce it.  Using version 9.4.15.v20190215.

Why does this happen and can I ignore it?

```
java.io.EOFException: Disconnected  
 	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.disconnect(AbstractWebSocketConnection.java:323)  
 	at org.eclipse.jetty.websocket.common.WebSocketSession.onClosed(WebSocketSession.java:393)  
 	at org.eclipse.jetty.io.AbstractConnection.onClosed(AbstractConnection.java:231)  
 	at org.eclipse.jetty.io.AbstractConnection.onClose(AbstractConnection.java:224)  
 	at org.eclipse.jetty.io.SelectorManager.connectionClosed(SelectorManager.java:345)  
 	at org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint.run(ManagedSelector.java:958)  
 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)  
 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)  
 	at java.base/java.lang.Thread.run(Thread.java:835) 
```

**Comment by sbordet** [comment]
This happens when a connection is being closed.
Is it logged at what level?
Client or server?

**Comment by joakime** [comment]
Have you declared a `@OnError` annotated method on your javax.websocket endpoint?
or `@OnWebSocketError`annotated method on your jetty websocket api endpoint?

**Comment by dan335** [comment]
If it happens when a connection is closed it does not happen every time.  Tonight it appeared 3 times in the logs.  It's coming from the server.

I do have OnError
```
@Override
    public void onWebSocketError(Throwable cause)
    {
        cause.printStackTrace();
    }
```

**Comment by joakime** [comment]
When a WebSocket is closed, the protocol has to perform a handshake.
The local side sends a CLOSE frame, the remote side reads it.
The remote side sends a CLOSE frame, the local side reads it.
If this handshake is interrupted (from say an EOFException on the low level socket), then the stacktrace you see is produced to indicate this.

In that specific stacktrace we can see that the physical connection is being closed, and the local websocket endpoint has gone through its onClose in order to let you know that, however the local endpoint was active, attempting to write content (there was a queue of outgoing frames being processed by the FrameFlusher) and that effort failed, hence the EOFException you see.

The reason you see it printed, is because of your `onWebSocketError` implementation.

**Comment by dan335** [comment]
Thanks for the help.  When I send a message I'm checking if the session is open.  Is there something else I should do or can I just ignore this error?

```
                 if (session.isOpen()) {
                    try {
                        session.getRemote().sendStringByFuture(m.toString());
                    }
                    catch (Throwable e)
                    {
                        e.printStackTrace();
                    }
                }
```

**Comment by joakime** [comment]
`sendStringByFuture(String msg)` enqueues and returns a Future for the status of that particular message.
The enqueued messages will be handled by the FrameFlusher i mentioned before.
When the message has been written, the Future will succeed, otherwise it will fail with the Throwable that caused the failure. (you don't seem to be interested in this detail as you are not using the Future that was returned)

Using session.isOpen() is a granular check, and can be useful to know when NOT to send messages.
However, between you asking isOpen (and getting a true) and then attempting to sendStringByFuture the connection/session could have been closed.

**Comment by dan335** [comment]
Thanks for the explanation.
