### ISSUE TITLE
documentation : maxFormContentSize / start.ini

### ISSUE THREAD

**Issue by mhow2** [eclipse/jetty.project#3388]
in https://www.eclipse.org/jetty/documentation/current/setting-form-size.html in the section "For All Apps in the JVM" it is mentioned : 

> Use the system property org.eclipse.jetty.server.Request.maxFormContentSize. This can be set on the command line or in the start.ini or start.d\server.ini file.

But it's not explained how nor the module that should be enabled. I tried to add the `server` module with `--add-to-start=server` but the resulting ini file doesn't mention the expected configuration directive.

**Comment by joakime** [comment]
All ini files are just a set of command line arguments (one argument per line).

Since the recommendation is to use a system property `-D<key>=<value>` that means you can put it anywhere.

Some options:

1. A new line in your `${jetty.base}/start.ini`
2. A new line in any file in `${jetty.base}/start.d/*.ini` (even a new one!)
3. A command line option `cd /path/to/myjettybase && java -jar /path/to/jetty-home/start.jar -Dorg.eclipse.jetty.server.Request.maxFormContentSize=128000`

> Note: If you are attempting to control multipart forms submitted as `Content-Type: multipart/form` that system property can be overridden by webapp declarations in `WEB-INF/web.xml` and the use of the [`@MultipartConfig`](https://docs.oracle.com/javaee/7/api/javax/servlet/annotation/MultipartConfig.html)

**Comment by mhow2** [comment]
Hi, thanks,

So a new line in `start.ini` containing `-Dorg.eclipse.jetty.server.Request.maxFormContentSize=xxxx` ?
I'm using a setup with `jetty.sh` that reads `/etc/default/jetty` so I guess I should put it here. Why not mentioning this ? I know it depends on the setup but it would help (at least it would help me ;) ) to provide directions like explaining very briefly "why start.ini vs /etc/default/jetty"

Another thing, in the same documentation page for "For All Apps on a Server", there is a example XML snippet but there is no mention of which configuration file it is about ?

**Comment by WalkerWatch** [comment]
@mhow2 I've made a few updates to the documentation. As for your question about start.ini vs pointing at the directory, well, that is another discussion.

I'd actually rather you point at a [Jetty Base](https://www.eclipse.org/jetty/documentation/current/startup-base-and-home.html) directory and not modify anything in the core set of the distribution. 

I am unsure how familiar you are with the concept but essentially the idea is to keep Jetty_Home (those core files that come with the distribution, sans the demo-base, readme...etc.) as a standard of truth and then creating another directory either within the Jetty_Home or somewhere else as the location for your webapps, static files, modified modules/XMLs, extra libraries, logs...etc.

Even if you are running just one server, this can be helpful. Upgrades are as easy as dropping in the new distribution over your old one or simply pointing your base to the new Jetty_Home,

If I've missed the point of the question entirely, I'd recommend using ini files over editing the XML files because it is easier and there are less chance of mistakes. Also, the upgrade stuff I mentioned above.

**Comment by mhow2** [comment]
bq. If I've missed the point of the question entirely
Yes, but it's not a problem. Thank you for having answered and updated the documentation.
I'll post to the mailing list to discuss the issue I'm having with start.ini and FormContent/FormKey system values
