### ISSUE TITLE
Reflect setAccessible is deprecated in Java 9+

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3396]
There are a few classes in Jetty 10.0.x that use the various `isAccessible()` and `setAccessible()` features of reflection.
These concepts are deprecated and will not work in the future.

We should migrate away from these soon.

https://github.com/eclipse/jetty.project/blob/3a7dee0e189b34419c5243dd6a918c2fd03c4257/jetty-plus/src/main/java/org/eclipse/jetty/plus/annotation/LifeCycleCallback.java#L115-L118

https://github.com/eclipse/jetty.project/blob/3a7dee0e189b34419c5243dd6a918c2fd03c4257/jetty-plus/src/main/java/org/eclipse/jetty/plus/annotation/Injection.java#L205-L212

https://github.com/eclipse/jetty.project/blob/3a7dee0e189b34419c5243dd6a918c2fd03c4257/jetty-plus/src/main/java/org/eclipse/jetty/plus/annotation/Injection.java#L226-L233

https://github.com/eclipse/jetty.project/blob/3a7dee0e189b34419c5243dd6a918c2fd03c4257/jetty-alpn/jetty-alpn-conscrypt-client/src/main/java/org/eclipse/jetty/alpn/conscrypt/client/ConscryptClientALPNProcessor.java#L58-L63

https://github.com/eclipse/jetty.project/blob/3a7dee0e189b34419c5243dd6a918c2fd03c4257/jetty-alpn/jetty-alpn-conscrypt-client/src/main/java/org/eclipse/jetty/alpn/conscrypt/client/ConscryptClientALPNProcessor.java#L90-L96

https://github.com/eclipse/jetty.project/blob/3a7dee0e189b34419c5243dd6a918c2fd03c4257/jetty-alpn/jetty-alpn-conscrypt-server/src/main/java/org/eclipse/jetty/alpn/conscrypt/server/ConscryptServerALPNProcessor.java#L59-L64

https://github.com/eclipse/jetty.project/blob/3a7dee0e189b34419c5243dd6a918c2fd03c4257/jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/utils/internal/DefaultFileLocatorHelper.java#L121-L122

**Comment by joakime** [comment]
There are several dozen violations in jetty-osgi, far more then highlighted above.

**Comment by olamy** [comment]
does it makes sense to have a unique way to do it with a method in jetty-utils?

**Comment by sbordet** [comment]
@olamy I don't think making a utility method solves the issue.

For Conscrypt, we can ask to make those methods public if they are not already, so we can use reflection but avoid `setAccessible()`.
Similar for the other cases.
`Injection` really needs to do private reflection, so relevant modules should be opened, and I would prefer to open to JPMS module `o.e.j.annotation` rather than `o.e.j.util`.
Can you please revert your change?

**Comment by olamy** [comment]
@sbordet all conscrypt classes are package private so ATM we cannot cast and use the methods (which are package private as well) 
I will create an issue and submit pr..

**Comment by sbordet** [comment]
@joakime where it is written that `setAccessible()` is deprecated? I cannot find any reference.
I agree that we should avoid it if possible, but I can live with it.

**Comment by joakime** [comment]
@sbordet the warnings you get from the JVM tell you, usually in the form of `Illegal reflective access by <class>`
Then there's the variety presented by JPMS too `Unable to make {member} accessible: module {A} does not 'opens {package}' to {B}`

**Comment by sbordet** [comment]
@joakime 

the first is when we access private JDK class members and we should not do that (except in the preventers).

the second is normal and won't change if we use methods handles instead of reflection; we need to ask to module A maintainers to make the API public instead (e.g. Conscrypt).

Given that @olamy has taken care of the second for Conscrypt, is there anything else we need to do?

**Comment by joakime** [comment]
The jetty-plus ones would be open ended (jetty-plus needs to access webapp classes? server classes?), and the OSGi ones haven't been addressed/talked about (there are many uses of setAccessible there).

**Comment by sbordet** [comment]
Injection of instances to satisfy the Servlet annotation requirements will be done by a Jetty module to a class in an unnamed module (because the webapp classloader produces an unnamed module).
An unnamed module is open to all other modules, so we should be good.

**Comment by olamy** [comment]
conscrypt side issue https://github.com/google/conscrypt/issues/632 pr https://github.com/google/conscrypt/pull/633

**Comment by olamy** [comment]
finally Conscrypt is not a problem anymore. They were provided some methods to help configuring sslengine

**Comment by sbordet** [comment]
@olamy we should update the Conscrypt version to the latest and also update our code to use their public APIs.

**Comment by olamy** [comment]
@sbordet done in the branch. but I guess we could do it in 9.4.x? better create an other issue and other branch for conscrypt effort?

**Comment by sbordet** [comment]
What branch? This should be a 9.4.x change and then merged to 10.0.x.

Open a new issue and PR for the Conscrypt changes only.

**Comment by olamy** [comment]
I started working on it in a branch called  jetty-10.0.x_rid_of_set_accessible (the description was mentioning jetty 10 so the branch based on 10.x) but makes sense to do it in 9.4.x
I will get rid of this branch and do the conscrypt changes in 9.4.x

**Comment by janbartel** [comment]
The references in the osgi stuff is some swizzling that needs to be done in order to access the actual file location of a bundle on disk:  every osgi framework implements it a different way. I can't see that they would ever change the api in osgi to allow this. I don't think there's another way to do this, other can call setAccessible - if you can think of another way to do it, please go ahead.
