### ISSUE TITLE
jetty-distribution depends on test-jetty-webapp:war and test-proxy-webapp:war

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#343]
The jetty distribution pom.xml depends on test-jetty-webapp:war and test-proxy-webapp:war, which are expanded by the dependency plugin into the demo base.

However, these artifacts are not actually published to maven-central, at least not since 9.0.0!

So it is strange that they are not published? why not?

I also think it is wrong that the jetty-distribution lists them and other jetty modules as dependencies.  The jetty-distribution expands its dependencies, so it should not advertise them as transitive dependencies... maybe it should list all dependencies as provided?

**Comment by gregw** [comment]
@jmcc0nn3ll I opened this after our IRC discussion.  Assigned to @joakime as he will probably know what is going on.

**Comment by joakime** [comment]
Just linking some relevant bits:
- [test-jetty-webapp:war is a dependency](https://github.com/eclipse/jetty.project/blob/jetty-9.3.7.v20160115/jetty-distribution/pom.xml#L631-L636)
- [test-proxy-webapp:war is a dependency](https://github.com/eclipse/jetty.project/blob/jetty-9.3.7.v20160115/jetty-distribution/pom.xml#L637-L642)

Not being deployed because of [tests/test-webapps/pom.xml](https://github.com/eclipse/jetty.project/blob/jetty-9.3.7.v20160115/tests/test-webapps/pom.xml#L37-L38)

The deploy of those wars does not happen because of the `<deploy>false</deploy>` introduced in commit 971115a00a7a67268b8fa29fb8a129487d121a17 (Oct 2011).

Last version to be deployed was jetty-9.0.0.M2 (it stopped appearing in [jetty-9.0.0.M3](https://github.com/eclipse/jetty.project/compare/jetty-9.0.0.M2...jetty-9.0.0.M3)) 

The f21b74dcb1184da2cd2a64a5defdd543d99f51e7 commit (Nov 2012) is the specific point when those 2 war files stopped being deployed as a result of moving the module (`test-jetty-webapp/pom.xml → tests/test-webapps/`)

**Comment by jmcc0nn3ll** [comment]
I bet we trimmed that because we simply saw no value for those artifacts being distributed outside of the distribution itself.

**Comment by gregw** [comment]
OK, so we know why they are not distributed.   We should now fix the transient dependency.... once that is done, we can ask if they should be distributed - I can see that either way.... they are always available from the distro if somebody really wants them.

**Comment by joakime** [comment]
Fixed
