### ISSUE TITLE
Jetty uber jar does NOT contain jetty-jaas

### ISSUE THREAD

**Issue by garydgregory** [eclipse/jetty.project#3437]
Jetty `jetty-all` uber jar does NOT contain code from the `jetty-jaas` module.

**Comment by joakime** [comment]
You are correct.
This will likely not be fixed.

**:warning: : It is inappropriate to use the single artifact `jetty-all` or `jetty-all-uber` in any project as a dependency.**

It is, however, fine to use the `jetty-all` pom to include all of the dependencies properly (or better yet, use the `jetty-bom` pom).

The role of `jetty-all` is for use as a tutorial / introduction to Jetty basics as outlined in the Jetty documentation. ( see Issue #1511 )
The `jetty-all` artifact is historical, it once did actually contain all of jetty, but that was around Jetty 6.x, and hasn't been true since.
Starting in Jetty 7.x we had conflicting implementations of the same classes and we could no longer have "all" of jetty in a single `jetty-all` artifact.
When [Jetty 9.x hit](https://www.eclipse.org/lists/jetty-users/msg06030.html) (and again when Java 9 got released) this truth of `jetty-all` became more pronounced.

If you have special needs, then consider building your own `jetty-all` jar with what you need in it.   
Be careful and mindful of JEP238 behaviors, JDK9+ behaviors, service loader requirements, and do not overlay jars with conflicting implementations).

**Comment by garydgregory** [comment]
Thank you for the detailed reply, very helpful! :-)
