### ISSUE TITLE
Stop server if Unavailable thrown

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#3440]
If a context has `setThrowUnavailableOnStartupException(true)`, then a call to server.start() may throw, leaving some components STARTED, some FAILED and some STOPPED.  This can stop the JVM existing if some of these components have non daemon threads running.

If startup fails, the server should be in a state that allows the JVM to exit cleanly.

**Comment by sbordet** [comment]
@gregw I'm not sure I understand the problem here.

If a component is STOPPED, then its schedulers/executors are stopped - there should be no problem.
If a component is FAILED, then we should arrange to call `doStop()` or similar from `AbstractLifeCycle`.

If we do the above, we don't need daemon threads at all, and I think it'll be a more robust solution than just making threads daemon.

Also, I'm not sure I understand why `Server.start()` must throw if one of the context fails to startup.
In a running server, if I hot deploy a new context that cannot be started, you don't stop the Server.
In a starting Server, a context that fails to start should not stop the other contexts to start, and should not stop the server to start.

**Comment by gregw** [comment]
@sbordet we have an option on WebAppContext to control if it throws if a webapp fails to start, or if it starts anyway with the context just in unavailable state (and returning 503s for all requests).
So sure, for hot deploy you don't fail the server if the context fails.  But for things like docker, where you have only 1 webapp bundled with the server, you want the image to stop if the webapp fails (specially as running instances often costs money).  Hence we have `setThrowUnavailableOnStartupException(true)`

Now when running in that mode, we can have the situation where with the following main:
```java
  public static void main(String... args) throws Exception
  {
      Server server = new Server();
      // ... configure server here
      server.start();
      server.join();
   }
```
if `server.start()` throws the exception is not caught and main exits.  But we have a half started, half failed server, with non daemon schedulers and thread pools started etc.   So the JVM just hangs waiting for those threads to die.   We now have a dead docker image, costing us money, but that doesn't even serve a 503!     It should be the case that if an exception thrown from `server.start()` causes main the exit, then the JVM can also exit.

I don't recall any problems with non-daemon schedulers?   Even if we did, hanging JVMs is a costly and bad way to detect such errors.  Thread dumps are much simpler way to identify any schedulers left over after a stop and this PR names the schedulers so they are easy to identify their source if they are not correctly stopped by a stop.

Note that this PR also does `server.doStop()`, which should be sufficient, but having daemon schedulers is defence in depth.

**Comment by sbordet** [comment]
If you know you want to exit the JVM, why you don't just:

```java
public static void main(String... args) throws Exception {
  try {
    Server server = new Server();
    // ... configure server here
    server.start();
    server.join();
  } catch (Throwable x) {
    System.exit(1);
  }
}
```

I don't see the point of making these changes for a very specific, single, use case that can be solved with a `System.exit()`.

I don't buy the "make all daemons" so that the JVM can exit when it's just how you have coded your main class.
We have a gazillion other components, possibly even written by others, that may use non-daemon threads and be part of the `Server` component tree.
What if a JDK `Executor`, not configured as daemon, is used to replace our default `QueuedThreadPool`?

This is not "defense in depth", it's just "let's hope making some daemon here and there works out" - it won't.

**Comment by gregw** [comment]
System.exit is ugly and requires user action. A failed server should not prevent JVM from exiting, so yes we need to call doStop. This PR does that, but I'll look to see if I can make it more general.

However, I don't understand your point on daemon threads? why should a running scheduler prevent the JVM from exiting? Other than that being the default?  I see little reason why arbitrary threads should hold JVM!

**Comment by sbordet** [comment]
@gregw my point of daemon threads is that they just hide a broken lifecycle. 
From your reasoning, also executors should be daemon, and also any thread created by components that may be added to the component tree, and so we should ban any thread that is non-daemon.
It's just the wrong solution and won't fix the problem in general.
How do you prevent a user-created thread in a Servlet at startup from holding the JVM?

**Comment by gregw** [comment]
Sure there are problems with user-created threads holding the JVM... but we are not responsible for creating them.   We are responsible for creating scheduler threads and thus we have a decision to make - do we wish arbitrary schedulers that we create as side effects in various components to be sufficient to hold up a JVM?  I don't see why, nor do I see why we should treat that as bug detection - we should detect and fix resource leaks by checking for resource leaks, not by hoping that some of them have noticeable side effects.

For ThreadPool, it is less clear, as we can run a server fine without a main thread but with a working ThreadPool,  however perhaps any ThreadPools we create in components should be daemon. 

Anyway - I think it should be changed, but I'll revert to non-daemon for now as we need this PR to progress.  We can discuss separately.

**Comment by joakime** [comment]
Merged. closing issue.
