### ISSUE TITLE
HttpClient with deferred content can result in EOF exceptions

### ISSUE THREAD

**Issue by LG987234122** [eclipse/jetty.project#3450]
Jetty appears to have issue with high volumes of client requests using deferred streaming content.

Attached test uses a repeating ping/pong message from client to server and back. First 100 iterations uses direct content which always seems to be ok. Second set of 100 iterations uses deferred content used from client, the test fails after around 50 iterations. This is shown in the output.txt file also attached.

Tests run using 

- Jetty 9.4.14

- Microsoft  Windows 7 [Version 6.1.7601]

- openjdk version "1.8.0_192"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_192-b12)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.192-b12, mixed mode)

[issue.zip](https://github.com/eclipse/jetty.project/files/2952808/issue.zip)

**Comment by joakime** [comment]
Took code and made it a maven project at https://github.com/jetty-project/issue-3450-httpclient-deferred-content

**Comment by joakime** [comment]
@LG987234122 does not occur on Jetty 9.4.15.v20190215 / OpenJDK 8u202  (Note: [Java 8u192 expired on Feb 15, 2019](https://www.oracle.com/technetwork/java/javase/8u192-relnotes-4479409.html))

I went ahead and [simplified your testcase](https://github.com/jetty-project/issue-3450-httpclient-deferred-content/tree/simplified) at https://github.com/jetty-project/issue-3450-httpclient-deferred-content/blob/simplified/src/main/java/org/eclipse/jetty/issues/JettyBug.java
Diff at commit https://github.com/jetty-project/issue-3450-httpclient-deferred-content/commit/1975184338001a2fe64ba38ce5a857e8b52041ff

Since the report is about deferred streaming content (and not the specifics of what stream implementation is used), I simplified it to use only inputstream/outputstream.

**Comment by joakime** [comment]
Possible reason for your issue.

When you use deferred content send, your request body content becomes Chunked.
Which means you are in a streaming mode.

Your use of 

``` java
            final DataInputStream dataIn = new DataInputStream(servletRequest.getInputStream());
            final int size = dataIn.readInt();
            final byte[] bytes = new byte[size];

            dataIn.readFully(bytes);
            dataIn.close();
```

... does not read fully from the request body content.
You didn't read to the -1 EOF indicator on the chunked content.
That means the request body content isn't finished being read.

Your debug output indicates this as well ...

2019-03-11 11:50:37.559:DBUG:oejs.HttpConnection:qtp1717159510-18: Possible unconsumed input HttpConnection@11e0022c::SocketChannelEndPoint@576ca446{/127.0.0.1:51711<->/127.0.0.1:8080,OPEN,fill=-,flush=-,to=0/30000}{io=0/0,kio=0,kro=1}->HttpConnection@11e0022c[p=HttpParser{s=CHUNK,1115 of -1},g=HttpGenerator@25114a3b{s=END}]=>HttpChannelOverHttp@2bd6a0e9{r=100,c=true,c=true/true,a=COMPLETED,uri=//localhost:8080/,age=3}
2

The persistent connection you have for this HTTP/1.1 connection is now in a bad state.
If you are using Chunked transfer-encoding you must read the ENTIRE stream, meaning up to -1.

**Comment by joakime** [comment]
The reason the simplified version doesn't show an issue, is because that simplified code actually reads the entire inputstream up to -1 EOF.

**Comment by sbordet** [comment]
@gregw the code pattern is "wrong" because it does not read -1, but it's annoying that we choke on the server only when chunked.
What about `HttpInput.close()` reading the -1 on behalf of the application?

**Comment by LG987234122** [comment]
Thanks for the assistance - correcting the code pattern to consume the -1 EOF and it's all working.

Thanks again

**Comment by joakime** [comment]
@LG987234122 you could alternatively throw an error if there's actually content after what you expect there to be.
