### ISSUE TITLE
Cannot receive FIN packet on browser cancel 

### ISSUE THREAD

**Issue by artmdv** [eclipse/jetty.project#3473]
Hi,
We are hosting our API using jetty and have long running and heavy requests in the background (can take over 20s easily), and during high load situations users keep refreshing page or stopping requests, this creates situation where we get even more heavy requests and they start responding even slower. In C#, when browser cancels request, we receive CancellationToken and can issue operation abort down to database, to save resources/computing power for other requests that are waiting. From our understanding, in C# this is achieved by reading input stream and seeing if FIN packet is sent. In Jetty we are always receiving "-1" when reading input stream no matter what. Using Jetty, Wireshark shows that our service responds with "ACK" right after "FIN" packet is dispatched to it. So how can we know that user initiated request cancel in jetty?

Any help would be appreciated :)

**Comment by joakime** [comment]
Reading -1 from the input stream means only that the input stream on that specific request is at EOF.
The connection for that request could be still valid, or disconnected, you cannot tell from the inputStream by reading a EOF (-1).
You could tell by attempting a write on the response.outputStream on the other hand.
Another choice might be to use the Servlet 3.1 Async I/O features.   Both the ReadListener and WriteListener have an `onError()` event that will report failure on read/write.

But if you really just want to know about the connection, you could hook into the Connection via a Connection.Listener to detect the `onClose()`, bu that would be a Jetty specific API, not something supported by the Servlet API.
The next step would be some custom code to cancel the database request and other resources you want to terminate.

**Comment by artmdv** [comment]
We have tried writing, but that means the end user will receive all the "trash" that was written to outputstream if he hasn't cancelled the request :) 

Our intended flow is like this (and it works on C#/.net):
1. user initiates request 
2. server reads request (request is fully read)
3. server initiates heavy database operation
4. user initiates request cancellation
5. server is aware about cancelled request (without writing "trash" to output stream)
5. server cancels database operation (we already have this)

Would the connection.listener onClose() return us info that request was cancelled without the need to explicitly write to output stream? (or user getting "trash" if he hasnt cancelled the request)

**Comment by sbordet** [comment]
There is no standard way to "initiate request cancellation" from browsers. C#/.Net may have had their proprietary way to do it, but there is nothing standardized.

Which means that you just have to implement this in your application.
Save the request ID for your long request, send back a page with a "Cancel" button which will send another request to the server with the request ID to cancel.

Done in this way will be portable in any technology.

If the tab/browser is closed the browser may send the FIN to the server, but you won't be able to detect that from the application.
The reason is that per Servlet specification we don't read past the end of the request content.

This is partially possible with HTTP/2 since the client will send a `RST_STREAM` frame to the server, but while this event is handled by Jetty, there is no standard API to surface this event to applications.

If the user is gone, let your DB query to run and when it's done it's done; you will write the result and probably get an `IOException` because the connection is closed.
If the user is not gone and frantically clicks on your UI to get the result - causing instead more DB queries - then fix your UI: don't allow the user to click on anything else than a "cancel" button that behaves like described above.

**Comment by gregw** [comment]
@sbordet when you say " is no standard API to surface this event to applications", that is only true for blocking.   I thought we can deliver the closed exception from http2 via the asyncListener onError method?

Another possibility is writing [102 Processing](https://httpstatuses.com/102) responses with `response.sendError(102)`.  This a from the WebDAV standard and indicates the server is still working on the response, while testing the connection and keeping it alive from idle timeouts.  You'll have to test if your client can handle that response code.

Yet another possibility is that the client sends another request to inform the server of the cancel, using cookie/session/token to identify which request is no longer being waited for.

Closing for now, because nothing much more that Jetty can do given the limitations of TCP/IP and current standards.

**Comment by joakime** [comment]
@artmdv in case you want to play with it, here's a demo of the Connection.Listener stuff ...

https://gist.github.com/joakime/38a702d5b34eb2fafac6a2e53f721b8e

**Comment by artmdv** [comment]
@sbordet Well, it's not a "proprietary" way, just "FIN" package read from TCP input stream is treated as request cancellation. Apparently .net core currently has an open issue about this as well: https://github.com/aspnet/AspNetCoreModule/issues/38

Is there a way to handle "FIN" packages in jetty/servlet ourselves? any way to inject/override into somewhere? Maybe there is a place in code we could change and create a fork so it would work for us?

**Comment by sbordet** [comment]
@artmdv there is currently no way to handle TCP FIN in Jetty server. During the processing of a request, when the request content has been fully read, we don't go back reading from the network (we are not even read interested from the NIO point of view).

Also, there are clients that send the request, perhaps with a `Connection: close` header and immediately shutdown their output so the server receives the FIN. However, that is not an indication that the request should be aborted.

The only solution, as we explained, is to do it at the application level: your client must send another request to the server to cancel the previous one.
