### ISSUE TITLE
Jetty WebSocket Session.suspend() issues in 9.4.x

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#3498]
`Session.suspend()` in jetty-9.4.x does not seem to be implemented correctly

I have written a new test for this intended to test the implementation in jetty-10.0.x for #3382, however this test also fails in jetty-9.4.x even though this is supposed to be implemented and tested in `SuspendResumeTest`

**Comment by lachlan-roberts** [comment]
@joakime can you take a look at why this test is failing

**Comment by lachlan-roberts** [comment]
I figured out why it was failing. We cannot cancel demand once a frame has been demanded, so if `suspend()` is called we will still receive the very next frame, if this is taken into account for the test then it does pass.

I think this behaviour should be documented in the javadoc for suspend

**Comment by sbordet** [comment]
@lachlan-roberts the new behavior is wrong though. If I call `suspend()` I don't mean suspend after a message. I really mean suspend now.

> We cannot cancel demand once a frame has been demanded

If the frame has not arrived yet, we should be able to cancel the demand, that is exactly what `suspend()` is for.

The test, how it was _before_ 13de54c4edb9c4896912dd2479e12b86a36e9a7e, was testing the right behavior. 
So rather than changing the test to match the implementation, the implementation should be changed to match the test.

**Comment by lachlan-roberts** [comment]
@gregw was saying that it is practically impossible to cancel the demand of a frame after it has been demanded

**Comment by sbordet** [comment]
@lachlan-roberts well, I would need details about "impossible". The demand is an `int` so does not seem impossible to decrease it by 1.

**Comment by gregw** [comment]
@sbordet see discussions in #3382 ... but the issue is not decrementing the int, the problem is stopping all the asynchronous mechanism that are started when the int transitions from 0 to non-zero.  Once started, those mechanism cannot be atomically stopped.

**Comment by sbordet** [comment]
@gregw I would need to look again at core, but this semantic _must_ be supported in a reactivestreams implementation.

It would be better if we don't have to buffer in an upper layer, but just tell core to stop feeding the upper layer until the upper layer demands.

We have done this so many times in `HttpClient`, the server, etc. that I don't see what could possibly be so different in WebSocket.

**Comment by lachlan-roberts** [comment]
so is it okay for jetty-9.4.x to stay with its current behaviour where the next frame after calling suspend will always be delivered unless you were processing a frame, or should onFrame be delayed until after resume has been called like it is in the jetty-10.0.x implementation

**Comment by gregw** [comment]
@sbordet I think I'm answering an old comment of yours.... but just to be sure.... and to deal with the latest commit as well.

The correct reactive style semantic is well supported in core.
The problem is only in Jetty API which starts with an implicit `demand(1)`  outstanding and a `suspend()` call is effectively a `demand(-1)`, which is intrinsically a race if called outside of the scope of a frame handler (where we are `demand(0)` and `suspend()` is implemented by NOT doing a `demand(1)`

@lachlan-roberts latest code does buffer a single message in the API layer, but only to reduce the size of the window in which 1 frame can be delivered after a call  to `suspend()`.  I'm dubious about it's value as any code that calls `suspend()` outside of the scope of a frame handler has to be prepared to accept +1 frame... and a nano second later or 20 seconds later doesn't really change that much.   So we could remove the single frame buffer from the jetty API and essentially get the same semantic:  calling `suspend()` from a message handler works as expected; calling `suspend()` from another thread will work, but 1 frame may be delivered after the call to `suspend()`.

I'm not 100% convinced we need that 1 frame buffer and I'll comment inline more about that....

**Comment by lachlan-roberts** [comment]
WebSocket Session.suspend() has now been updated with #3637 to suspend incoming websocket frames instead of only suspending connection reads.
