### ISSUE TITLE
is it intentional that failed requests are retried?

### ISSUE THREAD

**Issue by rsslldnphy** [eclipse/jetty.project#3541]
A change of `jetty-server` dependency  from `9.2.24.v20180105` to `9.4.12.v20180830` in the Clojure library `ring` appears to have changed the behaviour around unhandled exceptions - since the dependency upgrade, when a handler throws an unhandled exception, the handler is *called a second time*.

Is this intentional on jetty's part or is it a bug?

We ran into the issue with an endpoint that sends an email and then accidentally returns an unserializable response - since the dependency update, the email is sent twice every time the endpoint is called.

Have created a [simple repo that reproduces the issue](https://github.com/HealthUnlocked/ring-issue) (in clojure, unfortunately, we're not java devs) and raised the issue on the `ring` github as well: https://github.com/ring-clojure/ring/issues/364.

**Comment by sbordet** [comment]
> when a handler throws an unhandled exception, the handler is called a second time.

It's intentional. The second time we are calling it with `DispatcherType=ERROR` to generate an error page.
It was a bug in previous Jetty versions.

You want to look at `AbstractHandler.ErrorDispatchHandler` and use that class as the basis for your handlers, rather than `AbstractHandler`.
Or use the same logic there in your Clojure implementation.

**Comment by joakime** [comment]
Link to `ErrorDispatchHandler` that @sbordet mentioned ...

https://github.com/eclipse/jetty.project/blob/jetty-9.4.15.v20190215/jetty-server/src/main/java/org/eclipse/jetty/server/handler/AbstractHandler.java#L159

**Comment by rsslldnphy** [comment]
Thanks @sbordet and @joakime !
