### ISSUE TITLE
Provide way to allow sharing of HttpClient within javax.websocket client

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3649]
There's a few use cases.

1. Embedded Jetty user setting up the `HttpClient` (with custom SSL) and accessing the javax.websocket client from [`ContainerProvider.getWebSocketContainer()`](https://docs.oracle.com/javaee/7/api/javax/websocket/ContainerProvider.html#getWebSocketContainer--), where the HttpClient they created should be used by the `javax.websocket.WebSocketContainer` too. 
2. An admin on a standalone container (`jetty-home`) with multiple WebApps deployed using `javax.websocket.WebSocketContainer` that need a common `HttpClient` configuration for SSL and ThreadPool reasons.
3. A simple single WebApp scenario where they are sharing an `HttpClient` for `javax.websocket.WebSocketContainer`, and normal http client usage in their app, along with usage of an `AsyncProxyServlet`.

**Comment by joakime** [comment]
@sbordet any solution we come up with should be able to be used by other components in Jetty that need an `HttpClient` too (eg `AsyncProxyServlet`), right?

**Comment by sbordet** [comment]
@joakime nope.

The JSR WebSocket client is the only one that needs tricks.
Jetty components are injectable with the right dependencies, so no need for tricks.

**Comment by lachlan-roberts** [comment]
you can currently provide a custom `HttpClient` to the JSR WebSocket client through the `XmlBasedHttpClientProvider` but I don't think there is any way to supply one programmatically

**Comment by gregw** [comment]
@lachlan-roberts I think this is done now?  at least optionally, as the issues we had recently indicate that their may be classloader issues that prevent sharing of HttpClient.
Can you comment, link to any related issues and then close.

**Comment by lachlan-roberts** [comment]
@gregw we have ways of sharing the `HttpClient`, but for `ContainerProvider.getWebSocketContainer()` there is no way to use a shared `HttpClient` without using a dependency to the Jetty implementation of the `ContainerProvider`.

When you call `ContainerProvider.getWebSocketContainer()` we will create a new websocket client each time this is called, this does not share its `HttpClient` and it does not return the `ServerContainer` if found (which is also a client). The settings of the `HttpClient` created can be configured through the `jetty-websocket-httpclient.xml` file.

Instead of using the `javax.websocket.ContainerProvider` you can directly use the Jetty implementation of this directly and provide an `HttpClient` to the static method `JavaxWebSocketClientContainerProvider.getContainer(httpClient)`.

Then we have the `JavaxWebSocketServerContainer` which also needs an `HttpClient` because it extends the client container. This will lazily create the `HttpClient` only when it is first needed. Before creating an `HttpClient` it first searches for one as a `ServletContext` attribute, then as an attribute on the server.

**Comment by gregw** [comment]
@lachlan-roberts so you are saying: "yeah this can be closed"?

**Comment by lachlan-roberts** [comment]
I was just describing the current state in Jetty-10. But sure, if this sounds okay to you then we can close this issue.
