### ISSUE TITLE
websocket close timeout

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#3671]
there should be some sort of close timeout which will ensure the connection is eventually closed if `Session.close()` is called

say the server attempts to close the websocket connection by sending a websocket close frame with a normal status
the client could ignore the close frame and keep sending data frames which will be processed by the server, and as long as the data frames are sent regularly enough to not trigger the idle timeout the connection will never close

```java
@Test
public void testServerCloseClientIgnores() throws Exception
{
    container.setIdleTimeout(Duration.ofMillis(idleTimeout));

    URI uri = new URI("ws://localhost:8080");
    EventSocket clientSocket = new EventSocket();
    client.connect(clientSocket, uri).get(5, TimeUnit.SECONDS);

    // suspend the client so that no frames received, then close on the server
    clientSocket.session.suspend();
    serverSocket.session.close();

    // periodically send messages from the client waiting half the idle timeout each time
    while (true)
    {
        clientSocket.session.getRemote().sendString("keep-alive");
        String message = serverSocket.messageQueue.poll(5, TimeUnit.SECONDS);
        assertThat(message, is("keep-alive"));
        Thread.sleep(idleTimeout/2);
    }
}
```
this test demonstrates the issue, the server calls `Session.close()` but the connection is never closed and this loop goes on indefinitely

**Comment by sbordet** [comment]
@lachlan-roberts I think the current behavior is what we want.
If the server really wants to close the connection, it will send the close frame and then perform a hard TCP close.
Not sure there are APIs to do that in JSR 356, but there should be APIs in the Jetty WebSocket APIs.

**Comment by gregw** [comment]
Having a half closed connection can be normal

**Comment by IlyaZu** [comment]
> If the server really wants to close the connection, it will send the close frame and then perform a hard TCP close.

But what if the server wants to give the client a bit of time to do its thing - but not too long. This is currently doable but not terribly clean. 
See [here](https://github.com/eclipse/jetty.project/issues/3666#issuecomment-493414074) for an example of when something like this might be useful.

> Having a half closed connection can be normal

It can be normal but it's not necessarily desirable.

**Comment by gregw** [comment]
@IlyaZu I think #3666 can be better resolved without resorting to a timeout.
@lachlan-roberts perhaps this is a reasonable thing to include in an @extension - something that imposes a half closed timeout, but would not be a penalty for those who don't want it.

**Comment by sbordet** [comment]
I think it's overkill to have an additional timeout, even in the form of an extension.
You will have then to handles cases where the idle timeout is smaller than this extension timeout, and when the 2 are equal and they race.

> But what if the server wants to give the client a bit of time to do its thing - but not too long.

The problem is that the server does not know how long is "too long".
It can be connected with a fast client so 10 seconds is really long.
OTOH it can be connected with a very slow client, so 10 seconds is now short.

Idle timeout is IMHO the right semantic: independent from the client (sorry slow ones), simple and clear: send the close frame, I'm willing to wait the idle timeout before hard closing.
Otherwise, applications can implement their own logic: send close frame, start a scheduled task, when it fires call `disconnect()/abort()`.

About the attack surface (a client that sends frames at a regular interval without closing) I would rather see something like the `minDataRate` - perhaps only applied after one peer has locally closed.

**Comment by IlyaZu** [comment]
@gregw @sbordet 

Having given it some more thought: 

> The problem is that the server does not know how long is "too long".

I don't think that's the problem I'm seeing. I *want* a client to get hard disconnected if it's taking longer than X (whatever X is). 

The problem is (for my application, at least) that a timeout of Y is good under "normal" conditions but is too long when I'm waiting on a close response. 

> Otherwise, applications can implement their own logic

I could manually set session timeout/schedule a hard disconnect every time I call `session.close()` but a) that seems hard to enforce and b) I'm not sure if that will catch all cases when a close frame is sent (i.e. Jetty sends a close frame if it receives a very large message "automatically" - I don't have an option for setting that timeout). I could also enforce a shorter timeout for everything but that's not ideal for a other reasons IMHO.

A single place to set a timeout for waiting on a close response would be helpful I think - since the server/client on the other end of the WebSocket connection is allowed to (effectively) never send a close frame back. 

> I think #3666 can be better resolved without resorting to a timeout.

I'm more than happy to resolve #3666 through non-timeout means but an application can't decide what implementation it's talking to so it can't guarantee that any close frame will be responded to in a "timely fashion"/ever. The advice I had in the other thread was to deal with it via timeouts (which sounds reasonable to me) but this doesn't seems to be a clean way of doing this (barring setting global timeout - which I don't think is desirable) in Jetty. Maybe I'm missing something about the Jetty's implementation/API?
