### ISSUE TITLE
Missing WebSocket ServerContainer after server restart

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#3698]
In Jetty 9.4.x, the following pseudo code works:

```java
Server server = new Server();
ServletContextHandler context = new ServletContextHandler(server, ...);
WebSocketServerContainerInitializer.configureContext(context);
server.start();
ServerContainer ws1 = (ServerContainer)context.getAttribute(ServerContainer.class.getName()); // -> it's there.
server.stop();
server.start();
ServerContainer ws2 = (ServerContainer)context.getAttribute(ServerContainer.class.getName()); // -> it's there.
```

In Jetty 10.0.x, after the server restart, `ws2` is missing.

I'm not sure what is exactly the right semantic here, but if the context stays in the Jetty component tree, I'm leaning towards the behavior that application code should not re-initialize WebSocket (like it does not re-add Servlets, Filters, etc.).

@gregw @joakime @lachlan-roberts thoughts?

**Comment by lachlan-roberts** [comment]
In Jetty-10.0.x we store the container as an attribute on the `ServletContext` and all the attributes on the `ServletContext` are cleared on `ContextHandler.doStop()`.

If you use the ServletContainerInitializer to get the container you don't have to worry about it not being there but it will still just create it again on restart. So maybe it should be stored somewhere more persistent.

**Comment by joakime** [comment]
The use of `WebSocketServerContainerInitializer.configureContext(context);` skips the SCI behaviors.

In other words, your usage is manual.
So your restart will be manual as well.

If you register the SCI instead of going manual it will work.

**Comment by sbordet** [comment]
I need manual for testing and works in 9.4.x - we just need to make it work in 10.0.x.

**Comment by joakime** [comment]
If you switch to proper SCI usage, then it will work as you expect in both 9.4.x and 10.0.x

**Comment by sbordet** [comment]
@joakime what's "proper SCI usage"? Example?

**Comment by gregw** [comment]
Proper SCI usage is when you let a SCI actually execute and do it's initialisation work.

I think the problem with the current embedded code could just be naming.   It is not a `configureContext`, because once configured it should be able to be stopped and started without any other steps.    So what it is really doing is initialising the context and this has to be done for every start.

So we could just rename.....

Or we could change so that it really did do a configuration (eg add a listener) and then let other mechanism (eg a listener) do the initialisation on every start.

**Comment by joakime** [comment]
Looks like @sbordet is using `ServletContextHandler` which wouldn't work with the existing `ServletContainerInitializersStarter` (which expects a `WebAppContext`).
Plus his embedded-jetty usage would need to change to add websocket Endpoints during context initialization instead of during the embedded-jetty setup.

**Comment by joakime** [comment]
I see that jetty-10.0.x is using `ServletContext` attributes for the `ServerContainer` now.
In jetty-9.4.x the `ServerContainer` is a bean on the `ServletContextHandler` (or `WebAppContext`) so that it can stop properly. (a requirement of the JSR356 spec btw is to deregister encoders/decoders)
Why was that change made in jetty-10.0.x?
How is the `ServerContainer` expected to respond to the stop of the `ServletContext`?
Is there a missing behavior to have removed attributes be passed through `LifeCycle.stop(Object)`? (that isn't a great idea IMO)

**Comment by joakime** [comment]
Opened Draft PR #3706 for this.
