### ISSUE TITLE
bad HTTP parsed: 400 HTTP/0.9 not supported for HttpChannelOverHttp@2587070{r=0,c=false,a=IDLE,uri=null}

### ISSUE THREAD

**Issue by pethers** [eclipse/jetty.project#370]
We have some old client sending invalid http request.

Found other people having the same issue, info at : http://www.itdaan.com/faq/2015/02/13/100645178.html

Test with invalid http 1.0 get request containing extra CRLF "printf "GET /\r\nHTTP/1.0\r\n\r\n" | nc localhost 8080"

$ printf "GET /\r\nHTTP/1.0\r\n\r\n" | nc localhost 8080
HTTP/1.1 400 HTTP/0.9 not supported
Content-Length: 0
Connection: close
Server: Jetty(9.3.8.RC0)

Error log at server "bad HTTP parsed: 400 HTTP/0.9 not supported for HttpChannelOverHttp@2587070{r=0,c=false,a=IDLE,uri=null}" 

Even if the parser will not accept the http request, shouldn't the error message say just "bad http request" or is it really related to http/0.9 support ?

**Comment by gregw** [comment]
The input "GET /\r\n" is a valid HTTP/0.9 request, so if sent to a server that handles 0.9 it will return the root resource at /.       HTTP/0.9 can never be persistent connections, so the "HTTP/1.0\r\n\r\n" will just be ignored if 0.9 is supported.

So I think it is valid for this to be a 0.9 related error and I don't think that saying so is over sharing.  Perhaps the argument could be made that we need not share that with the client, but there are a surprising number of clients still sending 0.9 requests... so much so that in 9.3.8 we are offering a RFC2616 compliance mode that will again accept such requests.

cheers

**Comment by pethers** [comment]
Happy with RFC2616 compliance mode, websphere application running java6 and old web service stack that was causing our problem.
