### ISSUE TITLE
Module automation for session managers

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#380]
If a module is used to enable a different session technology (eg gcloud-sessions) then currently only a session ID manager is installed and each and every context deployed needs to be customised to have the appropriate session manager set.

Since it is impossible to use mixed session managers once a session ID manager is set, we should automate this in the deployer so an appropriate session manager is automagically configured for each context without the need for customisation.

**Comment by laeubi** [comment]
> Since it is impossible to use mixed session managers once a session ID manager is set

Is this true? I just noticed that sometimes they are just to closely coupled to be mixed. So either there should be a generic API without having the strong coupling of Id+Session Manager or both should be merged because there is literally no use if havin one Id and one Session Manager as different Objects.

Another way beside merging the two would be to have a method in SessionId manager that simply creates SessionMnager objects related to the IdManager.

**Comment by gregw** [comment]
@laeubi Well it is not always true.... if you are using non-clustered session managers then a HashSessionIdManager could work for a mixed bag of session managers.       But in general, it is best if they match.

So the "automation" suggested here may well end up being a factory method on the id manager or similar...  but sessions mean so many different things to different users that we have to be very careful not to remove flexibility.

**Comment by gregw** [comment]
Done in 9.4.x
