### ISSUE TITLE
Which thread is used by Jetty Client for establishing connections

### ISSUE THREAD

**Issue by iamrohitbanga** [eclipse/jetty.project#3841]
When does Jetty HTTP client establish connections? Especially interested in HttpClientTransportOverHTTP2.

Let's say we make a call using the POST method on HttpClient, then:
Does the address resolution, connection establishment happen on the async/sync path of the POST thread? Does it pull a new thread from the Jetty QueuedThreadPool in order to establish the connection?

**Comment by sbordet** [comment]
WRT address resolution, it is controlled by `HttpClient.socketAddressResolver`. By default is `SocketAddressResolver.Async`.

WRT connection establishment, it is controlled by `HttpClient.connectBlocking`. By default this is `false`.

An HTTP/2 connection is opened for the first request, and reused until the max number of concurrent streams is reached, at which point another connection is opened.

**Comment by iamrohitbanga** [comment]
Ok thank you for your response.
I need some more clarification. While the requests are waiting for address resolution or the default non blocking connect, are they on the QueuedThreadPool and do they count towards the max concurrent streams limit on the client side.

Essentially, who does the async wait - one of threads from the QueuedThreadPool we configure? 

Also after the max concurrent streams limit is hit on the first connection, what is preferred - putting in the QueuedThreadPool, waiting for the existing requests to finish or establishing a new connection assuming the max connection limit is not met.

**Comment by sbordet** [comment]
I feel you are asking these questions because you have some other problem. If that's the case it's better if you detail the problem first.
From your questions you seem to have a wrong understanding of how `HttpClient` works, so I would like to avoid to confuse you by answering directly your questions - state your problem and it's probably simpler to answer.

Requests are not "on the QueuedThreadPool" (they are queued in their `Destination`) and async waits are threadless - no threads are involved (apart from address resolution that is unfortunately only blocking).

After the max concurrent stream is reached for one connection, another one is used. If it's not present, it's created. If it cannot be created because the max number of connections per destination is reached, new requests remain queued in their `Destination` until some previous request ends. All pending requests are waiting threadlessly.

**Comment by iamrohitbanga** [comment]
I see thank you.

I am trying to understand the Jetty Client architecture better to see how I can efficiently tune the client to higher request rates than what I am able to do right now.

As far as specific problems I am noticing, I will open a separate github issue for those.

**Comment by sbordet** [comment]
@iamrohitbanga we routinely see `HttpClient` doing tens of thousands of request/s on a laptop.
What are your numbers?
