### ISSUE TITLE
Need Strict 6265 cookie compliance mode

### ISSUE THREAD

**Issue by dfish3r** [eclipse/jetty.project#3886]
When parsing a cookie header that contains mismatched double quotes, Jetty should discard invalid cookies and continue parsing the remaining cookies.

For the following header, where the first cookie is missing a double quote:
`Customer="WILE_E_COYOTE; Part_Number="Rocket_Launcher_0001"`
It would be preferable to discard the Customer cookie when the first semi-colon is detected. Instead the following value is produced:
`WILE_E_COYOTE; Part_Number="Rocket_Launcher_0001`
where the second cookie bleeds into the first.

What we see in the wild is that if an application sets a domain wide cookie with an invalid value like the one above, other applications in the same domain running on Jetty may fail to parse their own session cookie when the invalid cookie is encountered.
The user experience at that point can be very interesting depending on what order the cookies are presented to Jetty.

Here is a simple unit test for the `CookieCutterTest` class:
```
    /**
     * Invalid leading double quote
     */
    @Test
    public void testRFC6265_MismatchDoubleQuote()
    {
        String rawCookie = "Customer=\"WILE_E_COYOTE; Part_Number=\"Rocket_Launcher_0001\"";

        Cookie cookies[] = parseCookieHeaders(CookieCompliance.RFC6265,rawCookie);

        assertThat("Cookies.length", cookies.length, is(1));
        assertCookie("Cookies[0]", cookies[0], "Part_Number", "Rocket_Launcher_0001", 0, null);
    }
```

**Comment by janbartel** [comment]
Due to the historical differences between the way various browsers have generated cookies, jetty has been designed to be pretty lenient on what we accept.  We even already have a test for a similar case to yours, see lines for tests with mismatched quotes around line 106: https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/test/java/org/eclipse/jetty/server/CookieCutter_LenientTest.java#L106

Delving into that maelstrom of crumbly cookie mess isn't appetising; indeed changing the behaviour might break others who have come to rely on the lenient parsing.

One way forward for you would be to configure the RewriteHandler to insert the double-quote at the right place in the request before it hits the servlet mechanism. You'd need to write a little bit of code, a subclass of the org.eclipse.jetty.rewrite.handler.Rule class in fact. It would look a bit like this:

```java
public class CookieFixerRule extends Rule
{
    @Override
    public String matchAndApply(String target, HttpServletRequest request, HttpServletResponse response) throws IOException
    {
        Request baseRequest = Request.getBaseRequest(request);
        for (ListIterator<HttpField> i=baseRequest.getHttpFields().listIterator(); i.hasNext();)
        {
            HttpField field = i.next();
            if (field.getHeader() != HttpHeader.COOKIE)
                continue;
            String value = field.getValue();
            
            // TODO: check value for badly formatted cookie, then fix as appropriate
            
            i.set(new HttpField(HttpHeader.COOKIE, value));
        }
        
        return target;
    }
}
```

The documentation here: https://www.eclipse.org/jetty/documentation/9.4.19.v20190610/rewrite-handler.html should help enable the rewrite-handler and set up your rule for it.

**Comment by serac** [comment]
As a compromise, would you consider a pull request that patches `CookieCutter` to provide a stricter parsing mode that would be off by default but optionally enabled by deployers like us that want stricter cookie parsing behavior?

**Comment by joakime** [comment]
> `"Customer=\"WILE_E_COYOTE; Part_Number=\"Rocket_Launcher_0001\""`

Strict Cookie Parsing of RFC6265 should reject this entire Cookie string at the first `;` because that octet is not allowed within a DQUOTE pair.

This, btw, is what Chrome and Firefox already does in this same situation when parsing `Set-Cookie` with an identical DQUOTE syntax.  In Chrome the cookie will be silently dropped, in Firefox you'll see a console message and it will be dropped.

I propose that Jetty drop the cookie and log that fact on this kind of Cookie.

Being lenient here is a security issue, as it would become trivial to sneak in values from other cookies (possibly ones not even belonging to the same httpOnly and secure rules)

**Comment by serac** [comment]
I agree with the observation that the current parsing behavior could be a vector for security vulnerabilities.

**Comment by dhawes** [comment]
> This, btw, is what Chrome and Firefox already does in this same situation when parsing Set-Cookie with an identical DQUOTE syntax. In Chrome the cookie will be silently dropped, in Firefox you'll see a console message and it will be dropped.

This is not my observation. Neither Chrome nor Firefox drops Customer. Part_Number does seem to be dropped.

Here's a simple test to recreate on your local machine:

`echo -e 'HTTP/1.1 200\r\ndate: Mon, 29 Jul 2019 16:30:19 GMT\r\ncontent-type: text/html;charset=iso-8859-1\r\ncontent-length: 5\r\nset-cookie: Customer="WILE_E_COYOTE; Part_Number="Rocket_Launcher_0001"\r\nexpires: Thu, 01 Jan 1970 00:00:00 GMT\r\ncontent-language: en-US\r\n\r\ntest' | nc -q 1 -l 8080`

Now go to http://localhost:8080 in your browser and inspect the cookies.

**Comment by janbartel** [comment]
Google Chrome Version 74.0.3729.169 (Official Build) (64-bit) on Ubuntu 18.04.2 I get a single cookie:

```
Customer="WILE_E_COYOTE
```

**Comment by janbartel** [comment]
@dfish3r how is the Set-Cookie being generated? Ie how is your code setting the cookie that the browser returns with the mismatched double quote? What is the CookieCompliance you have configured for the HttpConfiguration (see the property value jetty.httpConfig.requestCookieCompliance and the jetty.xml config file). Looks to me like the code would reject a bad set cookie value when using RFC6265 compliance, but I'll see if I can modify one of our existing tests to confirm that.

**Comment by gregw** [comment]
@serac I don't believe the current handling is a security problem.
It is the behaviour you proposed that has a security problem.  Looking into what could be a cookie value to find entirely new cookies is the security vector.
If we see `Customer=` we are sure there is a cookie called `Customer`.  Currently our leniency allows some values of that which a strict reading of the spec would say are illegal, but we create no other cookies.  Your proposal is that we look past irregular characters and discover entirely new cookies... we are not going to do that.

I think the rewrite rule proposed by @janbartel gives you sufficient power and flexibility to work around any strange clients that you may have.

**Comment by dfish3r** [comment]
@janbartel in our case we discovered a vendor application that was setting invalid cookies like this for our entire domain. I can't say how that application was generating the Set-Cookie header. What I can say is that our Jetty based applications are broken when they receive the header.

We are using the default Jetty settings for cookie compliance, which I believe is RFC6265.

**Comment by janbartel** [comment]
@dfish3r whew, good, I'm glad it's not jetty generating bogus set-cookie headers: I checked the code and couldn't see how it could possibly happen, so glad to have your confirmation.

@gregw what do you think about having an inbound cookie header strict 6265 compliance parsing mode as an option to the lenient parsing?

**Comment by gregw** [comment]
I'm not opposed to have a strict 6265 compliance parsing mode, but I don't see how that would help this issue as a strict mode would just  ignored the whole header value OR  reject the whole request with a 400 Bad Request response.

So there is absolutely no way (in any mode) that we are going to ignore a missing " and interpret a ; as a cookie separator. Never going to happen!!! As @joakime pointed out, it would be a huge security problem with cookie injection.

The only way this cookie can be handled is by some special purpose handling in this specific application - as per the rewrite Rule that has been suggested.

**Comment by serac** [comment]
@gregw, I appreciate your feedback as it helped me reason through the cookie injection risk, and I tend to agree that changing the parsing mechanism as we have proposed actually increases the risk of cookie manipulation. That said, we have observed the current behavior presents a denial of service risk. In our case, a third-party application set a malformed cookie scoped to our entire domain; when clients showed up to any of our Jetty apps, the application-specific cookies were ignored when they followed the malformed cookie in the cookie header value. It took many man-hours of sleuthing and coordination with other groups to track down the root cause, and while the misbehaving app has been patched, the risk remains.

I would advocate for a strict parsing mode that results in a 400 response as you suggested. While that doesn't strictly fix the DOS vector we have observed, the fail fast behavior and presumably clear diagnostic messages (either response status, server logs, or both) would have helped us identify and remediate the friendly fire far more quickly and with less effort.

**Comment by gregw** [comment]
I'm happy for us to have strict 6265 mode and I've changed the name of this issue to match.

Note however that Jetty follows [Postal's law](https://en.wikipedia.org/wiki/Robustness_principle) and we are strict in what we generate and lenient in what we parse.  So currently you cannot use Jetty to set such a non-compliant cookie, which somewhat limits the DOS vector.   To receive bad cookies the sender must have control of the client, in which case they can send/hide arbitrary cookies anyway.

**Comment by joakime** [comment]
I forget, can't 3rd party javascript set cookie headers against the base uri of the web page?

**Comment by gregw** [comment]
@joakime potentially... but my point remains... if the client allows an invalid cookie to be set/sent then the client probably allows cookies to be duplication or removed or update etc.  We don't allow them to be set via jetty.   But it would still be good to have a strict compliance mode on receive as well

**Comment by gregw** [comment]
@joakime 
that PHP example is kind of strange as it has not stripped the DQUOTES at all, as it should according to RFC6265.  If it's not handling DQUOTES, then of course it will not have to issue of if ';' can be quoted or not!... which really is the issue here with regards to how we should be lenient.

In a truly strict interpretation of RFC6265,  it doesn't really matter the order of the parsing, as any violation should result in a 400 Bad Request response.   The order of parsing only really affects how we are lenient in as much as what cookies we will see in the face of spec violations.  I maintain that due to the history of allowing DQUOTES to wrap arbitrary tchars and the fact that we've had issues asking for this very leniency, then we should not change that style of leniency.
