### ISSUE TITLE
DefaultServlet as a Filter

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#3917]
I tried binding `DefaultServlet` to `/*` to handle static resources and binding servlets to `/api/*`.

Unfortunately, `DefaultServlet` is a servlet ... not a filter. So it does not allow the servlet handler to ever get invoked.

Would it be possible to expose the `DefaultServlet` functionality behind a `Filter` or does this kind of configuration never make sense?

**Comment by gregw** [comment]
Firstly this is not really an issue, but a question.  You can ask such questions on the jetty-user mailing list or on stackoverflow!  Issues are really just for bugs and enhancement requests.

You want the default servlet bound to / rather than /* because the semantic of / is the default servlet - ie it matches if nothing else does.  /* is a suffix match and will be preferred over patterns like *.jsp.  So with your servlet at /api/* and DefaultServlet at /  you should get the behaviour you need.

But to answer your question directly - yes you can have a filter invoke the default servlet directly by forwarding to a named dispatcher with the name "default"

**Comment by joakime** [comment]
Why would you want to have the `DefaultServlet` as a Filter?

I ask this, as it's a surprisingly common question on Stackoverflow with users using jax-rs / jersey.

The way `DefaultServlet` works is on url-pattern `"/"` and will be invoked when no other Servlet matches the request.
Then it will look for static resources within your declared BaseResource and serve those.

But you can also have multiple `DefaultServlet` in your webapp.
See [DefaultServletMultipleBases.java](https://github.com/jetty-project/embedded-jetty-cookbook/blob/master/src/main/java/org/eclipse/jetty/cookbook/DefaultServletMultipleBases.java) in the `embedded-jetty-cookbook` for example.

You can also have a `ErrorPageErrorHandler` setup to respond on status code 404 to include / redirect to a pre-defined `DefaultServlet` that you control. (just be sure you don't redirect / include to something that would itself also produce a 404 == bad error loop)

**Comment by cowwoc** [comment]
I apologize for extending this discussion further on the issue tracker when the mailing list might be more appropriate.

@gregw I mistakenly thought that this was something Jetty was missing so I thought I was filing a feature request.

@joakime Coming from a filter-oriented worldview I thought that requests are answered using a chain-of-responsibility design pattern: requests walk through the filter chain until someone picks it up. Baring that, requests would flow on to the next handler. Thinking about this further, I understand that this behavior isn't necessary so long as `*` isn't used.

Coming back to JAX-RS/pathspec discussion, I posted this question for your review: https://stackoverflow.com/questions/57282362/how-to-register-resource-hierarchy
