### ISSUE TITLE
Deadlock between new HTTP2Connection() and Server.stop()

### ISSUE THREAD

**Issue by swankjesse** [eclipse/jetty.project#3929]
`Server.stop()` holds `AbstractLifeCycle._lock` while it joins a network thread:

```
  java.lang.Thread.State: WAITING
	 blocks qtp2102368942-24@2434
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.join(Thread.java:1313)
	  at org.eclipse.jetty.util.thread.QueuedThreadPool.doStop(QueuedThreadPool.java:179)
	  at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	  - locked <0xe86> (a java.lang.Object)
	  at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:178)
	  at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:199)
	  at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:124)
	  at org.eclipse.jetty.server.Server.doStop(Server.java:464)
	  at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	  - locked <0xe87> (a java.lang.Object)
```

But that network thread will never complete because it’s attempting to acquire `AbstractLifeCycle._lock`:

```
"qtp2102368942-24@2434" prio=5 tid=0x18 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for Time-limited test@1899 to release lock on <0xe86> (a java.lang.Object)
	  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:65)
	  at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	  at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
	  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	  - locked <0xe88> (a java.lang.Object)
	  at org.eclipse.jetty.util.component.LifeCycle.start(LifeCycle.java:139)
	  at org.eclipse.jetty.http2.HTTP2Connection.<init>(HTTP2Connection.java:70)
	  at org.eclipse.jetty.http2.server.HTTP2ServerConnection.<init>(HTTP2ServerConnection.java:100)
	  at org.eclipse.jetty.http2.server.AbstractHTTP2ServerConnectionFactory.newConnection(AbstractHTTP2ServerConnectionFactory.java:243)
	  at org.eclipse.jetty.server.NegotiatingServerConnection.onFillable(NegotiatingServerConnection.java:130)
	  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	  at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
	  at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
	  at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	  at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	  at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	  at java.lang.Thread.run(Thread.java:834)
```

So we get a deadlock.

Here’s [thread_dump.txt](https://github.com/eclipse/jetty.project/files/3458156/thread_dump.txt), captured in the deadlock.

I was able to reproduce this with [JettyFailsToStopTest.java](https://github.com/eclipse/jetty.project/files/3458159/JettyFailsToStopTest.java.txt). It needs OkHttp and Okio to create an HTTP/2 connection. I observed the deadlock 1 attempt out of every 5 on my MacBook Pro.

**Comment by joakime** [comment]
Buildable / Testable project for your test code is at https://github.com/jetty-project/okhttp-jetty-http2-deadlock

What version of Jetty?
What version of Java are you using?
What version of OKHttp are you using?

After 8,000 runs of the testcase, I have no failures, and no deadlocks.

I'm using ...

* Linux / Ubuntu 18.04.2 LTS
* Jetty 9.4.19.v20190610
* OKHttp 4.0.1
* Java 12.0.1+12

**Comment by joakime** [comment]
Results of same project on Mac OS ...

4000 iterations, no failure, no deadlock.

Environment:

* Mac OS 10.14.5
* MacBook Pro (Retina, Mid 2012) - 2.6Ghz Intel Core i7
* Jetty 9.4.19.v20190610 (from example project)
* OKHttp 4.0.1 (from example project)
* AdoptOpenJDK 12.0.2+10

**Comment by sbordet** [comment]
@swankjesse can you set `QueuedThreadPool.stopTimeout = 0` and verify if it still happens?

@joakime @gregw so we are calling `Thread.join()` from `doStop()`, which is called with the lifecycle lock held.
The `HTTP2Session` creates a `EatWhatYouKill` strategy and the starts it. Because `EatWhatYouKill` references back the `QueuedThreadPool` (as a `TryExecutor`) as a bean, it tries to start it again (because it is not running, it is stopping).
I guess the culprit is here:
https://github.com/eclipse/jetty.project/blob/jetty-9.4.19.v20190610/jetty-util/src/main/java/org/eclipse/jetty/util/component/ContainerLifeCycle.java#L116
The `else` branch should start the bean only if it is stopped.
Thoughts?

**Comment by gregw** [comment]
@sbordet I think EWYK should not add the tryExecutor as an auto bean.  It should add it explicitly as unmanaged - ie the EWYK strategy should never try to start the executor.

**Comment by sbordet** [comment]
@gregw how would EWYK know that it must not add the `TryExecutor` as a bean?
It could be a just allocated instance for that particular EWYK instance, we want it as a bean for dump purposes.

**Comment by swankjesse** [comment]
On reproducing: I found this only reproduces for me when it's the first attempt in a JVM run. I got the one-in-five result by hitting "go" in JUnit five times in a row.

**Comment by swankjesse** [comment]
The `stopTimeout` feature mitigates this nicely. If I set that to say 4300 milliseconds then the shutdown takes about 4350 milliseconds!

**Comment by joakime** [comment]
> On reproducing: I found this only reproduces for me when it's the first attempt in a JVM run. I got the one-in-five result by hitting "go" in JUnit five times in a row.

@swankjesse What JVM did you use?
Be accurate, run `java --version` and report back the details.

Did you use the example project at https://github.com/jetty-project/okhttp-jetty-http2-deadlock ?

If not, can you modify that example project (probably with your exact jetty and okhttp versions) and still cause it?

**Comment by gregw** [comment]
@sbordet I think that EWYK should never own an executor so it should probably just do something like:
```java
    public EatWhatYouKill(Producer producer, Executor executor)
    {
        _producer = producer;
        _executor = executor;
        _tryExecutor = TryExecutor.asTryExecutor(executor);
        addBean(_producer);
        addBean(_executor, false);
        if (_tryExcecutor != _exectutor)
            addBean(_tryExecutor);
        if (LOG.isDebugEnabled())
            LOG.debug("{} created", this);
    }

```

**Comment by sbordet** [comment]
> I think that EWYK should never own an executor

And why is that?

> if (_tryExcecutor != _exectutor)
    addBean(_tryExecutor);

This is not necessary, as `addBean()` has `Set` semantic.

While it may solve this particular problem, I don't see how we are solving in general the problem of a bean being added to the tree while one of its beans is stopping?

**Comment by gregw** [comment]
@sbordet My thinking goes that if a component can be created during shutdown, then it really can't be responsible for starting executors that are passed into it.  
More over, any component that may be created within a ThreadPool thread also can't be doing lifecycle operations on the threadpool!
EWYK should never start the executor, because it is being executed by a thread owned by the executor.

Either that or we somehow do not hold the lifecycle lock while stopping, or make the ThreadPool a very special lifecycle so it can do a join without the lock... which is a much much bigger change... and will probably not work because a STOPPING threadpool will just get restarted by EWYK.

With regards to adding the `_tryExecutor`, not that the `TryExecutor.asTryExecutor` may return a different executor, hence the need to call addBean again- perhaps also with false as per the logic above.

**Comment by sbordet** [comment]
> My thinking goes that if a component can be created during shutdown, then it really can't be responsible for starting executors that are passed into it.

Why not? The problem here is not about starting executors, it's about trying to start the same executor that is stopping, of which the starting component has no idea.
I really think this is more a problem in `ContainerLifeCycle` than in EWYK. We fix EWYK as you are suggesting, we will discover we have the same exact problem elsewhere - better fix it in `ContainerLifeCycle`.

**Comment by gregw** [comment]
You are proposing a [useless box "solution"](https://www.geek.com/wp-content/uploads/2014/06/11.gif).
If we avoid the deadlock then we will still have the problem that the ThreadPool has been commanded to stop, yet an EWYK created due to an inbound connection can then command it to start.    

The deadlock is not the problem here - it's a symptom of the problem.   

Nothing an inbound connection can trigger should be able to overrule the stopping of the server!    If we avoid the deadlock, then we are still faced with problem that our stopping ThreadPool will now be started.  Sure if we fix that in EWYK then we may discover the same problem somewhere else and then it has to be fixed there too.   NOTHING that a remote user can trigger should be able to affect the stopping of the ThreadPool, so no components that are dynamically created can manage static components like the threadpool.   Dynamic components managing static components is just broken and has not sensible interpretation.  If we let the dynamic EWYK component start the threadpool, then it will stop it when that connection is complete.

So any dynamic component that is passed a static component should add it as an unmanaged bean.    OK this is difficult for components like EWYK that may be used statically and dynamically, but fundamentally the problem here is getting component relationships right and using AUTO is not doing that for us.

**Comment by joakime** [comment]
Opened PR #3938 to address this issue

**Comment by gregw** [comment]
For the record... I was convinced that we should treat neither the symptom nor the root cause.   @sbordet proposed change to handling of `AUTO` beans is a good change in it's own right and will avoid the bad relationship being setup between dynamic EWYK and static ThreadPool.... but the potential for such bad relationships remains and we may have to think a bit harder if we find other examples.
