### ISSUE TITLE
Consider adding demand API to HTTP/2

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#3951]
I've been thinking about this problem in the abstract and thought I'd write a few thoughts to move the conversation along.   Essentially the problem is that we have several examples of asynchronous events that look like:
```
void onData(DataFrame frame, CallBack callback);
```
We have existing code that is written to this style of API and the basic contract is that from the time the `onData` is called until the time either `succeeded()` or `failed(Throwable)` are called that:
 - The data within the frame is available and underlying buffer will not be recycled.
 - Flow control is exerted and more calls to `onData` will not be made.

We would like to separate those concerns, so that passed buffer may be retain after or recycled before the flow control completion signal.  However, it needs to be done in such a way that existing code will work seamlessly without need for an update.

One idea is to make the CallBack instance passed polymorphic so that instead of just being:
```java
interface CallBack
{
    void succeeded();
    void failed(Throwable failure);
}
```
It could be something like:
```java
interface ReleaseableCallBack
{
    void finished();
    void release();
    default void succeeded() { finished(); release(); }
    void failed(Throwable failure);
}
```
Code implementing `onData` could continue to call `suceeded()` as before, or it could down cast and call `finished()` and `release()` independently.    There would need to be some further complexity to handle strange code that calls `finished()` or `release()` and then `succeeded()` or `failed(Throwable)` to ensure that double handling is not done.

This does work, but the problem is that it does not cope well with wrapping of callbacks, which is frequently done in our code base.   When callbacks are fanned out, aggregated or wrapped, the type of the callback is hidden and we essentially have a multiple inheritance problem to keep all the concerns on the callback.

more thinking......

_Originally posted by @gregw in https://github.com/eclipse/jetty.project/issues/2439#issuecomment-383003517_

**Comment by sbordet** [comment]
@gregw given the reactivestreams semantic and the websocket refactor, I am inclined to provide an explicit demand API that people can use, as in `Session.demand()` or similar - exactly because the `Callback` object may be wrapped and will be a problem to forward the demand request.

**Comment by gregw** [comment]
@sbordet I agree - the separate `demand()` API in jetty-10 websocket core works well.   It also allows for auto-demand to be used in situations where users don't want to manage their own demand.   With autodemand, rather than trying to split the concerns on a call by call basis, they are either combined (autodemand) or split (demandable) by some prior arrangement  - in the case of websocket, this is a tag on the FrameHandler.   While such modal APIs can be bad, at least it is trivial to give an ISE if used the wrong way: https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketCoreSession.java#L467-L475

Even if autodemand is not considered worthwhile, I think splitting demand away from callback semantics is a good thing.
