### ISSUE TITLE
Improve efficiency of listeners

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#3964]
Some implementations of listeners can be made more efficient, specially with regards to ones that are:
- seldom ever set
- set to a fixed preknown list

**Comment by sbordet** [comment]
I have strong doubts about this. All I see in the PR is more code to run for every operation and more fields (even duplicated to have read-only behavior) that consumes more memory.
Adds and removes now possibly run a lot more code and copy stuff around.
Iteration has added an `if` and a cast.

Do you have a JMH benchmark that shows the problem?

Also consider that the JDK has been modified so that the memory impact of an empty `ArrayList` is negligible (used to allocate 16 empty elements in the past - not anymore).

I'm not convinced we should do this until I see a JMH benchmark with evidence.

**Comment by gregw** [comment]
@sbordet you've missed the point of the PR. See discussion in #3965
