### ISSUE TITLE
Project state w.r.t. HTTP/2 vulnerabilities

### ISSUE THREAD

**Issue by bripkens** [eclipse/jetty.project#3978]
Hey folks,

a whole bunch of projects are currently fixing issues in their HTTP/2 implementation due to recently disclosed [security vulnerabilities](https://www.kb.cert.org/vuls/id/605641/), e.g. Netty, nginx, Node.js…

Do you know whether Jetty is affected by these as well and also needs fixes?

**Comment by sbordet** [comment]
The vulnerabilities are a bit vague as in:

> Depending on how efficiently this data is queued this can consume excess CPU, memory, or both, potentially leading to a denial of service.

Many if not all of them have already been reported to the Jetty project from users and have since been fixed.
We don't implement priorities, we don't allocate memory we are not immediately using, etc. so the initial assessment is that we don't "consume excess CPU, memory, or both" apart from what is needed to operate the server.

Rest assured that we will be looking in details of the specific vulnerabilities. Thanks!

**Comment by gregw** [comment]
Note also:
 - See #2722 which addressed CVE-2019-9515
 - Jetty is tested for TCP/IP congestion for CVE-2019-9517 
 - Manly of these DOS vectors apply equally well to normal requests for h1 or h2, so we have minimum data rate settings, so all CVEs that rely on dribbling data or holding open connections can be addressed that way.

So generally speaking our http/2 is very much aware of the style of vulnerability these CVEs raise and is designed to minimize exposure as much as possible. We continue to monitor and develope to handle these issues, but ultimately clients can send requests to servers that consume CPU/Memory and it can be hard to generally determine what is "disproportionate".
