### ISSUE TITLE
Review Jetty 10 WebAppContext default server classes

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#4030]
https://github.com/eclipse/jetty.project/blob/a6ab7771501e2007ce485e8d888519e64b262d5e/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppContext.java#L178-L184

Do we still need this default?
Isn't everything locked away now?
After all, we can't access server loggers or server datastores now, and have to specifically open up the ability with a new Configuration.

**Comment by gregw** [comment]
@joakime "everything is locked away" precisely because of this line!   The key change is that rather than having a carefully curated list of exposed/hidden classes here, we now just hide all of jetty.   Individual Configurations may choose to expose/hide more classes, but this is the correct default to start with.

So with respect to #3873, the problem there was that the test classes were within "org.eclipse.jetty." and the unit test was running them from the container classpath by opening a hole for them.   The better fix was to move them to a non hidden package, so the default classpath settings can be used.  Another solution would be to put them and all their dependencies entirely in the WEB-INF/lib
