### ISSUE TITLE
Embedded Jetty with multiple WebApps fail with default temp directory

### ISSUE THREAD

**Issue by tsmortenson** [eclipse/jetty.project#4136]
I have a pair of webapps which were each working perfectly within embedded Jetty.
But when I tried adding both webapps to the same Jetty instance, each with their own WebAppContext, the first webapp was failing with lots of strange errors.

I figured out early on from the errors that the two webapps seemed to be overlapping eachother, but It took me a couple days of debugging to figure out the cause.

I finally realized that I was missing the setTempDirectory() call on each of the WebAppContexts.  Jetty defaults to using the same temp directory.  This was causing the second webapp to overwrite the files stored from the first webapp.

Now that I understand this, I am good.   But it would really help other users avoid this problem if Jetty implemented a check to make sure that multiple WebAppContexts each use a unique temp directory by default.

**Comment by joakime** [comment]
The temp directory will not overlap unless you specify it to overlap. (we have tests for this)

Have you specified the temp directory in your WebAppContext's?

**Comment by tsmortenson** [comment]
Thanks for the quick reply.
I checked the list.  But we were not doing anything.  We are using embedded code so the jetty.home work dir doesn't exist.  I think we were using the #6 option, as it was putting the files for both webapp in the same directory under the default temp dir.
We were not setting a work directory anywhere until I discovered the setTempDirectory() method.

**Comment by janbartel** [comment]
@tsmortenson note that when jetty has to make a temp directory for a webapp, if you haven't called setTempDirectory() then we use the algorithm shown in  https://stackoverflow.com/questions/19232182/jetty-starts-in-c-temp/19232771#19232771 to work out a _parent_ directory. Then each webapp will create its own _subdirectory_ in the parent directory, with a name that is composed of these elements:
`"jetty-"+host+"-"+port+"-"+resourceBase+"-_"+context+"-"+virtualhost+"-"+randomdigits+".dir"
`

If you call setPersistTempDirectory(true), then we leave off the random digits (and also the ".dir" suffix (which is a bit wierd)) so that the name of the directory will be invariant across invocations of jetty, so it will look like:
`"jetty-"+host+"-"+port+"-"+resourceBase+"-_"+context+"-"+virtualhost+"-"`

So unless both your webapps have exactly the same resourceBase and context path and you're persisting the temp directory, I don't see how this could be happening. Please post more details.

**Comment by joakime** [comment]
Several attempts at using multiple WebApps (via WAR files) on embedded-jetty shows that the generated temp directories do not overlap.

Why you experienced overlapping temp directories is a mystery without more information.
Closing for now.
If you can provide a reproduction case, we will be happy to reopen, perhaps this issue can go further to either explaining the behavior, or identifying a bug.
