### ISSUE TITLE
Change in async timeout behavior from 9.4.20.v20190813 to 9.4.21.v20190926

### ISSUE THREAD

**Issue by tipsy** [eclipse/jetty.project#4267]
I have a SSE implementation in [Javalin](https://github.com/tipsy/javalin/blob/7b50ca7fd6adbf3b7f8720d426a4170021675efc/src/main/java/io/javalin/http/sse/SseHandler.kt) which uses Jetty.

When I bumped to the latest version of Jetty just now, my SSE test stopped working. 
The test is very hacky: I do a standard GET request, but I set the timeout to 10ms by using `httpServletRequest.getAsyncContext().setTimeout(10)`.

I can rewrite my test, but is this change in behavior intended?

**Comment by gregw** [comment]
@tipsy can you give us more info?   I don't know any change of behaviour with the timeout per se.
We have changed ERROR dispatch handling a bit, so if your onTimeout callback does not do a AsyncContext.complete or a AsyncContext.dispatch, then an ERROR dispatch will be done.

If you want to test the timeout, add a listener that in it's onTimeout method sets a special status or writes "OK" content and then does a complete.  Otherwise you'll go around the ERROR dispatch, which if you are not handling it, may loop doing async start, async timeout, async start, async timeout etc.

**Comment by tipsy** [comment]
Thanks for your response @gregw. I don't have an `onTimeout`, so that's something I could look into adding. I'll have a look some time next week.

**Comment by tipsy** [comment]
Decided to just have a look now. Calling `complete()` on timeout fixes the issues: 

```kotlin
httpServletRequest.asyncContext.addListener(object : AsyncListener {
    override fun onComplete(event: AsyncEvent?) {
    }

    override fun onStartAsync(event: AsyncEvent?) {
    }

    override fun onTimeout(event: AsyncEvent?) {
        event?.asyncContext?.complete()
    }

    override fun onError(event: AsyncEvent?) {
    }
})
```

I guess I could try to fill all the listeners with something meaningful, but is there a way to just set the one?

**Comment by gregw** [comment]
Unfortunately that interface predates having default implementations, so you have to implement all methods.

**Comment by tipsy** [comment]
Alright, thanks for your help!

**Comment by sbordet** [comment]
@tipsy also look at Jetty's implementation of SSE, no need to write one.
https://github.com/eclipse/jetty.project/blob/jetty-9.4.22.v20191022/jetty-servlets/src/main/java/org/eclipse/jetty/servlets/EventSourceServlet.java

**Comment by tipsy** [comment]
Thanks for the tip @sbordet. Javalin also runs on other servers, so I think it's worth having an independent implementation. 

I didn't write this implementation myself though, so I'm a bit worried after seeing the amount of code in the Jetty implementation 🤔
