### ISSUE TITLE
Limit queue size in ByteBufferPools

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#432]
Limit queue size (or maybe memory commitment?) in the Buckets of ArrayByteBufferPool.java

**Comment by gregw** [comment]
Make that all the ByteBufferPools

**Comment by gregw** [comment]
@sbordet can you remind me why we no longer have a ThreadLocal based buffer pool?

**Comment by sbordet** [comment]
@gregw because deployments that had thousands of threads configured in the thread pool would see it as a memory leak.
Whatever you do here, you should do it for `MappedByteBufferPool` too, but consider not using locks (e.g. using `java.util.ArrayBlockingQueue`).
Perhaps it's time to have just one `ByteBufferPool` ?
Also see #133.

**Comment by gregw** [comment]
#133 is about having a better buffer allocater which is different to having a better buffer pool.  However if we do limit the size of the buffer queues in the pool, then we will free more buffers and in a bursty server end up putting more load towards the buffer allocater... so perhaps increasing the need for a jemalloc style allocator as well.

**Comment by gregw** [comment]
@sbordet I've pushed an impl of this.  When you have time, can you give it a review for performance and/or correctness.

**Comment by joakime** [comment]
Closing as implemented
