### ISSUE TITLE
rewrite prevents URL session tracking.

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#4329]
**Jetty version**
9.4.23
**Java version**
any
**OS type/version**
any
**Description**

The rewrite rules as configured for the demo webapp in a jetty distribution remove URI parameters so that session tracking by URI does not work.
Ideally rewrite should be able to be used without preventing URL session tracking.... even if it has to be a special rule to extract and remember the jsessionid somehow.

**Comment by joakime** [comment]
I cannot get `/test/session` example to work as expected in any past release of Jetty.

Versions of Jetty tested ...

* 9.4.22.v20191022
* 9.4.21.v20190610
* 9.4.14.v20181114
* 9.3.25.v20180904
* 9.2.27.v20190403
* 9.2.5.v20141112
* 9.1.5.v20140526

This issue is old, and not unique to the staged 9.4.23

**Comment by joakime** [comment]
Opened PR #4337
