### ISSUE TITLE
Jetty 9 failed to use pinpoint (maybe more other tools), unable to find classes in bootstrap classloader

### ISSUE THREAD

**Issue by hoverwinter** [eclipse/jetty.project#4357]
**Jetty version**
jetty-9.4.20.v20190813
**Java version**
 java version "1.8.0_172"
**OS type/version**
CentOS 7 (No impact)
**Description**

WebAppClassloader rejects to use parent classloader (system classloader) to load Pinpoint classes (in bootstrap classloader), older version jetty has no such problems. Tracing interceptors depends on `AroundInterceptor`, but 

```
2019-11-23 16:24:06.184|1|warn|com.navercorp.pinpoint.profiler.instrument.classloading.URLClassLoaderHandler|injectClass|Failed to load plugin class [com.navercorp.pinpoint.bootstrap.plugin.jdbc.interceptor.StatementExecuteQueryInterceptor, WebAppClassLoader{taotao-manager-web}@64d43929, java.lang.ClassNotFoundException: com.navercorp.pinpoint.bootstrap.plugin.jdbc.interceptor.StatementExecuteQueryInterceptor] with classLoader {}
2019-11-23 16:24:06.184|1|warn|com.navercorp.pinpoint.profiler.instrument.classloading.JarProfilerPluginClassInjector|injectClass|Failed to load plugin class 
```

Here are some outputs from arthas.

![image](https://user-images.githubusercontent.com/7020808/69547623-ea7e9580-0fd0-11ea-8985-2d3611db2958.png)

![image](https://user-images.githubusercontent.com/7020808/69547639-f0747680-0fd0-11ea-86d7-5fcf64b825cb.png)

I can use system classloader to load the class, but failed to use WebAppClassloader to load it.

![image](https://user-images.githubusercontent.com/7020808/69547648-f702ee00-0fd0-11ea-8184-880f581f55a4.png)

![image](https://user-images.githubusercontent.com/7020808/69547662-fa967500-0fd0-11ea-9e0a-81d02cc38d45.png)

Another arthas shell to load class, the other to watch & trace , I find the codes below 

![image](https://user-images.githubusercontent.com/7020808/69547669-fe29fc00-0fd0-11ea-8a38-da702f279a86.png)

`isServerClass` return `true`, but classes of Pinpoint should not be classes of Jetty!

How to fix it? This problem make it unable to tracing web apps using Jetty as container.

**Comment by joakime** [comment]
You have inverted the `WebAppContext.setParentLoaderPriority(boolean)`.
The default is `false`, make sure you are using that, otherwise the WebApp doesn't play by Servlet rules, but rather Java rules.

> `isServerClass` return `true`, but classes of Pinpoint should not be classes of Jetty!

Having `setParentLoaderPriority(true)` means exactly that, the webapp and all of the server and above classes belong to the webapp (in a classloader sense), and would favor its use from the parent classloader over the webapp specific version (in a classloader sense).

---

The Servlet 3.0 spec mandates a few things that are getting in the way.

First is the Classloader Isolation, and the requirement to poke holes for specific things (be it something like javax, or something more complex like a jdbc DataSource, a jndi resource, a Security provider, etc).  We need this ability to see what this class (and it's declarations of parents, and implemented interfaces, generics, etc) belongs to (webapp, jndi scope, server), where it belongs to (url location, esp important in the Java 9+ world), all via the `isServerClass()` call.  This is further nuanced by requiring some classes to always be loaded from the server classloader and not allowing the webapp to override them with local copies.

Next are the existence of classes that implement [`javax.servlet.ServletContainerInitializer`](https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContainerInitializer.html).
If those classes have a [`javax.servlet.annotation.HandlesTypes`](https://docs.oracle.com/javaee/7/api/javax/servlet/annotation/HandlesTypes.html) then the bytecode scanning has to occur.
This includes everything about the class (example: `@HandlesTypes({SecurityInterface.class})` would require us to scan all bytecode for anything that implements `SecurityInterface`).

----

**Comment by gregw** [comment]
How is your server classes configured?     In #4358 you propose changing the default return from combine.  However because there are by default inclusions in the server classes, that default return should never be executed.  So something else is going on.

**Comment by hoverwinter** [comment]
@gregw all default values.

![image](https://user-images.githubusercontent.com/7020808/69595790-7a592980-103b-11ea-91c8-ed8d958cb002.png)

I don't think this pattern match function `org.eclipse.jetty.webapp.ClasspathPattern#combine`  works well, the classes not appear in `org.eclipse.jetty.webapp.WebAppContext#__dftServerClasses` should be false not true?

**Comment by hoverwinter** [comment]
firstly, it has no matter whether the option is set true or false, the return value of `isServerClass` make it not possible to return the class loaded by parent.

secondly, the exception is thrown on line 565, I forget to put the backtrace, here is the call trace from arthas:

![image](https://user-images.githubusercontent.com/7020808/69594339-fe5ce280-1036-11ea-90d6-5e09d32c1a89.png)

@joakime I know the isolation, and I have read the codes about this problem, but the main problem is the logic below, true or false of `WebAppContext.setParentLoaderPriority(boolean)` has no impact on this.

```
// If the webapp is allowed to see this class
                    if (Boolean.TRUE.equals(__loadServerClasses.get()) || !_context.isServerClass(parentClass))
                    {
                        if (LOG.isDebugEnabled())
                            LOG.debug("PLP parent loaded {}", parentClass);
                        return parentClass;
                    }
```

The pattern match of `org.eclipse.jetty.webapp.ClasspathPattern#combine` make all classes not included or not  exclued in `org.eclipse.jetty.webapp.WebAppContext#__dftServerClasses` to be server classes (default value = true), in my case, the` _context.isServerClass(parentClass)` when loading `com.navercorp.pinpoint.bootstrap.interceptor.AroundInterceptor` return `true`, so pinpoint classes will not be return by WebAppClassloader.

Maybe there is a better way to make classes in bootstrap classloader visible to web apps, with jetty all default values?

**Comment by janbartel** [comment]
Please can you retest with a more recent version of jetty, like 9.4.24. An issue in this area was resolved recently, which may solve your problem, see: https://github.com/eclipse/jetty.project/issues/4183

**Comment by hoverwinter** [comment]
thank you
