### ISSUE TITLE
jetty-maven-plugin doesn't take into account generated / prepared phases in jetty:run

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#4422]
**Jetty version**
9.4.24

**Java version**
Any

**OS type/version**
Any

**Description**
If a project is using plugins that cause content (any kind of content) to be generated by the various standard `generate-*` and `prepare-*` phases, then the jetty-maven-plugin does not seem to include them for execution in `jetty:run`.

Note: these `generate-*` and `prepare-*` phases are not a problem for `jetty:run-war`

**Comment by janbartel** [comment]
Exactly. That's why we have the run-war goal. It would not be possible to work out which configuration parameters for all plugins refer to generated content locations. We treat the war plugin specially as it is very typically associated with war projects, but there are a kaleidoscope of other plugins that can be used and generate stuff in all manner of different ways.
