### ISSUE TITLE
Request to support non-SSL HTTP/2

### ISSUE THREAD

**Issue by judge2005** [eclipse/jetty.project#4440]
From what I understand, Jetty only supports HTTP/2 over SSL. This is a request to support it over a regular connection for use with isolated web service networks. A typical architecture is to terminate SSL at the edge, using an appliance or proxy such as an F5, and then use un-encrypted traffic between web service nodes on an isolated network. Traffic between networks would always be separately encrypted/decrytped at the edge.

**Comment by sbordet** [comment]
Jetty supports clear text HTTP/2 since the beginning of HTTP/2 support.

You want to use `HTTP2CServerConnectionFactory` and look at [this example](https://github.com/eclipse/jetty.project/blob/jetty-9.4.24.v20191120/jetty-http2/http2-server/src/test/java/org/eclipse/jetty/http2/server/HTTP2CServer.java).
