### ISSUE TITLE
RFC2616 Compliance Mode should track and report RFC7230 violations

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#448]
When the server is in RFC2616 compliance mode, and a request (or response) is encountered that would violate RFC7230 mode, this information should be tracked in a way that the webapp can utilize to triage problematic clients.

**Comment by gregw** [comment]
I've committed to a branch with 9352d91d48056272f6609a23baa794e28365f80f so that compliance violations are called out on a ComplianceHandler.   Default implementation is to log as debug in the server with the endpoint.

I am concerned that there are performance implications as an extra string compare is needed to avoid needed compliance logging.    Perhaps this is not a fix for general consumption?

**Comment by gregw** [comment]
@sbordet @joakime review please.

**Comment by joakime** [comment]
This is heading in the right direction, could use some tweaking.

Went ahead and added (to this branch) the following ...

 [`jetty-servlet/ComplianceViolations2616Test.java`](https://github.com/eclipse/jetty.project/blob/7be58f97308e5a3bde759170d75d0c5246faf60a/jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ComplianceViolations2616Test.java) - to demonstrate setup of `HttpConnectionFactory.setRecordHttpComplianceViolations(true)` and access to the violations from the web application (so that extra information from the request and/or HttpSession can be used to determine how to operate, including the ability to report the violations back on API calls)

Currently, the violations being reported are not indicating the correct compliance level they are violating (operating in 2616 mode, violating a 7230 spec, it should report that a 7230 spec was violated), and also there is a lingering empty header value issue (quoted empty) from Issue #451 still present.

**Comment by joakime** [comment]
This is now present in the jetty-9.3.x branch
