### ISSUE TITLE
Self-signed expired certificates not validated on client side?

### ISSUE THREAD

**Issue by steffyP** [eclipse/jetty.project#4517]
**Jetty version**
9.4.19.v20190610 but there is still the same code in the master repo

**Java version**
tested with 1.8 and 11 (but java version doesn't really matter)

**Question**
I recently discovered a problem when the certificate of my server expired. For testing reasons, we use self-signed certificates, however, I believe this shouldn't matter at all. 
When my client (using the jetty websocket client library) connects to the server, the certificate is trusted, and there is no indication that the certificate expired, and therefore should not be trusted anymore. 
I also tried to set validation for peers certs `sslContextFactory.setValidatePeerCerts(true)`.

I believe the `sslContextFactory.setValidateCerts(true)` is only relevant for server side? 
In `SslContextFactory.java`  this attribute is checked however, with the following code (line 321 on branch _jetty-10.0.x_), 
```
if (isValidateCerts())
{
    [.... shortened the irrelevant code part ....]
    validator.validate(keyStore, x509C); // TODO what about truststore?
   }
```
**So does this open TODO mean, that this has not been implemented?** Is there no certification validation on client side?

Thank you for any help and hints in advance.

**Comment by sbordet** [comment]
You don't clarify how you configure the client-side `SslContextFactory`.

However, if you have just one self-signed certificate, and you use that as a trusted certificate on the client (i.e. it's a `trustedCertEntry` in the client trust store), then the certificate is trusted and there are no checks on its validity, not even the time validity. 
This is how the JDK implementation works.

If you want to enforce time validity, you have to have:

on the server:
* a self-signed CA certificate, `ca_cert`.
* a server certificate `server_cert` signed by `ca_cert`

on the client:
* a trust store with `ca_cert`.

When `server_cert` expires, the JDK implementation will fail the time validity as you seem to expect.

When `ca_cert` expires you won't notice because it's trusted.
