### ISSUE TITLE
Jetty server always allocates maximum response header size

### ISSUE THREAD

**Issue by electrum** [eclipse/jetty.project#4541]
`HttpConnection` always allocates the full value of `HttpConfiguration.getResponseHeaderSize()`, regardless of how much memory is actually needed to write the response. My expectation is that it should work similarly to `getRequestHeaderSize()` which is only a maximum (setting it to a large value does not result in large allocations unless required).

For testing purposes:
```java
configuration.setRequestHeaderSize(1024 * 1024 * 1024); // this is fine
configuration.setResponseHeaderSize(1024 * 1024 * 1024); // this blows up
```

**Comment by joakime** [comment]
Those are insane configuration values for the Header size.
You open yourself to many kinds of other issues, and vulnerabilities, that the limited header sizes protect you from.
Plus, if you use those settings because you actually produce headers and whatnot of that size you'll hit issues with many HTTP Clients.

**Comment by joakime** [comment]
Both of those configurations allocate a java.nio.ByteBuffer at the configured size.
The problem isn't unique to response vs request.

**Comment by joakime** [comment]
The recommended maximum values for configured header data.

* Browsers (all modern) support up to 256kb (very few support larger header data, and of those the performance takes a huge hit)
* Proxies / Load Balancers support is stable up to 16kb (support for larger headers do exist, but is inconsistent)
* HTTP Client Libraries (eg: REST Clients) have stable support up to 16kb.

As for individual headers, most implementations have maximums as well (eg: Chrome is currently at 4kb per header now)

**Comment by gregw** [comment]
The difference between the two is parsing vs generation.   

When receiving a request, we read the bytes in smaller buffers and convert the header values to strings, fields etc as we go.  So the memory is being allocated, but not as a single byte buffer. We police the maximum as we receive the bytes.

When sending a message, we generate the header into a buffer that is allocated at the maximum size.  If we allocated smaller buffers, then we'd need to complicate the generator as it could buffer overflow at any point and then we'd have to reallocate, copy and continue generating, assuming we could start from where the overflow occurred.   As it is extremely rare to have large headers, it is not worth making the trillions of responses that don't need that complexity pay for the few that do.

**Comment by sbordet** [comment]
Or, put it in another way, we cannot generate 200 OK and some headers in the buffer, write over the network the buffer, then generate more headers in the buffer, only to figure out that they are too large, because at that point we should send a 5xx error but we cannot since we have already sent the 200.

We would have to pre-generate all headers, do the check on the max bytes and then generate (again) the headers.

**Comment by gregw** [comment]
I had a look at HttpGenerator and it would be feasible to check size before each putTo and if there was not space to return with an action asking for a larger buffer.  But it would be a moderate increase in complexity.

The other option would be to start with a smaller buffer and try generate.   If the buffer overflows, then the exception can be caught, the buffer discarded, are new larger buffer allocated and the whole generation tried again.   This could be made to work without any impact on normal generation, but would be inefficient for generating large headers.   However if we did it so that the first attempt used the network buffer size and if that overflowed we went straight to the max size, then it would not be too bad.

But we'd need to know the use-case for support such large response headers before we can say if this is feasible or meaningful

**Comment by electrum** [comment]
The values gave were for testing, since they immediately fail if anything allocates the max buffer size. We'd be targeting a max size of around 4MB.

The use case is that we have an existing protocol which uses HTTP headers for values and sometimes these values are quite large. We plan to change the protocol, but it's difficult due to backwards compatibility with existing clients, and making clients compatible with multiple versions of the server. Being able to support the existing protocol without huge memory requirements for every request would thus be very helpful.

The simpler approach outlined by @gregw would be fine for our use case, as very few responses are larger than the default buffer size. If helpful, we could even indicate this to Jetty somehow, such as by setting a specially named header on the servlet response. We start Jetty programmatically and control the entire stack, so we're open to any "clever" ideas you might have to make this work.

**Comment by gregw** [comment]
@electrum can you try #4544 
@sbordet what do you think of #4544 - I don't love it... and would kind of prefer to come up with pluggable behaviour... but we can consider this perhaps???

**Comment by electrum** [comment]
@gregw Thanks so much! I tried it out and this does exactly what we want. I'd be great if we can get this in an upcoming 9.4.x release.
