### ISSUE TITLE
Each 9.4.x maintenance release breaks links to preceding version's documentation

### ISSUE THREAD

**Issue by wilkinsona** [eclipse/jetty.project#4546]
A Spring Boot user has [reported](https://github.com/spring-projects/spring-boot/issues/20044) a problem with Spring Boot's reference documentation linking to Jetty's documentation. Spring Boot's reference documentation links to the Jetty documentation for the specific version of Jetty that it built against. For example, the documentation for Spring Boot 2.2.4 links to  https://www.eclipse.org/jetty/documentation/9.4.25.v20191220. Unfortunately, this link is now broken. As far as I can tell, the breakage occurred when 9.4.26 was released as its documentation replaced the documentation for 9.4.25.

I'm aware of the 9.4.x link but this points to snapshot documentation which we'd prefer not to use. I'm also aware of the current link, but this will, presumably, eventually link to 9.5.x or 10.x so it will become inaccurate over time.

Would it be possible to avoid breaking links by publishing new documentation in addition to rather than in place of the existing documentation. Failing that, would it be possible to provide a link for 9.4 that points to the latest release rather than the latest snapshot?

**Comment by joakime** [comment]
We have a "current" at https://www.eclipse.org/jetty/javadoc/current/
But that's not enough detail.  Especially as we are working towards Jetty 10.x (Jakarta EE 8 based) and 11.x (Jakarta EE 9 based) atm.

**Comment by WalkerWatch** [comment]
@wilkinsona Let me discuss with @jmcc0nn3ll. I think the idea has merits, as I know other projects in addition to Spring link to our documentation. We would need to create something like `/documentation/9.4.x/` for each major release version, in addition to `/documentation/current`, which should be feasible.

**Comment by wilkinsona** [comment]
We’ve stopped linking to Jetty’s documentation as a workaround for this problem. We’d still welcome a fix for it as it would allow us to reinstate the links.

**Comment by joakime** [comment]
@jmcc0nn3ll @WalkerWatch looks like the script to move docs to https://archive.eclipse.org/jetty/ isn't working again.

**Comment by jmcc0nn3ll** [comment]
It is not working because we stopped archiving things. I am open to replacing all of this but question the value of exposing generally the same documentation with updated version identifiers.  Major versions of Jetty may have unique documentation but within that major version each release of documentation is more an improvement then chronicling new changes or features.  IMO third parties should point to the best version of each major release documentation, which is the latest release.  I can be convinced otherwise of course, but knowing the way our documentation has been developed for years now that is how I see things.

**Comment by wilkinsona** [comment]
IMO, there's value in users being able to read documentation that's for the precise version that they're using. In my experience, it reduces the risk of frustration caused by trying to do something that the documentation describes but isn't actually possible in the version being used.

**Comment by joakime** [comment]
There's 3 camps for documentation archives in the open source community ...

### Option 1 - Archive it all

* https://docs.spring.io/spring-framework/docs/

### Option 2 - Only allow access to latest docs of major supported versions

Old, out of date, or end of life versions are not accessible anymore.

* https://netty.io/wiki/index.html
* https://tomcat.apache.org/


### Option 3 - just use javadoc.io

This is what projects like dropwizard, jersey, etc are using now.

Example: https://javadoc.io/doc/org.eclipse.jetty/jetty-server/9.4.42.v20210604/org/eclipse/jetty/server/CustomRequestLog.html

**Comment by jmcc0nn3ll** [comment]
All of the old jetty documentation versions are available in archived form in Maven central.  With modern editors the need for published javadoc is basically nil, it is all downloaded and available automagically in the editor, especially for specific versions.

Regarding documentation, within a major release, I think the ability for a user to read a chunk of documentation that has been rewritten for clarity is far more common then a user stumbling into a strange corner where a property was added that is not available in a previous release.  At least for Jetty, the common case is far more docs being improved for clarity then tweaked with a new feature (within major release versions).

Again, open to changing my opinion on it.

**Comment by wilkinsona** [comment]
Is the documentation for older minor releases of Jetty available online? I'm wondering about something like session management that was rewritten in 9.4. A user who's stuck on 9.3.x for whatever reason might want to read the older docs.

**Comment by jmcc0nn3ll** [comment]
Not on the website, but available here: 

https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-documentation/9.3.29.v20201019/

They all are since we moved off of the wiki.

There will always be every permutation of user stuck in odd situations, so documentation is always available for these releases, just not indexed or deep linkable online.  General rule of thumb we have tried to service is directing the majority of users, regardless of knowledge level, towards the latest, most likely quality resource to answer their problems.  

This does raise the point we should make it easier for someone in a rough situation to find their resources, @WalkerWatch could you add a line and link on the documentation page explaining where minor release documentation can be retrieved from?  That is an important thing to note.

**Comment by jmcc0nn3ll** [comment]
It is perhaps less of an issue now that we have documentation that is single page, but we were getting to the point where we had tens of thousands of pages of documentation that were the same content growing from release to release and each website update would take longer and longer.  I feel it important to note we are not trying to make these things disappear or harder on anyone, just try and cater to what we think is the most common scenarios for users.  Happy to consider alternate approaches, especially if they make life easier on other projects.
