### ISSUE TITLE
Jetty datasource bind using programmatically is not working. 

### ISSUE THREAD

**Issue by boopathiraja** [eclipse/jetty.project#4559]
We are using Jetty server and need an equivalent code for 

`<resource-ref>
    <description>cardsdb</description>
    <res-ref-name>jdbc/cardsdb</res-ref-name>
    <res-type>javax.sql.DataSource</res-type>
    <res-auth>Container</res-auth>
  </resource-ref>` 

How to add resource-ref programmatically in jetty server.
we tried multiple ways  like below

`Resource resource = new Resource("java:comp/env/" + jndiName, simpleDataSource);
    server.setHandler(context);`

but none of them are working. Please help.
Using version Jetty-webapp:9.4.9.v20180320

**Comment by janbartel** [comment]
https://www.eclipse.org/jetty/documentation/9.4.26.v20200117/using-jetty-jndi.html

The org.eclipse.jetty.plus.jndi.Resource constructor takes 3 args: an object that is the scope, the relative name, the object to bind.

**Comment by boopathiraja** [comment]
thanks for your response.
As per the above link, still I need to have the xml in any of the scope right.
I don't want to use any xml and just wanted to try everything programatically.

**Comment by janbartel** [comment]
Please describe how you intend to do the lookup of the resource in your application code. Are you doing it from inside a servlet/filter, and are you expecting to do it with code like:

>  InitialContext ic = new InitialContext();
>  DataSource something = (DataSource)ic.lookup("java:comp/env/jdbc/cardsdb");

Alternatively, if you bind your resources to the jvm scope (see the document I linked for what that means), you can just do lookups  inside your servlets/filters as:

>  InitialContext ic = new InitialContext();
>  DataSource something = (DataSource)ic.lookup("jdbc/cardsdb");

Or, regardless of however you scoped your Resouce declarations,  you could use annotations like @Resource in your code instead to inject the DataSource:

>     @Resource(mappedName = "jdbc/cardsdb")
>     public void setMyDatasource(DataSource ds)
>     {
>         myDS = ds;
>     }

**Comment by boopathiraja** [comment]
Basically I need to move the xml based deployment descriptor to programmatically.

Currently I have a 
`<resource-ref> <description>dbname</description> <res-ref-name>jdbc/dbname</res-ref-name> <res-type>javax.sql.DataSource</res-type> <res-auth>Container</res-auth> </resource-ref>`

how I can achieve the same in code.

**Comment by janbartel** [comment]
@boopathiraja you haven't given me enough information. I want to know how you are doing the lookup in your code, and whether you have any ability to make changes?

The servlet-spec way to do things without an xml descriptor is to use annotations, which is why I suggested using the @Resource annotation injection of your datasource.

If you can't change your servlet code to use annotations, then you're going to have to do all the work that jetty does behind the scenes for you to link up org.eclipse.jetty.plus.jndi.Resources that you declare in the container environment to the java:comp/env environment that is specific to your webapp. You'll need to have access to the classloader of the webapp (as the jndi java:comp/env environment is based on the webapp classloader). When you're configuring the WebAppContext, that classloader won't exist, so you'll have to create your own, and set it on the WebAppContext. Then, you'll need to ensure that it is set as the TCCL, then:

```java
//create the java:comp/env namespace: 
Context context = new InitialContext();
Context compCtx = (Context)context.lookup("java:comp");
 compCtx.createSubcontext("env");

//link the names from your org.eclipse.jetty.plus.jndi.Resources to your java:comp/env namespace:
org.eclipse.jetty.plus.jndi.NamingEntryUtil.bindToENC(scope, name, mappedName);
//where:
// scope is the object you passed as the first arg to your org.eclipse.jetty.plus.jndi.Resource call
// name is the name you want to reference in your webapp namespace  eg "jdbc/myds"
// mappedName is the name from the container space that you gave as the 2nd arg to your org.eclipse.jetty.plus.jndi.Resource call eg "jdbc/mydatasource"
```
Make sure you set the TCCL back after doing this setup.

By far the easiest thing to do is to use annotations instead.

**Comment by boopathiraja** [comment]
okay make sense. thanks for your help.
