### ISSUE TITLE
Create Jetty 11.x Branch

### ISSUE THREAD

**Issue by WalkerWatch** [eclipse/jetty.project#4568]
We need to decide when to spin off the Jetty-11 branch, and then do so.

**Comment by joakime** [comment]
Some dependencies we need to track.

### APIs from Jakarta EE 9 and implementations:

 - [x] **Servlet API** - available as Milestone - https://repo1.maven.org/maven2/jakarta/servlet/jakarta.servlet-api/5.0.0-M1/
 - [x] **WebSocket API** - available as Milestone - https://repo1.maven.org/maven2/jakarta/websocket/jakarta.websocket-api/2.0.0-M1/
 - [x] **JSP API** - 
 - [x] **JSP Implementation** - Apache Jasper? or Glassfish Jasper?
 - [x] **JSTL API** - probably decided for us when we choose the JSP implementation.
 - [x] **EL API** - available as RC https://repo1.maven.org/maven2/jakarta/el/jakarta.el-api/4.0.0-RC1/
 - [x] **JAAS API** - (No effort required, [part of the `java.base` module in Java 11](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/javax/security/auth/callback/package-summary.html))

**Comment by gregw** [comment]
As an alternative, I'd like to consider making servlet-5.0 support an optional modules within jetty-10, so that it can support both servlet 4.0 and 5.0.  It would do this initially by facading the 5.0 API to run directly on top of the Jetty request/response/context/etc. even though they are dependent on 4.0.

The main issue will be how to support request/response wrapping as we currently depend on the 4.0 servlet-API in the handler signature.  However, there are alternate mechanisms for this.

**Comment by gregw** [comment]
I have created #4578 to discuss the alternative approach for supporting jarkata APIs within jetty-10.
If that approach is successful, then jetty-11 should only be created once we decide to rearchitect the core of jetty to be independent of any servlet version.

**Comment by joakime** [comment]
I see Jasper 10.0.0-M1 available on maven central now - https://search.maven.org/artifact/org.apache.tomcat/tomcat-jasper/10.0.0-M1/jar

**Comment by joakime** [comment]
This has been completed a long time ago.
