### ISSUE TITLE
NoSuchMethodError: javax.servlet.ServletContext.createServlet(Ljava/lang/Class;)Ljavax/servlet/Servlet;

### ISSUE THREAD

**Issue by kvopencode** [eclipse/jetty.project#4635]
**Jetty version**
9.4.27.v20200227

**Java version**
1.8.0_201

**OS type/version**
Red hat enterprise server linux 6.1 (Santiago)

**Description**
@sbordet - when a http resource is requested i get the below error and 500 server error. 
Can you please check and help here ? Let me know if you need any further information.
<img width="1062" alt="Screenshot 2020-03-04 at 10 59 03" src="https://user-images.githubusercontent.com/954768/75874988-bfdf7c80-5e0a-11ea-9571-cc153e8ce81e.png">

**Comment by kvopencode** [comment]
WARN HttpChannel: /rest/mypage

**Comment by joakime** [comment]
`ServletContext.createServlet()` was added in Servlet 3.0

See: https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContext.html#createServlet-java.lang.Class-

That means your Jetty setup is using an old Servlet API jar (probably 2.5 or 2.4)

Since you are using Jetty 9.x you should be using Servlet 3.1

See: https://stackoverflow.com/questions/44730096/javax-servlet-http-httpservletresponse-getstatus-not-found/44730174#44730174

**Comment by kvopencode** [comment]
@joakime Thanks for your pointers. It worked well. My app had indeed javax-servlet-api 3.1 jar
but i found conflicts of javax.Servlet class with other jars tomcat, weblogic etc. 
I removed the mvn dependencies of the jar and it worked well. Attached other jars which were causing the conflict
<img width="169" alt="Screenshot 2020-03-04 at 12 20 07" src="https://user-images.githubusercontent.com/954768/75879114-b1955e80-5e12-11ea-80c4-8ea5933de91c.png">

**Comment by joakime** [comment]
@kvopencode you might want to use https://github.com/basepom/duplicate-finder-maven-plugin to see what other duplicate classes you have present.
It's really fishy that you have `tomcat-servlet-api-<ver>.jar` and `weblogic-<ver>.jar` on your classpath when using Jetty.
