### ISSUE TITLE
maxFormContentSize fix in Issue #3856 broke JenkinsCI/Winstone

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#4638]
Note that this is incompatible as seen in https://github.com/jenkinsci/winstone/pull/95/commits/8a8a146c88e55e2258e063a041fb43c21753cf5b.

_Originally posted by @jglick in https://github.com/eclipse/jetty.project/pull/3899_

---

The fix in PR #3899 (Issue #3856) seems to have broken JenkinsCI

**Comment by joakime** [comment]
@jglick it's not obvious from your linked testcases ( https://github.com/jenkinsci/winstone/commit/8a8a146c88e55e2258e063a041fb43c21753cf5b ) what is happening on your testcase.

Can you explain that testcase some?

**Comment by jglick** [comment]
The test case in https://github.com/jenkinsci/winstone/pull/95 was merely adding retroactive coverage for a longstanding bit of code in Jenkins which attempted to set a maximum form content length (by default to -1, i.e., no maximum). I think it should be pretty self-explanatory: submit some really big forms and see if the servlet is able to process parameters without error.

The original method Jenkins used to do this was to set a named attribute on the `Server`. This worked until #3899, which began unconditionally honoring the value from a `ContextHandler` if one exists (which in the case of Jenkins it always did), even if the `Server` attribute was overridden (say, to -1) and the `ContextHandler` value was the system default of 200_000. The fix was to call the setter on `ContextHandler` rather than use the `Server` attribute.

Make sense now? This may be too obscure a corner case to bother restoring compatibility for in Jetty; we already have a fix.

**Comment by joakime** [comment]
@jglick thank you for the explanation.

There were a few reasons for the change in behavior here.

1. the Issue #3856 report where there was a difference in behavior with HTTP/1 and HTTP/2 and whether or not the `Content-Length` header was present (lack of that header has meaning on HTTP/1 but HTTP/2 doesn't need or use the header)
2. We had others asking for per-context based configuration of the various max form limits (size / length / etc), which was not possible with the old server attribute.
3. Those that wanted different behavior of the max form limits on a per path or even a per request scope had no options other then to set the server attribute to the other value and then run the request extraction and then restore the server attribute (as you can probably understand this isn't a great idea)

So the change in PR #3899 attempted addressed all 3 scenarios.  But it seems on jenkinsci it broke the server defaults. :-/

**Comment by olamy** [comment]
so in case of an existing context server configuration is not read anymore I guess we need to fix the code or the doc :) 

https://www.eclipse.org/jetty/documentation/current/configuring-form-size.html  

> If a context does not have specific form limits configured, then the server attributes are inspected to see if a server wide limit has been set on the size or keys

**Comment by gregw** [comment]
@joakime @olamy can this be closed? what needs to be done prior to 9.4.28?

**Comment by joakime** [comment]
Fixed in PR #4740
