### ISSUE TITLE
HttpChannel recycling in h2

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#4695]
Currently `h2` does not recycle the `HttpChannel`.   This does create more garbage and also invalidates the `Cookie` caching done in `CookieCutter` (see #1056 )

It is unclear why recycling is not done in h2.  If it is not possible, then a definitive reason should be known.
We probably also need to do some benchmarks to see if HttpChannel recycling is still beneficial.

We should either recycle for both h1 and h2, or we should recycle for neither and pull out the recycling machinery and caches.

**Comment by sbordet** [comment]
See also #2188.

**Comment by lorban** [comment]
See also #3673.

**Comment by lorban** [comment]
The approach I've taken to answer this question is a bit upside down. I started by writing a benchmark I could use to measure the amount of garbage Jetty normally generates.

In the simplest case, where a single client loads the server with 8 threads doing GET requests and the server responds with a static hardcoded message as to avoid generating any garbage, according the the Flight Recorder, Jetty itself generates about 50 MB/s of garbage when serving HTTP 1.1 and about 200 MB/s when serving HTTP 2. In the case of HTTP 2, the largest offender in heap allocation actually is the HttpChannel allocation, which about for about 50% of the garbage when taking into account the entire object graph attached to the channel.

So the above answers the first question: is HttpChannel recycling is still beneficial? Yes, definitely.

I then re-ran the same benchmark after enabling HTTP 2 channel recycling and I could never manage to get it running to completion. After investigating, it appears that I'm hitting the problem reported in #3673. After another investigation, @sbordet figured out that there's a race condition in the HTTP 2 stream creation code, and that fixing it would require modifying the code in a way similar to what should be done for #2188, while the motivation for the latter actually was a performance improvement.

As a summary:
 - Channel recycling is beneficial.
 - Disabling it does not impact latency, only the max theoretical throughput.
 - Re-enabling it by default for HTTP 2 should be done.
 - This requires fixing a race condition (maybe more than one?) in the client code.
 - Fixing the client will have a side effect of getting rid of one of known bottleneck.
 - This issue is about killing three birds with a single stone: lowering the generated garbage, fixing an old, well-known race condition, improving concurrency of the client.

**Comment by lorban** [comment]
I pushed a draft PR: https://github.com/eclipse/jetty.project/pull/4801

**Comment by sbordet** [comment]
@lorban does it work? So far looks good to me - do you have more changes to this PR?

**Comment by lorban** [comment]
Channel recycling does work with these changes in place, yes. I still need to import the tests you wrote, look at the coverage and perform a few more benchmarks with more complicated code (POST, respond with more data, more clients, errors...) but so far, I'm happy it didn't take too much to make your original changes work, and that they fixed the bug.

**Comment by sbordet** [comment]
Fixed in #4803.
