### ISSUE TITLE
Scan annotations even if web.xml is 2.5

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#4727]

**Comment by janbartel** [comment]
@olamy I'm not in favour of this change.  Servlet spec 4.0 might say this, but we have a user base that specifically didn't like this behaviour.

We had users complain that they didn't change their web application for years, but an upgrade to the jetty container made their webapp misbehave due to the existence of annotations in 3rd party libs used by the webapp.

Similarly, we had other users complain that a 2.5 webapp was now being subjected to full annotation scanning and causing a lot of lost startup time.

Our solution is to have the WebAppContext.setConfigurationDiscovered(boolean) method, which by default is set to `false`. Setting it to `true` will result in annotation scanning taking place regardless of the version of the web descriptor. I suggest we set this to `true` for the execution of the relevant tck tests.

**Comment by gregw** [comment]
@janbartel perhaps in 10 we should default to true but keep the boolean so users can revert?

**Comment by joakime** [comment]
> @janbartel perhaps in 10 we should default to true but keep the boolean so users can revert?

I'm in favor of having Jetty 10.x be default of true.
And keeping around the `.setConfigurationDiscovered(boolean)` for those users & applications that want to use it.

**Comment by olamy** [comment]
I agree with  the change for 10.x default and having it configurable. Not matter of the version

**Comment by olamy** [comment]
see https://github.com/eclipse/jetty.project/pull/4732

**Comment by gregw** [comment]
@janbartel has pointed out the issue that we have some very large deployments that have lots of 2.5 webapps, that do not want to pay the price of scanning for annotations that are not there.   So if we do change the default, then I think we need to do some clear warnings if 2.5 webapps are deployed and that configuration has not been set eitherway.

**Comment by olamy** [comment]
merged
