### ISSUE TITLE
Proposal: rename DecryptedEndPoint to SslEndPoint

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#4731]
**Jetty version**
10.0.x

**Description**
`SslConnection` nests an `EndPoint` called `DecryptedEndPoint` that is the endpoint that is fed with decrypted bytes for the unencrypted protocol (e.g. HTTP).

Looks like this:

```
SocketChannelEndPoint --> SslConnection --has-a--> DecryptedEndPoint --> HttpConnection
```

However, the `DecryptedEndPoint` is not really "decrypted" since it handles both the encryption and decryption.

I propose to rename it to `SslEndPoint` to match `SslConnection`. 

Thoughts?

**Comment by joakime** [comment]
I see the word "Decrypted" in `DecryptedEndPoint` as the interface it provides to me.
I use it in a decrypted way, reading / writing to it.
The underlying implementation is doing the encryption / decryption where necessary.

It's like the File object, I use "File", not "IO Descriptor" or "File Descriptor" or "Block device" or "INode" to do what I need with it.

Also, why stick with the old term "SSL", and not the more up to date term "TLS"?
Eg: `TlsEndPoint` and `TlsConnection`.

Or just using a neutral term for encryption vs decryption?
Eg: `CipherEndPoint`, or `CryptographicEndPoint`, or `CryptoEndPoint`, or `CrypticEndPoint`

**Comment by gregw** [comment]
I agree with @joakime, the "Decrypted' part of the name refers to the contract of the interface that it implements, so in this case the fill/flush calls are passed/provide decrypted bytes.
"SslEndPoint" is confusing to me, as the original `SocketChannelEndPoint` is the endpoint that is handling SSL, so that name feels wrong.

I guess "Unencrypted" would technically be more correct than "Decrypted".  The SslEngine interface refers to that side of the conversation as "Application" and "plaintext bytes", so if you really want to rename then perhaps one of:

- `UnencryptedEndPoint`
- `AppEndPoint`
- `AppDataEndPoint`
- `ApplicationEndPoint`
- `PlainTextEndPoint`  (Even if it is not text???)

**Comment by sbordet** [comment]
All right, no need to change the name then.
