### ISSUE TITLE
File Descriptor Leak with TCP ping

### ISSUE THREAD

**Issue by Amarendraar23** [eclipse/jetty.project#4733]
Jetty version = 9.4.25
Java version = ibm-java-x86_64-80-sr5-fp40
OS type/version = Red Hat Enterprise Linux Server release 7.7
We are doing TCP pings to Jetty server to see if the web server is up and alive. This TCP ping involves FULL_CLOSE TCP connection. After certain time we see sudden spike in file descriptor leaks. This can be seen happening with the connection between the TCP ping with Jetty web server. The connection from Jetty side is not closing cleanly by not sending a FIN packet intermittently. Once the FD leak reaches the ulimit level the JVM crashes.

**Comment by sbordet** [comment]
@Amarendraar23 do you have proof? 

I ask because I just wrote a test case that opens and immediately closes a connection to a Jetty server in a tight loop, and I don't see any file descriptor leak, nor any problem of any kind.

If you can reproduce the problem, please attach to this issue full server-side DEBUG logs of this "ping" so we can analyze it.

We ask for proof and DEBUG logs because we have many reports of these leaks and failures, and almost all the times it is not Jetty the cause but something else (e.g. faulty load balancers, faulty clients, JVM bugs, etc.)

Make sure you are using the latest JVM. 

Can you upgrade to Java 11 or later and reproduce the issue?

**Comment by Amarendraar23** [comment]
@sbordet  Yes i do see file descriptor leaks at the jetty side. I am in the process of redacting the logs for sensitive information. Will share it after the redaction.
The issue is seen only after certain duration(i.e. few days). We don't have any event that is different than usual at that point that could trigger these leaks.
I do have one question regarding handling TCP pings from jetty server. Do you recommend using a ProxyConnector rather than using HTTPConnector to handle these pings as mentioned in below link? 
https://www.eclipse.org/jetty/documentation/9.4.x/configuring-connectors.html

**Comment by sbordet** [comment]
@Amarendraar23 how sure you are that this is not a problem of the IBM JVM? 
Have you tried to use OpenJDK? 
Have you tried Java 11?

`ProxyConnector` and `HTTPConnector` are not Jetty classes, they are not mentioned in the link you refer to, so I am not sure what you mean.

**Comment by joakime** [comment]
I think you can use `nping` (from the `nmap` project) to perform the TCP ping.

```
$ sudo nping --tcp -c 1 -p 80 192.168.1.217
Starting Nping 0.7.60 ( https://nmap.org/nping ) at 2020-03-31 15:31 CDT
SENT (0.0497s) TCP 192.168.1.217:50061 > 192.168.1.217:80 S ttl=64 id=25693 iplen=40  seq=3295555692 win=1480 
RCVD (0.2310s) TCP 192.168.1.217:80 > 192.168.1.217:50061 RA ttl=64 id=0 iplen=40  seq=0 win=0 
 
Max rtt: 181.255ms | Min rtt: 181.255ms | Avg rtt: 181.255ms
Raw packets sent: 1 (40B) | Rcvd: 1 (40B) | Lost: 0 (0.00%)
Nping done: 1 IP address pinged in 1.09 seconds
```

**Comment by sbordet** [comment]
Closing as no further information was provided.
