### ISSUE TITLE
wantClientAuth behavior

### ISSUE THREAD

**Issue by garan82** [eclipse/jetty.project#4769]
I think it's not specific to jetty/java version so I omit them. I'm wondering if `wantClientAuth` is true, and client provides client cert, is this cert validated against the CA during SSL handshake? Thanks.

**Comment by sbordet** [comment]
> I'm wondering if wantClientAuth is true, and client provides client cert, is this cert validated against the CA during SSL handshake?

Yes it is validated.

Typically the client certificate is signed by a server certificate (stored in a trustStore) rather than a CA (although it could be signed by a CA).

The verification is done by the TLS implementation, controlled by `SslContextFactory.endpointIdentificationAlgorithm` and by `SslContextFactory.hostnameVerifier`.
Please read the javadocs of those 2 properties to understand how they interact.

**Comment by joakime** [comment]
Also, the behavior for those to setters on Jetty's `SslContextFactory` result in Jetty setting the `javax.net.ssl.SSLParameters` for those options (with the same name).

* [`javax.net.ssl.SSLParameters.setNeedClientAuth(boolean)`](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLParameters.html#setNeedClientAuth-boolean-)
* [`javax.net.ssl.SSLParameters.setWantClientAuth(boolean)`](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLParameters.html#setWantClientAuth-boolean-)
