### ISSUE TITLE
Bad Content-Encoding values are not supported when used in combination with POST request (Content-Type: application/x-www-form-urlencoded)

### ISSUE THREAD

**Issue by pradeep-panda** [eclipse/jetty.project#4785]
Hi Team, 
I am running the jetty server to expose my rest APIs. Back end APIs are receiving  "UTF-8" as the "Content-Encoding" header value, but jetty is not accepting it and ending with 
"org.eclipse.jetty.http.BadMessageException: 501: Unsupported Content-Encoding" exception.

I am seeing this part of the code where the validation is failing and leading to this issue. I m kind of block on this. Any help is really appreciated.

( Requirements: I m trying to read the value using getParameterMap() method of HttpServletRequest )

ClassName and method name : "org.eclipse.jetty.server.Request.extractContentParameters()"

Code block ::
     if (_metaData != null)
                    {
                        String contentEncoding = getHttpFields().get(HttpHeader.CONTENT_ENCODING);
                        if (contentEncoding != null && !HttpHeaderValue.IDENTITY.is(contentEncoding))
                            throw new BadMessageException(HttpStatus.NOT_IMPLEMENTED_501, "Unsupported Content-Encoding");
                    }

stack trace ::
org.eclipse.jetty.http.BadMessageException: 501: Unsupported Content-Encoding
	at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:517)
	at org.eclipse.jetty.server.Request.getParameters(Request.java:430)
	at org.eclipse.jetty.server.Request.getParameterMap(Request.java:1068)

**Comment by joakime** [comment]
The `Content-Encoding` header has the following behavior ...

Documented in the spec RFC 7231 - Hypertext Transfer Protocol (HTTP/1.1): Semantics and Content
Section: 3.1.2.1.  Content Codings
https://tools.ietf.org/html/rfc7231#section-3.1.2.1

```
   The "Content-Encoding" header field indicates what content codings
   have been applied to the representation, beyond those inherent in the
   media type, and thus what decoding mechanisms have to be applied in
   order to obtain data in the media type referenced by the Content-Type
   header field.  Content-Encoding is primarily used to allow a
   representation's data to be compressed without losing the identity of
   its underlying media type.
```

The only valid values for that header are listed at 
https://www.iana.org/assignments/http-parameters/http-parameters.xhtml#content-coding

Of which, Jetty only supports `gzip` or `identity` when received on a Request header.

The value `utf-8` is never a valid value for the `Content-Encoding` header, either as a Request header or a Response header under any interpretation of the HTTP spec (past and present).
I suspect you meant to specify the encoding for mime-type, or for the form values.

If it's the mime-type, then you use the `Content-Type: <mime-type>; charset=<charset>` syntax.
Such as ...

```
Content-Type: text/plain; charset=utf-8
Content-Type: text/html; charset=Shift_JIS
Content-Type: application/octet-stream; charset=iso-8859-1
```

But seeing as you pointed out in your stacktrace the use of `org.eclipse.jetty.server.Request.extractContentParameters()`
Then that means you are actually using a POST request with `Content-Type: application/x-www-form-urlencoded`
That mime-type is always restricted to printable 7-bit US-ASCII.

But as it's encoded (notice the "urlencoded" in the mime type?), you can have it represent almost anything, in any charset.

But then you have to pass with that form, what charset the form value are encoded in.

**Using the Servlet spec to specify the charset before accessing the form value**

You'll have to obtain the charset from the request first.
Then you set the request character encoding, and THEN ask for a request parameter.
You cannot use any of the request.getParameter() methods to obtain the form charset value.

``` java
protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
{
    String formCharset = getCharsetOfFormFromRequest(request);
    request.setCharacterEncoding(formCharset);
    String userName = request.getParameter("UserName");
}
```

Since you have out of spec clients that are not using Content-Encoding properly, you should get them to use a unique request header field, such as `X-Form-Charset: utf-8`.
Make sure you use `X-` prefix on that header to be compliant to the HTTP spec.

This charset limitation of the old school `application/x-www-form-urlencoded` is pointed out here -> https://tools.ietf.org/html/rfc7578#section-5.3

**Using multipart/form-data spec**

The better option would be to use the `multipart/form-data` techniques to send your form from the client.

Include in the form itself, a field called `_charset_` which is the charset used to decode the form values.
This is documented in the multipart/form-data spec -> https://tools.ietf.org/html/rfc7578#section-4.6

If you are using a browser, you can even include a hidden form field in your HTML that will automatically populate based on the browser and/or document charset in use.

Example:

``` html
<form method="POST" enctype="multipart/form-data" action="/submit-form">
    <input type="hidden" name="_charset_"/>
    <input type="text" name="UserName"/>
    <input type="Submit" value="Submit">
</form>
```

That's it, you have no other work to do on the Servlet side.
You can use ...

``` java
protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
{
    String userName = request.getParameter("UserName");
}
```

You can see an example of this in our test cases.

* The [Raw multipart/form-data sent from Chrome from a Japanese user](https://github.com/eclipse/jetty.project/blob/jetty-9.4.28.v20200408/jetty-http/src/test/resources/multipart/browser-capture-sjis-charset-form-chrome.raw).
* The [Expected values from that form](https://github.com/eclipse/jetty.project/blob/jetty-9.4.28.v20200408/jetty-http/src/test/resources/multipart/browser-capture-sjis-charset-form-chrome.expected.txt#L15-L18).

**Comment by pradeep-panda** [comment]
@joakime Thanks for the elaborate explanation. Let me reassess and change based on your suggestions. I tried removing Content-Encoding value from the header and it just worked fine.

Note : I tested passing "gzip" instead of utf-8, but it did not work and faced the same exception.
The application was working fine with "Content-Encoding: utf-8" in jetty-7.4 version, but we started facing this issue when upgraded to jetty9.4.

**Comment by joakime** [comment]
Closing, as `Content-Encoding: utf-8` is a bad header value, the `utf-8` value is not a content encoding, but rather a charset encoding.

**Comment by allenleung86** [comment]
> @joakime Thanks for the elaborate explanation. Let me reassess and change based on your suggestions. I tried removing Content-Encoding value from the header and it just worked fine.
> 
> Note : I tested passing "gzip" instead of utf-8, but it did not work and faced the same exception. The application was working fine with "Content-Encoding: utf-8" in jetty-7.4 version, but we started facing this issue when upgraded to jetty9.4.

I tested passing "identity", it works
