### ISSUE TITLE
Does Jetty support TLS v1.3 on OpenJDK11?

### ISSUE THREAD

**Issue by pkcs11newbie** [eclipse/jetty.project#4799]
Hello

jetty version - 9.4.26.v20200117

Java version - OpenJDK11

We have jetty embedded server application and we need to explore our application for TLS v1.3 support. Do we need to provide IncludeProtocols information in jetty configuration file ( for TLSv1.3?

I was under the impression that since OpenJDK11 supports TLSv1.3 by default, no need for such configuration in jetty. 

Please do let me know.

Thanks in advance ..

**Comment by sbordet** [comment]
You don't need to specify TLSv1.3, it is enabled by default in Java 11 or later.

**Comment by pkcs11newbie** [comment]
Thank you for the response and changing the title.

Am I understanding this correctly then ?  As long as the underlying JVM supports the protocol (in this case OpenJDK11 by default supports TLSv1.3), jetty (9.4.26.v20200117) will support as well? 
We do not need to add below highlighted setting in jetty configuration for our embedded jetty server application ?
![image](https://user-images.githubusercontent.com/30663103/79984894-6b05cd00-846f-11ea-89ba-3ead693a7e84.png)

Thanks in advance..

**Comment by sbordet** [comment]
@pkcs11newbie your understanding is correct: as long as the JVM supports TLS 1.3 (Java 11+) then recent Jetty 9.4.x also supports it, and no need to explicitly configure it in `SslContextFactory`.

However, remember that the TLS protocol is negotiated between client and server.
Even if it is enabled on the server, the client may not support it and will fall back to TLS 1.2.

**Comment by pkcs11newbie** [comment]
Thanks again ...

**Comment by pkcs11newbie** [comment]
Hello..

Am I using TLS v1.3 protocol ? I see references to TLSv1.2 in the log 

jetty version - 9.4.26.v20200117 
Java version - OpenJDK11.0.4
Firefox version - 70

Based on below pic, i would think jetty embedded server is TLS v1.3:
![image](https://user-images.githubusercontent.com/30663103/80149866-ff118a80-857c-11ea-977b-e62484209a7f.png)

Handshake:
[Handshake.log](https://github.com/eclipse/jetty.project/files/4525471/Handshake.log)

References to TLSv1.2 in client version and server version and elsewhere is throwing me off ...

Appreciate if you could confirm negotiation is indeed TLS v1.3

Thankyou.

**Comment by sbordet** [comment]
It is TLSv1.3.

Search for "1.3" in your logs and you will see that it is the only protocol the client supports, and the server negotiates it with the client.

**Comment by pkcs11newbie** [comment]
Thank you for confirming..

My bad I should have checked out TLSv1.3 draft. it clearly has this section.. 
![image](https://user-images.githubusercontent.com/30663103/80215982-fcf20f00-8602-11ea-9c2e-a8d6f8d6e773.png)

**Comment by durga-kumari-tfc** [comment]
HI Team, I have to set jdk.tls.client.protocols="TLSv1.2" in Jetty so that any AWS calls happen can be enabled only with TLS1.2 and not 1.3. I don't see SslClientConnectionFactory settings. We already have Jetty SSL enabled. Will it work if I set SslContextFactory.addExcludeProtocols ?

**Comment by joakime** [comment]
@durga-kumari-tfc perform a Server dump.

See https://eclipse.dev/jetty/documentation/jetty-12/operations-guide/index.html#og-troubleshooting-dump

Then look at your SslContextFactory configuration details.
See example output in https://github.com/jetty/jetty.project/issues/4799#issuecomment-618690960

Keep in mind that simply enabling a specific protocol in the JVM is often not enough.
You have to also be careful about what related cipher suites you want to use with the specific protocol as well.
This is because the JVM will disable cipher suites as they become dropped by the general internet due to security issues.
This can be a complete drop of the cipher suite entirely, or a partial drop (such as mandating a minimum bit size), or a required crypto layer is dropped rendering the cipher suite unusable (or the crypto of the certificates in your keystore become invalid and the SSL/TLS cannot be negotiated)
See https://www.java.com/en/jre-jdk-cryptoroadmap.html

Finally, AWS supports TLSv1.3 in all of their products as of Mar 22, 2023 (the final product, ALB was finished then).
