### ISSUE TITLE
Review PathSpec classes

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#4877]
The current implementation of PathSpec is an abstract base class with mutable protected fields.
PathSpec itself is immutable once constructed, so it would be best if the fields themselves were final and private.  Perhaps the class should just be an interface?

**Comment by gregw** [comment]
@lachlan-roberts @joakime @lorban Can one of you have a look at this.  Not high priority, but would be nice to clean up and API changes before 10.0.0.

**Comment by lorban** [comment]
Here's a first attempt at refactoring the PathSpec hierarchy: https://github.com/eclipse/jetty.project/pull/4884

One issue I haven't tackled yet is the `PathSpec.getRelativePath()` method that's not tested, not used and only implemented in `ServletPathSpec`. Maybe it should go away?

**Comment by lachlan-roberts** [comment]
@lorban I merged PR #4884 however the tests are failing since I merged these changes to jetty 10 and 11. 

See
https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-10.0.x/19/tests

I have tracked this down to that the `PathSpec.equals()` method is no longer implemented so it is comparing references. So now the code at `PathMappings.get(PathSpec)` is no longer working. A simple fix would be use `PathSpec.compareTo()` here instead, but maybe it would be better to bring back the `PathSpec.equals()`.

**Comment by lorban** [comment]
@lachlan-roberts Thanks for the heads up; this test failure in 10.0.x uncovered some long-standing bugs and hairy problems.

 - `PathMappings.remove()` lacked a if-null check that made it throw when a `UriTemplatePathSpec` with a group of type `EXACT`, `PREFIX_GLOB` or `SUFFIX_GLOB` was removed.
 - The `Comparable.compareTo()` and `Object.equals()` could disagree when their declaration was the same but not their group or specLength. 

I've added to the javadoc of `PathSpec` that `equals` and `hashcode` have to be implemented and overridden `equals()` in each of the `PathSpec` implementations by basically doing a `return compareTo(other) == 0` which makes `equals()` and `compareTo()` at peace.

I believe I didn't break the existing behavior in any way by doing so but I'd appreciate some reviews, especially from @joakime as he changed the `UriTemplatePathSpec.compareTo()` implementation.

**Comment by gregw** [comment]
I believe this is complete.  @lorban @lachlan-roberts reopen if it is not.

**Comment by fluidsonic** [comment]
FYI this made it as a binary-incompatible change into patch 9.4.30. Not sure if that's intentional.

9.4.29:
https://github.com/eclipse/jetty.project/blob/77c232aed8a45c818fd27232278d9f95a021095e/jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathSpec.java#L24

9.4.30:
https://github.com/eclipse/jetty.project/blob/271836e4c1f4612f12b7bb13ef5a92a927634b0d/jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathSpec.java#L26

At runtime:
```
java.lang.IncompatibleClassChangeError: Found interface org.eclipse.jetty.http.pathmap.PathSpec, but class was expected
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:455)
```

**Comment by KenActifio** [comment]
> FYI this made it as a binary-incompatible change into patch 9.4.30. Not sure if that's intentional.
> 
> 9.4.29:
> https://github.com/eclipse/jetty.project/blob/77c232aed8a45c818fd27232278d9f95a021095e/jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathSpec.java#L24
> 
> 9.4.30:
> https://github.com/eclipse/jetty.project/blob/271836e4c1f4612f12b7bb13ef5a92a927634b0d/jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathSpec.java#L26
> 
> At runtime:
> 
> ```
> java.lang.IncompatibleClassChangeError: Found interface org.eclipse.jetty.http.pathmap.PathSpec, but class was expected
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:455)
> ```

I get the same error with 9.4.30 or later. This is a breaking change and should be fixed.

**Comment by joakime** [comment]
@KenActifio the error you are getting is because you have different versions of Jetty components/libs/jars in your classloader.
That's not supported or recommended.
The classes in the `jetty-http` are internal classes shared by many components.
In your case, the ServletHandler (from jetty-servlet) and the PathSpec (from jetty-http) are on different versions of Jetty.

Align your versions to the same version.  
Consider using the [`jetty-bom`](https://search.maven.org/artifact/org.eclipse.jetty/jetty-bom) to fix your issue.

Also, make sure you don't have inappropriate jetty jars in your `WEB-INF/lib` (such as `jetty-http-<ver>.jar` or `jetty-util-<ver>.jar` or `jetty-io-<ver>.jar` to name just a few common ones)
Example, if you have `jetty-client-<ver>.jar`, you should probably be using the `<classifier>hybrid</classifier>` version in your `WEB-INF/lib` instead as that has been shaded and uber-jar'd to include all it needs without causing conflicts.

**Comment by KenActifio** [comment]
Ah, you're right. jersey-container-jetty-http 2.34 pulled in Jetty 9.4.28. Sneaky devil. Turns out I don't need that dependency, so all good now.

I couldn't get the jetty-bom to work; never used a bom in maven before and couldn't find examples.

**Comment by joakime** [comment]
To use a bom ...

``` xml
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-bom</artifactId>
        <version>${jetty.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```

**Comment by KenActifio** [comment]
Thanks, Joakim. I tried that but it didn't work, at least in IntelliJ. No worries.
