### ISSUE TITLE
ServletInputStream.isReady() gets stuck in always true at EOF with async servlet

### ISSUE THREAD

**Issue by bakksjo** [eclipse/jetty.project#489]
Since Jetty 9.3, the behavior of async servlets has changed and no longer matches our expectations.

Previously (9.2.x), we've assumed that onDataAvailable() for a registered ReadListener is invoked when data is available for reading and either
a) setReadListener() has been called
b) isReady() on the input stream has been called and has returned false.

Hence, what we did in our ReadListener.onDataAvailable() was loop until ServletInputStream.isReady() returned false, then exit the callback and await the next callback invocation (onDataAvailable(), onAllDataRead(), or onError()).

Since 9.3, this no longer works. ServletInputStream.isReady() returns true even when there is no data available for reading due to reaching EOF. isReady() continues to say true, but ServletInputStream.available() says zero.

The spec (https://java.net/downloads/servlet-spec/Final/servlet-3_1-final.pdf) says (section 3.7): "The isReady method returns true if data can be read without blocking." The behavior, as I see it, doesn't match the spec unless one gets creative with statements like "yes, you can read zero bytes without blocking". ;)

I have tried applying a workaround for the case where isReady() returns true and available() returns zero. Unfortunately, it seems to only push the problem someplace else, as we never get any of the ReadListener's finishing callbacks invoked (onAllDataRead(), onError()).

I have attached a simple program that reproduces the issue consistently. Just unpack and run 'mvn test'.
[asyncjetty.tar.gz](https://github.com/eclipse/jetty.project/files/206642/asyncjetty.tar.gz)

I hope you can shed some light on this. Maybe we have misunderstood how to use the async apis and our expectations of callsbacks are incorrect?

**Comment by sbordet** [comment]
I believe the 9.2 is a bug and the 9.3 behavior is correct.

For reads, `isReady()` cannot convey all the information required to complete the read in all cases, and that is why there is `isFinished()`. If `isReady()` returns false, you have no idea whether there is more content or not, therefore the behavior of `isReady()` is now that of returning true when at EOF so that applications can read -1 and know that they have reached EOF.

`ServletInputStream.available()` is not a reliable source of information, ever.
Never base any logic on it.

The only way to know if there are bytes to read is to actually perform the read, i.e. `ServletInputStream.read(...)`. 

If that returns -1, you know you are at EOF, and at that point `isFinished()` will return true.

Having said that, @gregw has the final word regarding this behavior, but IIRC it was clarified as it is in 9.3 by the Servlet Expert Group (either in some errata or in Servlet 4).

**Comment by gregw** [comment]
I believe that Simone's interpretation is correct.  The creative statement I would use is that EOF is data that can be read!

However, I will check with the expert group to ensure that we have the correct behaviour and if so suggest the javadoc is updated.... standby...

**Comment by gregw** [comment]
@bakksjo Here is the [discussion on the expert group list](https://java.net/projects/servlet-spec/lists/jsr369-experts/archive/2015-02/message/13) where this change was discussed.     I think there was general agreement, but after I posted a summary of the thread there was no further posts confirming the interpretation, so it was kind of left hanging - so I'll ask for confirmation.

The point made in the summary that is relevant is: If the stream is at EOF, then isReady() will return true as -1 can be read.

**Comment by bakksjo** [comment]
Thanks for the quick and helpful feedback, folks. +1 on getting this behavior documented, it is not self-evident and may cause some confusion (empirically proven). :)

Could you please verify that this is a sensible implementation of onAllDataRead():

                @Override
                public void onDataAvailable() throws IOException {
                    while (servletInputStream.isReady()) {
                        final int estimatedNumBytesAvailable = servletInputStream.available();
                        final byte[] buffer = new byte[estimatedNumBytesAvailable];
                        final int numBytesRead = servletInputStream.read(buffer);
                        if (numBytesRead < 0) {
                            // End of stream; there should be no more data available, ever.
                            return;
                        }
                        // Consume buffer
                    }
                }

i.e. it will guarantee invocation of onAllDataRead(). And there's no requirement to call ServletInputStream.isFinished(), right?

**Comment by sbordet** [comment]
It's wrong.

As I said, never use `ServletInputStream.available()`.

If it returns 0 (even if there are bytes that can be read), you will allocate a `byte[0]` which of course cannot read any bytes.

Allocate the byte[] with a constant length (e.g. `new byte[1024]`) outside the `while` loop.

The check `numBytesRead < 0` is correct, and there is no need to call `isFinished()`.

After reading -1 and returning from `onDataAvailable()`, `onAllDataRead()` will be called.

**Comment by bakksjo** [comment]
Right, I forgot about available() being unreliable (read that part of your replies yesterday). Not to keep beating a dead horse, but given that both over-allocation and repeated under-allocation is inefficient, I'd like to hear your opinion on the following:

    @Override
    public void onDataAvailable() throws IOException {
        while (servletInputStream.isReady()) {
            final int estimatedNumBytesAvailable = servletInputStream.available();
            // MIN_BUFFER_SIZE is some number > 0
            final int bufferSizeBytes = Math.max(estimatedNumBytesAvailable, MIN_BUFFER_SIZE);
            final byte[] buffer = new byte[bufferSizeBytes];
            final int length = servletInputStream.read(buffer);
            if (length > 0) {
                writeRequestContent(ByteBuffer.wrap(buffer, 0, length));
            }
        }
    }

**Comment by sbordet** [comment]
This is wrong too, because when it reads -1 it continues to loop :)

Because calls to `onDataAvailable()` are guaranteed to be sequential by the container, I typically prefer to allocate one `byte[]` in the class that implements `ReadListener`, storing it as a field.

This way there is one allocation per request, compared to allocation outside the `while` - one allocation per `onDataAvailable()` invocation, compared to inside the loop - one allocation per read.

You want to look at [Scale your WebApps with Servlet 3.1 Async I/O](https://webtide.com/downloads/) for further gotchas.

**Comment by bakksjo** [comment]
Sorry, I pasted our old, broken code. I rushed to edit (see above, should be correct now), but it seems you saw and commented on the first, incorrect comment from me. Bummer.

I cannot re-use the same byte array in onDataAvailable() in our application, because the data is not immediately consumed, but put on a queue.

**Comment by gregw** [comment]
@bakksjo The expert group has responded and confirmed our interpretation of the API (See archive thread above).

With regards to an algorithm to achieve goldilocks buffering (not too big not too small), well that is tough.  Calling available will be of little use, because even if it returns >0 it may just be the size of the first packet of many that might be queued and available, some in java heap, some available in kernel space for an immediate read.

So two approaches come to mind:  dynamic buffer sizes that learn from previous reads and shrink or grow as appropriate;  or allocate a large buffer to read into and then slice of the part that is fill with a byte buffer and add that slice to the queue.    You will need a back channel to learn when all the slices have been consumed and to free/reuse the underlying buffer.

The second approach is used internally by Jetty for handling chunked content read into a big buffer of HttpConnection and sliced into a queue within HttpInput as [HttpConnection.Content instances](https://github.com/eclipse/jetty.project/blob/master/jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java#L575-L595).
