### ISSUE TITLE
jetty-continuation module

### ISSUE THREAD

**Issue by senivam** [eclipse/jetty.project#4934]
**Jetty version**: 11.0.0 SNAPSHOT

**Java version** JDK 11

**Question** why module: 
<dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-continuation</artifactId>
        </dependency>
is missing from jakartified version 11? I've noticed it is not included into the 10th Jetty version as well. If it is by design, could you please let me know how to re-wrok modules which are dependent on the jetty-continuation module?

Another question is if Jetty 11 will support JDK 1.8 as well? 

Thank you

**Comment by sbordet** [comment]
The `jetty-continuation` module has been superseded by the official Servlet 3.0 APIs.

If you had applications using `jetty-continuation`, update them to use the official Servlet 3.0 APIs (notably `ServletRequest.startAsync()` and related).

Jetty 10 and Jetty 11 require Java 11.

**Comment by senivam** [comment]
Thank you for the prompt reply, will do as advised :)

**Comment by HiuKwok** [comment]
Hi, 
I faced the same problem when upgrading Jetty for Apache Spark, wonder if should this be part of the migration guide.
https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-migration-94-to-10

**Comment by joakime** [comment]
> Hi,
> I faced the same problem when upgrading Jetty for Apache Spark, wonder if should this be part of the migration guide.
> https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-migration-94-to-10

The jetty-continuations module ceased to be relevant with the release of Jetty 8 and Servlet 3.0 with AsyncContext.

The jetty-continuation module was deprecated 6 years ago as part of Issue #1444 (be56ecc523b9363f85b97fdd140f82fba0244172)
The `@Deprecated` tag and `@deprecated` javadoc was added.
The release of Jetty 9.4.4 had mention as well https://github.com/jetty/jetty.project/releases/tag/jetty-9.4.4.v20170410
Every release of Jetty 9.4.x since 9.4.4 has had deprecation warnings on the continued use of those classes.

If you want to migrate, [others have found that reading the Servlet3Continuations class is handy](https://github.com/jetty/jetty.project/issues/1444#issuecomment-295404873).
