### ISSUE TITLE
org.eclipse.jetty.websocket.common.message.MessageWriter initialisation time

### ISSUE THREAD

**Issue by bennAH** [eclipse/jetty.project#4964]
**Jetty version** 
9.4.19.v20190610

**Java version** 
1.8

**OS** 
Windows/Linux

**Question**

This is the code of interest:

MessageWriter writer = new MessageWriter(wsSession)

Using MessageWriter as want to stream some JSON content and avoid creating the JSON upfront using:

gson.toJson(object, writer);

Before the call to gson, the code of interest, just calling the constructor can sometimes take up to 400ms.

The scenario is messages will be published fairly frequently, let's say for example on average every 5-10 seconds, based on some other events.

My questions are:
- Is this expected?
- Is there a way to pay a one of cost and avoid initialising each time or is there some other recommended approach?

**Comment by joakime** [comment]
9.4.19 is a bit on the older side.
Can you try the code on 9.4.29.v20200521 ?

Streams as message handlers on WebSocket are heavy objects by their very nature.
Streams as receivers are even worse as they require a new thread for each new message.

> The scenario is messages will be published fairly frequently, let's say for example on average every 5-10 seconds, based on some other events.

How big are the resulting messages?  Can you convert from object to String before you send instead? (that's what the internal code has to do anyway, but in a typical for Streams, much less optimized fashion)

**Comment by joakime** [comment]
Another thing to consider is that if performance is your goal, don't use Streams or fancy objects in WebSocket, use the basics (String for TEXT, and ByteBuffer for BINARY message).
This will reduce the number of websocket frames produced as well.

With a Stream based writer each "write" is a frame, and the closing of the writer is another frame (to finish the message).
With the basic TEXT and BINARY approach it's often 1 send == 1 frame

**Comment by bennAH** [comment]
Thanks @joakime for responding quickly.

The resulting message can vary in size, sometimes they could be fairly big, user input dependent, which is why if possible to avoid creating the string upfront, or at least in cases where we know it is possibly going to be over a certain size.

The results after updating to 9.4.29.v20200521, ignoring first few calls:
375
351
356

Acknowledge at this point, alternatives may have to be considered.

**Comment by joakime** [comment]
Using streams will created a new String object for each write, you are a saving a single "new String" in your app for multiple "new String" in the implementation.
The WebSocket protocol mandates that we convert messages to UTF-8 and validate every message before sending otherwise it's a violation of the protocol that can result in a closure.
Streams also mandate that we hang onto leftover bytes from a previous stream write that doesn't complete a sequence on a frame and use them as the next beginning bytes for the next frame.
This means lots of memory GC, lots of memory / array manipulation, lots of new Strings being created, etc...

Streams in the WebSocket API are not designed for small messages (small in this case is roughly defined as under 40MB) or a usage where you have lots of messages.

The Streams exist for users that have few long lived messages that stream constantly are written as partial messages and read as partial messages.
The most common use case for Streams on WebSocket is to open a single stream for the lifetime of the WebSocket and keep it open sending data as multiple frames for a single large message.

**Comment by bennAH** [comment]
@joakime My bad it's been a while.

I fully understand your point and currently considering alternatives. I'm still intrigued though, the timings above where just for the _constructor call only_ for the MessageWriter without doing any writes. Why is this part expensive?

**Comment by lachlan-roberts** [comment]
@bennAH it should not be an expensive operation to create the `MessageWriter`. The constructor doesn't really do much other than allocate a buffer from the `ByteBufferPool`. How are you measuring the time spent in the constructor call?
