### ISSUE TITLE
What happens to new connection which gets opened after reaching maxConcurrentStream on an opened connection

### ISSUE THREAD

**Issue by SushmaReddyLoka** [eclipse/jetty.project#4972]
In this issue, https://github.com/eclipse/jetty.project/issues/3206 , I saw that its mentioned that 
"When HttpClient is used with the HTTP/2 transport, it will pool connections (as it does for the HTTP/1.1 transport), it will queue requests if it cannot immediately send them (e.g. connection not open yet) and yes it will multiplex requests onto a connection until maxConcurrentStream is reached (then it will open a new connection)." 

Where can one configure maxConcurrentStream ? Is it Http2Client.setMaxConcurrentPushedStreams() ? or any config file which gets applied to all connections  ? 

So what happens to this new connection which gets opened when a connection has reached 
maxConcurrentStream . When does it gets closed ?

How requests are handled later on these two connections ?  Any strategy ( is it done in round robin fashion )? 

Is their any connection pool for this connections ? If so does it pool opened connections ? What is the size of the pool ?

**Comment by sbordet** [comment]
> Where can one configure maxConcurrentStream ?

On the server, see `HTTP2ServerConnectionFactory.setMaxConcurrentStreams(int)`.

> So what happens to this new connection which gets opened when a connection has reached
maxConcurrentStream . When does it gets closed ?

The new connection will be used to send more requests. It is closed typically by idle timeout.

The connection usage depends on the connection pool you have configured.
The default `MultiplexConnectionPool` will prefer to use less connections as possible and prefer to use always the same connections (so that less used ones will eventually idle timeout).
The `RoundRobinConnectionPool` will use connections in a round-robin algorithm.

The connection pool is configured by application code via `HttpClientTransport.setConnectionPoolFactory(ConnectionPool.Factory)`.

For default connection pools, the configuration is taken from `HttpClient`, for example `HttpClient.setMaxConnectionsPerDestination(int)`.

**Comment by SushmaReddyLoka** [comment]
@sbordet , Where do we set maxConcurrentStream  on client side, I am using HttpClient2 for my usecase.

**Comment by sbordet** [comment]
You cannot set `maxConcurrentStream` on the client side, it's a server setting.

**Comment by SushmaReddyLoka** [comment]
Okay.
- What is setMaxConcurrentPushedStreams() for on Http2Client ?
    -  Looking more into code, I think setMaxConcurrentPushedStreams is what isused to set the max concurrent streams allowed by reciever i.e. client, through settings frame ?   

- I see that default MaxConnectionsPerDestination is 64.  So MultiplexConnectionPool tries to open new connections only when existing connection for a client hits the concurrent stream threshold ?

**Comment by SushmaReddyLoka** [comment]
Looking more into code, I think setMaxConcurrentPushedStreams is what is used to set the max concurrent streams on server side by client, through settings frame ?
