### ISSUE TITLE
How do I get Jetty thread status?

### ISSUE THREAD

**Issue by pschaeffer** [eclipse/jetty.project#4974]
Folks, this is not a problem, just a question. I would like to get the status of every thread in Jetty and of course a list of every thread. I already have mechanisms for doing this at the Linux level. I can get a list of all of the Linux threads in the JVM and the status of each one. I would like to do the same thing at the Jetty level. Is this possible? Reasonable?

**Comment by sbordet** [comment]
Can you detail why? The JVM thread dump should already give you that sort of information, and JMX consoles such as JMC too.
Also, the after you get the status or the number of threads, the values may already be out of date.

**Comment by pschaeffer** [comment]
Mr. S. Bordet,

I have a Jetty server (embedded Jetty) that runs on AWS. I would like to build in as many tools as possible for diagnostic purposes. Knowing the Jetty status of each Jetty thread in the Jetty thread pool (I use MonitoredQueuedThreadPool) would be helpful. I have added a bunch of commands to my server for displaying diagnostic data. Jetty thread status would be helpful (at least I think it would be helpful). 

On an unrelated (mostly unrelated) issue, is getHeader() case-insensitive in 9.4.18?

**Comment by sbordet** [comment]
> On an unrelated (mostly unrelated) issue, is getHeader() case-insensitive in 9.4.18?

Yes it is.

I'm not sure what you mean by "Jetty thread status".
There is no special thread status in Jetty, so you can use the normal JVM thread facilities to know the thread status.

If a global representation is ok with you, you can `dump()` the thread pool via a JMX console such as JMC. See: https://www.eclipse.org/jetty/documentation/current/jetty-dump-tool.html

If you need something particular, you can extend `MonitoredQueuedThreadPool` for your needs.

**Comment by pschaeffer** [comment]
Mr. S Bordet,
Thank you
Please close any other issues that I may have open. 
What I am sort of looking for is an indication of what each Jetty thread thinks that it is doing. 
Waiting to consume something, that a producer produces? 
Waiting for the NIO selector to respond?
Running a servlet that does something? 
These seem like possibilities, but I am not sure about this.
Thank you
Peter Schaeffer

**Comment by sbordet** [comment]
>  What I am sort of looking for is an indication of what each Jetty thread thinks that it is doing.

That information is in the stack trace so you can get it at the JVM level.

>  Waiting to consume something, that a producer produces?

That is application dependent, Jetty can't tell you this.

All other cases you listed can be detected by looking at the stack traces and understanding what they mean - kind of requires a human to do that because you want to give a meaning ("waiting for NIO") to an opaque list of stack frames.

We could do something, especially for the internal stuff, but we would need to make it different for every JVM vendor etc. and we will soon enter a rabbit hole of ifs and elses that are JVM vendor and version dependent - not a good spot.

Let's say that I tell you that you have 42 threads idle in the pool, 2 threads in NIO select and 1 thread accepting connections.

Those numbers won't tell you if your system is working correctly, or if it can answer a new request, etc. The only way to know is to try.
That's why most monitoring is done via "pings" that stimulate the system to do some dummy operation that verifies that the system is alive.

`MonitoredQueuedThreadPool` exports a number of information via JMX so you may want to periodically monitor that.

Feel free to close the issue yourself if you're satisfied with the answer.

**Comment by pschaeffer** [comment]
Thank you
Peter Schaeffer
