### ISSUE TITLE
Are there any retry attempts or retry delay which can be configured for http/2 connection establishment ?

### ISSUE THREAD

**Issue by SushmaReddyLoka** [eclipse/jetty.project#4990]
Are there any retry attempts or retry delay which can be configured for http/2 connection establishment ? 
What happens when there is a single connection active in a connection pool and it gets closed due to error or due to connection idleness ? Will i be able to make a new request on same client ? Will it automatically open a new connection in such case ?

**Comment by sbordet** [comment]
> Are there any retry attempts or retry delay which can be configured for http/2 connection establishment ?

There are no retry attempts made by either `HttpClient` or `HTTP2Client` in case of failed connection establishment.

> What happens when there is a single connection active in a connection pool and it gets closed due to error or due to connection idleness ?

If the connection is closed due to e.g. protocol errors, all streams in that connection are failed.
If the connection is idle, it is just closed via the HTTP/2 close mechanism (i.e. send a `GOAWAY` frame before TCP close).

> Will i be able to make a new request on same client ? Will it automatically open a new connection in such case ?

If a connection is closed, and then you make a new request, then that new request will trigger the opening of a new connection (when using `HttpClient` - with `HTTP2Client` applications must manually open connections).

**Comment by sbordet** [comment]
Closing as answered.
