### ISSUE TITLE
DefaultSessionIdManager config to control extendedId behaviour

### ISSUE THREAD

**Issue by rymsha** [eclipse/jetty.project#5003]
**Jetty version**

9.4.29

**Java version**

11.0.7

**OS type/version**

Any

**Description**

When `flushOnResponseCommit=true` for the reasons described in #4049 (common sessionstore, NullSessionCache, non-sticky load balancer) we observe an undesired behaviour:
Jetty keeps sending responses with Set-Cookie header for JSESSIONID cookie. Only last part of extended session id is changed.

Example:
- request 1 gets set-cookie `JSESSIONID=worker1<random>.worker1`
- request 2 gets set-cookie `JSESSIONID=worker1<random>.worker2`
- request 3 gets set-cookie `JSESSIONID=worker1<random>.worker3`

This happens because  DefaultSessionIdManager assumes sticky LB and tries to "help" LB to stick the session to a new Jetty instance.

Such behaviour makes `flushOnResponseCommit=true` and non-sticky configurations in general less useful.

It is easy to fix by the following code
```
MySessionIdManager extends DefaultSessionIdManager {
@Override
public String getExtendedId( String clusterId, HttpServletRequest request ) {
   return clusterId;
}
};
```

But it should rather be a configuration of DefaultSessionIdManager - the behaviour of extendedId.

**Comment by rymsha** [comment]
Fond this is the code of DefaultSessionIdManager :
```
                //add in the id of the node to ensure unique id across cluster
                //NOTE this is different to the node suffix which denotes which node the request was received on
                if (!StringUtil.isBlank(_workerName))
                    id = _workerName + id;
```

But strictly speaking, when SeureRandom is used (default), adding worker name is not necessary as it is practically impossible for two instances to generate same sessionid.
Maybe it is even harmful as it may unintentionally expose internal cluster setup.

Taking this into account the best approach would be provide `null` or empty string to `setWorkerName`, nd disable both `.` worker-name suffix and prefix on JSESSIONID. Am I right?

**Comment by janbartel** [comment]
Non-sticky load balancers with sessions are not recommended, especially if your sessions are read/write. If you have read-mostly sessions then you can probably get away with it. If you really don't want to distinguish your nodes, then just leave the workerName blank or use the same name for all of them.  If you do that, depending on which SessionDataStore you use (unless you're using the NullSessionDataStore), you may get some session expirations you're weren't expecting because some of them use the last known node to manage a session as a guide to when a session whose expiration time has passed can be safely removed.
