### ISSUE TITLE
Impact of the JMM

### ISSUE THREAD

**Issue by pschaeffer** [eclipse/jetty.project#5023]
I wrote the following about port code from x86 to ARM

"The only caveat I can see is multi-threading. In theory, the JMM (Java Memory Model) addresses even this issue. However, it is entirely possible (and even likely) for developers to become dependent on hardware behavior, that is better than the JMM, without even realizing it. Of course, this hidden dependency will cause very strange, intermittent failures once the Java code is ported (moved) to a new platform.

Is this an obscure issue? You bet. The general solution is have all work done by one thread, where the JMM and hardware concurrency don’t matter. Indeed, it is probably true, that 99%+ of all Java programs don’t do any multi-threading. The converse point, is that the tiny fraction of Java programs that use concurrency (Jetty, Tomcat, etc.) are very important. The converse/converse point is that the folks who work on Jetty/Tomcat/etc. are likely to be members of the tiny minority that actually understands concurrency. A closely related point is that users of Jetty/Tomcat don’t need to understand concurrency issue. The problem is handled for them."

Do you folks agree? Am I correct about this?

**Comment by sbordet** [comment]
Some additional reference about this:

[Examining ARM vs X86 Memory Models with Rust](https://www.nickwilcox.com/blog/arm_vs_x86_memory_model/)

**Comment by sbordet** [comment]
> A closely related point is that users of Jetty/Tomcat don’t need to understand concurrency issue. The problem is handled for them.

While it is true that in many cases this is the case, in others it's not.

It has always been an issue, for example, handling concurrent access to the `HttpSession`: the Servlet specification leaves that to application writers rather than containers.

Also, Servlet 3.0 introduced asynchronous processing of requests and responses, and Servlet 3.1 introduced asynchronous I/O.
While typically it's simple to write such applications, in other cases application writers have to be aware of timeouts and/or concurrent access triggered by external events (e.g. receive JMS messages that must be sent back as HTTP response) that needs to be handled carefully.

As for the JMM, it is true that container writers need to make sure that their product work fine under Intel as well as under ARM.

It is also true that over the past years Intel had the lion share of Java deployments, so there may be cases where the code assumed Intel behavior and will not work reliably under ARM.
In such cases, IMHO it is a bug and we will fix it.

**Comment by pschaeffer** [comment]
Thank you for the answer. Please close this question. One quick note. Some number of years ago, I tried to discuss the JMM with another programmer. He was an MIT graduate. He had never even heard of the JMM. 'jmm java' gets only 478,000 hits in Google. Sadly, most programmers don't even known this is an issue.

**Comment by sbordet** [comment]
@pschaeffer most programmers don't need to worry, so they can program well even if they don't know the JMM.

On the other hand we are aware of the JMM and try our best to write Jetty so that it behaves well with any CPU.
Having said that, if there are issues on non-Intel CPUs, we consider them bugs and we are committed to fix them.

Thanks for sharing your thoughts!

**Comment by pschaeffer** [comment]
Mr. Bordet,

 

Thank you for the link. I read it. No surprise that ARM has a “relaxed” memory model compared to x86. This will have no effect on 99+% of programmers. However, it may impact you (Jetty). ARM vs. x86 is a big subject in my circles these days. You won’t be surprised to here that I think ARM is the future (of everything).

 

Thank you

 

Peter Schaeffer
