### ISSUE TITLE
What does URI really mean?

### ISSUE THREAD

**Issue by pschaeffer** [eclipse/jetty.project#5060]
Hi,

This is definitely a question, not a bug. I have noticed that methods such as "getRequestUri()" return all or part of the current path to the caller (the part of a URL starting with the forward slash after the domain name). However, the word URI is used elsewhere to mean Uniform Resource Identifier which is (according to Wikipedia) a superset of URLs. This seems like a contradiction. What am I missing here? 

Thank you

Peter Schaeffer

**Comment by joakime** [comment]
Uniform Resource Identifier is a formalized spec.
https://tools.ietf.org/html/rfc3986

URI is simpler then URL, without all of the contradictory behaviors that URL has.

URI is also the language of HTTP (not URL).
See: https://tools.ietf.org/html/rfc7230

**Comment by joakime** [comment]
The relationship between URL, URI, and URN from the point of view of a web server can be diagrammed like this ...

```
/-----URI ------------------------------------\
|                                             |
/---- URL ------------------------\           |
|                                 |           |
https://tools.ietf.org/html/rfc7230#section-2.7
        |                                     |
        \---- URN ----------------------------/
```

The complexity in URL comes from the various specs built around the registered URI schemes.

https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

For a web server, you really only have to worry about `http://` and `https://`.
You don't even have to worry about logical schemes (like websocket's `ws://` or `wss://` as those start out as `http://` or `https://` before they exist as websocket).

For a web server, it's easy. (just http and https)
For a web browser, it's a nightmare. (you have http, https, ws, wss, ftp, mailto, about, chrome, chromes, googlechrome, googlechromes, etc.  it even supports anything that can be registered by an extension, such as itms-apps for apple itunes)

On Java, using `java.net.URI` is predictable and reliable.
`java.net.URI` is focused purely on the rules for URI, not the rules that the various specs around URL introduce.
It's so strict that various badly designed specs (that haven't been updated to URI) will not work on `java.net.URI`.

On Java, using `java.net.URL` is a nightmare of unpredictable behaviors. (so much so that it's strongly encouraged to avoid URL at all possible moments, using URI everywhere)
The URL behaviors on java are dependent on the implementations of the various schemes in use, and you can even register your own schemes (old versions of OSGi registered the `bundle://` scheme for example.  They don't do that anymore as it was a classloader disaster)

**Comment by pschaeffer** [comment]
Mr. Joakime,

I agree with all of your comments about URIs, URLs, and URNs. However, the getRequestUri() API call seems to return a small part of the URI/URL/URN information. Is that right or wrong? Is getRequestUri() misnamed?

**Comment by pschaeffer** [comment]
Thank you

Peter Schaeffer

**Comment by joakime** [comment]
`javax.servlet.http.HttpServletRequest.getRequestURI()` is part of the Servlet Spec.

See: [https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html#getRequestURI--](https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html#getRequestURI--)

It specifically works with the URI portion of the first line of the HTTP request.
See javadoc link above for examples.

What your user-agent uses in that portion of HTTP will impact what you see when using that method.

This is also heavily tested on the Servlet TCK.

**Comment by pschaeffer** [comment]
Hi,
I followed the link. One example was GET http://foo.bar/a.html. The returned value is just '/a.html'. Wouldn't the URI include the domain (foo.bar) and possibly the scheme (http).
Thank you
Peter Schaeffer

**Comment by joakime** [comment]
Depends on how your user-agent uses http.

Chrome, for example, will send `http://foo.bar/a.html` as ...

```
GET /a.html HTTP/1.1
Host: foo.bar
Connection: close
```

The `http` will be used to connect using HTTP/1.1 on port 80.
The `foo.bar` will be part of the `Host` header.
The `/a.html` will be part of the http request-line.

The portion of the HTTP spec that `HttpServletRequest.getRequestURI()` works with is is called the "request-line".

See https://tools.ietf.org/html/rfc7230#section-3.1.1

**Comment by pschaeffer** [comment]
Thank you

You can close this question.

Peter Schaeffer

**Comment by gregw** [comment]
Peter,

there is also a bit of history in the method names, with URL being used initially when perhaps URI would have been better, in part because there was only a library API for URL. Later usage has gone more towards URI, in part because of the introduction of standard URI classes.       So there is inconsistency in the naming.
