### ISSUE TITLE
eclipse.org/jetty/download.html says release notes are in the GitHub releases page, but they are not

### ISSUE THREAD

**Issue by larrywest42** [eclipse/jetty.project#5118]
On https://www.eclipse.org/jetty/download.html

> Note: Release notes can be found in the VERSION.txt file included with the distribution and on the GitHub Releases page for the Jetty project. Release notes are also made available on the jetty-announce@eclipse.org mailing list.

The "GitHub Releases" text there links to https://github.com/eclipse/jetty.project/releases where you will find many releases with exactly zero words of release notes.'

![image](https://user-images.githubusercontent.com/31381548/89394980-97adbf80-d6c1-11ea-9bb7-33ab97452850.png)

**Comment by joakime** [comment]
See the individual releases tags.

**Comment by joakime** [comment]
See the individual releases tags. (Github, for some reason, equates releases and tags, which isn't correct).
We make tags, with descriptions.
The existence of a tag does not mean a release exists with that tag. (it could have been a tag that is currently being tested in a staged release mode).

But if you want to know the details of a specific tag, click on it.

Example: https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.31.v20200723

Also, see the VERSION.txt within each release, which contains the release notes for all versions up to that release.

Example: https://github.com/eclipse/jetty.project/blob/jetty-9.4.31.v20200723/VERSION.txt

If you download the released jetty-home tarball/zip, or the older jetty-distribution tarball/zip, you'll have a VERSION.txt within it.

You can also just download the version.txt from the global maven repository system.

Example: https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-project/9.4.31.v20200723/jetty-project-9.4.31.v20200723-version.txt

**Comment by larrywest42** [comment]
@joakime Huh.  You're right (of course).

I've never come across that before in the "releases" GitHub tab. 

_E.g._, [Spring Boot release](https://github.com/spring-projects/spring-boot/releases):

![image](https://user-images.githubusercontent.com/31381548/89468724-f0667200-d72c-11ea-8ebd-3bfcca519c2d.png)

Or [grpc releases](https://github.com/grpc/grpc/releases):

![image](https://user-images.githubusercontent.com/31381548/89468818-1d1a8980-d72d-11ea-9117-91b974f04b15.png)

And [Envoy Proxy releases](https://github.com/envoyproxy/envoy/releases) at least has visible links to external notes:

![image](https://user-images.githubusercontent.com/31381548/89469012-797da900-d72d-11ea-8037-46459b670894.png)

But if this is as intended in Jetty, my complaint is moot.

**Comment by joakime** [comment]
We've been experimenting with the release-drafter github action in other repositories to better understand how to configure it.

https://github.com/marketplace/actions/release-drafter

So you should start to see github release pages better filled out. (the ones for Jetty-10.0.0 and Jetty-11.0.0 will be thousands of entries long though, so not sure how valuable those specific ones will be)

We don't really release any assets on this repository, so the release page would only really exist for the purposes of filling out the release page, not actually providing a release asset. (which is typical for github projects)

It should be noted that going backwards and filling out old releases will likely not happen. (unless we can figure out how to automate that from the VERSION.txt via the github api.  last time i looked, the release process wasn't exposed in the github api, but that could have changed by now)

To be clear, we love working on github, and we want to do better.

We have already enabled the dependabot release facilities so that other github projects that also have dependabot enabled will benefit when a new release is announced.  Especially so when the release addresses a CVE.

Example of what other projects would see:
https://github.com/jetty-project/jetty-maven-wagon/pull/8

We also work each release via a github project.
Examples:
 * Jetty 9.4.30 (closed) - https://github.com/eclipse/jetty.project/projects/18
 * Jetty 9.4.31 (closed) - https://github.com/eclipse/jetty.project/projects/19
 * Jetty 9.4.32 (in progress) - https://github.com/eclipse/jetty.project/projects/20
