### ISSUE TITLE
Improve ResourceFactory and Resource list handling

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5133]
**Jetty version**
10.0.x

**Description**
While reviewing PR #5131 it was discovered that the WebAppClassLoader constructor automatically added the WebAppContext.getExtraClassPath() entries on it's own.
While at the same time WebInfConfiguration was processing the WebAppContext.getExtraClassPath() in it's own Servlet specific ways.

https://github.com/eclipse/jetty.project/blob/e117fbe8281bd43ec5601a30d39f50a09cbcef22/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppClassLoader.java#L195-L196

This behavior in the WebAppClassLoader constructor should be removed.

**Comment by joakime** [comment]
@janbartel if I remove these 2 lines from the jetty-9.4.x branch then the WebAppClassLoader is not updated from the extraClasspath.

Should WebInfConfiguration set the WebAppClassLoader? or is that handled in a later Configuration from the MetaData?

**Comment by janbartel** [comment]
@joakime I think that WebInfConfiguration should do the parse of the extraClassPath and then poke the results into the WebApPClassLoader, because it is already poking the WEB-INF/classes and WEB-INF/lib jars into it.

WebInfConfiguration should not create the WebAppClassLoader, that is handled by the WebAppContext in it's startup sequence, and allows for the user to supply their own.

**Comment by joakime** [comment]
Opened PR #5142
