### ISSUE TITLE
Forked Jetty stop (via jetty.sh) results in FAILED when started again due to reintroduced state file

### ISSUE THREAD

**Issue by LouisVN** [eclipse/jetty.project#516]
Using an unaltered jetty.sh from the distribution archive (9.3.8.v20160314), we run a `sudo service jetty restart`. The state file contains:

```
STOPPED org.eclipse.jetty.server.Server@3419866c
STARTING org.eclipse.jetty.server.Server@3419866c
STARTED org.eclipse.jetty.server.Server@3419866c
```

which causes the jetty.sh to report a failed start, because the state file contains a line with "STOPPED".

**Comment by LouisVN** [comment]
Any update on that ?

**Comment by joakime** [comment]
So far ...

Fedora 23 and Ubuntu 16.04 do not exhibit this behavior.

What distribution are you running?

**Comment by LouisVN** [comment]
Ubuntu Trusty 14.04

**Comment by mhow2** [comment]
@joakime I'm afraid I have the same issue, and I think I've spotted out what is the problem.
The problem is when Jetty is configured to fork a child process.

What's happen is jetty.sh stops the master process well and remove the state file.
But the child process is still running, and when it dies some seconds after the state file is written back to the filesystem.

At this point the state file contains STOPPED and as stated by @LouisVN , when starting Jetty again, started() function returns 1 because the state file contains STOPPED and the script exits...

**Comment by jason199101** [comment]
We have the same issue, currently we are using 9.4.12.v20180830

**Comment by gregw** [comment]
@olamy I think we are really late acting on this one!!!

I'm guessing the solution will be that when we are stopping, we should watch the state file until we see STOPPED in it (or a short timeout) so we know that any forked jetty has written to the file, before we delete it and start again.

**Comment by olamy** [comment]
@jason199101 can you detail exactly the procedure/steps to reproduce. I cannot reproduce using ` Ubuntu 18.04.2 LTS`

**Comment by gregw** [comment]
@olamy have you configured the server to ensure that it forks?   try adding --exec to the command line.
Even then it could be a little racy and only happen sometimes.. perhaps with busy servers that are slow to stop.

**Comment by olamy** [comment]
@gregw I added the module `logging-jul` which fork jvm  `--add-to-start=resources,server,http,logging-jul` I will try with generating some load on the server

**Comment by olamy** [comment]
I cannot reproduce even with some load `  httperf --port 8080 --num-conns 100 --rate 1000 --num-calls=5000000000 --timeout 10000 --retry-on-failure --wsess=500,500,10 --burst-len 50 ` (that's a significant load :) ).
@jason199101 @mhow2 is the machine very busy?

**Comment by mhow2** [comment]
@olamy : well, it was 2 years ago :) But as far as I remember, not really busy.
Since then, I'm not forking the process anymore, because of this issue.

See this answer as reference : https://www.eclipse.org/lists/jetty-users/msg08039.html

BTW In this thread, the answer from @joakime doesn't fit the point. I'm saying that jetty.sh doesn't handle the child process race condition properly, and he answers that this behavior is "is common and desired". So to circumvent I just taken what he said for granted and removed `--module=logging-logback` from my `${jetty-base}/start.ini`.

**Comment by gregw** [comment]
I think the race is clear.
Currently on stop the script is just waiting for the PID to finish, but if we fork then that might not be the PID of the actual server.   Thus we may think it is stopped when it is not yet stopped.  We go on to try to start, but the still running server now writes STOPPED into the state file and we are confused!

The fix is that we need a mechanism in stop to wait for the real process to stop.  I think looking for STOPPED in the state file is a good start... but am worried that if the server crashes we could wait forever. So waiting for a time to see STOPPED is probably OK.... unless we can somehow find out the real PID and wait for it?  Maybe we can write that with STARTED in the state file?
