### ISSUE TITLE
Intermittent onWebSocketClose message with code: 1001, reason: "none"

### ISSUE THREAD

**Issue by janikgithub** [eclipse/jetty.project#5274]
**Jetty version**  9.4.15.v20190215.

**Java version** 1.8.0_181

**Question** I am getting intermittent onWebSocketClose  messages with code: 1001, reason: "none",
which I assume happens due to some error.
In my application I need to do invoke certain protocol when user closes browser or leaves the page.
However I can't detect a distinction between the above mentioned "error" 1001 and a normal 1001.
Is there any information that I can get to find the difference between those 2 cases?

Thanks

**Comment by joakime** [comment]
You are subject to several security issues with 9.4.15.
Please be aware of them - https://www.eclipse.org/jetty/security-reports.html

Please try  on 9.4.31.v20200723 (there's been many updates to close handling in websocket since 9.4.15), close should generally behave more cleanly for you.

If you get a status code 1001, that means "Shutdown" or "GoAway", which means either the local side, or the remote side has terminated the connection.
Your use cases of "user closes the browser or leaves the page" is a common one for code 1001.

**Comment by janikgithub** [comment]
Thank you, @joakime
