### ISSUE TITLE
Remove examples/embedded

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5279]
**Jetty version**
10.0.x

**Description**
The `examples/embedded` directory contains examples that should be instead present in the documentation as code snippets.

Eventually all the files under `examples/embedded` should go away as the documentation covers them.

**Comment by gregw** [comment]
I disagree.

The examples in the documentation are very specifically laid out and marked up.  They are not suitable for a programmer who checks out the source code and wants to go find some examples to start working with.

I'm happy if we somehow update examples/embedded so that they can also be used by the documentations, but we can't have it that a programmer that starts from the source has to look in the documentation directory for examples to play with.

**Comment by sbordet** [comment]
Agreed.
