### ISSUE TITLE
Does jetty have a method to convert bean into XML?

### ISSUE THREAD

**Issue by james-z-repo** [eclipse/jetty.project#5296]
**Jetty version**
9.4.19.v20190610
**Java version**
jdk1.8
**Question**

Does jetty have a method to convert bean into XML?

I created an object in Java and I want to convert it into XML. Does jetty have a built-in method that can be called?

![image](https://user-images.githubusercontent.com/33625419/93575417-31100700-f9cc-11ea-8451-f3546e7dc1a9.png)

**Comment by gregw** [comment]
unfortunately no.

It is something that we thought about a few times, but the problem is that while simple setter/getter only cases are pretty simple, the general solution is not really possible.   Specifically because configuring and object can also call methods like `addSomething(value)` or `getSomething().setValue(value)` or `getArray()[index]=value`.   Plus there are stateful methods like `start()` and `open()`.

So there is no real alternative other than authoring the XML.   Good news is that a human can convert java code to XML very easily.  Your example above is something like:
```xml
<Ref refid="info">
  <Get id="contextPath" name="contextPath"/>
  <Get id="war" name="filePath"/>
</Ref>
<New id="webAppContext" class="org.eclipse.jetty.webapp.WebAppContext">
  <Set name="contextPath"><Ref refid="contextPath"/></Set>
  <Set name="war"><Ref refid="war"/></Set>
</New>
```
