### ISSUE TITLE
Linking to .mod files in the documentation

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#5315]
**Jetty -10**

Currently the operations guide links through to the .mod files when discussing configuration parameters. My concern is that this will lead to users mistakenly modifying the `.mod` files to change params instead of the `.ini` files. Although we do document that `.ini` files should be edited instead of `.mod` files, unless you've read the whole guide very closely you can miss this point; if you're in a hurry and just dive into the section on the module you've been told to enable you'll be lead to the `.mod` file, and you might easily think you need to modify that to effect changes.  IMHO it would be better to link through to something that _appears_ to be a `.ini` file - whether that's achieved by only linking to the `[ini-template]` subsection of `.mod` files or by some other means.

**Comment by gregw** [comment]
It should be pretty easy to write a script that can generate adoc files from out mod files that would well present the name, description, dependencies and the ini template, without the need to just import the whole file

**Comment by sbordet** [comment]
@janbartel I disagree that we should write a documentation to read the documentation, because it's turtles all the way down.

Linking something else that _seems like_ an `*.ini` file that does not even exist as a concept will confuse people even more.

Also, you may have looked at initial modules, whose whole content was embedded.
Later, I just list the properties without mentioning where the come from, see for example:
https://www.eclipse.org/jetty/documentation/jetty-10/operations-guide/index.html#og-module-console-capture

**Comment by sbordet** [comment]
As reported in the previous comment, we can now just isolate the properties, so there is no "link" to the module file, just a section in the documentation with the list of properties.
