### ISSUE TITLE
DefaultServlet should serve favicon.ico

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5490]
**Jetty version**
10.0.x

**Description**
`DefaultServlet` does serve `jetty-dir.css`, the default stylesheet.

However, it does not serve `favicon.ico`, the default icon, but `DefaultHandler` does serve it.

I think `DefaultServlet` should have a `favicon` `init-param` (like it has a `stylesheet` `init-param`) and we should default to the Jetty favicon if the `init-param` is missing.

**Comment by sbordet** [comment]
@gregw @joakime opinions?

**Comment by joakime** [comment]
Would only make sense for a ROOT Context.
If you have a WebAppContext on say contextPath of `/app` then there would never be a request for `/app/favicon.ico`

**Comment by joakime** [comment]
It would make sense for a virtualhost setup with multiple WebAppContext on ROOT

**Comment by sbordet** [comment]
Furthermore, if I do directory listing I would like to avoid to put the file in the directory that I'm listing - as `init-param` I would be able to put it anywhere in the file systems.

**Comment by gregw** [comment]
I'm not in favour of this.
`DefaultHandler` is only hit if no other context/webapp handles the request. 
It is an entirely different thing to make deployed webapps serve jetty branded image from their context.   I don't think that is acceptable.
Serving `jetty-dir.css` is acceptable as it only happens if the webapp has deferred listing a directories contents to the server, which they seldom do.

**Comment by sbordet** [comment]
Okay then.
