### ISSUE TITLE
ArrayTernaryTrie consumes too much memory

### ISSUE THREAD

**Issue by leonchen83** [eclipse/jetty.project#5562]
**Jetty version**
9.4.x
**Java version**
java 11
**OS type/version**
centos 7
**Description**
ArrayTernaryTrie consume 17% memory.
![image](https://user-images.githubusercontent.com/5235764/97957520-51621c80-1de6-11eb-86f0-30560d675e7d.png)

more details please see following chart
[advance01-20201103-instanceorder.zip](https://github.com/eclipse/jetty.project/files/5479680/advance01-20201103-instanceorder.zip)

**Comment by gregw** [comment]
Tries are currently being reviewed as part of #5291

**Comment by gregw** [comment]
Note also that there is a per connection header cache, so that if you have lots of short lived connections, then you may allocated a lot of caches for no reason.
You can configure the cache with `HttpConfiguration.setHeaderCacheSize(int)` method  or the `jetty.httpConfig.headerCacheSize` property.

I'll also have a look to see if we can be smarter about when we create this cache.

**Comment by gregw** [comment]
See #5565 as an alternative to disabling the HttpField cache. This PR will change the parser to only create the cache on a second request.
