### ISSUE TITLE
Review ThreadPool.isLowOnThreads()

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#557]
`ThreadPool.isLowOnThreads()` current checks whether all threads have been started and whether the number of idle threads is less than or equal to the number of jobs.

However, situations where `idleThreads = 0` or `idleThreads = 1` are not reported as low on threads, but they actually are.

**Comment by gregw** [comment]
@sbordet I think the pool should be considered low on resources if 
` (max - current + idle - jobs ) <= threshhold`

The threshhold could be 1, but I'd be more comfortable with it being a small integer, perhaps the number of cores as a heuristic for the size of the machine.

Note that calculating it like above deals with the situation were there may be 8 threads from a max of 10, 0 idle, but 3 jobs in the queue - so that is low on resources even though all threads are not yet started!
