### ISSUE TITLE
Enable TCP Keep-Alive in jetty

### ISSUE THREAD

**Issue by pkcs11newbie** [eclipse/jetty.project#5579]
Jetty 9.4.26

OpenJDK11

Hello

We have http request that takes too long to be processed by the server. Because connection is idle, proxy server times out. I've been researching into TCP Keep-Alive functionality.
https://tldp.org/HOWTO/TCP-Keepalive-HOWTO/overview.html

Our application is an embedded jetty server. How would I enable **TCP Keep-Alive** in jetty.

Thanks.

**Comment by sbordet** [comment]
TCP Keep-Alive is a feature of the TCP stack, not of Jetty, and will not help with your problem.

You need to either fix your application to take less time to process requests, or configure the proxy with longer idle timeouts, or change the structure of your application so that you submit tasks that take a long time and then you notify the client of the result when it's ready.

**Comment by pkcs11newbie** [comment]
Thank you for confirming
