### ISSUE TITLE
jetty add context environment args

### ISSUE THREAD

**Issue by james-z-repo** [eclipse/jetty.project#5686]
**Jetty version**
9.4.19.v20190610.
**Java version**
1.8
**Question**
i hava 3 apps in webapps：A B C
i want A app active config file in path: spring.config.location=/usr/local/dev.yml

app B: spring.config.location=/usr/config/test.yml

app C: spring.config.location=/usr/prod/prod.yml

How should I configure to activate different files

**Comment by gregw** [comment]
@zhengshundong01 I don't think this is a Jetty question.  I think it is a spring question.   Also it is best to ask usage questions on the forums rather than open issues.

In jetty, you create different webapps by having different `ContextHandler`s created under a `ContextHandlerCollection`.   This can be done many ways: with the deployer of WebAppContexts (which extend `ContextHandler`; programmatic creation; using a framework like spring.

So I'm closing this for now, but please reopen if you think you have an issue specific to Jetty .
