### ISSUE TITLE
ResourceHandler, ResourceService, and DefaultServlet list files that have no read access

### ISSUE THREAD

**Issue by sirmspencer** [eclipse/jetty.project#5716]
**Jetty version**
jetty-distribution-9.4.34.v20201102

**Java version**
openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-120.04, mixed mode, sharing)

**OS type/version**
Ubuntu 20.04

**Description**
I have the Jetty server set up to run as user jetty.  This user does not have read access to certain directories in the static file folder.  The default web view still lists these files.  How is it that Jetty or these resources have more permissions than the user that Jetty is being run on.  If you click on a file that does not have propper permission to read, you get a permission error. `HTTP ERROR 500 java.lang.RuntimeException: java.io.FileNotFoundException: /mshr/test/test2.text (Permission denied)`

This is related to my stack overflow question https://stackoverflow.com/questions/64978351/jetty-static-resources-dont-respect-the-file-permission-read-specifically-when

**Comment by gregw** [comment]
Jetty will always list directories with it's own permissions.
It is possible that the server has permission to read the directory but not the individual files.

Can you give us a listing with `ls -lsa` of the directory?

**Comment by sirmspencer** [comment]
![image](https://user-images.githubusercontent.com/33734037/100168810-d33de680-2e76-11eb-8733-fbe825912cf0.png)
![image](https://user-images.githubusercontent.com/33734037/100168834-de911200-2e76-11eb-8457-a11929118ece.png)

Im running as user matt. 
![image](https://user-images.githubusercontent.com/33734037/100168864-efda1e80-2e76-11eb-9e4b-c41a169aab23.png)

So clearly since im can list the directory in bash, than user matt has permission to list files in the directory. It just doesnt make sense to me to be showing files in the web that jetty cant access.

**Comment by gregw** [comment]
@sirmspencer Ultimately jetty lists all the files in the directory for the same reason that `ls` lists all the files in the directory.  They exist and there are operations that can be done on them:

- their attributes such as modified time and size can be queried
- they can be deleted if the DELETE method is enabled
- they may be able to be accessed by some alternative authentication - eg there might be a filter/servlet that intercepts and fetches them with permissions.

So I don't think we should hide them, at least not by default.   But if you wanted to give us a PR of an options to hide them, then we might consider it... but no promises until I see the details

**Comment by joakime** [comment]
Also, that theoretical PR should work fine on the majority of JVM, Runtime, and FileSystem combinations out there.

Examples:

Obtain the user information of the running Jetty instance. (user / group / ACL / realm / etc ..)

* On Unix / Linux / OSX / WSL, with Posix permissions you need to know the user/group of the running Jetty instance, and apply the user/group/other logic against `java.nio.file.attribute.PosixFilePermission` for each entry.
* On OSX, with HFS+ or APFS you'll need to interrogate the appropriate permissions for each file and see if the jetty user can access it.
* On Windows, with FAT32, use the `java.nio.file.attribute.DosFileAttributes` to interrogate the readonly / hidden states
* On Windows, with NTFS, use the `java.nio.file.attribute.AclEntryPermission` to interrogate the permissions that the jetty instance can use, per directory entry.

There was an attempt a long time ago to just open each file for reading to know if the Jetty instance can read it or not (an error / exception would be one indication, a failure to read the first byte would be another indication.  Some filesystems wont error on the open, but only error on the attempt to read).
That was *super slow* and left a lot of dangling resources laying around, so that's not a viable option.

You might be tempted to use `Files.isReadable(Path)` and/or `Files.isHidden(Path)` but those have historically not worked very well on Windows NTFS, OSX HFS+, and OSX APFS.

**Comment by joakime** [comment]
Another option would be to allow applications to supply a `Predicate<Path>` to the Jetty `ResourceService` that filters paths based on application logic.

**Comment by sirmspencer** [comment]
My main request is for the auto generated web ui.  It sounds like that it is just one small part of the whole resource management. In retrospect, a <filter> for the web UI is really the request I need.  In my case a regex filter would work well.  Should I close this issue and re-open a request?

**Comment by joakime** [comment]
> Should I close this issue and re-open a request?

Nah, just detail what your idea is, this issue can evolve to fit that.
