### ISSUE TITLE
Past Session Cookies not deleted?

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5750]
**Jetty version**
10.0.x

**Description**
Using the standard jetty-home 10.0.x, with demo module added, I can see that past/invalid JSESSIONID cookies are not deleted.

Example output:

```
Cookie Dump Servlet:
JSESSIONID=node0466fe4wk00i51luzbfnzbdu540.node0
visited=yes
JSESSIONID.c0b79a84=node01mkw67bkh9bvpvm3utazxe8vf2.node0
screenResolution=2560x1440
jenkins-timestamper-offset=18000000
JSESSIONID.4270d3da=node0z386ci06yd198ylii30rbo881.node0
JSESSIONID.03c27bcc=node010rw8e77yyufy1940e13dnee2n18.node0
JSESSIONID.bb911a40=node01ngl6r0hes1gfvu1os8znjgm81.node0
JSESSIONID.07245d4f=node0oijgv0ajl1yiaqo84rmwo7963.node0
JSESSIONID.37d66ddd=node01l8dhlo1ej7csw9nwg2b007r96.node0
Name: name
Value: value
Max-Age: 60
```

Shouldn't the old JSESSIONID cookies be deleted in a subsequent request?

**Comment by joakime** [comment]
I've noticed this behavior on Jenkins (which runs Jetty 9.4.x) as well.
Is this the responsibility of Jetty's Session handling? or is this the responsibility of the application?

**Comment by janbartel** [comment]
What are the cookies with JSESSIONID.4270d3da ?? That is not a session cookie, unless you've specifically configured jetty with that name.

Also, Jetty does not delete a session cookie, it's up to the browser what session cookies get sent.

**Comment by joakime** [comment]
Those are past cookies assigned against `http://localhost:8080` which is a destination only ever used against Jetty demo base.

**Comment by janbartel** [comment]
@joakime well, those aren't cookies that jetty is going to recognize as a session cookie, which _must_ be named JSESSIONID. When we set a session cookie, it is called JSESSIONID. When we change a session cookie because eg the user logged in, or the user invalidated the session or it expired and they created a new session, the cookie is still called JSESSIONID. The only time it is never _not_ called JSESSIONID is if the webapp is configured with a different name - so you'd have to check the demos to see if one of them is configured to use some kind of special name.

**Comment by janbartel** [comment]
https://issues.jenkins.io/browse/JENKINS-43927

Looks like this is a known and unresolved jenkins issue.
