### ISSUE TITLE
ErrorHandler : request.getRequestDispatcher return null

### ISSUE THREAD

**Issue by max3163** [eclipse/jetty.project#5751]
**Jetty version**
9.4.35.v20201120
**Java version**
14.0.2+12-46
**OS type/version**
Linux
**Description**

I use jetty to route my SPA page on index.html when 404 error is detected. For this I implemented an ErrorHandler. 
So far I used jetty version 9.4.20.v20190813 with this code and it work very well: 

```java
@Override
public void handle(String target, Request baseRequest, HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
	{
		// On 404 page we need to show index.html and let JS router do the work, otherwise show error page
		if ( (response.getStatus() == HttpServletResponse.SC_NOT_FOUND) ) {
		   	RequestDispatcher dispatcher = request.getRequestDispatcher("/index.html");
			if (dispatcher != null) {
				try {
					// reset response
					response.reset();
					dispatcher.forward(request, response);
				} catch (ServletException e) {
				    super.handle(target, baseRequest, request, response);
				}
			}
		} else {
			super.handle(target, baseRequest, request, response);
		}
	}
```

Now when I upgrade my jetty lib to 9.4.35.v20201120 ( but all version after 9.4.20.v20190813 are affected ) the request.getRequestDispatcher("/index.html") method return null.  ( because the _context is null ) 

I don't understand if it's an issue or if I need to implement the forward in an other way now ? 
Help is welcome. 

Thanks.

**Comment by gregw** [comment]
The issue is as you suggest - the ErrorHandler is outside of any context, so the request does not know which context to get it from.

Also, the whole dispatcher mechanism is not specified how it should work from a handler. It is after all a servlet mechanism and is specified as routing a request from a dispatch to one servlet to another.  So in this case, the request is not currently dispatched to a servlet, so a dispatcher.forward is kind of undefined and it is probably only by luck that it has worked before....  It does work, because we do use it for our error page mapping mechanism, but that is an implementation detail, so it can (and has) changed.    But you can see how we do it here: https://github.com/eclipse/jetty.project/blob/jetty-9.4.35.v20201120/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java#L104-L111   Note we get the error context and then get the dispatcher from that.

But more importantly, the feature you are implementing is already supported without a custom ErrorHandler.  Just define an error page for 404 status of index.html..... ah unless you want it relative to the request... hmmm OK copy our code, but it will be a little fragile as it is an internal mechanism.  But then I don't know of any plans to change that.

**Comment by joakime** [comment]
The RequestDispatcher pretty much requires a valid ServletContext as well, in both use cases.

For [`HttpServletRequest.getRequestDispatcher(String path)`](https://docs.oracle.com/javaee/7/api/javax/servlet/ServletRequest.html#getRequestDispatcher-java.lang.String-) you need a `ServletContext` to support the relative path behavior that it describes.

For `ServletContext.getRequestDispatcher(String path)` you need a ServletContext to even call that method.

**Comment by max3163** [comment]
@gregw 

I change my code like this : 
```java
		// On 404 page we need to show index.html and let JS router do the work, otherwise show error page
		if ( (response.getStatus() == HttpServletResponse.SC_NOT_FOUND) ) {
		    ContextHandler.Context context = baseRequest.getErrorContext();
		    Dispatcher dispatcher = (context != null) ? (Dispatcher)context.getRequestDispatcher("/index.html") : null;
			if (dispatcher != null) {
				try {
					// reset response
					response.reset();
					dispatcher.forward(request, response);
				} catch (ServletException e) {
				    super.handle(target, baseRequest, request, response);
				}
			}
		} 
```
And it work ! thanks for your help !!!
