### ISSUE TITLE
Redirect header encoding/decoding

### ISSUE THREAD

**Issue by openconcerto** [eclipse/jetty.project#5846]
**Jetty version**
9.3 and 9.4
**Java version**
Java 8 and Java 11
**OS type/version**
Windows & Linux
**Description**

If in an Handler, you use :
`response.sendRedirect("/é");`

The source code is encoded in UTF8,
app started with -Dfile.encoding=UTF-8
and  System.setProperty("org.eclipse.jetty.util.UrlEncoding.charset", "UTF-8"); as first line in main

The redirect is encoded as  /%E9  which is ISO-8859-1
Even if modern browsers support UTF8 in  headers, it doesn't seems clear if Jetty should encode as UTF8,
but,, there is a but,... in the doHandle method of Handler :

```
  @Override
    public final void doHandle(String target, Request baseRequest, HttpServletRequest request, HttpServletResponse response)
```

the org.eclipse.jetty.util.UrlEncoded.decodeString(target);
throws a org.eclipse.jetty.util.Utf8Appendable$NotUtf8Exception: Not valid UTF8! incomplete UTF8 sequence

Shouldn't it be more symmetrical from the encoding point of view?

- Maybe the "encoder" for the redirect should or could encode the string as /%C3%A9
- Maybe the target should be properly decoded
- Maybe the decodeString should do the job.

Of course, this kind of problem is easily solvable with a try/catch and a second try with a decode call with the "ISO-8859-1" as parameter. 
Something could be done to avoid such encoding traps, traps we have to deal with for more than 30 years... but technically solved years ago with unicode.

**Comment by gregw** [comment]
The issue here is that `sendRedirect` is not really an encoder. It's parameter is a URL and thus should already be encoded.
The actual encoding being done here is by the HTTP generator that takes the field and encodes it as USASCII assuming 8859-1 as per RFC7230.

I'm really not sure what more we can do here.... although it feels like we should.
If we treated the location passed as unencoded, then users that are doing the right thing and passing locations like `/some%20path` will get double encoded to `/some%2520path`.
I also don't think it is correct the change the HTTP encoding to UTF-8

So I'll leave this open for a bit to think, but I don't think there is anything we can do.
