### ISSUE TITLE
Jetty 11.0.0 P2 Update Site/Repository

### ISSUE THREAD

**Issue by mduft** [eclipse/jetty.project#5879]
**Jetty version**
11.0.0

**Java version**
11

**Question**
We're currently using Jetty 9.x from the official update site: https://download.eclipse.org/jetty/updates/jetty-bundles-9.x/

We are now forced to update to jakarta namespaces due to updates to Jersey (& co.). Thus I would like to update Jetty to 11 as well - where can I find the according P2 repository for this?

**Comment by joakime** [comment]
We don't manage the p2 update site / repositories at eclipse.

That's done by folks at eclipse that have the osgi experience (and rights to publish p2 bundles).
@rgrunber is this something you can kick off?

**Comment by rgrunber** [comment]
Looking at the Jenkins jobs https://ci.eclipse.org/jetty/ , my guess would be we don't currently produce Jetty 11 update sites. The biggest determinant would be whether the Eclipse platform intends to move to the newer version, and having just spoken to @akurtakov , it seems the plan is for Jetty 10.

From my understanding, rather than producing p2 update sites for Jetty, they will be consuming the artifacts directly from Maven central, and using them as OSGi bundles through Tycho.

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=569804

**Comment by mduft** [comment]
Ugh - that would prevent any consumer of Eclipse RCP to update to a newer Jetty version as long as we don't have maven (which we don't have, we only have plain P2 update sites)... Hmm..

**Comment by akurtakov** [comment]
Nothing prevents anyone from taking care of generating such p2 repos. Neither me nor Roland are Jetty developers but we did it because our project (Eclipse SDK) needed it. 
Even in the (unlikely) case that we don't manage to make use of the new Tycho features now and have to generate p2 repo for Jetty 10 it will be shortterm until we manage to skip that extra step.
Jetty 11 would be extra work which someone else should take if they need it.

**Comment by mduft** [comment]
OK, sad story :| but understandable...
