### ISSUE TITLE
Logging non-confidential requests when jetty is configured with security constraint - transport-guarantee “CONFIDENTIAL”

### ISSUE THREAD

**Issue by shimon-cherny** [eclipse/jetty.project#5911]
Adding security constraint with transport-guarantee “CONFIDENTIAL” to the web.xml:
 
<security-constraint>
    <web-resource-collection>
      <web-resource-name>Everything in the webapp</web-resource-name>
      <url-pattern>/*</url-pattern>
    </web-resource-collection>
    <user-data-constraint>
      <transport-guarantee>CONFIDENTIAL</transport-guarantee>
    </user-data-constraint>
  </security-constraint>
 
Is it possible to log the non-confidential requests as errors?
The main goal is to keep the clear message which explains why the request is redirected. It’s very useful in the wrongly configured SSL offloading environment, when the original request is https but Jetty recognizes it as http.

**Comment by joakime** [comment]
The request log should show the various 302 redirects happening.

**Comment by leontievle** [comment]
The goal is to understand WHY the redirection happens.

**Comment by gregw** [comment]
I think we could perhaps have some better debug logs in `SecurityHandler` and `ConstraintSecurityHandler`.  
@leontievle would that be sufficient? You would have to configure your logging to show the debug from `ConstraintSecurityHandler`, which is currently not much at all, but we could augment to give the reason for failure and/or redirection.
We are not going to log these as errors, because for most web applications they are just part of the normal conversation and not errors.
