### ISSUE TITLE
ClientCertAuthenticator is not taking account SslContext configuration

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#5933]
**Jetty version**
10.0.x (but might a 9.4.x issue as well)

**Description**
Using CLIENT-CERT as login with a configured trustStore via ssl.ini.
```
  <login-config>
    <auth-method>CLIENT-CERT</auth-method>
  </login-config>
```
The used `ClientCertAuthenticator` instance is not using the configuration from the instance SslContextFactory instance.

**Comment by sbordet** [comment]
@lachlan-roberts do you want to tackle this?

Ideally, web applications that need this kind of authentication will need to setup a custom Jetty context XML file, where the configure the authenticator.

However, we want to have a good default if that custom XML is not there.

The idea is that, in `DefaultAuthenticatorFactory.getAuthenticator(...)` we create a `ClientCertAuthenticator` passing to the constructor the `SslContextFactory.Server` that we extract from the `Server` parameter.

If there is more than 1 `SslContextFactory.Server`, do nothing; otherwise pass it to `ClientCertAuthenticator`.
