### ISSUE TITLE
regression: ContextHandler#_baseResource considered as alias in 9.4.34 and not in 9.4.29

### ISSUE THREAD

**Issue by surli** [eclipse/jetty.project#5956]
We are using jetty in XWiki platform for a long time, and we recently performed an upgrade from 9.4.29 to 9.4.34 where we discover a regression in the way `ContextHandler#_baseResource` is resolved.
We are using jetty with a configuration file containing `<SystemProperty name="jetty.home" default="."/>/../webapps/xwiki</Set>` (from: https://github.com/xwiki/xwiki-platform/blob/master/xwiki-platform-tools/xwiki-platform-tool-jetty/xwiki-platform-tool-jetty-resources/src/main/resources/jetty/contexts/xwiki.xml). This directory `xwiki` directory is actually a symbolic link pointing to `../../xwiki` in our testing environment. 
When debugging I discovered that in **9.4.29** the `ContextHandler#_baseResource` field contained: 

> file:///home/urli/Github/xwiki-platform/xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/target/hsqldb_embedded-default-default-jetty_standalone-default-firefox/xwiki/

and calling `isAlias()` on it was returning false.

However in **9.4.34** the same field contained: 
> file:///home/urli/Github/xwiki-platform/xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker/target/hsqldb_embedded-default-default-jetty_standalone-default-firefox/jetty/webapps/../../xwiki/

and calling `isAlias()` on it was returning true. 
On our case, the fact that `isAlias()` returns true on 9.4.34 leads to some resource not being properly loaded because `ContextHandler#checkAlias` returns false.

**Comment by joakime** [comment]
The relative path reference in 9.4.29 with `...jetty/webapps/../../xwiki/` should have resulted in an `.isAlias()` returning `true`, that was definitely a bug.

But I don't think looking at `Resources.isAlias()` is the right place to pay attention to this.
Why is the path normalized in the 9.4.29 case, but not the 9.4.34 case?  That's more interesting.
Looking at 9.4.29 vs 9.4.34 the `ContextHandler.setResourceBase(String)` would have flowed into the `Resource.newResource(String resource, boolean useCaches)` which [was fixed in 9.4.32](55f4e4fa6377d4b72ceafec3906266568ac26123) to not crash on valid Resource bases containing resource collections, not yet valid directories, and even resources defining glob references.
The use of `File.getCanonicalPath()` in the error case was the trigger that broke valid use cases, and also invalidated the Resource alias checking before it had a chance to run.  

This is the code you relied on in 9.4.29... an resource base reference that is definitely an alias (both for the relative paths, and again for the symlin), intentionally triggering an error case, which had a side effect of canonicalizing the path before Resource got involved.

You should have had extra `AliasChecker`s defined for this usage.

To fix this, use the use the `org.eclipse.jetty.server.SameFileAliasChecker` (available since Jetty 9.4.21).
That will work for both symlinks and relative path references (the `SameFileAliasChecker` was created to deal with Resource Bases that are deployed on filesystems that normalize their paths across the various unicode/utf forms, seen on modern flavors of linux and OSX).
If you want just symlinks, you use the `org.eclipse.jetty.server.handler.AllowSymlinkAliasChecker` (available since Jetty 7.6.13)

**Comment by sbordet** [comment]
@joakime I un-staled this for you.

**Comment by lachlan-roberts** [comment]
Seems to me that this is not an issue in later versions of Jetty. We have done some more recent work on alias checking and path decoding + canonicalization since `9.4.34`. After testing out `9.4.45` it seems that if I try to access `/foo/../file.txt` then I can access the file and the resource is not an alias.

But if you are still having issues with the resources being classified as aliases then adding `AllowedResourceAliasChecker` should fix the issue.

Do not use `SameFileAliasChecker` as it has since been deprecated and replaced with `AllowedResourceAliasChecker`.
