### ISSUE TITLE
Close active connections without a restart

### ISSUE THREAD

**Issue by CodeExc** [eclipse/jetty.project#6086]
Jetty version: 11.0.0

Java version: openjdk 1.8.0_271

Question: 
We are using jetty as a simple/small forward proxy with InetAccessHandler to block ip addresses and traffic.
Is it possible to disconnect active connections (http-tunnels or websockets) from the server side?

**Comment by gregw** [comment]
If you sending a response on the connection, you can add the `Connection: close` header that will force a http1 connection to close after the response is sent.

Otherwise, you can use jetty APIs to get to the Connection instance and close it. Servers are entitled to close idle connections at any time.

I think you can also dynamically set a very short idle timeout .

So there are options, but detailed depend a lot on your proxy and business logic

**Comment by CodeExc** [comment]
Many thanks for the help. I found a good solution. 

From the ServerConnector you can get all ConnectedEndPoints and close single connections.

Example:
```
//Addresses to terminate
List<String> addresses = new ArrayList<>()
 
List<EndPoint> endPoints = new ArrayList(connector.getConnectedEndPoints());
for (EndPoint endpoint : endPoints) {
	String remoteAddress = endpoint.getRemoteAddress().getAddress().getHostAddress();
	if(addresses.stream().anyMatch(s -> s.contains(remoteAddress))) {
		endpoint.close();
	}
}

```
