### ISSUE TITLE
Support HTTP Trailer

### ISSUE THREAD

**Issue by klk-** [eclipse/jetty.project#612]
Add support for trailer after chunked-encoded content, as specified by https://tools.ietf.org/html/rfc2616#section-14.40

This is currently a TODO in HttpParser.java:

```
                case CHUNK_END:
                {
                    // TODO handle chunk trailer
                    ch=next(buffer);
                    if (ch==0)
                        break;
                    if (ch == HttpTokens.LINE_FEED)
                    {
                        setState(State.END);
                        return _handler.messageComplete();
                    }
                    throw new IllegalCharacterException(_state,ch,buffer);
                }
```

**Comment by joakime** [comment]
RFC2616 is obsolete.

Here's the relevant section for the updated RFC - http://tools.ietf.org/html/rfc7230#section-4.1.2

**Comment by gregw** [comment]
Currently we do not support HTTP trailers because we have no use-cases for them and no APIs to set/get them in either client or servlet.

Thus we are very unlikely to add support for them, unless somebody can tell us why and give us something to test against.

**Comment by gregw** [comment]
Will add better ignoring of trailers in 9.3 and may implement support in 9.4

**Comment by gregw** [comment]
@sbordet I added HTTP/1.1 trailer support. Can you give the 5011f07 change a quick review and then wire up the HTTP/2.0 trailers to call the same callback?

**Comment by gregw** [comment]
@sbordet I reverted the change because the current tests are too unstable to get an idea if this is OK or not.  I moved to a [branch](https://github.com/eclipse/jetty.project/tree/jetty-9.4-httpTrailers), so if you get time can you add the HTTP/2 stuff to the branch and perhaps see if the failures below are related:
```
  AsyncIOServletTest.testAsyncReadEarlyEOF:1148
  HttpClientStreamTest.testBigUploadWithOutputStreamFromInputStream:930
```

**Comment by sbordet** [comment]
Finished the implementation for both HTTP/1.1 and HTTP/2, and merged the branch.

Typical usage:

```java
@Override
protected void service(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
    Request jettyRequest = (Request)request;
    // No trailers yet.
    Assert.assertNull(jettyRequest.getTrailers());

    // Fully read the content, even if there is no content.
    ServletInputStream input = jettyRequest.getInputStream();
    while (true) {
        int read = input.read();
        if (read < 0) {
            break;
        }
    }

    // Now the trailers are available.
    HttpFields trailers = jettyRequest.getTrailers();
    if (trailers != null) {
        // Use the trailers.
    }
}
```

**Comment by sbordet** [comment]
@gregw, while the read side of this was simple, the write side (i.e. how to write a response trailer) is more complicated.

At the end of the processing of a request we call `HttpOutput.close()`, with the idea to flush the content remaining in the aggregate buffer.
This goes through the interceptors, that have a signature:

```java
void write(ByteBuffer content, boolean last, Callback callback);
```

However, with trailers that is not enough, since we need to pass the additional `HttpFields` object that holds the trailers.
We can add a new `default` method, but it will have effects on the sponsored `BufferedResponseHandler` and on `GzipHandler`.
Furthermore, there is the problem of _when_ we pass the trailers. 
In HTTP/1.1 we would need to know very early if there are trailers, so that we can switch to chunked transfer coding, rather than content length based. However, that is not always possible: the trailer could be calculated dynamically (e.g. content checksum), so it's the application that must hint that it wants chunked transfer coding.

Thoughts ?

**Comment by gregw** [comment]
current work in https://github.com/eclipse/jetty.project/tree/jetty-9.4-httpTrailers2

**Comment by sbordet** [comment]
Completed the implementation.

The client has now "private" APIs in `HttpRequest` and `HttpResponse` to get/set the trailers.

Parsers and generators for both HTTP/1.1 and HTTP/2 have been updated to parse and generate the trailers, and the correspondent event is now linked to the application invocation mechanism, so that applications can get/set the trailers (via Jetty specific APIs for now).
