### ISSUE TITLE
Move the online documention into a standalone page

### ISSUE THREAD

**Issue by hantsy** [eclipse/jetty.project#6129]
**Jetty version**
11.0.2

Currently when I go to the document page, http://www.eclipse.org/jetty/documentation/jetty-11/programming_guide.php

It embeds the generated static docs in the original page, **the menu navigation does not work at all**.  In one word, it is difficult to read

Please move the docs files into a standalone uri and when clicking the URL, open a blank page for it.

**Comment by hantsy** [comment]
I found there is a standalone link for the docs,  http://www.eclipse.org/jetty/documentation/jetty-11/programming-guide/index.html, but why not use it direclty.

**Comment by jmcc0nn3ll** [comment]
I'm inclined to agree, I think we'll be moving those out to their own page
this week or so. The goal had been to have the documentation fit into the
overall website look and feel because it's been a long time since we had
any documentation that matched or integrated nicely. This integrates but
the actual user experience is quite lackluster. We only had that there for
a month or two and I don't particularly like it.

Jesse

**Comment by hantsy** [comment]
For look and feel, consider adding a CSS file to the generated static HTML(there are also some themes for it). But for developers, the original LAF is ok.

**Comment by jmcc0nn3ll** [comment]
Finally make the commit to do away with the links that embed it, I'll check it and remove the php pages soon.
