### ISSUE TITLE
Possible regression in Jetty 10's h2c support

### ISSUE THREAD

**Issue by wilkinsona** [eclipse/jetty.project#6164]
**Jetty version**

10.0.2

**Java version**

11

**OS type/version**

macOS 10.15

**Description**

There appears to be a regression in Jetty 10's h2c support when using Apache HttpClient 5. Code that works with Jetty 9.4.39 fails fails with Jetty 10.0.2. Please see [this sample project](https://github.com/wilkinsona/jetty-h2c-problem) and its README for further details.

**Comment by sbordet** [comment]
Jetty 10 supports WebSocket over HTTP/2 as defined by https://tools.ietf.org/html/rfc8441.

RFC 8441 defines a new settings: `SETTINGS_ENABLE_CONNECT_PROTOCOL = 0x8`.

Jetty 10 sends that setting to Apache's client, which is not able to handle it.

In particular, Apache's client consumes the key (`0x8`) but it does not consume the value, leaving the buffer unconsumed, which causes an exception to be thrown later.
It's an Apache's client issue.

**Comment by wilkinsona** [comment]
Thanks, @sbordet. I'm a bit confused by the link to a WebSocket RFC but this is quite likely due to my ignorance of the low-level workings of HTTP/2. Am I right in thinking that RFC8441 is building on a general HTTP/2 mechanism that the Apache client doesn't support correctly? In other words, as WebSocket isn't involved here, the client should be consuming and effectively ignoring the setting rather than partially consuming it as it is at the moment?

**Comment by sbordet** [comment]
> Am I right in thinking that RFC8441 is building on a general HTTP/2 mechanism that the Apache client doesn't support correctly?

Correct.

WebSocket is not involved here; I mentioned it because it's the difference between Jetty 9 and Jetty 10: only the latter implements this additional RFC with its new setting.

It's just that Apache's client does not properly parse unknown settings.

This is a snippet from Apache's `AbstractH2StreamMultiplexer`:

```java
    private void consumeSettingsFrame(final ByteBuffer payload) throws HttpException, IOException {
        final H2Config.Builder configBuilder = H2Config.initial();
        while (payload.hasRemaining()) {
            final int code = payload.getShort();
            final H2Param param = H2Param.valueOf(code);
            if (param != null) {
                final int value = payload.getInt();
```

`payload.getShort()` reads `code=0x8`, but then `H2Param.valueOf(code)` returns `null` because code `0x8` is not supported.
The null check on the next line skips `payload.getInt()` which would read the value for that key.
Loop around, and now the value is interpreted as the next key, which is wrong.

**Comment by wilkinsona** [comment]
Thanks very much, @sbordet. I've opened [HTTPCORE-673](https://issues.apache.org/jira/browse/HTTPCORE-673).
