### ISSUE TITLE
Review Http[Input|Output].Interceptor

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#6167]
**Jetty version**
10.0.x

**Description**
`Http[Input|Output].Interceptor` are underspecified and need to be reviewed and clarified.

This issue stems from work on #6163 and also #6156 and #6010.

Interceptors are not allowed to throw checked exceptions, so they have to wrap failures in runtime exceptions, which would be unnecessary.

Furthermore, if an interceptor throws, the exception handling needs to be careful in both blocking and non-blocking I/O.

@lachlan-roberts @lorban @gregw please add your comments about this matter.

**Comment by sbordet** [comment]
@lorban please use this issue as an umbrella to port #6163 to Jetty 10.

However, this issue is also for `HttpOutput.Interceptor` so you may want to issue a PR for `HttpInput` but not close this issue until also `HttpOutput` is done.

**Comment by lachlan-roberts** [comment]
The `HttpOutput.Interceptor` can fail the callback instead of throwing, however failing the callback causes the connection to be aborted with no 500 response even if the `HttpChannel` is not committed.

**Comment by gregw** [comment]
An interesting question is that if there is a failure during an async write (either in interceptor or below) then should it be thrown from the call to async write?  If we don't throw, then the caller might loop on isReady and write, never seeing the exception. We can't call onError because we are already in onWritePossible. @sbordet how sure are we that we have not introduced such a loop with the new catches?

So i think we should throw.... but then do we call onError as well once the call to onWritePossible returns?

**Comment by lorban** [comment]
`HttpInput` side is done.

**Comment by sbordet** [comment]
Closing, as Jetty 12 does not have interceptors anymore.
