### ISSUE TITLE
Unusual system property behaviour in maven multi-module builds. 

### ISSUE THREAD

**Issue by afmm** [eclipse/jetty.project#619]
Greetings, 

We encountered an interesting bug in a maven multi-module project.

When the jetty container starts for the individual worker module, the expected system property is passed through as expected, in this example, the `property spring.profiles.active` is "base,extra".

When the jetty container starts as part of the multi-module project build, for the worker module, the property `spring.profiles.active` is "base", which is defined up in the framework project. 

We have tried multiple versions of maven and jetty, and we have setup a minimal reproduction for this behaviour here: https://github.com/afmm/maven-jetty-properties-bug-2016-06

Steps to reproduce with the above repository:

1. From the project root - mvn clean install. The worker build will fail.
2. From the worker sub folder - mvn clean install. The worker build will pass. 

Thanks for your time.

**Comment by janbartel** [comment]
@afmm  thank you for the repro project.

The problem is that the <systemProperties> element by default does not replace a system property that is already set. Remembering that system properties are set on the jvm, and the jvm is the same for the entire build: in a multi module build, when the framework project executes first, it sets the system property to "base", thus when the worker project then executes, it doesn't override that value.

The solution is to specify <systemProperties><force>true</force></systemProperties> to force it to overrwrite an already existing  system property.

regards
Jan
