### ISSUE TITLE
Might be a deadlock in jetty 

### ISSUE THREAD

**Issue by zjffdu** [eclipse/jetty.project#6193]
We use jetty 9.4.31.v20200723, but sometimes see no response from jetty server. Here's a thread dump, it looks like due to jetty is stuck in org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block, and I found the ticket https://bugs.eclipse.org/bugs/show_bug.cgi?id=435322 which is already fixed, but not sure whether this is a known regression issue in 9.4.31.v20200723

[thread_dump.txt](https://github.com/eclipse/jetty.project/files/6331685/a.txt)

Could you anyone help take a look at it ?

**Comment by sbordet** [comment]
You have 37 threads blocked waiting for a lock on `org.apache.zeppelin.socket.ConnectionManager`.

Only one thread is blocked on `SharedBlockingCallback`, probably because the client is not reading.

You are also doing blocking WebSocket writes with a lock held, which is recipe for application lockup.

I suggest that you solve your application issues and review its locking.
You can switch to non-blocking WebSocket writes if your clients are not reading WebSocket content.

**Comment by zjffdu** [comment]
@sbordet Thanks for the reply, All the threads of `ConnectionManager` are blocked due to they are waiting for a lock `<0x00000000c15baca0>` which is blocked by thread of `SharedBlockingCallback `, that's why I suspect it maybe some issue of jetty.

**Comment by sbordet** [comment]
You are using a blocking API with a lock held, so this may happen if the client does not read from the WebSocket connection.
The same would happen with any other blocking call such as HTTP, JDBC, etc.
Don't hold locks while using blocking APIs, or switch to non-blocking APIs.
Well, it's not you, it's Zeppelin that does this, and it should not.

Do you have evidence that the `SharedBlockingCallback` is blocking for more than expected?
