### ISSUE TITLE
jetty-keystore Invalid manifest header Bundle-SymbolicName: ""

### ISSUE THREAD

**Issue by laeubi** [eclipse/jetty.project#6238]
**Jetty version**
11.0.2

**Java version**
11

**OS type/version**

**Description**
!ENTRY org.eclipse.equinox.p2.publisher.eclipse 2 0 2021-05-06 07:01:23.762
!MESSAGE An error has occurred while adding the bundle .m2/repository/org/eclipse/jetty/jetty-keystore/11.0.2/jetty-keystore-11.0.2.jar.
!STACK 0
org.osgi.framework.BundleException: Invalid manifest header Bundle-SymbolicName: ""

if I take a look at the metainf I see that the BSN is empty:

```
Bundle-ManifestVersion: 2
Bundle-Name: Jetty :: Test Keystore
Bundle-RequiredExecutionEnvironment: JavaSE-11
Bundle-SymbolicName: 
Bundle-Vendor: Eclipse Jetty Project
Bundle-Version: 11.0.2
```

**Comment by sbordet** [comment]
@laeubi can you please detail how you are using the `jetty-keystore` module?

I ask because it is supposed to be a dependency only for `jetty-home`, it's not something that is intended as a generic dependency.

Since no other Jetty module depends on it, I am wondering how it ended up as an OSGi bundle?

**Comment by laeubi** [comment]
@sbordet I don't really use it atm but currently working on a module that transforms maven BOMs automatically into a (maven based) P2 site and just noticed the faulty meta-data.

If it is never supposed to be a bundle then it probably should have no OSGi headers, otherwise at least valid ones (e.g. simply jetty.test.keystore.do.not.use.me)...
