### ISSUE TITLE
Request after EofException

### ISSUE THREAD

**Issue by makeua** [eclipse/jetty.project#6297]
**9.4.41.v20210516**

**JDK 11.0.11**

**Is there any way to consume request body after EofException under Spring WebFlux reactive chain? Request contains very small body (like 40-50 bytes), but an example request is sent before browser is closed so the connection is terminated after request is submitted and Jetty server issues a EofException.**

**Comment by sbordet** [comment]
@jboo7 I have doubts that your explanation of the issue is in fact what's happening, at least at the Jetty level.
Jetty would read the 50 bytes and call the application, which would then read them until EOF; Jetty would not know yet if the client closed the connection.

I am guessing that the content did not arrive completely to the server, so for example the server received `Content-Length: 50`, but actually received less than that (possibly 0), and the client closed the connection without sending the body.

Without evidence in form of DEBUG logs or network trace, we cannot tell you more.

**Comment by makeua** [comment]
> @jboo7 I have doubts that your explanation of the issue is in fact what's happening, at least at the Jetty level.
> Jetty would read the 50 bytes and call the application, which would then read them until EOF; Jetty would not know yet if the client closed the connection.
> 
> I am guessing that the content did not arrive completely to the server, so for example the server received `Content-Length: 50`, but actually received less than that (possibly 0), and the client closed the connection without sending the body.
> 
> Without evidence in form of DEBUG logs or network trace, we cannot tell you more.

Thank you, after investigating deeper the logs on debug level we found that while the request body is being read on the server side the connection is being reset-ed.

**Comment by sbordet** [comment]
> Thank you, after investigating deeper the logs on debug level we found that while the request body is being read on the server side the connection is being reset-ed.

Who resets the connection?

**Comment by makeua** [comment]
> > Thank you, after investigating deeper the logs on debug level we found that while the request body is being read on the server side the connection is being reset-ed.
> 
> Who resets the connection?

The connection is being close by the client, so from Jetty perspective everything works great

**Comment by sbordet** [comment]
@jboo7 if everything is fine, feel free to close the issue, thanks!

**Comment by makeua** [comment]
> @jboo7 if everything is fine, feel free to close the issue, thanks!

thanks!
