### ISSUE TITLE
Separation of responsibility between IO events and Execution of requests

### ISSUE THREAD

**Issue by praveenkjvs** [eclipse/jetty.project#6324]
**Jetty version**
9.4.12.v20180830

**Java version**
Open JDK 1.8

**Question**
Ambari uses jetty as embedded web server. Ambari is basically a cluster controller that is responsible to maintain a large set of nodes with a Hadoop cluster. Occasionally we see that the jetty server has a large number of connections under CLOSE_WAIT state, leading to "Too Many Open files" issue. We are trying to reproduce this issue consistently. Once I have it, will raise a new issue, with jetty dumps and logs.

Meanwhile, what I understand is 

1. Jetty uses same threadpool to to process both,
    a) Network relation I/O events (everything that's related to selectors, channels, endpoints, protocol parsing etc)
    b) To do actual request processing of application logic 

This is causing the below (my understanding):
1. When the application logic becomes slow (for various uncontrollable reasons)
2. Then all threads in the pool are busy,
3. As more connections come in, requests are piled up in the job queue.
4. As even more connections come, even the network i/o operations like connecting, reading, accepting sockets etc are piled up in the queue.
5. Meanwhile, clients move on by sending a FIN and on server side even closing the socket (event) is queued up in the server's job queue. Causing the socket to go to CLOSE_WAIT state. (more bad, is when clients have retry logic and they start putting more pressure on the server)
6. If the server picks up and starts processing quickly, then the queue is cleared and the CLOSE_WAIT sockets are cleared
7. If the server did not pickup the processing, (in fact it goes even bad, because may be application logic is trying to open new file handles in the form of connections to external endpoint, they fail and retry kicks in and this further delays the request processing causing more build of queue)
8. Essentially at some point the server is stuck with a lot of CLOSE_WAIT sockets. 

So, what I am looking for is, 
1. why not handle all network io operations in separate threadpool? Do not use the server's threadpool
2. Send the request once completely  parsed to the server's job queue
3. If the network detects that the client closed the connection, call a method on the server's object to cancel the request (if not yet started processing the request), if it already started processing, there is nothing much to be done, also the servlet spec doesn't allow such interruption

This way, at-least the server is not piling up the CLOSE_WAIT (except for those connection whose requests are under processing and client bails out. which I guess will roughly equal to total number of threads available for request processing) 

Meanwhile, I looked at using DOS, QOS, HTTPChannel Listener, Endpoint onClose, onOpen etc to make the server limit/reject the requests under load. But then filters, listeners are also dependent on server's job queue back pressure, free thread availability and finally how fast the application logic completes and thus helping to clear the queue

What I am looking for is:

1. Is there a way to use separate threadpools for request processing and network i/o processing
2. Is there way to intercept the request and if need be, reject it , if certain parameters of the server are beyond threshold level (like job queue length, available free thread, open file handles etc) with out dependence on the same thread pool, used for request processing.
3. Also is there way of using priority queue to prioritize certain clients and put them in the front of job queue

If I misunderstood, please correct my understanding and put me in the right direction towards a solution.

Disclaimer: I did go through the existing issues/articles/jira's concerning issues pertaining to jetty's connections going into CLOSE_WAIT state. And understand that almost always its some issue with the application code and not the Jetty's code itself.

**Comment by sbordet** [comment]
We have tried to split the execution point past the network reads, but it was a performance killer.
You can read why here: https://webtide.com/avoiding-parallel-slowdown-in-jetty-9/

We cannot continuously read from the socket, hoping to find a -1.
This would be an attack vector to the server because it would require infinite buffering from the server.

For the reasons above, separating thread pools is not a solution, not for Jetty.

You can already use a different thread pool in your application: you receive the request in a Servlet, start async, submit the request processing to your own thread pool, then complete when you're done.
You don't need Jetty to do this for you, and you will have much more control, like prioritization based on client IP address or request data, processing timeout, or whatever you need.

If your application blocks threads indefinitely, changing Jetty does not seem the right way to go.

I would instead change your application (or the libraries it uses) to be non-blocking and implement timeouts to control the processing time, all of which is already present in the Servlet APIs.

**Comment by joakime** [comment]
Also, upgrade your version of Jetty, as 9.4.12 is an early version of Jetty with the Reserved Thread concepts (introduced in 9.4.9 and refined over time).

Reserved Threads were a concept introduced to handle HTTP/2 better, where the physical connection (and it's I/O) still needs to be handled even if the individual streams (I like to think of them as virtual connections and requests) are not ready to process their states (thousands of reasons for this, from blocking behavior in the app, async behaviors, long processing times in the app, etc).

While the focus of ReservedThread work was HTTP/2, it was not exclusive for HTTP/2 usage, and other components have benefited.

The other improvements in Jetty since 9.4.12 will also benefit your usage.

Out of curiosity, can hadoop be used with HTTP/2? (maintaining a single physical connection to each of your nodes, but handling countless requests)
