### ISSUE TITLE
JettyWebSocketServletContainerInitializer without @HandlesTypes

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#6326]
**Jetty version**
10.0.x

**Description**
`JettyWebSocketServletContainerInitializer` is not annotated with `HandlesType`, so it is not able to automatically discover WebSocket endpoints annotated with `@WebSocket`, or extending `WebSocketListener`.

Constrast this with `JavaxWebSocketServletContainerInitializer` that is correctly annotated and whose discovered classes are properly processed.

**Comment by sbordet** [comment]
@lachlan-roberts is this by design? 
Seems strange not be able to get automatic discovery of WebSocket endpoints when using the Jetty WebSocket APIs.

**Comment by lachlan-roberts** [comment]
@sbordet I don't know if its by design, the but discovery of WebSocket endpoints with the Jetty WebSocket APIs is just not something we do even in 9.4. 

Even if we discover them we don't have the metadata on how to deploy them, the annotation for Jetty websocket endpoints is just `@WebSocket` for both client and server, and doesn't take the uri parameter like javax one does `@ServerEndpoint("/path")`, so we wouldn't know how to deploy it.

**Comment by janbartel** [comment]
@sbordet @lachlan-roberts can this be closed or is this something we want to pursue?

**Comment by lachlan-roberts** [comment]
Yep, I think this can be closed.
