### ISSUE TITLE
How to handle/log Broken Pipe Exceptions

### ISSUE THREAD

**Issue by johannesherr** [eclipse/jetty.project#6393]
**Jetty version**
10.0.3

**Java version**
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)

**Question**
Summary: We need to log or handle Exceptions ("Broken pipe") that result from clients having closed their connection before the server can send the response.

More Info:
We sometimes have the problem that our server takes too long to respond to the client. Then a read timeout configured by the client is triggered and the client closes the connection. When the server is done processing the request it cannot send the response.
The result should be something like a IOException "Broken pipe" or an EofException.

Now it seems like Jetty deliberately only logs such errors in debug or trace levels:
https://github.com/eclipse/jetty.project/issues/2443#issuecomment-381540145
https://github.com/eclipse/jetty.project/issues/4250#issuecomment-547808086

Unfortunately it seems the classes that might log these exceptions also log a huge amount of other information at these levels, so that we cannot enable debug or trace permanently.

I was hoping we could use something like HttpChannel.Listener to get a hold of these exceptions, unfortunately onResponseFailure is not invoked here.

Debugging the exception handling I get the impression, that the method doShutdownOutput in DecryptedEndPoint swallows (i.e. logs in trace) the exception in line 1309: 

```
catch (Throwable x)
{
    LOG.trace("IGNORED", x);
    endPoint.close();
}
```

My question is, am I missing something? Is there a way to handle "Broken pipe" exceptions (preferably) with a listener or to configure logging so that these exceptions are logged, but not too much other debug information?

Thank you for your help.

**Comment by sbordet** [comment]
I don't think there is a reliable way of making your proposed solution work.

The first issue is that it is different from HTTP/1.1 and HTTP/2.

The second issue is that you can only be aware of a broken pipe if you try write to the socket.
However, it's not enough to try to write, you have to write _enough_ to get the exception, otherwise the small content you write is just silently dropped.
Not to mention differences among OSes that will make this very brittle.

The third issue is that you will never catch the race conditions where the client is closing _exactly_ while you're writing.

If your problem is not catching broken pipes, but just figuring out if a client is gone or not, the only reliable way is to have the client "ping" the server regularly and have a timeout on the server that fires when it does not see a client's "ping" for long enough.
As an example, [CometD](https://cometd.org) is based on a protocol where clients have a heart-beat protocol with the server, so the server knows when they are gone.

**Comment by johannesherr** [comment]
Thank you for your quick reply. Good points, we hadn't considered yet.
