### ISSUE TITLE
How to print jetty request logs in console output

### ISSUE THREAD

**Issue by vikkyomkar** [eclipse/jetty.project#6413]
**Jetty version** 9

**Java version** openjdk version "11.0.5.0.101"

**Question** I am running solr instance with jetty in docker container. i need to print request logs on console output sothat it can be shipped to logging system. 

How can i achieve it ?

**Comment by lachlan-roberts** [comment]
You can use the `RequestLog.Writer` interface to specify what the `RequestLog` does with its output.

The simplest approach would be to use the `Slf4jRequestLogWriter` implementation. Otherwise you will have to write your own `RequestLog.Writer` to do exactly what you want.

See documentation for Jetty request logs https://www.eclipse.org/jetty/documentation/jetty-9/index.html#configuring-jetty-request-logs

In Jetty embedded code this would look something like this:
```java
CustomRequestLog requestLog = new CustomRequestLog(new Slf4jRequestLogWriter(), CustomRequestLog.EXTENDED_NCSA_FORMAT);
server.setRequestLog(requestLog);
```

Otherwise if you are using Jetty standalone you can enable the customrequestlog module and copy the `jetty-requestlog.xml` file into `$JETTY_BASE/etc/`. Then edit it so it uses the `RequestLog.Writer` class that you want to use, something like this:
```xml
<Configure id="Server" class="org.eclipse.jetty.server.Server">
  <Set name="RequestLog">
    <New id="RequestLog" class="org.eclipse.jetty.server.CustomRequestLog">
      <Arg>
        <New class="org.eclipse.jetty.server.Slf4jRequestLogWriter"/>
      </Arg>
      <Arg>
        <Property name="jetty.requestlog.formatString" deprecated="jetty.customrequestlog.formatString">
          <Default>
            <Get class="org.eclipse.jetty.server.CustomRequestLog" name="EXTENDED_NCSA_FORMAT"/>
          </Default>
        </Property>
      </Arg>
    </New>
  </Set>
</Configure>
```

**Comment by vikkyomkar** [comment]
Thanks for the suggestion @lachlan-roberts. I am able to print request logs in console output but it doesn't have latency value.
Is there any way to modify EXTENDED_NCSA_FORMAT to get latency aswell ?

**Comment by lachlan-roberts** [comment]
@vikkyomkar yes, you can provide a customised format string to the CustomRequestLog.

Take a look at the Javadoc for an explanation of how to use it.

https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/server/CustomRequestLog.html

I believe the code you're looking for is something like %{ms}T.
