### ISSUE TITLE
Flakey test ConnectionPoolTest.testConnectionMaxUsage

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#6455]
**jetty-10.0.x**

Test fails sometimes, see eg 
https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-10-6442-Remove-IRC-reference/1/pipeline

**Comment by lorban** [comment]
This test also fails sporadically on 9.4.x.

I've managed to reproduce it, it is basically due to some incompatibility between the `duplex-maxDuration` pool and the test's assertions.

The `duplex-maxDuration` pool is configured to make its connections expire after 10ms. If for some reason the delay between the 1st and the 2nd requests in `testConnectionMaxUsage` takes more than 10ms, then the existing connection that the test expects to be removed because it reached its max usage is actually replaced by a fresh one that did not reach the max usage limit, hence failing the assertion.

Forcing the `MaxDuration` mechanism to be disabled for that test should solve this problem for good.
