### ISSUE TITLE
Duplicate charset declaration in <meta http-equiv="Content-Type"/>

### ISSUE THREAD

**Issue by ChristianGruen** [eclipse/jetty.project#6667]
**Jetty version(s)**

9.4.43.v20210629

**Java version/vendor** `(use: java -version)`

openjdk version "1.8.0_302"

**OS type/version**

Windows 10 Home 19043.1165 (latest)

**Description**

If the following HTML snippet…

```html
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>
</html>
```

…is sent to a Jetty output stream (which seems to be an HttpOutput instance), an additional `charset` property seems to be added. This is what the client receives:

```
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8; charset=UTF-8">
  </head>
</html>
```

Would it be possible to suppress the attachment of a second `charset` property if it’s already provided in the `content` attribute?

**How to reproduce?**

1. Download and unzip https://files.basex.org/releases/9.6/BaseX96.zip (just 10 mb; Jetty is embedded)
2. Download and unzip [jetty.project-6667.zip](https://github.com/eclipse/jetty.project/files/7054529/jetty.project-6667.zip) into `basex/webapp/` (less than 1 kb)
3. Run `basex/bin/basexhttp` or `basex/bin/basexhttp.bat`
4. Call `http://localhost:8984/jetty.project-6667` (via `curl`, the web browser, …): The `charset` property will be returned twice.

**Comment by joakime** [comment]
Jetty doesn't get involved in mutating output content.

Looking at the basex code, the response header manipulation makes a few assumptions about behavior that seemed fishy, but we have specific testcases for those behaviors already.

Example seen in `basex-api/src/main/java/org/basex/http/HTTPConnection.java` - (set charsetencoding, then set content-type with charset too):

``` java
response.setCharacterEncoding("utf-8");
response.setContentType("text/html; charset=UTF-8");
response.getWriter();
assertEquals("text/html;charset=utf-8", response.getContentType());

response.setCharacterEncoding("UTF-8");
response.setContentType("text/html; charset=UTF-8");
response.getWriter();
assertEquals("text/html;charset=utf-8", response.getContentType());

```

This works as expected in Jetty 9.4.43 (the version in use by BaseX 9.6)

The problem seems to lie in the Token or Serializer methods in basex.
The fact that you get upper case "UTF-8" is also an indication that you are not getting the Content-Type from Jetty, which always uses lowercase "utf-8" in response headers (even if the application uses uppercase).  Then there's also the extra space in your output before the content-type charset attribute (a space that Jetty eliminates in its response headers).

**Comment by ChristianGruen** [comment]
Thanks a lot, Joakim, for taking your time. Your hint that Jetty doesn’t change the content was very helpful.
The issue will be further investigated and resolved in BaseX.
