### ISSUE TITLE
Introduce non-multiplexed pool

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#6683]
**Target Jetty version(s)**
10.0.x

**Enhancement Description**
Class `Pool` was introduced to improve the performance of `HttpClient`'s connection pools.
As such, it was implemented with multiplexing built-in.

However, it is now being reused in other cases (e.g. deflater/inflater pools, and possibly for `ByteBuffer` pools) where multiplexing makes no sense.

The idea is to split the functionalities, and introduce a `MonoPool` class that can be used when multiplexing is not necessary, leaving `Pool` with multiplex handling.

**Comment by gregw** [comment]
The multiplexing methods on `Pool` have been deprecated, thus I think that it will be OK to make the util `Pool` class into a mono class.

Are there any other uses of MultiPool other than the connection pool?   If not, then I suggest that we just reimplement the Pool algorithm directly in the AbstractConnectionPool class rather than try to make a generic multi pool with only 1 examplar usage.

**Comment by sbordet** [comment]
@lorban should we close this after #8458?

Does it still make sense to have a specialized, non-multiplexed `Pool`?
We would save a number of calls to `getMaxMultiplex(T)`, increments, decrements and comparisons with maxMultiplex, etc. but the state would still be an `AtomicInteger` for -1, 0, 1.

**Comment by lorban** [comment]
I think this was done when `MonoEntry` / `MultiEntry` were introduced. With the cleanups and simplifications we did in 12, they went away as they weren't needed anymore since the `AtomicBiInteger` state could be replaced with a `AtomicInteger` state in all cases.

I agree that getting rid of increments and the `getMaxMultiplex` calls aren't likely to improve perf in any meaningful way.
