### ISSUE TITLE
Late timeouts for requests in Jetty Client

### ISSUE THREAD

**Issue by prateekkohli2112** [eclipse/jetty.project#6699]
We have implemented a Jetty Client that sends synchronous requests to 30 servers over HTTP2. We have configured a request timeout of 3seconds with each server. 

Incidentally, all 30 servers have stopped receiving requests due to a network failure. In such a case, most of the requests are timedout within 3seconds and we get a callback for it. 
But in some cases we see that the callback is delayed by upto 5 or 7seconds. We see that the timer  scheduled pool executor by default runs single threaded. Could that be the reason that few timeout callbacks are delayed?

**Comment by sbordet** [comment]
Could be, but unlikely. 
You did not provide any evidence of these 5 or 7 seconds, so we cannot tell what could be.

**Comment by prateekkohli2112** [comment]
We are on Jetty version 9.4.31 and we are facing delayed timeouts.

So can our issue be related to https://github.com/eclipse/jetty.project/issues/6323

**Comment by joakime** [comment]
> We are on Jetty version 9.4.31 and we are facing delayed timeouts.
> 
> So can our issue be related to #6323

Upgrade to 9.4.43.v20210629 and try again please.

Reasons:

1. Version 9.4.31 is subject to several security vulnerabilities. (see https://www.eclipse.org/jetty/security_reports.php)
2. Version 9.4.31 is old, and is 14 minor versions behind current. (keep in mind Jetty versioning since 1995 is `<ee_support_level>.<major_version>.<minor_version>`)  - you are not merely 14 point releases out, you are 14 minor versions out of current.
3. Version 9.4.31 is 802 commits (to *just* `jetty-client`) behind of 9.4.43
``` shell
[jetty-client][jetty-9.4.x]$ git log --oneline jetty-9.4.31.v20200723...jetty-9.4.43.v20210629 | wc -l
802
```

If you can still replicate with 9.4.43, we need more details.
How are you using jetty-client?
What are the DEBUG logs telling you? (can we see your DEBUG logs?)

**Comment by prateekkohli2112** [comment]
Thanks, we are trying on the latest version. Will let you know the results.

Just 1 more doubt regarding Http2, what would be the behavior of Jetty client when it sends the MAGIC frame, but server does not send the HTTP2 Settings frame in the initial handshake.
Would the client wait indefinitely for the settings frame or will it retry after a certain timeout?

**Comment by sbordet** [comment]
> Would the client wait indefinitely for the settings frame or will it retry after a certain timeout?

It will wait for the idle timeout only, and then close the connection. It will not retry.
