### ISSUE TITLE
HTTP3: Qpack and Http3Fields

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#6731]
**Target Jetty version(s)**
10.0.x

**Enhancement Description**
Class `Http3Fields` seems to be used only by the encoder to do a job that in HTTP/2 was done by the encoder.
Note how `Http3Fields` has similar fields to `HpackEncoder`.
Is `Http3Fields` needed?

**Comment by sbordet** [comment]
@lachlan-roberts please work on branch `jetty-10.0.x-quic-http3`.

**Comment by lachlan-roberts** [comment]
@sbordet the reason I separated the logic from the Encoder is because it really has nothing to do with QPACK. 

QPACK is just specifying how the headers are encoded not what pseudo headers must be generated, the QPACK specification has no mention of pseudo-headers. The logic in this class may be actually be incorrect for HTTP/3 as I have not checked if there is a difference from HTTP/2. 

Maybe there is some way to improve `Http3Fields`, but I think it would be best if this logic was kept outside of the `QpackEncoder` class. The `Http3Fields` class is inside the internal package so it is not public API anyway.

We have `Http3Fields` to go from `MetaData` -> `HttpFields` in the Encoder.
We have  `MetaDataBuilder` to go from `HttpFields` -> `MetaData` for the Decoder.
