### ISSUE TITLE
Do not include jakarta.servlet packages in jetty.servlet.api

### ISSUE THREAD

**Issue by roman-kitko** [eclipse/jetty.project#6947]
Jetty version : **11.06 **

java version : **15,16,17**

OS : **any**

jetty.servlet.api module, which is used in org.eclipse.jetty.server includes jakarta packages.

But there are already now official jakarta jars that other projects normally use as dependency : 
https://mvnrepository.com/artifact/jakarta.servlet/jakarta.servlet-api

Those jars are automatic java modules, so they export all packages. 

Then the project, that uses both jakarta.servlet-api and jetty modules, exports the package twice, which is not allowed in java system.

Why jetty does not use official jakarta modules, but 'embeddes' the packages from jakarta in another module ?

**Comment by joakime** [comment]
The official jakarta servlet api is broken for JPMS (see xsd / resource loading issues with the official jars).

Jetty 10.x and 11.x both use fixed jakarta.servlet (artifact) jars with proper JPMS layer and include the web/jsp/servlet resources that cause the official jars to be so broken.

This might be fixed in Jakarta EE 10, but not before then, as Jakarta EE 9 (and earlier) will never have the necessary fixes to support JPMS properly.
