### ISSUE TITLE
Improvement: Change HttpClient to be (Auto)Closable

### ISSUE THREAD

**Issue by allanwax** [eclipse/jetty.project#698]
It would be convenient in certain circumstances to make HttpClient implement AutoClosable so we can do something like the following:

...
```
try (HttpClient httpClient = new HttpClient(...)) {
... do something with the client
}
```
...
and have cleanup of the client happen automatically

**Comment by joakime** [comment]
`LifeCycle` is a different scope then `AutoCloseable`.

Using the try-with-resources approach, the `try()` scope would issue a `LifeCycle.start()` and when the scope exits a `LifeCycle.stop()` would occur. How would we expose the ability to configure the `HttpClient` before `.start()` then?

`HttpClient` startup is costly, and it is meant to be kept alive for the lifetime of your JVM, not repeatedly started/stopped for small discrete units of operation.

Think of the `HttpClient` as a browser, and each connection being a tab, and each request being a request within that tab.

**Comment by joakime** [comment]
If you really want this, you can use an implementation of it in your project.

``` java
import org.eclipse.jetty.client.HttpClient;
import org.eclipse.jetty.client.HttpClientTransport;
import org.eclipse.jetty.util.ssl.SslContextFactory;

public class CloseableHttpClient extends HttpClient implements AutoCloseable
{
    public CloseableHttpClient() throws Exception
    {
        super();
        // Perform init / configuration here
        start();
    }

    @Override
    public void close() throws Exception
    {
        stop();
    }
}
```

**Comment by joakime** [comment]
@sbordet you can decide if this is a good idea (or not)

**Comment by sbordet** [comment]
While I have been tempted to do this many times, I always resisted because like @joakime said, the lifecycle of `start()` and `stop()` is typically different from what you would use with `AutoCloseable`.

For example, typically applications create one `HttpClient` instance that lives for the whole duration of the application, while try-with-resources are used at the method level.

Sure, tests could benefit from a try-with-resources, but test libraries have facilities like JUnit's `@After`, so it does not appear to be that useful.

If you have a different use case, please detail it but for now we won't implement this.

Thanks !

**Comment by allanwax** [comment]
The use case is for one time use at startup.  That being said, it's just as easy to do `try { ... } finally { ...stop();}`
