### ISSUE TITLE
Query on Jetty Client verison upgrade

### ISSUE THREAD

**Issue by idikshit** [eclipse/jetty.project#7011]
**Jetty version**
9.4.42.v20210604

**Java version**
17

**Question**
Hi, we are currently using 9.4.42.v20210604 version of Jetty Client. Is there a planned action item to retire Jetty Client 9.4 series after the release of Jetty Client versions 10 and 11. If yes, is there any planned date for it?

**Comment by joakime** [comment]
Jetty 9 is currently in maintenance mode (no new features, only bug fixes), and it's EOL (End of Life) is dependent on a few things.

* How active is the open source Java 8 community.
* Are up to date (non-expired) Java 8 JVM releases available to the world as a whole and not locked down behind "Extended Support Contracts".

Currently, we see far more Java 11+ users than Java 8 (based on the questions we see, and the hundreds of thousands of github projects using Jetty).
Even the most vocal crowd for Java 8 (Android users) have moved on to Java 11.

Java 8 support is expected to go from "Premier Support" to "Extended Support" in March 2022. (5 months from now).
If history holds true, this means no more public releases of Java 8.
When it comes to SSL/TLS (a critical thing in a web server, or http client), this means the death of viable support of Java 8.

Jetty 10 and Jetty 11 are our mainline stable development branches.
You'll see new features, like HTTP/3, show up there.

Jetty 12 is the next development branch (already active), for Jakarta EE 10, Servlet 6.0, etc.
We *really* don't want to be maintaining 4+ branches, so that's added pressure on the deprecation of Jetty 9.
