### ISSUE TITLE
Reuse HTTP1 to HTTP2 upgraded connection

### ISSUE THREAD

**Issue by rabelenda** [eclipse/jetty.project#7022]
**Jetty version**
11.0.6

**Java version**
11.0.10

**Question**

When I try a code like following with a server that support HTTP1 to HTTP2 upgrade, I get 2 connections to the server:

```java
ClientConnector clientConnector = new ClientConnector();
    HTTP2Client http2Client = new HTTP2Client(clientConnector);
    ClientConnectionFactoryOverHTTP2.HTTP2 http2 = new ClientConnectionFactoryOverHTTP2.HTTP2(
        http2Client);
    HttpClientTransport transport = new HttpClientTransportDynamic(clientConnector,
        HttpClientConnectionFactory.HTTP11, http2);
    HttpClient httpClient = new HttpClient(transport);
    httpClient.start();
    try {
      HttpRequest req1 = (HttpRequest) httpClient.newRequest("http://localhost:8081")
          .headers(headers -> headers
              .put(HttpHeader.UPGRADE, "h2c")
              .put(HttpHeader.HTTP2_SETTINGS, "")
              .put(HttpHeader.CONNECTION, "Upgrade, HTTP2-Settings"));
      req1.send();
      HttpRequest req2 = (HttpRequest) httpClient.newRequest("http://localhost:8081");
      req2.send();
    } finally {
      httpClient.stop();
    }
```

Is there a way to reuse the upgraded connection?

As far as I have seen, it seems that the connection is not reused due to [this line](https://github.com/eclipse/jetty.project/blob/jetty-11.0.x/jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpChannelOverHTTP.java#L136).

Regards

**Comment by sbordet** [comment]
The first request starts as HTTP/1, but then upgrades to HTTP/2. From that point on, that connection can only speak HTTP/2.

The second request you make is a plain HTTP/1 request, so it cannot reuse the previous connection, which speaks HTTP/2.

To reuse the first connection, you have to explicitly configure the protocol version:

```java
HttpRequest req2 = (HttpRequest) httpClient.newRequest("http://localhost:8081")
    .version(HttpVersion.HTTP_2);
req2.send();
```

This is necessary because the server speaks 2 different protocols on the same port, so if you don't specify the protocol version the client defaults to HTTP/1.

**Comment by rabelenda** [comment]
Great, thanks!
