### ISSUE TITLE
org.apache.jasper.compiler.disablejsr199 is no longer present in Jetty 9.3+

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#706]
The documentation has several mentions of it, along with the `jvm.mod`

We should remove these references in the code, test cases, and documentation.

The existing documentation should be updated to document how to use ECJ vs Java SDK for JSP compilation.

**Comment by joakime** [comment]
@janbartel can you explain to @WalkerWatch how the switch between ECJ vs JDK is now done?

**Comment by janbartel** [comment]
Since switching to use Jasper from Apache (instead of Glassfish) in jetty-9.2 and above, compilation is only supported with ECJ - Apache Jasper has never supported the jdk compiler as did Glassfish. Thus, we supply the necessary eclipse java compiler jars with the jetty distro.

The only other compilation alternatives that Apache Jasper supports are 1. Ant or 2. a custom compiler.

For compilation with Ant, you need to:

* set the servlet init-param "compiler" on the org.eclipse.jetty.jsp.JettyJspServlet  to be one of the values supported by Ant's javac task: http://ant.apache.org/manual/Tasks/javac.html#compilervalues. The JettyJspServlet is defined in webdefault.xml: see the documentation section on changing values defined in webdefault.xml.
* supply all the Ant-related jars and ensure they are on the classpath

To use a custom compiler:

* write a class that extends org.apache.jasper.compiler.Compiler and ensure it is on the classpath
* set the JettyJspServlet init-param "compilerClassName" to the name of the custom class

**Comment by joakime** [comment]
@janbartel we should remove all of the references to this org.apache.jasper.compiler.disablejsr199 attribute in the jetty-9.3.x branch then.

**Comment by joakime** [comment]
@janbartel the documentation at [`jetty-documentation/src/main/asciidoc/configuring/jsp/configuring-jsp.adoc`](https://github.com/eclipse/jetty.project/blame/jetty-9.3.x/jetty-documentation/src/main/asciidoc/configuring/jsp/configuring-jsp.adoc#L186) still needs to be updated.

**Comment by WalkerWatch** [comment]
@joakime @janbartel I removed references to disablejsr199 in the documentation as part of #712. I was hoping to follow up to see if additional changes need made.

**Comment by joakime** [comment]
@WalkerWatch its still present in the documentation.

```
[jetty-9.3.x]$ git pull origin jetty-9.3.x
X11 forwarding request failed on channel 0
Already up-to-date.
[jetty-9.3.x]$ git grep -n jsr199
jetty-documentation/src/main/asciidoc/configuring/jsp/configuring-jsp.adoc:182:// This is best done when using the standalone distro by uncommenting the System property `org.apache.jasper.compiler.disablejsr199` in the jsp link:#startup-modules[module]:
jetty-documentation/src/main/asciidoc/configuring/jsp/configuring-jsp.adoc:186://  -Dorg.apache.jasper.compiler.disablejsr199=true
```

**Comment by janbartel** [comment]
@joakime I didn't want to remove that property from the FragmentActivator class just in case people were deploying jetty using the glassfish jsp bundles. But  if its gone, its gone and we should update the osgi documentation to mention that only the apache jsp bundles are supported.

**Comment by WalkerWatch** [comment]
@joakime I commented it out pending any other changes. I will remove it wholly.
