### ISSUE TITLE
Jetty 12 API Layer

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#7074]
**Target Jetty version(s)**
Jetty 12

**Enhancement Description**

With the proposed separation of the API layer from the Server to the WebApp, we need to come up with a structure for this.

1. In the git repository
2. In the Maven multi-module tree
3. In jetty-home structure
4. In jetty-home / jetty-base modules system
5. In deployment to select the APIs

**Comment by joakime** [comment]
Here's a proposed structure for the jetty-home / jetty-base with an eye on the module system and the deployment.

These API layers should exist as jetty-home modules, but they now only take effect when deploying a webapp.
The classes / libs they introduce won't exist on the Jetty Server classpath now.

```
/jetty-home/
   /etc/
   /lib/
      /api-suites/
         /jakarta-ee-10/
           jakarta.servlet-api-6.0.jar
           jakarta.websocket-api-4.0.jar
           jakarta.jsp-api-4.0.jar
           jetty-servlet-ee10-12.0.0.jar
           jetty-jsp-ee10-12.0.0.jar
           jetty-annotations-ee10-12.0.0.jar
           jetty-plus-ee10-12.0.0.jar
   /modules/
      /ee-8/
        /servlet.mod
        /websocket.mod
        /jsp.mod
        /jstl.mod
        /el.mod
      /ee-9/
        /servlet.mod
        /websocket.mod
        /jsp.mod
        /jstl.mod
        /el.mod
      /ee-10/
        /servlet.mod
        /websocket.mod
        /jsp.mod
        /jstl.mod
        /el.mod
      /servlet.mod   -> (alias for "ee-10/servlet")
      /websocket.mod -> (alias for "ee-10/websocket")
      /jsp.mod       -> (alias for "ee-10/jsp")
      /jstl.mod      -> (alias for "ee-10/jstl")
      /el.mod        -> (alias for "ee-10/el")
      

/jetty-base/
   /etc/
   /lib/
     /jakarta-ee-8/
       jakarta.servlet-api-4.0.jar
       jakarta.websocket-api-1.1.jar
       jakarta.jsp-api-2.5.jar
       jetty-servlet-ee8-12.0.0.jar
       jetty-jsp-ee8-12.0.0.jar
       jetty-annotations-ee8-12.0.0.jar
       jetty-plus-ee8-12.0.0.jar
     /jakarta-ee-9/
       jakarta.servlet-api-5.0.jar
       jakarta.websocket-api-2.0.jar
       jakarta.jsp-api-3.0.jar
       jetty-servlet-ee8-12.0.0.jar
       jetty-jsp-ee9-12.0.0.jar
       jetty-annotations-ee9-12.0.0.jar
       jetty-plus-ee9-12.0.0.jar
   /webapps/
     /foo.war
     /foo.xml
     /foo.ini
       "depends: ee-8-servlet
        depends: ee-8-websocket"
     /baz.war
     /baz.xml
     /baz.ini
       "depends: ee-10-servlet
        depends: ee-10-websocket
        depends: ee-10-jsp"
```

**Comment by joakime** [comment]
I see this "API Layer" as a fake "Server/System" classloader layer/scope between the Jetty Server Core and the WebApp.

This is where the `WebAppClassloader` behaviors should sit with regards to system/server ClasspathPatterns.

The whole "API Suite" are connected at the hip, so that using Servlet 4 means Jakarta EE 8 with a unique jetty-annotations / jetty-plus / jetty-webapp / jetty-servlet for EE8.  
Enabling technologies like JSP should only be sane within the same "API Suite" (aka Jakarta EE 8 / Jakarta EE 9 / Jakarta EE 10) level.
You shouldn't be able to mix/match nonsense like Servlet 4 with JSP 4.

**Comment by joakime** [comment]
I imagine it will work like this ...

![Jetty 12 Tech](https://user-images.githubusercontent.com/191721/139940071-5e1317a6-3aee-4dcb-a0e5-1bfcd8b6626d.png)

**Comment by sbordet** [comment]
What's interesting is that there is one more ClassLoader in the hierarchy.

I imagine `jetty-util` be in the blu-ish top `ClassLoader`, say "server" ClassLoader.

However, `jakarta.servlet-api` must be in a child ClassLoader (as there could be different versions), say the "container" ClassLoader;

Also, any resource that may be specified in `web.xml` would need the interface (e.g. `jakarta.mail.Session`) in the "container" ClassLoader, but also the implementation (as it cannot be in the "server" ClassLoader).

```
system ClassLoader (class-path)
  server ClassLoader (jetty-util.jar, etc.)
    container ClassLoader (jakarta.servlet.api.jar, but also jetty-servlet-ee10.jar, etc.)
      webapp ClassLoader 
```

However, I don't think that `jetty-servlet-ee10.jar` should be in JETTY_BASE... I think JETTY_HOME has all the ones that we want to support and the modules just references the one it wants.

I think we can have multiple `webapps` directories, as currently the `webapps` directory is created by `deploy.mod`.
We would need to modify `deploy.mod` in something like `deploy-ee10.mod`, so that JETTY_BASE is:

```
$JETTY_BASE/
  /webapps-ee8/
    old-webapp.war
  /webapps-ee10/
    new-webapp.war
```

`deploy-ee10.mod` depends on `webapp-ee10.mod`, which depends on `servlet-ee10.mod` and so on.
