### ISSUE TITLE
Add support to deprecate jetty-home modules

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#7111]
**Jetty version(s)**
10.x +

**Description**
We need a feature to allow deprecation of modules.

It should notify on add and use.
It should also allow freeform text to indicate what the suggested action on the deprecation. (such as an alternate module name)

**Comment by sbordet** [comment]
@joakime there already exist a "deprecation" mechanism, see https://github.com/eclipse/jetty.project/blob/jetty-11.0.7/jetty-home/src/main/resources/modules/deprecated.properties.
The file above is loaded by the `Modules` class.

However, that seems more a "removed" rather than "deprecated" mechanism (as the warning is printed only if the module is missing), to support complete removal of modules e.g. during upgrade to a newer major Jetty version.

It'll be trivial to add a section such as:

`foo.mod`
```
[deprecated]
Module 'foo' is deprecated for removal in a future Jetty version.
Use module 'bar' instead.

[tags]
deprecated
```

In this way, modules that still exist but are deprecated can be listed, a warning printed, etc.

I'll give it a go at implementing the `[deprecated]` section.
