### ISSUE TITLE
jetty client: HttpRequest#abort is unreliable

### ISSUE THREAD

**Issue by phraktle** [eclipse/jetty.project#722]
Under some conditions, `HttpRequest#abort` does not terminate the connection (returning false). From the documentation, it's not clear what these conditions are or what the caller should do about it. However, one would expect that after some retries it should eventually be able to abort, but this is not the case. The method first CAS-es the abort cause then tries to do the same for the underlying `HttpConversation` (which also does a CAS internally). If the abort on the `HttpConversation` fails, calling `HttpRequest#abort` repeatedly will not retry aborting the `HttpConversation` again (since the abort reason was already CAS'ed in `HttpRequest`), making the connection linger on forever.

Ultimately, I would expect to have a reliable way of terminating a request.

**Comment by sbordet** [comment]
Aborting a request is in a natural race with the request being completed or failed.

`Request.abort()` has the semantic that if it returns true, it was able to abort something about sending the request or receiving the response.

If it returns false, then the request has been completed otherwise.

The connection won't linger forever because eventually the request will either be aborted or it will complete.

Do you have a reproducible test case that shows that the connection lingers in a bad state ?

**Comment by phraktle** [comment]
I don't have an isolated test case, but we have experienced this in production. The request in this case is using Server Sent Events, which just keeps streaming forever, so the request never normally ends.

**Comment by sbordet** [comment]
We have test cases that show that aborting a request/response while it is receiving content does work (https://github.com/eclipse/jetty.project/blob/jetty-9.3.10.v20160621/jetty-client/src/test/java/org/eclipse/jetty/client/HttpResponseAbortTest.java).

At this point yours can be an edge case that we did not consider, but we need more details and possibly a reproducible test case.

**Comment by phraktle** [comment]
So is `Request#abort` not designed to be idempotent? Calling it once should succeed, but it is supposed to fail on subsequent attempts?

**Comment by sbordet** [comment]
How many times you want to abort a request ? Once should be enough :smiley: 

The return value of `abort()` tells you whether it was possible to abort the request/response cycle or not.

**Comment by phraktle** [comment]
I expected idempotent behavior such as `java.io.Closeable#close` which is expected to mark the resource as closed internally and succeed silently on subsequent calls.

I believe this would be more in line with API user expectations (at least with mine ;). If you don't wish to change the API to be idempotent, I would advise an explicit warning in the `Request#abort` JavaDoc.

In any case, I'm closing this issue for now, since it could be classified as an application error based on an incorrect assumption.

**Comment by phraktle** [comment]
Btw, given this non-idempotent design, what is the expected handling of the return value of `abort`? Is there anything useful a caller can / should do? If not, why not just make it void?

**Comment by sbordet** [comment]
You have no idea the number of times I wished that `close()` returned a boolean, because you cannot atomically check if it's open, and if it is close it; and sometimes you must close just once.

The return value is informational. Applications can use it like they want. For example to display a message "sorry, you aborted too late, we already sold your item".
