### ISSUE TITLE
HTTP2 Support

### ISSUE THREAD

**Issue by pschaeffer** [eclipse/jetty.project#7431]
I am not sure if this is a Jetty issue or not. I am getting an error trying to use Jetty with HTTP2. The ultimate cause appears to be cancel_stream_error/invalid_priority_frame_rate. I am not sure if this is a client of server error. A series of screen captures is attached. 

<img width="1382" alt="Http2Error1" src="https://user-images.githubusercontent.com/3717450/150437075-d086229b-382d-4f3c-ae09-70a1aea1f997.png">

<img width="1379" alt="Http2Error2" src="https://user-images.githubusercontent.com/3717450/150437104-a3bc9320-2ba3-4986-9219-5d8ddad66d1a.png">

<img width="1382" alt="Http2Error3" src="https://user-images.githubusercontent.com/3717450/150437117-90dd4ba1-4f3b-41a6-a985-40dcef0d58bb.png">

<img width="1381" alt="Http2Error4" src="https://user-images.githubusercontent.com/3717450/150437126-0cc55b90-1d4e-4a8e-8777-eedc2e0d9a7c.png">

**Comment by sbordet** [comment]
The issue happens on the server.

The cause is the client sending too many PRIORITY frames in the unit of time, which is indistinguishable from a category of attacks that servers must prevent, see #3978.

This may happen when a web page with many resources "confuses" the browser that tries to re-prioritize, possibly multiple times, the page resources.

Since Jetty 9.4.21, you can configure the rate of PRIORITY frames with a `RateControl.Factory` in the HTTP/2 `ConnectionFactory` with embedded code.
If you use Jetty as a standalone server, you can configure the rate as documented here: https://www.eclipse.org/jetty/documentation/jetty-10/operations-guide/index.html#og-module-http2.

**Comment by pschaeffer** [comment]
I added the second line below and the problem went away. This issue should be closed (or at least I think it should be closed).

Thank you

Peter Schaeffer

HTTP2ServerConnectionFactory http2ConnectionFactory = new HTTP2ServerConnectionFactory(httpsConfig);
http2ConnectionFactory.setRateControlFactory(new WindowRateControl.Factory(50));

**Comment by pschaeffer** [comment]
Mr. Simone Bordet,

 

Thank you for your help.

 

I tried implementing your suggestion and it workd.

 

Thank you

 

Peter Schaeffer
