### ISSUE TITLE
Adding InheritedListeners to already-started components can cause IllegalStateException

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#7514]
**Jetty 10.0.x**

When a webapp is hot-deployed to an already-started jetty via the `deploy` module, the `o.e.j.deploy.bindings.StandardStarter` does:

```
        if (contexts.isStarted() && handler.isStopped())
        {
            // start the handler manually
            handler.start();

            // After starting let the context manage state
            contexts.manage(handler);
        }
```

So the webapp is first started, and then the `ContextHandlerCollection` is told to manage it.  During the call to `manage`, if an `o.e.j.u.component.Container.InheritedListener` is registered with jetty, then it will be added to every component of the newly started webapp.

If one of those components happens to be a `o.e.j.io.ClientConnector`, when the `InheritedListener` is registered with the connector's `o.e.j.io.ClientConnector.ClientSelectorManager`, then the call to `addEventListener(EventListener)` will fail because the `ClientConnector.ClientSelectorManager` is _already_ in the `started` state, see:
https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-io/src/main/java/org/eclipse/jetty/io/SelectorManager.java#L399.

This does _not_ happen if the webapp is deployed during startup of jetty, because none of the component hierarchy is already in the `started` state, it is just `starting`.

This can be reproduced in the standard jetty distro by:

1. enabling the `jmx` module (which has an `InheritedListener`)
2. enabling the `deploy` module, along with `http` and `websocket`
3. starting jetty the usual way
4. deploying the `cometd-6.0.5` demo webapp (which will contain a `ClientConnector` and `ClientSelectorManager`)

**Comment by janbartel** [comment]
This problem does not affect jetty-9.4.

This problem is present in the jetty-10 series from 10.0.2 onwards.

**Comment by sbordet** [comment]
This issue has been introduced with 25f8c65539e3349e10f9b62ff9d4cee365e5afdb in #5840.

What happen is that the `JavaxWebSocketClientContainer` is added to the `WebAppContext` lazily when it's first used. 
In CometD, this happens when the `WebAppContext` is started, from a `Servlet.init()` method, which is earlier than usual (typically at the first WebSocket upgrade).
This adds an `HttpClient` instance as a child bean of `JavaxWebSocketClientContainer`, which is then already started when the `Servlet.init()` mechanism completes.

After the `WebAppContext` is started, like explained above, `contexts.manage(handler)` happens, which triggers the "inheritance" of the `MBeanContainer` listener on the component subtree.

I don't see a reason for `SelectorManager.[add|remove]EventListener(...)` to throw `IllegalStateException` if running, also because they are the only overridden methods that add the extra check that throws (other overrides do not).
