### ISSUE TITLE
Jetty with multiple JKSs

### ISSUE THREAD

**Issue by pschaeffer** [eclipse/jetty.project#7538]
This is a real question. This is not a bug (or I don't think it is a bug). Is it possible to use multiple JKS with Jetty? Can Jetty be configured to select a specific JKS based on the host name the browser thinks it is connecting too?

**Comment by sbordet** [comment]
This has been discussed in the mailing list about a month ago, see [this thread](https://www.eclipse.org/lists/jetty-users/msg10094.html).

Short answer is "it's not possible to use multiple KeyStores with Jetty because the JDK APIs do not allow it directly".
However, there may be workarounds, but require manual coding on your part.
