### ISSUE TITLE
Jetty 9.4.44 stops loading WebApps with new versions of Java 11 and Log4Shell mitigation in place (ClassCastException)

### ISSUE THREAD

**Issue by kimmerin** [eclipse/jetty.project#7558]
With Log4Shell a proposed suggestion was to set the system property `jdk.jndi.object.factoriesFilter` to `!*`. If you do that Jetty stops loading WebApps if a more recent version of Java 11 is used (that's what I've used for testing, newer versions of Java 8 might be affected as well). In the server.log you get the following error:

<pre>
2022-02-09 16:35:40 WARNING: Failed startup of context o.e.j.w.WebAppContext@12a8d03b{mywebapp,/mywebapp,file:///D:/somedir/tmp/jetty-0_0_0_0-80-mywebapp_war-mywebapp-any-559986278220402511/webapp/,STOPPED}{D:\somedir\webapps\mywebapp.war}
java.lang.ClassCastException: class javax.naming.Reference cannot be cast to class javax.naming.Context (javax.naming.Reference and javax.naming.Context are in module java.naming of loader 'bootstrap')
	at org.eclipse.jetty.plus.webapp.EnvConfiguration.createEnvContext(EnvConfiguration.java:254)
	at org.eclipse.jetty.plus.webapp.EnvConfiguration.preConfigure(EnvConfiguration.java:66)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:488)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:523)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
</pre>

To play around, I've created a test around the code you find at EnvConfiguration.createEnvContext:

<pre>
    
    @org.junit.Test
    public void testEnvConfiguration() throws Exception {
        System.setProperty("jdk.jndi.object.factoriesFilter", "!*");

        InitialContext ic = new InitialContext();
        Object res = ic.lookup("java:comp");
        System.out.println(res.getClass().getName());
        if (res instanceof Reference) {
            Reference ref = (Reference) res;
            System.out.println(ref.getClassName());
            System.out.println(ref.getFactoryClassLocation());
            System.out.println(ref.getFactoryClassName());
        }
        Context compCtx = (Context) res;
    }
</pre>

With Java 11 11.0.5 the test runs through and the output is

<pre>
Starting test testEnvConfiguration
org.eclipse.jetty.jndi.NamingContext
Finished test testEnvConfiguration
</pre>

With Java 11 11.0.14 you get the ClassCastException and the following output:

<pre>
Starting test testEnvConfiguration
javax.naming.Reference
javax.naming.Context
null
org.eclipse.jetty.jndi.ContextFactory
Finished test testEnvConfiguration
</pre>

I'm not sure if this should be considered a bug in Java that a Reference is returned where a Context is expected or in Jetty where one is assumed while the other can take place.

**Comment by joakime** [comment]
The difference in behavior from Java 11.0.5 to Java 11.0.14 is likely due to the changes in Java 11.0.11

See release notes about changes due to bug "JDK-8244473"
https://www.oracle.com/java/technologies/javase/11-0-11-relnotes.html#JDK-8244473

**Comment by kimmerin** [comment]
Most likely, yes. But that shouldn't lead to Jetty to stop working, should it?

**Comment by joakime** [comment]
There's likely something about your dependencies triggering this.
Run a duplicate class checker, I bet you have duplicate `javax.naming.Reference` classes coming from multiple locations (and even different versions).

We run our builds and tests on Java 8 (Temurin 8u312), Java 11 (Temurin 11.0.13), and Java 17 (Temurin 17.0.1) currently, for each commit to `jetty-9.4.x`, we only saw this error when we had a bad dependency that brought in an extra `javax.naming.Reference` implementation.

**Comment by kimmerin** [comment]
Hm, I can't see where a duplicate `javax.naming.Reference` should come from. I've stripped the whole thing down to a new Eclipse project that only contains the jetty-jars and extended above test a bit:

<pre>
    public void testInitContextRetrieval() throws Exception {
        System.setProperty("jdk.jndi.object.factoriesFilter", "!*");

        System.out.println(System.getProperty("java.class.path")
                .replace(JETTY_LIBDIR, "libdir/")
                .replace(";", "\r\n"));
        
        System.out.println();
        System.out.println(getClass().getClassLoader().getResource("javax/naming/Reference.class"));
        
        InitialContext ic = new InitialContext();
        Object res = ic.lookup("java:comp");
        System.out.println(res.getClass().getName());
        if (res instanceof Reference) {
            Reference ref = (Reference) res;
            System.out.println(ref.getClassName());
            System.out.println(ref.getFactoryClassLocation());
            System.out.println(ref.getFactoryClassName());
        }
        Context compCtx = (Context) res;
    }
</pre>

The output is

<pre>
D:\eclipse\eclipse-jee-2018\workspace\Playground\classes
D:\eclipse\eclipse-jee-2018\plugins\org.junit_4.12.0.v201504281640\junit.jar
libdir/asm-9.2.jar
libdir/asm-analysis-9.2.jar
libdir/asm-commons-9.2.jar
libdir/asm-tree-9.2.jar
libdir/geronimo-jaspi-2.0.0.jar
libdir/istack-commons-runtime-3.0.12.jar
libdir/javax.annotation-api-1.3.2.jar
libdir/javax.security.auth.message-1.0.0.v201108011116.jar
libdir/javax.websocket-api-1.1.jar
libdir/jaxb-api-2.3.0.jar
libdir/jaxb-runtime-2.3.5.jar
libdir/jetty-all-9.4.44.v20210927-uber.jar
libdir/jetty-schemas-3.1.jar
libdir/org.eclipse.jdt.ecj-3.19.0.jar
libdir/org.eclipse.jetty.apache-jsp-9.4.44.v20210927.jar
libdir/org.mortbay.jasper.apache-el-8.5.70.jar
libdir/org.mortbay.jasper.apache-jsp-8.5.70.jar
libdir/servlet-api-3.1.jar
D:\eclipse\eclipse-jee-2018\configuration\org.eclipse.osgi\402\0\.cp

jrt:/java.naming/javax/naming/Reference.class
2022-02-09 18:22:31.782:INFO::main: Logging initialized @556ms to org.eclipse.jetty.util.log.StdErrLog
javax.naming.Reference
javax.naming.Context
null
org.eclipse.jetty.jndi.ContextFactory
</pre>

**Comment by joakime** [comment]
Run this testcase, it will report it for you.

https://github.com/eclipse/jetty.project/blob/jetty-9.4.x-7558-clascastexception-envconfig/jetty-plus/src/test/java/org/eclipse/jetty/plus/webapp/EnvConfigurationTest.java

The results on Temurin 11.0.14 are as follows ...

**With factoriesFilter of `!*`**

```
jdk.jndi.object.factoriesFilter(initial) = null
Looking for: javax/naming/Reference.class
 - Found: jrt:/java.naming/javax/naming/Reference.class
 Found 1 times
Looking for: javax/naming/Context.class
 - Found: jrt:/java.naming/javax/naming/Context.class
 Found 1 times
2022-02-09 13:33:28.220:INFO::main: Logging initialized @392ms to org.eclipse.jetty.util.log.StdErrLog
res (class javax.naming.Reference) = [Reference Class Name: javax.naming.Context
Type: parser
Content: org.eclipse.jetty.jndi.java.javaNameParser
]
ref.className = javax.naming.Context
ref.factoryClassLocation = null
ref.factoryClassName = org.eclipse.jetty.jndi.ContextFactory
```

**With factoriesFilter of ``** (empty, aka unset/default)

```
jdk.jndi.object.factoriesFilter(initial) = 
Looking for: javax/naming/Reference.class
 - Found: jrt:/java.naming/javax/naming/Reference.class
 Found 1 times
Looking for: javax/naming/Context.class
 - Found: jrt:/java.naming/javax/naming/Context.class
 Found 1 times
res (class javax.naming.Reference) = [Reference Class Name: javax.naming.Context
Type: parser
Content: org.eclipse.jetty.jndi.java.javaNameParser
]
ref.className = javax.naming.Context
ref.factoryClassLocation = null
ref.factoryClassName = org.eclipse.jetty.jndi.ContextFactory
```

The fact that factoryClassLoaction is null fits with the changes introduced by JDK-8244473

**Comment by kimmerin** [comment]
Hm, I'm not sure what exactly I should see here that differs from your output:

<pre>
jdk.jndi.object.factoriesFilter(initial) = null
Looking for: javax/naming/Reference.class
 - Found: jrt:/java.naming/javax/naming/Reference.class
 Found 1 times
Looking for: javax/naming/Context.class
 - Found: jrt:/java.naming/javax/naming/Context.class
 Found 1 times
2022-02-09 18:42:21.773:INFO::main: Logging initialized @1104ms to org.eclipse.jetty.util.log.StdErrLog
res (class javax.naming.Reference) = [Reference Class Name: javax.naming.Context
Type: parser
Content: org.eclipse.jetty.jndi.java.javaNameParser
]
ref.className = javax.naming.Context
ref.factoryClassLocation = null
ref.factoryClassName = org.eclipse.jetty.jndi.ContextFactory
jdk.jndi.object.factoriesFilter(initial) = 
Looking for: javax/naming/Reference.class
 - Found: jrt:/java.naming/javax/naming/Reference.class
 Found 1 times
Looking for: javax/naming/Context.class
 - Found: jrt:/java.naming/javax/naming/Context.class
 Found 1 times
res (class javax.naming.Reference) = [Reference Class Name: javax.naming.Context
Type: parser
Content: org.eclipse.jetty.jndi.java.javaNameParser
]
ref.className = javax.naming.Context
ref.factoryClassLocation = null
ref.factoryClassName = org.eclipse.jetty.jndi.ContextFactory
</pre>

**Comment by joakime** [comment]
One thing I have to ask.

The suggested fix to use  `-Djdk.jndi.object.factoriesFilter=!*` was suggested as a mitigation against log4j2  https://nvd.nist.gov/vuln/detail/CVE-2021-44228, and the suggestion was to use log4j 2.15.0

This mitigation proved to not mitigate the issue, and another log4j2 vulnerability was filed as https://nvd.nist.gov/vuln/detail/CVE-2021-45046 with the suggestion to use log4j 2.16.0

Since then there's been 2 more CVEs, and this mitigation is again not solving for the entire scope of the issue (it started out as a jndi issue, then an ldap issue, then a jdbc issue, then a general dynamic loading issue), the recommended approach is still to use the correct fixed log4j2 version (iirc, it's 2.17.1 currently)

**Comment by kimmerin** [comment]
Removing that system property solved things here but there are valid reasons out there why somebody decides to set this filter and that shouldn't lead to a ClassCastException in Jetty. This is why I posted this issue.

It might be a consideration to adjust the title if you think that it might be misleading for people having this issue for non-Log4Shell-related reasons.

**Comment by kimmerin** [comment]
BTW: In your test, the lookup also seem to return a Reference, so EnvConfiguration should fall into a ClassCastException as well.

**Comment by joakime** [comment]
`ClassCastException` occurs because you are not using Jetty JNDI with your chosen configuration.

The `-Djdk.jndi.object.factoriesFilter=!*` configuration is rejecting all JNDI factories.
Even Jetty's own jndi factory. (found in `jetty-jndi-<ver>.jar`)

If you only allow Jetty's factory you'll see behavior similar to what it was like before this partial mitigation.

``` java
System.setProperty("jdk.jndi.object.factoriesFilter", "org.eclipse.jetty.jndi.**");
```

Be aware that depending on the libraries in your webapp's (`WEB-INF/lib`) or added into your server level (via 3rd party jndi layers) you might need to enable more factories.

The `Object res = ic.lookup("java:comp");` is where things go awry.

On a plain JVM, with no configuration, that wont work as you have no InitialContext.

On the test case, the `jetty-jndi-<ver>.jar` provides that InitialContext.
But then you configure it away with `jdk.jndi.object.factoriesFilter=!*`.
You wind up with a plain `javax.naming.Reference` which isn't a `javax.naming.Context`

On a normal Jetty server without extra configuration for `jdk.jndi.object.factoriesFilter` the
result of `Object res = ic.lookup("java:comp");` is a `org.eclipse.jetty.jndi.NamingContext`, which is a `javax.naming.Context`.

When you used `jdk.jndi.object.factoriesFilter=!*` on Java 11.0.5 it did nothing, causing no change in the JNDI layer.
The factory from `jetty-jndi-<ver>.jar` was loaded from a JAR file (see `jndi.properties` in JAR) and it couldn't be excluded in Java 11.0.5 using the `jdk.jndi.object.factoriesFilter` system property.

Why?  Because the `jdk.jndi.object.factoriesFilter` property and the associated code `ObjectFactoryFilters` was introduced in Java 11.0.11.
See: https://github.com/openjdk/jdk11u-dev/commit/b8f05df3e729e766b865f1a29177fbd02f838e1e

When you used `jdk.jndi.object.factoriesFilter=!*` on Java 11.0.14 the exclusion for Jetty's JNDI factory took effect, rejecting your ability to use the Jetty factory at all, this is because the change in Java 11.0.11.

You have a few choices from here ...

1. Don't reject all JNDI factories, allow specific ones that you need to function with your webapp. (System/JVM level, Server/Jetty level, Container/3rd-party level, Webapp/webinf-lib level)
2. Upgrade log4j2 properly instead and gain benefit from the protection of the other 4 CVEs you are not covered by this mitigation.

**Comment by joakime** [comment]
I strongly encourage you to abandon this approach of attempting to mitigate the multiple log4shell vulnerabilities.
This kind of mitigation, where you tweak the JVM, have all been discredited with newer Log4Shell CVE announcements (read them, including the discussions on the mailing lists).
This specific mitigation, about `jdk.jndi.object.factoriesFilter` started circulating around Dec 10th 2021, and there's been a tremendous amount of discoveries of the scope of the Log4Shell issue since.
This technique is not recommended by anyone anymore.

**Comment by kimmerin** [comment]
The setting of the system property is a "relict", that's why I were able to remove it easily solving the issue. So I'm not relying on it and Log4Shell is no issue Here[TM]. Thanks for the explanation of the inner workings of this and why a Reference instead of a context is returned. I still think that more than a not very helpful ClassCastException should happen if somebody misconfigured their system. Concluding that this particular ClassCastException occurs because of some system property (or a setting in the JVMs security setting) that is set somewhere else completely is quite unlikely. So maybe doing a check in `EnvConfiguration.createEnvContext` if a Reference is returned by the lookup and throw an exception hinting to the system/securlty-property and suggest adding `org.eclipse.jetty.jndi.**` to it as you've done in your answer above?

This suggestion is a result of my personal point of view that exceptions like a NullPointerException or a ClassCastException should never appear in a log (unless in the Caused-By part) but be replaced by an exception with a message more meaningful for the user.

**Comment by joakime** [comment]
There are countless ways to misconfigure your Java JVM and cause all kinds of spurious errors / exceptions / throwables in the applications you run on java.

We don't protect against these kinds of things simply because doing so would be time prohibitive to maintain across the java ecosystem.   Take for example your use of `jdk.jndi.object.factoriesFilter`, that's just a OpenJDK recommended system property, and not all jvms that Jetty runs on have implemented it.   You could get a similar errors like your initial ClassCastException by by building an uber-jar incorrectly for Java 8, or using a Java 8 compact2 profile, or using Java 11 JPMS improperly, or running your application within OSGi, or countless other scenarios that can mess up a working JNDI subsystem.

**Comment by janbartel** [comment]
If you're setting such powerful properties on jndi, then you need to understand the ramifications. Object factories are very common in jndi and by doing a blanket exclusion like that you should expect something to break. As @joakime said, I don't think there's any way in jetty that we could detect and prevent all of the myriad ways that people can misconfigure their setups. At least you got an exception that has lead to you fixing the problem :)

**Comment by janbartel** [comment]
I'm going to close this issue, as I think it's not possible to replace the ClassCastException with anything more meaningful, as it's impossible to work out that a misconfigured jndi property could be the cause of it.
