### ISSUE TITLE
Jetty-12 MetaData cleanup needed

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#7608]
**Target Jetty version(s)**
Jetty-12

**Enhancement Description**

The MetaData class is badly in need of a clean up:

 + Too many constructors, with multiple paths through to super constructor.
 + The content-length handling is done poorly.  It was meant to be an optimization to avoid HttpFields lookups when the content length is already known, but it now is more likely to cause a HttpFields lookup in every construction.
 + The content-length is sometimes set to -1 and sometimes set tio Integer.MIN_VALUE.  I think the later is probably meant to indicate that a HttpFields lookup should be done.  Eitherway, this needs to be clarified and perhaps some named constants used to communicate the intent.
 + Consideration could be given to using java-17 records

**Comment by gregw** [comment]
@lorban you want to tackle this, as you've already started.   @sbordet anything to add?

**Comment by sbordet** [comment]
@gregw cannot be a record as they cannot be subclassed, while `MetaData` needs to be subclassed.

Other than that, I would like to get consistent naming, for example `getFields()` should be renamed to `getHttpFields()` or `getHeaders()` because then we have the concept of `trailer(s)`.

* getFields() -> getHeaders()
* getTrailerSupplier() -> getTrailersSupplier() (plural)
* getURI() -> getHttpURI()
* getURIString() -> really necessary? How can the _uri be null?
