### ISSUE TITLE
Module requestlog in 9.4 has discrepancies for the stated defaults

### ISSUE THREAD

**Issue by anca-jalbum** [eclipse/jetty.project#7634]
**Jetty version(s)**
9.4.45

**Description**
Not really a "bug", but in module requestlog the defaults for jetty.requestlog.extended and jetty.requestlog.cookies as stated in [jetty-requestlog.xml](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/config/etc/jetty-requestlog.xml) are false. But in [requestlog.mod](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/config/modules/requestlog.mod) they are implied to be true.
Made configuring the request log a bit confusing, as the "defaults" in requestlog.ini looked fine, but didn't generate the expected request logs.

**Comment by joakime** [comment]
The defaults in `requestlog.ini` are comments. (meaning they start with the `#` symbol).

They don't have any impact.

_Unless you uncommented them._

You can always use `--list-config` to see what your configuration is (including the properties that are active).

Eg:

```
$ cd /path/to/myjettybase
$ java -jar /path/to/jetty-home/start.jar --list-config 
```

**Comment by joakime** [comment]
Closing, as I see no conflict in behavior or expectations.

**Comment by anca-jalbum** [comment]
I know they don't have any impact. It's just confusing when the comments usually states the defaults. It also conflicts with the documentation that says:

_"When a module is activated, a number of properties are set by default. To view these defaults, open up the associated ini file."_

And then further down:

_"To edit a property, first un-comment the line by deleting the # at the start of the line, then make the change after = sign (such as changing a true value to false)."_

**Comment by joakime** [comment]
That documentation is old and needs to be fixed.

The `ini-template` has evolved so much since that was written.
It's not possible to list all defaults in the ini-template, nor has the changes in the XML to support complex defaults or hierarchical defaults kept up with that 1 line in the documentation.
Most of the defaults in `jetty-10.0.x` are actually in the code, NOT in the ini-template or XML. (eg: `<Set name="timeout" property="foo.timeout.ms"/>` has no declared default in XML and that setter is only called if the property `foo.timeout.ms` exists as a start.jar property for the active `${jetty.base}` that XML is active for)

The ini-template is helpful, but not the be-all, end-all of default values.
It's more useful as example values, common settings, alternate settings.

---

Some examples of ini-template that don't follow the documentation stated behavior.

**fcgi**

The configuration here is too complex to document in the ini-template

https://github.com/eclipse/jetty.project/blob/4a0c91c0be53805e3fcffdcdcc9587d5301863db/jetty-fcgi/fcgi-server/src/main/config/modules/fcgi.mod#L14-L16

**deploy**

These are examples of usage, not defaults

https://github.com/eclipse/jetty.project/blob/4a0c91c0be53805e3fcffdcdcc9587d5301863db/jetty-deploy/src/main/config/modules/deploy.mod#L18-L23

**setuid**

These are example values, there can't possibly be defaults for setuid.

https://github.com/eclipse/jetty.project/blob/4a0c91c0be53805e3fcffdcdcc9587d5301863db/jetty-home/src/main/resources/modules/setuid.mod#L17-L23

---

You'll find that modules that depend on external information (datastores, session stores, infinispan, gcloud, mongo, ldap, openid, etc) all cannot declare default values and you must define the values yourself.
Those modules all have example values in their ini-template sections.
