### ISSUE TITLE
Custom Error Handler Added to ServerBeans is not used for ErrorHandling

### ISSUE THREAD

**Issue by santh5858** [eclipse/jetty.project#7747]
**Jetty version(s)**
> Jetty-home 9.4.44.v20210927

**Java version/vendor** `(use: java -version)`
> openjdk version "11.0.14" 2022-01-18

**OS type/version**
> Ubuntu 20.04.4 LTS

**Description**

I have been trying to setup a jetty server with common error handling. As per the [jetty-9 doc](https://www.eclipse.org/jetty/documentation/jetty-9/index.html#custom-error-pages), i have written a class that extends ErrorHandler class and overrides the handle() method. I exported it as a jar and included it in lib/ext and the class is being discovered and loaded properly (verified using ```--debug``` and ```-Dorg.eclipse.jetty.LEVEL=DEBUG``` flags). I've also added this to jetty.xml server instance as instructed in the doc. No matter what change is done, the error is only being handed by the default ErrorPageErrorHandler and not my custom class. This is the xml context file that i have

```
<?xml version="1.0"?><!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">

<Configure id="Server" class="org.eclipse.jetty.server.Server">
    ...
    <Call name="addBean">
        <Arg>
            <New class="com.example.test.CustomErrorHandler"/>
        </Arg>
    </Call>
    ...
</Configure>
```

I tried going through the code and as far as i understand, based on https://github.com/eclipse/jetty.project/blob/4a0c91c0be53805e3fcffdcdcc9587d5301863db/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java#L625

The ErrorHandler is first checked in the context and only if it's unavailable it's obtained from server beans.  But while creating the WebAppContext, ErrorPageErrorHandler is passed as default.

https://github.com/eclipse/jetty.project/blob/4a0c91c0be53805e3fcffdcdcc9587d5301863db/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppContext.java#L207
 
Hence, If it set the error handler in server bean and don't include it in context, my custom ErrorHandler is ignored and the default is used. Is this the expected behaviour. If so, nothing of this sort seems to be mentioned in docs.

**How to reproduce?**

1. Create a custom class which extends ErrorHandler and make necessary changes.
2. Add this to server using addBean in IoC XML.
3. Deploy webapps without adding this error handler to deployment descriptor (without setting it in WebAppContext).

**Comment by joakime** [comment]
There's nothing about common error handling across webapps in the jetty 9 doc.

The `Server.setErrorHandler(ErrorHandler)` is what you want to use for non-webapp error handling.

It's not really possible to have a single `ErrorPageErrorHandler` across multiple webapps, as each webapp will configure different handling of various pages/status codes/exceptions per the servlet spec to suit their needs.

What exactly are you trying to do?  The end goal. (the steps you are trying are not going to work as-is)

**Comment by joakime** [comment]
The reason that every `WebAppContext` has it's own `ErrorPageErrorHandler` is due to the servlet spec.

One area of the Servlet spec has to do with mapping of situations to error pages.
This is done by mapping ...

* Response status codes to page
* Throwable/Exceptions to page
* Global to page (if not matching above)

This requires the `ErrorPageErrorHandler` to exist in the `WebAppContext` due to classloader concerns around the mapping of exceptions/throwables to page.

The next requirement is the Servlet `DispatcherType.ERROR` which is used to re-dispatch (into the same context!) the error for a servlet to process the error.
This again requires the error handling to exist within the scope of the `WebAppContext`.

Tell us why you want a common error handler, as there's likely a completely different way for you do accomplish your end goal.

**Comment by santh5858** [comment]
Basically i'm looking for a way to handle errors/exception for webapps in that server instance with a custom error page. 
Here, by error/exception, i mean anything thrown that is not handled by the webapp. For example, instead of mapping 404 pages in web.xml for each webapp or handling a specific type of exception, i'd like to configure it outside the webapp. So in case the webapp throws an error and there is no handling for that error within the webapp, i want to show a custom page rather than the error page generated via jetty. While testing, i was testing with 404 case where i map a war with the context path /abc. When i go to /abc/random, instead of showing jetty's default 404, i want to show a custom error page (i intentionally avoided mapping 404 in webapp's web.xml). When i checked the "Creating Custom Error Pages : Custom ErrorHandler class", i saw that extending ErrorHandler and setting that custom class can handle this issue. So, i created a class that extended ErrorHandler and added my custom implementation in handle method. Now, when i map it to a specific webapp using using the context XML deployment descriptor for that webapp using​
```
​<Configure class="org.eclipse.jetty.server.handler.ContextHandler">
  ...
  <Set name="errorHandler">
    <New class="com.acme.handler.MyErrorHandler"/>
  </Set>
  ...
</Configure>​
```
​the error is handled properly using my handler. But when i add a second webapp, i have to then duplicated the same code on the context XML deployment descriptor of the second webapp. And this will keep happening for any number of webapps that i deploy in that server instance. So instead, i tried adding ​
```
​<Configure id="Server" class="org.eclipse.jetty.server.Server">
  ...
  <Call name="addBean">
    <Arg>
      <New class="com.acme.handler.MyErrorHandler"/>
    </Arg>
  </Call>
  ...
</Configure>​
```
​so that the error handler is set in server level and would be applicable for all the webapps (My understanding is that if i set a error handler on server level, it will be applicable for all the webapps deployed using that server instance). But when i tried executing the same, my handler was not used. ​
​​
​To summarise, i'm trying to add my custom error handler to all webapps deployed in that server instance and specify the error handler in a common place without specifying the handler to be used in each webapp's context XML deployment descriptor.

**Comment by joakime** [comment]
That `org.eclipse.jetty.server.handler.ContextHandler` does not use `ErrorPageErrorHandler`, it uses the server level error handler.
This is simply because it is not a `WebAppContext`.

404 is handled entirely within the `WebAppContext`, if you have no 404 mapping specified in the webapp, then the `DefaultServlet` answers the 404, no error handler involved.
This again is standard Servlet behavior, once you enter the `WebAppContext` you stay in the `WebAppContext`.

Even unhandled Exceptions and Throwables are handled by the ServletContext, they simply will not flow out to the server level, for the server level errorhandler to operate on it.

You cannot have a server level error handling for `WebAppContext` based web apps.
All other webapp concepts (Handler, AbstractHandler, ContextHandler, ServletContextHandler, etc) will use the server level error handler.

Having common behavior across multiple `WebAppContext` requires a few things.

1. They need a common configuration (either from a custom descriptor or via custom deploy logic)
2. They need a common JAR file loaded by each `WebAppClassloader` (requiring custom XML or custom deploy logic) 
3. The common implementation can only access what is in that `WebAppContext` (so no accessing server level components/jars/etc)

Start with adding the `global-webapp-common` module in your `${jetty.base}` instance.
Then configure the `${jetty.base}/etc/webapp-common.xml` to configure each deployed webapp the way you want.

For the common configuration, you can use custom descriptors.
Either a custom default descriptor, or a custom override descriptor.
See WebAppContext.setDefaultDescriptor(String file)
or WebAppContext.setOverrideDescriptor(String file)

These two will be useful to set to setup the common servlet error-page mappings you want/need.
You can register new Servlets to handle the `DispatcherType.ERROR` for those mappings you just added as well.

You'll next need to call `WebAppContext.setExtraClasspath(String path)` to add the JAR holding your common classes.

Note: You are not providing a custom `ErrorPageErrorHandler` or custom `ErrorHandler` doing this.
You are using Servlets, and servlet error-page mappings.

**Comment by santh5858** [comment]
I think i understand now. Thanks for the detailed explanation. I'll try implementing it in the way you suggested. Thanks
