### ISSUE TITLE
Support Loom

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#8007]
**Target Jetty version(s)**
10.0.x

**Enhancement Description**
With project Loom being integrated in Java 19+22, we should offer an option to call `Handler`s with a virtual thread.
This would allow testing by early adopters.

**Comment by AlanBateman** [comment]
Just a quick comment to say that testing if the Thread.startVirtualThread method is present will help detect if the runtime is 19+, using Runtime.version().feature() >= 19 would be simpler. Also just to say that this method throws UOE if not running with --enable-preview.

One thing you might want to consider is creating an ExecutorService with Executors.newVirtualThreadExecutor rather than using the Thread API directly. I understand the change here is more of "hand off" rather than a deep change but once advantage of using an ES is that it will mean the virtual threads are tracked and it means they will show up in thread dumps and serviceability tools. At this time, virtual threads that are created directly with the Thread API aren't visible to serviceability tools because they aren't party of any "grouping".

**Comment by sbordet** [comment]
@AlanBateman thanks for the suggestions! We'll make the changes.
