### ISSUE TITLE
Jetty preventing async event listener from getting garabage-collected

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#8068]
**Jetty version(s)**
11.0.9

**Java version/vendor** `(use: java -version)`
openjdk version "18.0.1" 2022-04-19
OpenJDK Runtime Environment Zulu18.30+11-CA (build 18.0.1+10)
OpenJDK 64-Bit Server VM Zulu18.30+11-CA (build 18.0.1+10, mixed mode, sharing)

**OS type/version**
Microsoft Windows [Version 10.0.19044.1706]

**Description**
I discovered a memory leak in commercial software that I am developing (so it's hard for me to share source code) but it roughly looks like this:

1. My code invokes the following code snippet:
```
private final AtomicReference<HttpResult> httpResult = new AtomicReference<>();

public void send(Consumer<HttpResult> resultConsumer)
{
	BufferingResponseListener responseListener = new BufferingResponseListener()
	{
		@Override
		public void onComplete(Result result)
		{
			HttpResult httpResult = new HttpResult(result, getContent(), getMediaType(), getEncoding());
			HttpRequestContext.this.httpResult.set(httpResult);
			resultConsumer.accept(httpResult);
		}
	});
	// ...
	Request newRequest = updateUri(request, newUri).tag(someString);
	newRequest.send(responseListener);
};

private Request updateUri(Request request, URI newUri)
{
	return scope.getHttpClient().newRequest(newUri).
		method(request.getMethod()).
		headers(newHeaders ->
			newHeaders.add(request.getHeaders())).
		body(request.getBody()).
		tag(request.getTag());
}
```

Essentially I'm taking an existing `Request` and construct a new instance with a different URI but the same headers, body, and tag. 

The event listener constructs an `HttpResult` (which is just a facade/wrapper of `BufferingResponseListener`) and passes it to some callback (`resultConsumer`) .

When I run the above code I end up with a memory leak with the following GC root:

![image](https://user-images.githubusercontent.com/633348/170892041-6aeab981-3325-4cac-a51c-8f2b76593246.png)

I'm finding it hard to interpret this stack trace but I think it means that Jetty is keeping `responseListener` alive which keeps `httpResult` and the enclosing `HttpRequestContext` class alive.

Am I doing anything wrong? Am I supposed to deregister the event listener somehow?

**Comment by gregw** [comment]
I don't think that is a stack trace, it is a reference trace.     This is telling me that at this point, the connection is still in the scheduler queue for an idleTimeout.   The connection is removed from that queue in its onClose method, so that connection is still open.... which may well be the case as the client attempts to use persistent connections where possible.

So this might not be a leak, rather just a pooled connection.

Now it may be that the connection should have nulled the exchange instance at this stage.... but that depends on the state of the request(s).    Can you tell us more about how many requests are being sent, when you are taking this log.  Can you do a HttpClient.dumpStdErr as well?

**Comment by cowwoc** [comment]
I think you're right. I'm going to close these issue for now and if the issue re-appears I will reopen it. Thank you.
