### ISSUE TITLE
Error reporting "Could not process key for channel" for unix sockets

### ISSUE THREAD

**Issue by usertree** [eclipse/jetty.project#8091]
**Jetty version(s)**
9.4.46.v20220331
**Java version/vendor** `(use: java -version)`
8
**OS type/version**
x86
**Description**
When the peer end is unreachable, the expected response code is 503. However, in practice, no result is returned until 30 seconds expires. How to solve or avoid this problem?
![image](https://user-images.githubusercontent.com/32734356/171363388-1c260d58-7d23-4d36-b8cb-48a7a9432045.png)

See this issue, but it does not seem to solve the problem.
https://github.com/eclipse/jetty.project/issues/4865

**Comment by sbordet** [comment]
The JNR UnixSocket implementation is not stable.

Please use Java 16's UnixDomain sockets instead, available in Jetty 10+.

See:
https://www.eclipse.org/jetty/documentation/jetty-10/programming-guide/index.html#pg-client-io-arch-unix-domain
https://www.eclipse.org/jetty/documentation/jetty-10/programming-guide/index.html#pg-server-http-connector

**Comment by usertree** [comment]
The JDK cannot be upgraded due to historical reasons. Can I replace jnr-unixsocket on which jetty-unixsocket depends with junixsocket?Are there any examples? After I replaced it, there seems to be some problems with the selector.

**Comment by kohlschuetter** [comment]
Related issue on junixsocket: https://github.com/kohlschutter/junixsocket/issues/108

(I'm the author of junixsocket. Please let me know if you found any problems with junixsocket with your setup; version 2.5.0 has seen significant improvements, also regarding Selectors)

**Comment by kohlschuetter** [comment]
Since there's probably at least another person who thought about adding junixsocket to jetty but then gave up: I'm now adding jetty support to junixsocket (via the "junixsocket-jetty" artifact).

The latest code (2.5.1-SNAPSHOT) now supports both a server connector (jetty >= 9.4.12) and a client connector (jetty >= 10.0.8). Please give it a try and let me know if that works for you.

See discussion in https://github.com/kohlschutter/junixsocket/issues/108
