### ISSUE TITLE
How to use Jetty Source Code start web app 

### ISSUE THREAD

**Issue by huifer** [eclipse/jetty.project#8114]
**Jetty version**
jetty verson: 11.0.9

**Java version**

java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

**Question**
How do I launch a Web application using the Main class in Jetty's source code

**Comment by huifer** [comment]
How should I set up the ${jetty.base}  directory

**Comment by sbordet** [comment]
Please read the documentation.
It's divided in 2, one part if you want to use code to deploy your web applications, and another part if you want to start Jetty as a standalone server and you want to deploy your web applications.

> How should I set up the ${jetty.base} directory

https://www.eclipse.org/jetty/documentation/jetty-11/operations-guide/index.html

> How do I launch a Web application using the Main class in Jetty's source code

https://www.eclipse.org/jetty/documentation/jetty-11/programming-guide/index.html

**Comment by huifer** [comment]
Sorry I don't see how to use Main to launch a WebApp

<img width="386" alt="image" src="https://user-images.githubusercontent.com/26766909/172126256-8cac17b0-79ec-49cd-8f86-9d88bdf3b9e3.png">

**Comment by sbordet** [comment]
@huifer you don't specify what "Main" is, so I have no idea what you are asking.
Furthermore, Jetty is very configurable, so "WebApp" may mean different things to different people.

If you mean that you want to use _code_ to start Jetty and deploy a standard EE9 web application, read here:
https://www.eclipse.org/jetty/documentation/jetty-11/programming-guide/index.html#pg-server-http-handler-use-webapp-context

Because you want to use code, the concept of a `$JETTY_BASE` is not relevant, as it is only used if you use Jetty as a standalone server.

**Comment by huifer** [comment]
Main is `org.eclipse.jetty.start.Main` . I want start from `org.eclipse.jetty.start.Main` just start . My application looks like this ![pic](https://user-images.githubusercontent.com/26766909/172126256-8cac17b0-79ec-49cd-8f86-9d88bdf3b9e3.png)

**Comment by huifer** [comment]
I see a test class `org.eclipse.jetty.quickstart.Quickstart#main` ，I started the test class directly and got an exception
```
ERROR: No WAR file or directory given
Usage: java -jar QuickStartWar.jar <war-directory> <context-xml>
       java -jar QuickStartWar.jar <war-file> <context-xml>
```
How can I solve it

**Comment by sbordet** [comment]
> How can I solve it

You are not providing enough information.

Read and follow the instructions in the documentation: https://www.eclipse.org/jetty/documentation/jetty-11/operations-guide/index.html

**Comment by joakime** [comment]
@huifer there are examples of setting up the `${jetty.base}` directory in the documentation at https://www.eclipse.org/jetty/documentation/jetty-11/operations-guide/index.html

You have not provided enough detail on your issue for us to give you any more specific information/help.

**Comment by huifer** [comment]
> 

i want start with `org.eclipse.jetty.start.Main`

**Comment by huifer** [comment]
> @huifer there are examples of setting up the `${jetty.base}` directory in the documentation at https://www.eclipse.org/jetty/documentation/jetty-11/operations-guide/index.html
> 
> You have not provided enough detail on your issue for us to give you any more specific information/help.

I can start a Web application in a separate base directory using the document you gave
<img width="465" alt="image" src="https://user-images.githubusercontent.com/26766909/172270078-240a122b-4c4a-456e-b47e-379f99137cb7.png">

But the way I do it is java -jar /jetty.project/jetty-home/target/jetty-home/start.jar ，I see that start.jar is compiled from Main(`org.eclipse.jetty.start.Main`) ，I want to start the Web application in the base directory using Main(`org.eclipse.jetty.start.Main`)

**Comment by joakime** [comment]
The Jetty `start.jar` is a bootstrap to build a server from configuration.
It manages jar files, classpaths/classloaders, properties, xml, etc...

The fact that you are using `java -jar /path/to/jetty-home/start.jar` means you are already using `org.eclipse.jetty.start.Main`.
Based on what you are asking, you are done, you've succeeded in starting your web application with `org.eclipse.jetty.start.Main`.  Congrats!

**Comment by huifer** [comment]
> 

ummmm, I just want to use the `org.eclipse.jetty.start.Main` , don't want to through the `java -jar /path/to/jetty-home/start.jar` , i want using `org.eclipse.jetty.start.Main` with base  directory
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/26766909/172281313-d88771c2-0cd2-46b7-88da-e2dec37e4f06.png">

**Comment by joakime** [comment]
The `org.eclipse.jetty.start.Main` cannot be used like that in your IDE.

Why?  it's because the `start.jar` contains a shaded portion of classes coming from other places.

The classpath / classloader of `start.jar` is empty (intentionally), it creates and manages the classloader/classpath and then kicks off a Jetty, and will even kick off a forked Jetty if your configuration specifies something that needs to kick off a forked Jetty.

If you want to debug with Jetty, you have 2 steps.

1. In a terminal, run Jetty with debug options enabled.
2. In your IDE, kick off a DEBUG session against the application running in debug mode.

For step 1, you'll need a way to kick off the JVM debug mode.

This means you'll create a small file in your `${jetty.base}/modules/` directory (create that directory if it doesn't exist yet)

*${jetty.base}/modules/remote-debug.mod*

```
[exec]
-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
```

This will be added as-needed with your manual run of Jetty.

``` shell
$ cd /path/to/my-jetty-base
$ java -jar /path/to/jetty-home/start.jar --module=remote-debug
```

You should see output with lines like ...

```
WARN  : Forking second JVM due to forking module(s): [remote-debug]. Use --dry-run to generate the command line to avoid forking.
Listening for transport dt_socket at address: 5005
```

This tells you that the JVM agent for debugging is now running.
Make sure you start your Jetty server with "remote-debug" first.

For step 2, you'll use your IDE to create a "Remote JVM Debug" entry in your "Debug ..." tooling.

![intellij-remote-jvm-debug](https://user-images.githubusercontent.com/191721/172376776-e7d37251-66f5-4d5d-9044-86f5ce2dacad.png)

This is the next step, you'll execute this new entry and now you have your IDE connected to your running Jetty instance.
Setup some breakpoints and you should see a normal Debug session.

**Comment by huifer** [comment]
Thank you very much @joakime

**Comment by huifer** [comment]
If I want to analyze the startup process of start.jar, which class should I start from

**Comment by gregw** [comment]
There are several key classes in jetty-start module. The `Main` and `StartArgs` are good ones to start with. Not also you can turn on debug you see how it works
