### ISSUE TITLE
jetty.sh does not read JAVA_OPTIONS anymore

### ISSUE THREAD

**Issue by fanf** [eclipse/jetty.project#8152]
**Jetty version(s)**

Jetty 10.x since commit c89866682c14ca1da0ce482eeca0953375b25da8, ie 

git tag --contains=c89866682c14ca1da0ce482eeca0953375b25da8                                   
jetty-10.0.8
jetty-10.0.9
jetty-11.0.8
jetty-11.0.9

**Java version/vendor** `(use: java -version)`

Any

**OS type/version**

Any

**Description**

Since commit c89866682c14ca1da0ce482eeca0953375b25da8, `JAVA_OPTIONS` is not read anywhere in `jetty.sh` script. 
I believe the goal of the refactoring was to add `JETTY_SYS_PROPS` and then add `JAVA_OPTIONS` in `RUN_ARGS`, but it was not done

**Comment by joakime** [comment]
The removal of JAVA_OPTIONS was because of the nature of how configurations could fork a JVM.
Those options would not carry over to a configuration that would fork the JVM.

The changes in jetty.sh reflect this, and an effort to build the true command line based on your Configuration.
This means using the `exec` module in your `${jetty.base}/start.d/exec.ini` and including any previous JAVA_OPTIONS there.

**Comment by fanf** [comment]
OK, thanks for the information. I'm not sure it will work for us, since we are sourcing external config files to get the option list, but I will look at the doc now that I know the entry point. Thanks for the pointer.
