### ISSUE TITLE
Customizers before HttpChannel.Listener.onBeforeDispatch

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#8218]
_**Reference conversation in PR #7255 for background.**_

Kind of.   Currently 12 has dropped the HttpChannel.Listener concept... but I expect that we will need either to restore it, or a similar mechanism.
So the ordering concern expressed in this PR should definitely be considered when we add listeners back to 12.

Maybe for now, it should just become a TODO in the 12 branch(es) to indicate that listeners should be called after customization.

_Originally posted by @gregw in https://github.com/eclipse/jetty.project/issues/7255#issuecomment-1056798866_

**Comment by gregw** [comment]
really, Really, REALLY want to avoid adding back listeners to Jetty-12.     Because we are able to wrap in jetty-12, we already have very good interception points and so far we have not found anything that a listener could do that can't be done with a wraper.   Wrappers are better than listeners because when they are not needed, there is zero cost, whilst listeners still need to check empty lists at key events.   When they are used, the extra dereferencing through a wrapper will cost about the same (or maybe less) than the iteration through listener lists.

**Comment by joakime** [comment]
I'm good with that.
Closing...
