### ISSUE TITLE
upgrade to 11.0.x ,is it still need alpn-boot jar for support http2?

### ISSUE THREAD

**Issue by xinguangduan** [eclipse/jetty.project#8258]
**Jetty version**
9.4.48.v20220622
**Java version**
jdk1.8
**Question**
I have a question. I want to upgrade jetty from 9.4. x to 11.0.x. Our scenario uses Jetty as an HTTP2 service, so alpn-boot-8.1.13.v20181017.jar is used in jetty9.4.x. If we upgrading to Jetty11.0.  x, is it still need alpn-boot-8.1.13.v20181017.jar?

**Comment by joakime** [comment]
alpn-boot is for older versions of Java.

Newer versions of Java, even Java 8 would need alpn-agent.
But with Java 9+ you don't need alpn-boot, this was true even with Jetty 9.4.x

See 

* https://www.eclipse.org/jetty/documentation/jetty-9/index.html#alpn-openjdk8-agent
* https://www.eclipse.org/jetty/documentation/jetty-11/operations-guide/index.html#og-module-alpn

Since you require the use of Java 11 (at a minimum) for Jetty 11.0.x, you are well past the need for alpn-boot or alpn-agent (you need neither)

The only thing that isn't supported (out of the box) is the IBM JVM, which uses non-standard SSL/TLS configuration (you can make the IBM JVM work with Jetty, but it requires an enormous amount of work on your part to configure the JVM, and Jetty to use all of the non-standard names).

**Comment by xinguangduan** [comment]
@joakime thanks a lot for your very detailed answer !
