### ISSUE TITLE
No Filesystem mounted on ee9 webapp deployment error

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#8290]
** jetty-12.0.x"

When the ee9 webapps deploy, the following warning occurs for every webapp:

> 2022-07-13 10:20:27.852:WARN :oejes.DefaultServlet:main: Unable to use stylesheet: null - java.lang.IllegalStateException: No FileSystem mounted for : jar:file:/home/janb/src/jetty-eclipse/jetty-12.0.x/jetty-home/target/jetty-home/lib/jetty-server-12.0.0-SNAPSHOT.jar!/jetty-dir.css

**Comment by lorban** [comment]
This was partially fixed in https://github.com/eclipse/jetty.project/commit/cdc1b079ae509e3485200728fd3d7acdce6561b2#diff-72000f31f0a66b20471a919375f90b2c4184d6d05281084fe97f20cdc2505e25R166

We're going to need https://github.com/eclipse/jetty.project/pull/8409 to properly fix this. I'll take care of this once that other PR gets merged.

**Comment by joakime** [comment]
Trying to address this specifically in PR #8416

**Comment by joakime** [comment]
This has been fixed for a few months now. Closing.
