### ISSUE TITLE
MBeanContainer no longer unregisters MBeans when "stopped"

### ISSUE THREAD

**Issue by grgrzybek** [eclipse/jetty.project#851]
In jetty 8, `org.eclipse.jetty.jmx.MBeanContainer` extended `org.eclipse.jetty.util.component.AbstractLifeCycle`, so this bean was unregistering MBeans on server stop.

In jetty 9, after 68ee346, only `Container.InheritedListener` is implemented and `destroy()` method doesn't seem to be called anywhere.

pax-web 4.2.x stops Jetty server, but `MBeanContainer` isn't explicitly destroyed() - we may add this call, but maybe `MBeanContainer`'s lifecycle should be again managed by server?

**Comment by sbordet** [comment]
`MBeanContainer` lifecycle should be managed by the container it is added to, typically a `Server`.

**Comment by sbordet** [comment]
@grgrzybek I was wrong regarding `MBeanContainer` lifecycle.

`Server.stop()` does not modify the bean tree so that the `Server` can be restarted.
MBeans are registered at `start()` but not unregistered at `stop()`, and a subsequent `start()` does nothing (i.e. they are _not_ registered twice).

Interface `Destroyable` was introduced exactly for this case, to destroy resources the server may hold on to to cover multiple start/stop cycles.

The right way to unregister the MBeans would then be:

```java
Server server = new Server();
...
server.start();

// Later
server.stop();
server.destroy();
```

Unfortunately, `MBeanContainer` does not implement `Destroyable`. If it did, the MBeans would be unregistered at the `destroy()` call. That is a bug.

Note that after the `destroy()` call, you may restart the server, but that won't re-register the MBeans, because the bean tree is unmodified. So `destroy()` is a terminal operation to do when you're sure you won't use the `Server` instance anymore.

**Comment by grgrzybek** [comment]
Thanks for the fix.
Is there a chance to add 10000th commit https://github.com/eclipse/jetty.project/tree/jetty-9.2.x branch?

**Comment by sbordet** [comment]
@grgrzybek backported to 9.2.x by @gregw with the above commit.

**Comment by joakime** [comment]
@grgrzybek  note that Issue #854 has been fixed, which will corrects some of the behavior surrounding `.stop()` -> `.destroy()` -> `.start()`

**Comment by grgrzybek** [comment]
thanks for info!
