### ISSUE TITLE
Disable revocation checking

### ISSUE THREAD

**Issue by Francis-Valcke** [eclipse/jetty.project#8533]
**Jetty version**
9.4.19
**Java version**
17
**Question**
The CertificateValidator hardcodes revocation checking on line 228:
`pbParams.setRevocationEnabled(true);`
I have a use case in an internal organization environment where I want to disable revocation checking.
Is there any way to do this with Jetty?
Thanks!

**Comment by joakime** [comment]
If you are using PKIX with Java then having `pbParams.setRevocationEnabled(false)` is not recommended.

In all of the PKIX vendors we've tested, having `pbParams.setRevocationEnabled(false)` will result in one of the two scenarios

1. PKIX featureset is disabled entirely, causing a server that cannot support PKIX.
2. PKIX fails to start/init causing a System.exit() and no server instance running.

**Comment by gregw** [comment]
As indicated above, it is not really best practise for us to support this, thus making it configurable is not going to be a high priority for us.  It is a little bit of work as it appears that we have not made the CertificateValidator instance pluggable where it is used, so it will be difficult to extend.  The class itself is also not that well setup for being extended.

I suggest that you create a PR to fix these problems, so that you can provide an extended CertificateValidator with the revocation mode either disabled or configurable.   Submit the PR and we'll consider it.
Alternately, you can consider a commercial support contract, as special support for special use-cases is the kind of thing commercial support if there for.

**Comment by Francis-Valcke** [comment]
Hey, thanks for the replies. Is it a viable strategy to introduce a system variable that allows for configuring/overriding this?

**Comment by gregw** [comment]
System properties are a poor way to configure jetty as we frequency have multiple connectors per server and sometimes multiple servers per JVM.   Thus a system property based PR would be unlikely to be accepted into the main line.

We prefer to configure things like this via setters that can be called directly in code or via XML injection.

**Comment by gregw** [comment]
System properties are a poor way to configure jetty as we frequency have multiple connectors per server and sometimes multiple servers per JVM.   Thus a system property based PR would be unlikely to be accepted into the main line.

We prefer to configure things like this via setters that can be called directly in code or via XML injection.

**Comment by Francis-Valcke** [comment]
Yeah, I understand! I'll try to find another way of tackling this problem. Thanks for the responses!
