### ISSUE TITLE
Add server/port and auth configuration for mongo sessions

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#856]

**Comment by janbartel** [comment]
Host and port are done, authentication is not yet done.

**Comment by Ashib** [comment]
Hi Jan, so until is done how do we authenticate if the mongodb is expecting a username and password to connect. 
Thanks.

**Comment by janbartel** [comment]
@Ashib if you're using the distro and modules, then you can subclass the MongoSessionDataStoreFactory and configure Mongo however you would like in the getSessionDataStore method.  If you're using code to configure, then of course you can set up Mongo before getting the Collection to pass in to the SessionDataStore.

If you go the MongoSessionDataStoreFactory route, then please consider making a patch and contributing it back to jetty :)

**Comment by Ashib** [comment]
@janbartel Thanks for the help. I am using the distro and modules and I like the idea of subclassing the MongoSessionDataStoreFactory. I am in the process of making the changes but since I am new to the jetty and mongo sessions I am a little confused about how do I refer to this new subclass for establishing the connection. I have a jetty-web.xml in my webapp and on the server I have the jetty-nosql.xml but I am not able to figure out from the documentation where I can insert the instruction to use this new subclass class to establish a mongo connection using the new username and password parameters.

**Comment by Ashib** [comment]
@janbartel okay, I have new information. We have to user jetty 9.3.x for this. So wanted your inputs on how can I achieve this with jetty 9.3.x. We will be using the distro and the modules approach. I have a jetty-web.xml in my webapp and jetty-nosql.xml on the jetty server. I was going through the jetty-nosql source on github but couldn't find any place where I can make the change. Thanks.

**Comment by janbartel** [comment]
@Ashib  for jetty-9.3 then you want to be looking at this documentation instead: https://www.eclipse.org/jetty/documentation/9.3.x/session-clustering-mongodb.html

You should be able to customize the jetty-nosql.xml file to set up the com.mongo.MongoDB instance the way you want with authentication.

**Comment by janbartel** [comment]
Assigning to @WalkerWatch for documentation.  Chris, we added in the ability to configure connection to the mongo instance with a secure uri.  Before it was only possible by specifying the host/port address combination.  I modified the session-store-mongo.mod file to choose between these two methods using the property "connection-type", which will default to  "address" but can be changed to value "uri" to use a mongodb:// uri that includes auth information. Have a look at the file changes and do ask if you have any questions.
