### ISSUE TITLE
Response to request for host leads to flood of new requests

### ISSUE THREAD

**Issue by pschaeffer** [eclipse/jetty.project#8632]
I have found a possible bug in Jetty. I am not sure about this, and the bug may actually be elsewhere. Here is the scenario. A request for abc.com (not really abc.com) comes in. The request is handled by sending a request to abc.com for a response. Of course, the leads to a flood of requests.

I think it is obvious that a request to abc.com should not generate another request to abc.com. That is/was an error on my part and I have fixed it. 

However, the flood of requests causes Jetty to hang. Jetty should not (in my opinion) hang, no matter what. If Jetty can not handle a request, then Jetty should (perhaps) send a ‘Connection Refused’ response.

**Comment by gregw** [comment]
I think you need to explain a bit more.  What do you mean by "request is handled by sending a request to abc.com for response"?  Is this a proxy? or a redirect?

You are correct that jetty should not hang.  Can you get a thread dump from the JVM when you think it is hung?

**Comment by joakime** [comment]
> Jetty should not (in my opinion) hang, no matter what.

Issue a request to something that is not part of your webapp.
 * eg: `/favicon.ico`
 * or something guaranteed to cause an error in the parser (eg `GET ---- HTTP/1.1`)  

This can verify if the issue is due to behavior in your webapp, or behavior in Jetty.

Also verify that you have sufficient machine resources to satisfy the requests.
Example: 
  * typical OS level configurations for high load systems.
  * not enough network resources (you are at capacity for your networking setup)
  * not enough file handles allowed to the server instance.
  * not a properly configured ThreadPool for high load systems.

**Comment by pschaeffer** [comment]
Gregw, how do I get a thread dump? How do I send it to you? My program (what I call abc.com for convenience) is sometimes used as a proxy. In other words, my program gets a request and then sends the request to some other machine for the answer. The problem is that in some cases, my program is sending the request back to itself. The leads to an overload condition where Jetty hangs (or so I think).

**Comment by joakime** [comment]
Are you using one of the Jetty `ProxyServlet` implementations to implement your proxy?

Regarding obtaining a Java Thread Dump, see https://www.baeldung.com/java-thread-dump

**Comment by pschaeffer** [comment]
Mr. Erdfelt, I tried https://www.owo.secure.dnsalias.com/favicon.ico and got the same result. I think I have plenty of resources. It looks like I have 250-260 threads in my Jetty instance. It looks like I am using Jetty 9.4,42, Could that be the problem? I am not sure either way.

**Comment by joakime** [comment]
9.4.42 is a bit out of date.
And is subject to a few Security vulnerabilities -> https://www.eclipse.org/jetty/security_reports.php

Can you upgrade?
[jetty-9.4.49.v20220914](https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.49.v20220914) was released about 3 weeks ago.

**Comment by joakime** [comment]
Also, 9.4.x is now at end of Community Support.
See: https://github.com/eclipse/jetty.project/issues/7958

**Comment by pschaeffer** [comment]
Mr. Erdfelt, greggw

Attached you will find some thread dumps. Are these what you need?
![threaddump-1664565664168](https://user-images.githubusercontent.com/3717450/193345150-4bb7c64a-b221-423e-9b3d-bc6e199224ea.gif)
![threaddump-1664565631108](https://user-images.githubusercontent.com/3717450/193345190-97b72e35-4f26-4f34-86b3-2005b7a14266.gif)Note that the actual file type was tdump, not gif. The first file is from an idle Jetty system. The second file is after then hang. I got these file using VisualVM.

Thank you

Peter Schaeffer

**Comment by pschaeffer** [comment]
Mr. Erdfelt, gregw,
I upgraded to 9.4.49. No change in observed behavior.
Thank you
Peter Schaeffer

**Comment by cowwoc** [comment]
@pschaeffer
Do you happen to use HttpClient to make HTTP requests using a proxy (by that I mean `HttpClient.getProxyConfiguration().getProxies()`)? If so, take a look at https://github.com/eclipse/jetty.project/issues/8584

I doubt you are running into the same scenario as me, but I figured I'd mention it just in case.

**Comment by pschaeffer** [comment]
COWWOC, I am using HttpClient. However, I am not using a proxy (or at least I don't think so). 
Thank you
Peter Schaeffer

**Comment by gregw** [comment]
If you are using HttpClient to make a request back to yourself, then isn't your application logic that is causing the loop?  
Surely you should check that the requested resource is not yourself before issuing a new request?
Or perhaps add a header to the outgoing request, so that if you see that header on an incoming request then you have detected a loop.

**Comment by pschaeffer** [comment]
gregw, you are quite correct. I have changed my logic to check for "a request back to yourself". I now generate a 500 HTTP code and exit. However, I don't think Jetty should hang in any case.

**Comment by gregw** [comment]
@pschaeffer i redirect the jetty hang was simply due to the thread pool bring totally consumed by there recursive nature of your request loop.

Note that if you had used async request handling and an async http client request, then jetty would not be blocked by a consumed thread pool.

**Comment by pschaeffer** [comment]
gregw, I would think that Jetty would handle a consumed thread pool by failing requests (or doing something else). However, no such behavior was noted. What I actually got was a hang, with no observed failures.

**Comment by gregw** [comment]
Jetty can be configured with a quality of service monitor that would do that. However, many users want a constrained thread pool to limit resource allocation and cause extra response latency rather than failing requests. Hence that is not the default configuration. Most exhausted thread pools are not actually dead locked like yours was.

**Comment by pschaeffer** [comment]
gregw, I had the problem in #1894 (illegal state exception). What is the best set of modules for 9.4.49? I don't have openjdk8 or conscrypt in my path. Should I add them?
