### ISSUE TITLE
Jetty 12 - Improve ErrorProcessor to handle error pages

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#8726]
**Jetty version(s)**
12+

**Description**
It would be nice if `ErrorProcessor` (or a subclass) can be configured with a mapping between the HTTP status code and an error page, something like:

```java
errorProcessor.addPage(404, "/404.html");
```

**Comment by gregw** [comment]
In order to do this, we would need an `ErrorPageErrorProcessor extends ErrorProcessor` that is aware of the server (or perhaps context).   Either way, there are two ways to implement:

1. On every error process call the `server.handle` method is called to get a processor for the error page.   This means there is a possible blocking call to `Handler.handle` before the processor is found.

2. During onStart, fake requests are used to call the `server.handle` method to pre-obtain processors for the error pages.   This would avoid the blocking stage during process, but I'm not sure it would work for all processors... as the requests ultimately passed to the processor would be different instance to the request passed to obtain the processor.  Any processor that retains the initial request (possibly wrapped) would not work.

So I think 2. is a non-starter and probably an over optimisation anyway.  1 it is then.

**Comment by sbordet** [comment]
@gregw left a feedback on the PR.
