### ISSUE TITLE
Jetty client hangs if less than 5 max threads in executor

### ISSUE THREAD

**Issue by dmitrymurashenkov** [eclipse/jetty.project#874]
Following example hangs with <5 threads and passes if 5+ threads in pool.

```
    public static void main(String[] args) throws Exception
    {
        int threads = 4;
        HttpClient client = new HttpClient();
        client.setMaxConnectionsPerDestination(1);
        client.setExecutor(Executors.newFixedThreadPool(threads));
        client.start();
        int status = client.GET("http://google.com").getStatus();
        System.out.println(status);
    }
```

**Comment by joakime** [comment]
That's an exceedingly low amount of threads, why do you want to run that low?

**Comment by joakime** [comment]
Hmm, the [`Executor`](http://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Executor.html) interface has no way for us to ask how many threads it has allocated (makes sense, knowing the variety of Executors out there).

Would be hard to present a warning / toss and exception if the thread count is too low when the Executor is set.

Perhaps we would need a runtime exception when the Executor is used, but is incapable of executing immediately?  Catch and report the `RejectedExecutionException` ?

OK, lets look at the example in the issue ...
A `client.GET("http://google.com/")` is ...

- thread httpClient itself
- `http://google.com/` destination
  - connection A
  - thread selector A
  - thread exchange selector A
  - GET results in -> 302 redirect to `https://google.com/` 
  - Connection not yet closed
- `https://google.com/` destination
  - connection B
  - SSL layer B
  - thread selector B
  - thread exchange selector B
  - GET -> 200 OK
- timeout: Connection A closes (selectors A are shut down, exchange A shuts down)
- timeout: Connection B closes (selectors B are shutdown, exchange B shuts down)

Since the example didn't send/set the `Connection: close`  request header, the HTTP/1.1 persistent connections stay open until timeout.

Also (future release concern), the work to integrate HTTP/2 into this client makes the practical minimum threads per destination about 6-ish (quick scan of the code: the selector, physical i/o, protocol i/o, stream i/o, application dispatch).  And that's if the destination decides not to use HTTP/2 all that effectively and not do push or multiple streams (unlikely).

**Comment by dmitrymurashenkov** [comment]
Actually, I was doing some load testing and wanted exact number of concurrent requests so I've started experimenting with number of connections and threads to see how this affects concurrency and run into this behavior.

I was expecting that any Executor can be passed and was surprised when some settings didn't work.

Not a critical issue, but it would be nice to have some sort of exception/log message to avoid searching for a problem in the code.

**Comment by joakime** [comment]
@sbordet got any pointers on how to configure for exact number of concurrent requests?

**Comment by sbordet** [comment]
Not sure what "exact number of concurrent requests" means. It's on the client ? On the server ? HTTP/1.1 ? HTTP/2 ?

My guess is that the best way to control things is when the application does it, because it's the application that knows exactly what needs to be controlled and when.
Relying on setting the number of threads or other configuration parameters is brittle since the defaults are subject to changes to match better "average" behavior (or bug fixes).
Also, the differences between HTTP/1.1 and HTTP/2 make things even more complicate to tune by relying on configuration only.

**Comment by sbordet** [comment]
Note that we have implemented a mechanism to notify application when the number of threads is too low in #1851.

That mechanism works for `ThreadPool.SizedThreadPool` instances.
We now have a wrapper to wrap JDK's `ThreadPoolExecutor` and expose it as a `SizedThreadPool` called `ExecutorSizedThreadPool`.

By either using a `QueuedThreadPool` and a `ExecutorSizedThreadPool` applications are warned (or failed) if the number of threads is too low.

**Comment by bradical** [comment]
Running in some issues that I think could be the result of this. Is there a recommended number of min/max threads to use here? Our current logic is:

```
QueuedThreadPool jettyThreadPool = new QueuedThreadPool(Math.max(8,Runtime.getRuntime().availableProcessors() * 4), 4);
jettyThreadPool.setDaemon(true);
```

**Comment by joakime** [comment]
min/max threads are a per application decision.

Like @sbordet pointed out, you have to understand your application, its needs, and the work outwards to the technology choices, APIs, hardware, etc..
"concurrent requests" isn't a useful metric to base any decisions on as it has very different meaning for client vs server and even HTTP/1.1 vs HTTP/2.
Even decisions like websocket, or long polling can have an impact.
Your choice of APIs can even have an impact.  Blocking I/O uses threads for a longer period of time vs async I/O which uses them only when needed.

A server usually uses more threads then a client, but even that is not always true.
Its easy to have an client API use far more threads then a server.

If you want to use defaults, then just don't configure the QueuedThreadPool and use its default settings.

Don't prematurely optimize, use defaults, monitor, learn the behaviors of your application, and adjust according to facts, not guesses or gut feelings.

**Comment by marcel91** [comment]
We have also some problems with limiting the jetty http client thread pool. In order to save resources, we tried to configure the upper limit of the jetty http client thread pool with

QueuedThreadPool threadPool = new QueuedThreadPool(8,1);
client.setExecutor(threadPool);

This worked fine in manual tests. I was able to do hundreds of concurrent long running requests without any problems or performance degradation. However problems are occurring in our CI builds, where we run into the situation that the http client doesn't send requests at all anymore. This only occurs on some machines. So it seems to me like some sort of race condition. In a thread dump I saw that only the "qtp..." threads were running and no "HttpClient...scheduler" thread.
This problem disappeared once I used the default settings.

My question is: Is there a minimum limit for the thread pool that guarantees the http client to work reliably?

**Comment by marcel91** [comment]
In order to save resources, we also tried to limit the threadpool with

QueuedThreadPool threadPool = new QueuedThreadPool(8, 1);
httpClient.setExecutor(threadPool);

When I tested this manually I was able to perform hundreds of concurrent long running requests without any problems or performance degradation.
However in our CI builds we get the following exception on some machines:

java.util.concurrent.RejectedExecutionException: org.eclipse.jetty.client.HttpClient@70b6f84e is stopped
at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:282)
at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:247)
at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:573)
at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:727)
at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:719)
	
At least in 9.4.9.v20180320. In 9.4.7.v20170914 the client just wouldn't send requests anymore. So I guess the problem is still the same but the error handling changed.
When I used the default settings for the QueuedThreadPool the problem does not occur.

Is this a bug or is there a minimum number of threads that must be used in order for the http client to work reliably?

**Comment by sbordet** [comment]
@marcel91 the exception says another thing, namely that the `HttpClient` instance is stopped, yet you want to send a request. Seems a bug in the code your CI runs.

> In order to save resources

This is misleading, as Jetty will timeout threads that are not used, so by constraining the thread pool to a small number of threads, you are not saving resources, you are limiting the operativity of `HttpClient`.
`HttpClient` will not overuse resources so that you have to configure it to save them.

We have too little information about your particular issue with the CI.
If you can reproduce it reliably please open another issue with all the details for us to reproduce it.

**Comment by marcel91** [comment]
@sbordet We never call stop on the http client in our code. Also the exception is not only thrown if the http client is stopped but always if the http client is not running. I guess that also includes the failed state.

The problem is only reproducible on some of our test machines. It does not occur on all of them. So unfortunately I don't really have a scenario that you could test.

The limited resource in our case is not only cpu but also memory. Therefore we were trying to reduce the number of threads because I observed that the number of threads increased quite quickly and at least in my manual tests I could get the same result with a smaller number.

**Comment by sbordet** [comment]
@marcel91 that you never call `HttpClient.stop()` in your CI is not ideal - you should stop the `HttpClient` when you're done using it.
That error may also imply that you don't start it, or it fails to start for some reason that will typically be logged.
Are your logs saying something ?

**Comment by marcel91** [comment]
@sbordet It's a server and the client is basically used the whole time. Therefore it is not stopped. I currently disabled logging. But I will enable it and get back to you, if I find something useful in the logs.

**Comment by sbordet** [comment]
@marcel91 I don't understand. The CI itself is Jetty server + `HttpClient` ?
Can you please describe your system in details ?

**Comment by marcel91** [comment]
@sbordet WIth CI builds I meant Countinous Integration builds were we test our server. The server that is tested is a http server that does http requests itself. In the code of the http server the problem occurs during the tests.

**Comment by bradical** [comment]
@sbordet:

> that you never call `HttpClient.stop()` in your CI is not ideal - you should stop the HttpClient when you're done using it.

So we have an HttpClient on standby to make requests to user-submitted URLs and to fetch data from those URLs. Are you saying that when that's not actively being used we should be stopping `HttpClient` and starting it again? Is there some threshold of how frequently we use this client where it makes sense to shut it down or keep it running all the time? What would be the downside to leaving it running all of the time?

**Comment by bradical** [comment]
@sbordet not a problem. I wasn't sure if you would prefer we create entirely new issues or look for similar problems to our own among existing issues in the tracker. We had a similar configuration to the original poster but I will happily start a new thread.

**Comment by marcel91** [comment]
@sbordet No problem, I just opened another issue: https://github.com/eclipse/jetty.project/issues/2503 

I was just assuming that this issue could have something to do with our problems because the OP also tried to limit the number of threads.
