### ISSUE TITLE
Restrict jetty-env.xml to only configure JNDI on a technical level

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#875]
There's a fair bit of abuse of the `jetty-env.xml` to configure things that are not JNDI, making our ability to adjust the internal load order / internal Configurations difficult.

If a webapp attempts to use something from `jetty-env.xml` that is not a JNDI setup, then that should fail.

**Comment by gregw** [comment]
That is a tough task as the XML configuration is rather powerful.      We would have to define a very fixed API in an interface and only make that available to the jetty-env.xml.

Alternately, we can just better document the jetty-env as a phase in the configuration processing and point users at better places to do their other configuration.

**Comment by joakime** [comment]
There's a similar issue in `jetty-web.xml` as reported in issue #872

**Comment by joakime** [comment]
A common usage pattern seen for `jetty-env.xml` (comes up in stackoverflow often) is attempting to set `DefaultServlet`  init-params from it.

Perhaps we should simplify this entire layer for Jetty 10.
Only 1 in-webapp configuration file supported.
And attempts to do things that are unsupported should throw an exception (such as changing the resourceBase)

**Comment by janbartel** [comment]
The only reason to have jetty-env.xml is to allow jndi resources to be configured from inside the war instead of from outside (in a context xml file).  Taking into consideration issue #872  maybe we should rename jetty-env.xml and jetty-web.xml to be jetty-pre-web.xml and jetty-post-web.xml?  Any WebAppContext config you need done before web.xml is interpreted goes into jetty-pre-web.xml and anything you want done afterwards can go into jetty-post-web.xml.

Comments?

**Comment by WalkerWatch** [comment]
@janbartel Where did we end up on this?
