### ISSUE TITLE
in Jetty 12, Request class methods gone or became unusable from outside

### ISSUE THREAD

**Issue by flozano** [eclipse/jetty.project#8910]
**Jetty version**
jetty 12.0.0.alpha2

**Java version**
OpenJDK 17.0.5

**Question**
in `Request` class, `getRemoteHost` / `getRemoteAddr`/ `getServerName` / `getLocalPort` became static and package-private.

`getRemoteUser` is gone.

I used these instance methods to apply a custom request logging, but by going package-private I would have to reimplement (copy?) such logic, which is far from ideal.

Is there any reason why these must be package-private? if not, could these be open again?

**Comment by sbordet** [comment]
The `static` methods are not package private, they are `public`.

**Comment by flozano** [comment]
you're right. getRemoteAddr, getServerName, getLocalPort became public static (reading the source I didn't notice I was looking at an *interface* :facepalm: ) 

getRemoteHost, getRemoteUser and getProtocol are gone.

(also, in Response, getLongContentLength is gone)

**Comment by sbordet** [comment]
Closing as answered.

**Comment by joakime** [comment]
The core `Request` object has nothing to do with the Servlet API now.
In fact, there's no Servlet API in the entire `/jetty-core/` layer.

* `getRemoteHost()` is just taking the `getRemoteAddr()` and normalizing it. (`String remoteHost = HostPort.normalizeHost(Request.getRemoteAddr(request))`)
* `getRemoteUser()` is a side effect of having an Authentication configured on the Servlet API, since there's no servlet api in core, this has no meaning and is not available. (FYI, if you don't configure authentication on the Servlet API, this API call returns nothing, even on Jetty 9/10/11)
* `getProtocol()` is `Request.getConnectionMetaData().getHttpVersion()` or `Request.getConnectionMetaData().getProtocol()`

**Comment by joakime** [comment]
As for `Response.getContentLengthLong()` that isn't implemented.

Mainly because HTTP/1.x has a `Content-Length` header, and HTTP/2, and HTTP/3 does not.
You can ask for the HTTP/1.x header via `response.getHeaders().getField(HttpHeader.CONTENT_LENGTH).getLongValue()` if you so desire.
Be aware that when you ask for it matters, as sometimes a handler sets it (early), sometimes the implementation sets it (late).

**Comment by flozano** [comment]
thanks a lot, this was very helpful.
