### ISSUE TITLE
Getting 404 for logging-modules repo related downloads

### ISSUE THREAD

**Issue by raviteja0312** [eclipse/jetty.project#9029]
One of our builds is failing when it is trying to download logback.xml from this url : https://raw.githubusercontent.com/jetty-project/logging-modules/master/capture-all/logback.xml , the build was successful previously but now it is failing because of this, is this some thing related to logging-modules repo since i cannot see the repo.
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/92906627/206658612-92afe0cf-1590-4397-8378-cd460b910685.png">

**Comment by joakime** [comment]
Your project shouldn't be relying on that `logging-modules` example repository, that repo was only for examples on how the module system works, and was deprecated back in Jetty 9.2.x. 
The contents of that repo was never kept up to date for logger versions releases (even security related updates, like the famous log4j issue!)

All of the functionality that repo provided is now present in Jetty proper (since Jetty 9.3.0)

**Note: the entire Jetty 9.x series is End of Community Support, you should be using Jetty 10. - See annoucement at https://github.com/eclipse/jetty.project/issues/7958**

Let's take a look at your usage.
You have `logback.xml` from the `capture-all` example project.

In Jetty 10, you would pick a single logger that represents your implementation, what is actually writing the log files.
Then the rest of the loggers you would pick as "capture" versions.

So, if you wanted `logback` as your implementation, and the rest as capture, you would use ...

```
java -jar /path/to/jetty-home/start.jar --add-modules=logging-logback,logging-jcl-capture,logging-jul-capture,logging-log4j1-capture
```
