### ISSUE TITLE
HTTP/3+QUIC support is experimental 

### ISSUE THREAD

**Issue by headlamp-software** [eclipse/jetty.project#9050]
11.0.12

Java 17

I get a message that reads 'HTTP/3+QUIC support is experimental and not suited for production use.' When will HTTP/3 be ready for production use? What version of Jetty will support HTTP/3 for production use?

Thank you

**Comment by sbordet** [comment]
You need HTTP/3 on the client or on the server?

**Comment by headlamp-software** [comment]
The server

Thank you

**Comment by sbordet** [comment]
Unfortunately the situation with QUIC in Java is that it's not there yet.
We bind to a native library, but the performance is terrible due to the many native calls that we need to make to this native library.
This situation is probably not going to change soon, so HTTP/3 may remain experimental for a while.

**Comment by headlamp-software** [comment]
Thank you for the information. Please keep me posted. 
Please close this question. Thank you.
