### ISSUE TITLE
POST/PUT + Kerberos authentication challenge

### ISSUE THREAD

**Issue by arhimondr** [eclipse/jetty.project#938]
Kerberos (and not only) authentication consist of 2 steps. Initially client send an unauthorized request. As a response to that request client receives status `400 UNAUTHORIZED` with the `Authentication` header. To prevent the streaming of the entire request body, HTTP server can send the response and drop the connection. As a result in `AuthenticationProtocolHandler#AuthenticationListener#onComplete` the failed `result` is being received with the failure cause `EofException`, and the failure is being forwarded to the client (https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-client/src/main/java/org/eclipse/jetty/client/AuthenticationProtocolHandler.java#L89).

I'm not sure what is the best way to fix this issue. Shold we just ignore the `Eof` failures by cheking the exception type? Is that will be good enough?

**Comment by arhimondr** [comment]
@gregw @sbordet Any help is highly appreciated.

**Comment by sbordet** [comment]
So, the client attempted to send a request, and the server closed the connection before the client could finish, so a failure from the client point of view is normal. I don't understand what you would expect instead ?

**Comment by arhimondr** [comment]
Yes, but the first request is only the challenge request. So it must retry it with the authentication afterwards. Same as for the requests without request body.

**Comment by arhimondr** [comment]
As a temporary workaround, i read the entire request body before sending the challenge with `400` status. But with such approach, i need to send the entire content twice, what is not desirable.

**Comment by sbordet** [comment]
Whether it's ok to retry the request if the request failed, that's not something that HttpClient can decide, even in case of 401 (not 400 like you reported above multiple times). Perhaps the intent is exactly to receive the 401, not to retrieve the resource.

If you are in control of the server, please note that Kerberos (well, RFC 4559) is "broken" in the sense that it relies on the connection to be authenticated, not requests.
For a server to close the connection after a 401 response will probably mean that the token sent along with the `WWW-Authenticate` cannot be used in another connection.

If you send a request with content to a URI that is protected, you cannot avoid to send the body twice (unless you use other mechanisms such as `Expect: 100-continue`).

Applications typically "prime" the URI with an idempotent request such as GET, HEAD or OPTIONS before sending request contents that may be rejected.

**Comment by gregw** [comment]
Note that `Expect: 100-continue` will not help in this situation, because when it is used the server has a choice of either sending 100-continue and reading the body OR sending a response without reading the body and then closing the connection.

You cannot not-send the body and keep the connection option, because sending the body may optionally be done without the 100-continue, so that would put the server in the situation where it may read body as a request and we are then vulnerable to attack.

**Comment by arhimondr** [comment]
If you think that it is fine that authorization doesn't work for non idempotent requests, than maybe we should throw the exception explicitly? It works for the small request bodies, but doesn't for the large ones (when server returns 400 response before the request content is all streamed). So, it is hard to catch such unpredictable issue, and hard to debug.

**Comment by gregw** [comment]
@sbordet I  reread this and I think @arhimondr has a point.    The client has received a response from the server that contains an authentication challenge, but then subsequently gets a failure trying to send the rest of the request body.    I think it is reasonable for the client to ignore the send failure and attempt another request in response to that authentication challenge.

If fact this will often be the case even if 100 continues is used.  The client will send headers including an expect 100 header, but wait before sending the body.  The server might decide to send a redirect without reading the body, so the client will then see a 302 response and the connection closes.    The client should react to the 302 rather than fire an error based on the EOF exception.

**Comment by arhimondr** [comment]
I provided a test that reproduces the bug, and some dummy solution. Maybe it would help. https://github.com/eclipse/jetty.project/pull/956

**Comment by arhimondr** [comment]
@gregw @sbordet I would like to have this fixed before the release. If there is anything else i can help with to get this done - just let me know.

**Comment by sbordet** [comment]
@gregw  and I discussed this, and I  am (actually, we are) _not_ convinced we should support this case.

Trying authentication with a POST request exposes (like you found) to interpretation differences in clients and servers.
Much better to "prime" the authentication with an idempotent request such as GET, HEAD or OPTIONS, and HttpClient will remember the authentication for the subsequent POST which will complete normally.

Even with the POST as first request the application code, on the client, can still inspect the response object, find the 401 and decide what to do. If it is possible to re-read the content they may retry. But in general, HttpClient cannot know if a content can be re-read, and so it cannot retry a different request with the same content expecting to work.

As I said, it is also unlikely that Kerberos authentication will work on different connections.

The case with 100 Continue and redirect is definitely wrong because the application code on the client will issue a POST and will see the response content resulting by following the redirect, but has no idea whether the content has been sent - it actually never left the client.

To sum up, best solution is to prime the authentication with a GET/HEAD. After that, the POST will be issued with the right headers to pass authentication.

For the record, it is possible to preempt authentication (as explained in the [documentation](https://www.eclipse.org/jetty/documentation/9.3.x/http-client-authentication.html)), but I guess it will only work for the "Basic" mechanism.
