### ISSUE TITLE
Jetty 12: Review JakartaWebSocketClientContainer use of reflection

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#9438]
**Jetty version(s)**
12+

**Description**
https://github.com/eclipse/jetty.project/blob/jetty-12.0.x/jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jakarta-client/src/main/java/org/eclipse/jetty/ee9/websocket/jakarta/client/JakartaWebSocketClientContainer.java#L356

Methods `addToContextHandler()` and `removeFromContextHandler()` use reflection, but they are currently broken as the methods do not exist anymore.

This is very fragile, as it obviously did not stand a method renaming/refactoring already, so should be converted to something more stable.

**Comment by gregw** [comment]
The reason reflection is used is that the websocket client can be used stand alone - i.e not withing a server context.   But if it is within a server context, we need to register the lifecycle so it is stopped with the context.    We don't want to force a client to load jetty server APIs just to test if we are in a Jetty server environment, hence reflection is used.

However, I thought we were also using a `ServletContainerInitializer`  for a similar purpose, so that if we are in a server context, that will have been run by the context and could set a boolean or similar to say that it is OK to load the classes that know about how to register a life cycle.    So yeah, perhaps the reflection is unnecessary.

**Comment by gregw** [comment]
joakim
  8:52 AM
i thought we had a way to know if we were executing in a Scope/Handler and could reference it?


gregw
  8:55 AM
@joakim
 we have several ways.  This code is trying to call the static method to look for the thread local that says you are in a context.
8:55
The other way is with a ServletContainerInitializer, which if run will tell you that you are in a context.
8:56
I'm sure we do the later, so I'm not sure why we also need the former.


joakim
  8:56 AM
sure, but a generic way would be better, no?  eg
Container container = Container.getOuterContainer();
if (container != null) container.addManaged(wsclient);
(edited)


gregw
  8:57 AM
But how do you implement that without jetty server classes or reflection?
8:57
putting a facade on it doesn't help.  We need to avoid the client loading server classes.
8:57
Hmm or at least try to load the server classes in a place that we can catch the exception and conclude we are not in a server


joakim
  8:57 AM
wouldn't care if it was a Jetty server managing it or not, you seem to just care about adding the wsClient to managed to allow it to shutdown properly with the outer container (the WebAppContext or ContextHandler in the case of wsclient running in a server)


gregw
  8:58 AM
The API facade doesn't help.  It might be nice.  The fundamental question is how do you implement such an API.


joakim
  8:58 AM
you could just as well have a ServletContextListener.onDestroy() (or whatever it's called) that just does LifeCycle.stop(wsClient) too.
8:59
which only exists on server, and doesn't on standalone client.


gregw
  8:59 AM
Can the SCI do something that will inform the new client that it is in a server and thus can load jetty away classes and register
8:59
This is the standard websocket API, we can't change it.
8:59
users just create a client instance and use it.


joakim
  8:59 AM
I know, there's an open issue about the lifecycle of the client.


gregw
  9:00 AM
if they are in a server context, we need to shut it down when the context is undeployed






joakim
  9:00 AM
we can blindly use LifeCycle.stop(jakartaWebSocketClient) in Jetty just fine.


gregw
  9:01 AM
that is not the problem. We have to know when we can try that code. We need server APIs to know we are in a context and to be told that the context is stopping
9:01
The SCI get's told we are in a context... but how can the SCI communicate that to an arbitrary client instance?
9:01
Specially as the classes might be on the server class path and shared between contexts. statics don't work


joakim
  9:02 AM
to cleanup that statement.   "We need a Jetty component lifecycle API to know that we are in a Jetty component Container and be told when that Container is stopping"
9:02
the entire Jetty LifeCycle tree (jetty-util) is present in websocket client regardless of standalone or server. (edited) 


gregw
  9:03 AM
Hmmmm maybe.    So we introduce the concept of a lifecycle scope.


joakim
  9:03 AM
I thought we had that already


gregw
  9:04 AM
I can kind of see it, but we don't want a thread local for each and every lifecycle.  We don't want to know if we are in any old lifecycle, we want to know if we are in a specific lifecycle
9:04
We do already have lifecycle listeners
9:04
but the trick it to find the right lifecycle to listen to
9:04
in this case we need to look for a ContextHandler to listen to
9:05
so the problem is not the registration, the problem is the discovery
9:06
Ah also that class can't use it's LifeCycle API for registration, as it may be a different LifeCycle.class instance to what the server is running!
9:06
So it knows the API, but it might be loaded inside the webapp context.   Hmm so how does this work on tomcat????
9:06
We really need to just use SCI if we can.... Lot's to ponder.

**Comment by sbordet** [comment]
Current status is the following:

* There already exist ee9/ee10 `JakartaWebSocketShutdownContainer` which is a `ServletContainerInitializer` that register itself as a `ServletContext` listener so that when the Servlet context is destroyed it also stops the `JakartaWebSocketClientContainer`s.
* The reflection blocks actually work (contrary to the initial comment on this issue) as they reflect on the implementation classes that do have those methods -- however, it's still a lot of reverse engineering.
Seems unnecessary to have 2 different mechanisms (reflection and  `JakartaWebSocketShutdownContainer`).
Seems to me that the only reason to have 2 different mechanisms is to be able to have better `Server.dump()` outputs, as the `JakartaWebSocketClientContainer`s will be beans of the `ContextHandler`, but not sure this is intentional or not.
* There are comments about the `JakartaWebSocketShutdownContainer` `ServletContainerInitializer` being run in other Servlet Containers, but that is not possible, as Jetty's `JakartaWebSocketClientContainer` should not be put into `WEB-INF/lib` and it is obviously not available from the server class-path in other Servlet Containers.
* I have doubts that `JakartaWebSocketShutdownContainer` works with 2+ web applications, as each web application will run the `ServletContainerInitializer` so the call to `JakartaWebSocketClientContainer.setShutdownContainer()` will overwrite the container every time a web application starts. I think we need a `Map<ServletContext, ContainerLifeCycle>` instead.

@lachlan-roberts we need to discuss this, but fundamentally 2 questions: why 2 mechanisms and why not a `Map`.

**Comment by sbordet** [comment]
Fixed by #9626.
