### ISSUE TITLE
[Question]Is it possible to compile jetty-http2 using JDK 7

### ISSUE THREAD

**Issue by nezen** [eclipse/jetty.project#974]
I want to use jetty-http2 on Android, but Android only supports JDK 8 from version 6.0.  So is there any chance I can run jetty-http2 under Android 6.0?

**Comment by sbordet** [comment]
If you want to run under Android 6.0 and that Android version supports JDK 8, why you want to use JDK 7 ?

**Comment by nezen** [comment]
Actually I mean older version than Android 6.0. sorry for that , not a native speaker anyway.

**Comment by sbordet** [comment]
HTTP/2 requires strong ciphers (that are not available in OpenJDK 7) and NPN/ALPN support (again, not available natively in OpenJDK 7).

If Android's JDK can provide those 2, I guess it may be possible to downgrade the compilation requirements.

Note however that we won't downgrade the compilation requirement, since Jetty 9.3.x requires JDK 8 for other features.

I know that other clients runs on Android with support for HTTP/2, most notably [OkHttp](http://square.github.io/okhttp/).

**Comment by nezen** [comment]
Thanks for your information, very helpful.
