### ISSUE TITLE
Pictures are missed in documentation

### ISSUE THREAD

**Issue by arctrong** [eclipse/jetty.project#9770]
https://www.eclipse.org/jetty/documentation/jetty-12/operations-guide/index.html#og-arch-concepts

Looks like Graphviz was not set up properly while documentation generation.

In the documentation for version 11 the pictures are shown properly.

**Comment by jmcc0nn3ll** [comment]
![image](https://github.com/eclipse/jetty.project/assets/273327/ccee315e-d6fa-480b-8d6f-309f14c0dcb4)

@olamy is there a way to fail the build if the dot executable is not available during the documentation build during the release profile execution? I don't know if we should always require it due to operating system diversity...but for release builds on Linux it seems like a good idea to require it.

**Comment by olamy** [comment]
it's normally tested at the start of the release script see https://github.com/eclipse/jetty.project/blob/e0ff8cd1a5ee140f59d2238b3e21fa80e115e7ea/build/scripts/release-jetty.sh#L21
So if dot installed we should have something such:
```
-----------------------------------------------
  Verify Environment
ERROR: dot not found.  Install dot
```
**BUT** if we resume the script by running the script manually (e.g running manually `mvn` command instead of running the script) this is not checked.
We can add a check if executing `dot -h` is returning something different from 0 and fail the build (at least for the profile `eclipse-release`)

**Comment by olamy** [comment]
@joakime are you happy if we add a check in the `eclipse-release` profile?

**Comment by jmcc0nn3ll** [comment]
FWIW, I think it makes a lot of sense to add this. It's better than
releasing things to Maven Central that aren't correct.

**Comment by olamy** [comment]
simple PR here https://github.com/eclipse/jetty.project/pull/9804
just testing if `dot` is available via maven build.

**Comment by olamy** [comment]
PR merged. 
Thanks for the report.
