### ISSUE TITLE
ForwardedRequestCustomizer: `proxyAsAuthority` incorrectly handled with `x-forwarded-server`

### ISSUE THREAD

**Issue by isker** [eclipse/jetty.project#9936]
**Jetty version(s)**
Latest master.

**Java version/vendor** `(use: java -version)`
Not relevant.

**OS type/version**
Not relevant.

**Description**

If I'm understanding [the documentation](https://www.eclipse.org/jetty/javadoc/jetty-10/org/eclipse/jetty/server/ForwardedRequestCustomizer.html#getProxyAsAuthority()) correctly, this `getProxyAsAuthority` check needs to be inverted:
https://github.com/eclipse/jetty.project/blob/5b1e7bd5496d51568c5010ac5e0496d0344f98d2/jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java#L825-L833

The equivalent check for the `forwarded` header seems to be correct; when `proxyAsAuthority` is false, `by` is not handled:
https://github.com/eclipse/jetty.project/blob/5b1e7bd5496d51568c5010ac5e0496d0344f98d2/jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java#L891-L896

**How to reproduce?**

Send x-forwarded-server in a request to a Jetty server using ForwardedRequestCustomizer, and observe that it takes effect with the default configuration of `proxyAsAuthority`.

**Comment by joakime** [comment]
@isker what version of Jetty? (we have no master branch)  what version of Java? (it has been relevant in the past)  what OS? (also relevant in the past).

Know that the entire `X-Forwarded-*` set of headers **are not a standard**, and in fact have multiple competing and incompatible definitions out in the wild.
The order of headers and the mix of headers can result in unexpected behaviors.
The `X-Forwarded-Server` will generally (but not always, see above and unexpected behaviors) result in changes for the `HttpServletRequest.getServerName()` value.
Since a lone `X-Forwarded-Server` header with no other `X-Forwarded-*` headers is rare beyond words, you will wind up impacting the authority, scheme, and port in unexpected ways as well (impacting all of the authority based portions of the `HttpServletRequest`, and even things like `HttpServletRequest.isSecure()`.

If you want consistency in behavior, we encourage the use of `Forwarded` header as declared in RFC7239 - https://tools.ietf.org/html/rfc7239

If you want a small sampling of these unexpected behaviors take a look at our test cases ...
https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java

Note: there are 3 connectors on that test case, one with a default `ForwardedRequestCustomizer`, one with alternate secure port, one with configurted header names.

**Comment by isker** [comment]
You're right, there is no master branch; my mistake.  I used the default branch in the GitHub UI, `jetty-10.0.x`.  The bug is also present in `jetty-12.0.x`.

This bug was filed as a result of static analysis, i.e. I read the documentation and read the code and have observed the documentation and the code to align in one case (handling of the `Forwarded` header) and not the other (handling of the `X-Forwarded-Server` header, where the code has the exact opposite behavior stated by the documentation).  So, standardization of any of these headers, or the lack thereof, is not particularly relevant to the problem.

**Comment by joakime** [comment]
Closing, not a bug in Jetty 12.
Just a theoretical issue discovered via static analysis.

If a concrete example of a request that fails is provided, then open a new issue with the concrete example.
